#+PROPERTY: header-args :tangle config

#+HTML:<h1 align="center">i3 Config ... With Gaps!</h1>

#+HTML: <p align="center"><a href="https://orgmode.org"><img src="https://img.shields.io/badge/Org-literate%20config-%2377aa99?style=flat-square&logo=org&logoColor=white"></a> <a href="https://www.gnu.org/software/emacs/"><img src="https://img.shields.io/badge/Made_with-Emacs-blueviolet.svg?style=flat-square&logo=GNU%20Emacs&logoColor=white" /></a></p>

#+HTML:<p align="center"><code><a href="https://i3wm.org/">i3</a></code> is an open source tiling window manager for X11. I use a fork of it called <code><a href="https://github.com/Airblader/i3">i3-gaps</a></code>.</p>
#+STARTUP: show2levels

- [[#monitors][Monitors]]
- [[#basic-controls][Basic Controls]]
- [[#emacs-i3-integration][Emacs i3 Integration]]
- [[#settings][Settings]]
- [[#looks][Looks]]
- [[#workspaces][Workspaces]]
- [[#utilities][Utilities]]
- [[#startup-apps][Startup Apps]]
- [[#workspace-apps][Workspace Apps]]
- [[#scratchpad-apps][Scratchpad Apps]]
- [[#modes--moded-apps][Modes & Moded Apps]]
- [[#tips][Tips]]

* Monitors
#+begin_src conf
set $laptop eDP-1-1
set $external HDMI-0
#+end_src

* Basic Controls
Mostly standard controls.
#+begin_src conf
# set mod key
set $mod Mod4

# drag floaters key
floating_modifier $mod

# make window float
bindsym $mod+Shift+space floating toggle

# focus between floating and tiling
bindsym $mod+space focus mode_toggle

# hide scratchpad windows on focused workspace
bindsym $mod+semicolon [workspace="__focused__" floating] scratchpad show

# cycle through scratchpad windows
bindsym $mod+apostrophe scratchpad show, move position center

# fullscreen
bindsym $mod+F11 fullscreen toggle

# emergency shutdown
bindsym $mod+Control+Delete exec --no-startup-id systemctl poweroff
#+end_src

* Emacs i3 Integration

This section allows me to control my windowing for both Emacs and i3 using common keybinds.

This was created by Pavel Korytov and can be found [[https://sqrtminusone.xyz/posts/2021-10-04-emacs-i3/][here]].

I've changed a few functions to get it up and running. The implementation is still in progress.

TODO: This needs integrated with my rofi-chemacs default profile.

** Emacs or i3 Command Parser
#+begin_src sh :tangle emacs-i3-integration :shebang "#!/bin/bash"
title="^.*Doom\sEmacs$"
if [[ $(xdotool getactivewindow getwindowname) =~ $title ]]; then
    command="(noncog/emacs-i3-integration \"$@\")"
    emacsclient -s doom -e "$command"
else
    i3-msg $@
fi
#+end_src

** Focus
#+begin_src conf
bindsym $mod+h exec --no-startup-id $HOME/.config/i3/emacs-i3-integration focus left
bindsym $mod+j exec --no-startup-id $HOME/.config/i3/emacs-i3-integration focus down
bindsym $mod+k exec --no-startup-id $HOME/.config/i3/emacs-i3-integration focus up
bindsym $mod+l exec --no-startup-id $HOME/.config/i3/emacs-i3-integration focus right
#+end_src

** Move
#+begin_src conf
bindsym $mod+Shift+h exec $HOME/.config/i3/emacs-i3-integration move left
bindsym $mod+Shift+j exec $HOME/.config/i3/emacs-i3-integration move down
bindsym $mod+Shift+k exec $HOME/.config/i3/emacs-i3-integration move up
bindsym $mod+Shift+l exec $HOME/.config/i3/emacs-i3-integration move right
#+end_src

** Resize
#+begin_src conf
set $resize_mode Resize: h, j, k, l
mode "$resize_mode" {
    bindsym h exec --no-startup-id $HOME/.config/i3/emacs-i3-integration resize shrink width 10 px or 10 ppt
    bindsym j exec --no-startup-id $HOME/.config/i3/emacs-i3-integration resize shrink height 10 px or 10 ppt
    bindsym k exec --no-startup-id $HOME/.config/i3/emacs-i3-integration resize grow height 10 px or 10 ppt
    bindsym l exec --no-startup-id $HOME/.config/i3/emacs-i3-integration resize grow width 10 px or 10 ppt

    bindsym Shift+h exec --no-startup-id $HOME/.config/i3/emacs-i3-integration resize shrink width 100 px or 100 ppt
    bindsym Shift+j exec --no-startup-id $HOME/.config/i3/emacs-i3-integration resize shrink height 100 px or 100 ppt
    bindsym Shift+k exec --no-startup-id $HOME/.config/i3/emacs-i3-integration resize grow height 100 px or 100 ppt
    bindsym Shift+l exec --no-startup-id $HOME/.config/i3/emacs-i3-integration resize grow width 100 px or 100 ppt

    bindsym equal exec --no-startup-id $HOME/.config/i3/i3-emacs-balance-windows

    # back to normal
    bindsym $mod+Escape mode "default"
    bindsym $mod+BackSpace mode "default"
    bindsym $mod+Return mode "default"
    bindsym Escape mode "default"
    bindsym BackSpace mode "default"
    bindsym Return mode "default"
    # back to normal: Enter or Escape
    bindsym Return mode "default"
    bindsym Escape mode "default"
}
bindsym $mod+r mode "$resize_mode"
#+end_src

** Balance Windows
#+begin_src sh :tangle i3-emacs-balance-windows :shebang "#!/bin/bash"
title="^.*Doom\sEmacs$"
if [[ $(xdotool getactivewindow getwindowname) =~ $title ]]; then
    emacsclient -s doom -e "(balance-windows)"
fi
#i3_balance_workspace
#+end_src

** Layout Control
#+begin_src conf
bindsym $mod+Tab layout tabbed
#bindsym $mod+grave exec --no-startup-id $HOME/.config/i3/emacs-i3-integration layout toggle split
bindsym $mod+grave layout toggle split
#+end_src

** Window Splitting
#+begin_src conf
bindsym $mod+v exec --no-startup-id $HOME/.config/i3/emacs-i3-integration split h
bindsym $mod+s exec --no-startup-id $HOME/.config/i3/emacs-i3-integration split v
#+end_src

** Kill Windows

#+begin_src conf
bindsym $mod+Shift+q exec --no-startup-id $HOME/.config/i3/emacs-i3-integration kill
#+end_src

* Settings
#+begin_src conf
focus_wrapping no
#+end_src

* Looks
** Font
I try to use Fira Code for everything.
#+begin_src conf
font pango:Fira Code 11
#+end_src

** Wallpaper
Check out my [[https://github.com/noncog/.dotfiles/tree/master/.config/wallpapers][wallpapers directory]].
#+begin_src conf
exec --no-startup-id nitrogen --restore 
#+end_src

** Theme
I use the [[https://draculatheme.com/][Dracula theme]] everywhere I can!
#+begin_src conf
# class                 border  bground text    indicator child_border
client.focused          #6272A4 #6272A4 #F8F8F2 #6272A4   #6272A4
client.focused_inactive #44475A #44475A #F8F8F2 #44475A   #44475A
client.unfocused        #282A36 #282A36 #BFBFBF #282A36   #282A36
client.urgent           #44475A #FF5555 #F8F8F2 #FF5555   #FF5555
client.placeholder      #282A36 #282A36 #F8F8F2 #282A36   #282A36

client.background       #F8F8F2
#+end_src

** i3-gaps
#+begin_src conf
# Necessary for i3-gaps to work properly (pixel can be any value)
for_window [class="^.*"] border pixel 2

# Smart Gaps
smart_gaps on
smart_gaps inverse_outer

# Smart Borders
smart_borders on

# Set inner/outer gaps
gaps inner 10
gaps outer 0
#+end_src

* Workspaces
I only use 3 universal workspaces and a 'coding' workspace. Some apps get their own workspace. Some apps live in the scratchpad.
#+begin_src conf
# name workspaces
set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $code "Code"

# switch to workspace
bindsym $mod+1 workspace number $ws1
bindsym $mod+2 workspace number $ws2
bindsym $mod+3 workspace number $ws3

# move focused container to workspace
bindsym $mod+Shift+1 move container to workspace number $ws1
bindsym $mod+Shift+2 move container to workspace number $ws2
bindsym $mod+Shift+3 move container to workspace number $ws3

# assign workspaces to monitors
workspace $ws1 output $external $laptop
workspace $ws2 output $external $laptop
workspace $ws3 output $laptop $external
workspace $code output $external $laptop
#+end_src

* Utilities
** Emacs Daemon
#+begin_src conf
exec --no-startup-id emacs --daemon
#+end_src

** Picom Daemon
#+begin_src conf
exec --no-startup-id picom -b
#+end_src

** Network-Manager
#+begin_src conf
exec --no-startup-id nm-applet
#+end_src

** Pulse Audio Control
#+begin_src conf
set $refresh_i3status killall -SIGUSR1 i3status
bindsym XF86AudioRaiseVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ +10% && $refresh_i3status
bindsym XF86AudioLowerVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ -10% && $refresh_i3status
bindsym XF86AudioMute exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ toggle && $refresh_i3status
bindsym XF86AudioMicMute exec --no-startup-id pactl set-source-mute @DEFAULT_SOURCE@ toggle && $refresh_i3status
#+end_src

** Extreme Cooling 4 Linux
#+begin_src conf
bindsym $mod+Shift+z exec --no-startup-id ec4Linux change-state
#+end_src

** Polybar
#+begin_src conf
exec_always --no-startup-id $HOME/.config/polybar/launch.sh

# note that exec_always runs every time you restart i3 not just initialization.
# this allows polybar to be restarted with i3 restarting.
#+end_src

** Rofi
#+begin_src conf
# desktop app launcher
bindsym $mod+BackSpace exec --no-startup-id rofi -show drun -show-icons
# custom menu launcher
bindsym $mod+Escape exec --no-startup-id $HOME/.config/rofi/cogmenu/cogmenu.sh
#+end_src

** ScreenKey
#+begin_src conf
bindsym $mod+Shift+question exec --no-startup-id screenkey
#+end_src

* Startup Apps
#+begin_src conf
exec --no-startup-id sleep 3 && profile=$(cat $HOME/.config/chemacs/profile) && emacsclient -c -s $profile &
exec --no-startup-id sleep 4 && firefox
exec --no-startup-id kitty --name Floating-Kitty
# restart i3 to make sure startup windows are moved to scratchpad
exec --no-startup-id restart
#+end_src

* Workspace Apps
These apps are given their own workspaces.

I use a particular format for how my apps are managed.
- =key= = focus
- =shift+key= = spawn
- =control+shift+key= = move to app's workspace
** Emacs Client
#+begin_src conf
set $emacs "Emacs"
assign [class="Emacs"] $emacs
workspace $emacs output $external $laptop
bindsym $mod+Control+Shift+e move container to workspace $emacs
bindsym $mod+Shift+e exec --no-startup-id $HOME/.config/rofi/rofi-chemacs/rofi-chemacs.sh
bindsym $mod+e [class="Emacs"] focus
#+end_src

** Firefox
#+begin_src conf
set $firefox "Firefox"
assign [class="Firefox-esr"] $firefox
workspace $firefox output $external $laptop
bindsym $mod+Control+Shift+f move container to workspace $firefox
bindsym $mod+Shift+f exec --no-startup-id firefox
bindsym $mod+f [class="Firefox-esr" tiling] focus
#+end_src

** Clion
#+begin_src conf
assign [class="jetbrains-clion"] $code
bindsym $mod+Control+Shift+c move container to workspace $code
bindsym $mod+Shift+c exec --no-startup-id clion
bindsym $mod+c [class="jetbrains-clion"] focus
#+end_src

** Pycharm
#+begin_src conf
assign [class="jetbrains-pycharm"] $code
bindsym $mod+Control+Shift+p move container to workspace $code
bindsym $mod+Shift+p exec --no-startup-id pycharm
bindsym $mod+p [class="jetbrains-pycharm"] focus
#+end_src

** IntelliJ Idea
#+begin_src conf
assign [class="jetbrains-idea"] $code
bindsym $mod+Control+Shift+i move container to workspace $code
bindsym $mod+Shift+i exec --no-startup-id idea
bindsym $mod+i [class="jetbrains-idea"] focus
#+end_src

** Anki
I give this it's own workspace to not deal with floating dialog issues in a scratchpad.
#+begin_src conf
set $anki "Anki"
assign [class="Anki"] $anki
workspace $anki output $external $laptop
bindsym $mod+Control+Shift+a move container to workspace $anki
bindsym $mod+Shift+a exec --no-startup-id anki
bindsym $mod+a [class="Anki"] focus
#+end_src

* Scratchpad Apps
The scratchpad is an invisible workspace. I put "floating" apps into it. They can only be spawned and focused/hidden.

** Kitty
#+begin_src conf
for_window [instance="Floating-Kitty"] floating enable, resize set 50 ppt 50 ppt, sticky enable
for_window [instance="Floating-Kitty"] move scratchpad
bindsym $mod+Shift+Return exec --no-startup-id kitty --name "Floating-Kitty"
bindsym $mod+Return [instance="Floating-Kitty"] scratchpad show, move position center
#+end_src

** Tor
#+begin_src conf
for_window [class="Tor Browser"] floating enable, resize set 75 ppt 75 ppt, sticky enable
for_window [class="Tor Browser"] move scratchpad
bindsym $mod+Shift+t exec --no-startup-id bash /opt/tor-browser_en-US/Browser/start-tor-browser
bindsym $mod+t [class="Tor Browser"] scratchpad show, move position center
#+end_src

** Discord
#+begin_src conf
for_window [class="discord"] floating enable, sticky enable
for_window [class="discord"] move scratchpad
bindsym $mod+Shift+d exec --no-startup-id discord
bindsym $mod+d [class="discord"] scratchpad show, resize set 50 ppt 85 ppt, move position center
#+end_src

** Spotify
#+begin_src conf
#for_window [class="Spotify"] floating enable, resize set 50 ppt 60 ppt, sticky enable
#for_window [class="Spotify"] move scratchpad
#bindsym $mod+Shift+s exec --no-startup-id spotify
#bindsym $mod+s [class="Spotify"] scratchpad show, move position center
#+end_src

** YouTube
Probably the pinnacle of my config...

A mini floating YouTube player with sizes and positions for laptop and desktop displays.
*** Set URL and Title
#+begin_src conf
# set to your unique youtube page. ideally a page you will never visit.
# otherwise your firefox will be turned into the youtuber player...
set $youtube_page https://www.youtube.com/premium
set $youtube_title "YouTube Premium - YouTube — Mozilla Firefox"
# found using xprop
#+end_src

*** Set Size and Location Per Monitor
#+begin_src conf
# size
set $yt_d_w 720
set $yt_d_h 407
# location
set $yt_d_x 2910 px
set $yt_d_y 1023 px
#+end_src

#+begin_src conf
# size
set $yt_l_w 636
set $yt_l_h 360
# location
set $yt_l_x 1274 px
set $yt_l_y 710 px
#+end_src

*** Floating YouTube Player
#+begin_src conf
for_window [title=$youtube_title] floating enable, move scratchpad, sticky enable, mark youtube
bindsym $mod+Shift+y exec --no-startup-id firefox --new-window $youtube_page
bindsym $mod+y exec --no-startup-id "if [ -z $(xrandr --listmonitors | grep HDMI) ]; then i3-msg \\"[con_mark=youtube] scratchpad show, resize set $yt_l_w $yt_l_h, move position $yt_l_x $yt_l_y\\"; else i3-msg \\"[con_mark=youtube] scratchpad show, resize set $yt_d_w $yt_d_h, move position $yt_d_x $yt_d_y\\"; fi"
#+end_src

** Nitrogen
#+begin_src conf
for_window [class="Nitrogen"] floating enable, resize set 50 ppt 50 ppt, move scratchpad, sticky enable
for_window [class="Nitrogen"] scratchpad show, move position center
#+end_src

* Tips
** Finding Keynames (keysym)
#+begin_src conf
# To find the name or keysym of the key to be used in this config use xev and press the key to get it's name.
#+end_src

** Window Information
#+begin_src conf
# To find window related information use:
# xprop and xwininfo
#+end_src
