section: screens
	Ganymede:
		ctrl = super
		alt = ctrl
		super = alt
		halfDuplexCapsLock = false
		halfDuplexNumLock = false
		halfDuplexScrollLock = false
		xtestIsXineramaUnaware = false
		switchCorners = none
		switchCornerSize = 0
	Callisto:
		halfDuplexCapsLock = false
		halfDuplexNumLock = false
		halfDuplexScrollLock = false
		xtestIsXineramaUnaware = false
		switchCorners = none
		switchCornerSize = 0
end

section: aliases
end

section: links
	Ganymede:
		right = Callisto
	Callisto:
		left = Ganymede
end

section: options
	protocol = barrier
	relativeMouseMoves = false
	win32KeepForeground = false
	disableLockToScreen = false
	clipboardSharing = true
	clipboardSharingSize = 3072
	switchCorners = none 
	switchCornerSize = 0
end

