#+TITLE: .dotfiles with git --bare
My system configuration files are managed with a git --bare repository.

This allows easy versioning and installation of dotfiles without symlinks or any form of moving/copying.

Simply put, the files are cloned to where they belong!

- To use these dotfiles as is, follow the usage.
- To setup your own git --bare managed dotfiles follow the short setup guide below!
* Usage
** Use my debian-autosetup
** Clone dotfiles as is
** Automated cloning script
* Short Setup Guide
This is the absolute bare minimum guide one could use to start managing their dotfiles with a bare repository. For more information, there are numerous guides on the internet.

A word of advice:
- See Recommendations section below for important github practices before beginning.
- You do not need a .gitignore, so long as you never add .dotfiles to your .dotfiles. 
** Create Bare Repository and Dotfiles Command
#+BEGIN_SRC
  git init --bare $HOME/.dotfiles
  echo "alias dotfiles='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'" >> $HOME/.bashrc
  dotfiles config --local status.showUntrackedFiles no
#+END_SRC
** Adding Files
#+BEGIN_SRC
  dotfiles add .bashrc
  dotfiles commit -m "Added .bashrc"
#+END_SRC
** First Push
#+BEGIN_SRC
  dotfiles remote add origin <your dotfiles repo>
  dotfiles push -u origin master
#+END_SRC
** Push + Other Commands
After everything is setup, you can use all git commands with the dotfiles alias.
#+BEGIN_SRC
  # common commands
  dotfiles push
  dotfiles status
  dotfiles log
#+END_SRC
** Recommendations
#+BEGIN_SRC
  Use the private noreply email provided by github to prevent leaking your personal email in git commits.
  https://github.com/settings/email
  
  - set on the command line using:
  git config --global user.email <noreply-email>
  - check it was set using:
  git config --global user.email
  
  Use personal access tokens when commiting from command line
  https://github.com/settings/tokens

  - generate a token for repository changes.
  - save it locally to your system, it will not be accessible again.
  - enter the token when prompted for your password during a push.
#+END_SRC
