#+TITLE: .dotfiles with git --bare
My system configuration files are managed with a git --bare repository.

This allows easy versioning and installation of dotfiles without symlinks or any form of moving/copying.

Simply put, the files are cloned to where they belong!

- To use these dotfiles as is, follow the usage.
- To setup your own git --bare managed dotfiles follow the short setup guide below!
* Usage
If you're on a debian-based distribution, you can use my [[https://github.com/noncog/debian-autosetup][debian-autosetup]] script to automatically install my system setup, software, and dotfiles. Or easily modify it to install your own software and dotfiles!

Otherwise, to install dotfiles managed with bare on a fresh system do the following:
** Simple Clone of dotfiles
#+BEGIN_SRC
  git clone --bare <git-repo-url> $HOME/.dotfiles
  # alias only in this shell instance, assumes that you back up your .bashrc where the permanent alias is, which will be installed momentarily.
  alias dotfiles='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
  dotfiles checkout
#+END_SRC
When you attempt to checkout, if you have configs already in place, the above will likely fail, and ask you to remove the config files before dotfiles can be cloned in. If this is the case use the following:
** Automated Cloning Script
#+BEGIN_SRC
  # clone dotfiles
  git clone --bare https://github.com/not-tacit/.dotfiles $HOME/.dotfiles

  # checkout will backup dotfiles in the way
  cd ${HOME}
  mkdir -p .dotfiles-backup && \
  /usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME checkout 2>&1 | egrep "\s+\." | awk {'print $1'} | \
  xargs -I{} mv {} .dotfiles-backup/{}

  # now check out
  /usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME checkout

  # hide untracked files
  /usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME config --local status.showUntrackedFiles no
#+END_SRC
* Short Setup Guide
This is the absolute bare minimum guide one could use to start managing their dotfiles with a bare repository. For more information, there are numerous guides on the internet.

A word of advice:
- See Recommendations section below for important github practices before beginning.
- You do not need a .gitignore, so long as you never add .dotfiles to your .dotfiles. 
** Initial Setup
Create a bare repository and an alias command to control it.
#+BEGIN_SRC
  git init --bare $HOME/.dotfiles
  echo "alias dotfiles='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'" >> $HOME/.bashrc
  dotfiles config --local status.showUntrackedFiles no
#+END_SRC
** Adding Files
#+BEGIN_SRC
  dotfiles add .bashrc
  dotfiles commit -m "Added .bashrc"
#+END_SRC
** First Push / Remote Setup
#+BEGIN_SRC
  dotfiles remote add origin <your dotfiles repo>
  dotfiles push -u origin master
#+END_SRC
** Commands
After everything is setup, you can use all git commands with the dotfiles alias.
#+BEGIN_SRC
  # common commands
  dotfiles push
  dotfiles status
  dotfiles log
#+END_SRC
** Recommendations For GitHub Users
Use the private noreply email provided by github to prevent leaking your personal email in git commits.
- Provided by GitHub [[https://github.com/settings/email][here]].
#+BEGIN_SRC  
  - set on the command line using:
  git config --global user.email <noreply-email>
  - check it was set using:
  git config --global user.email
#+END_SRC
Use personal access tokens when commiting from command line.
- Provided by GitHub [[https://github.com/settings/tokens][here]].
#+BEGIN_SRC
  - generate a token for repository changes.
  - save it locally to your system, it will not be accessible again.
  - enter the token when prompted for your password during a push.
#+END_SRC
