#+tags: export noexport
#+export_select_tags: export
#+export_exclude_tags: exclude noexport

#+begin_html
<div align="center">
<!-- Shields -->
<p><a href="https://www.gnu.org/software/emacs/emacs.html#Releases"><img src="https://img.shields.io/badge/Emacs-27.1+-blueviolet.svg?style=flat-square&logo=GNU%20Emacs&logoColor=white"></a> <a href="https://orgmode.org"><img src="https://img.shields.io/badge/Org-literate%20config-%2377aa99?style=flat-square&logo=org&logoColor=white"></a></p>

<!-- Doom Logo -->
<p><a href="https://github.com/Schievel1/doom-emacs-splash"><img src="https://github.com/Schievel1/doom-emacs-splash/blob/main/svg/doom/doomEmacsDracula.svg" height="300"></a></p>

<p><a href="https://creativecommons.org/licenses/by-sa/4.0/"><img src="https://img.shields.io/badge/CC--BY--SA-161b22?style=for-the-badge&logo=Creative%20Commons&logoColor=white"></a></p>

<!-- Description -->
<p><code>This is my <a href="https://github.com/doomemacs/doomemacs">Doom</a> <a href="https://www.gnu.org/software/emacs/">Emacs</a> configuration.</code></p>
</div>
#+end_html

* Table of Contents :TOC:QUOTE:
:PROPERTIES:
:CUSTOM_ID: table-of-contents
:VISIBILITY: folded
:END:

#+html:<details><summary>Table of Contents</summary>
#+BEGIN_QUOTE
- [[#doom][Doom]]
  - [[#resources][Resources]]
  - [[#doom-configs][Doom Configs]]
  - [[#variables][Variables]]
  - [[#appearance][Appearance]]
  - [[#behavior][Behavior]]
  - [[#keybinds][Keybinds]]
- [[#beacon][Beacon]]
  - [[#package][Package]]
  - [[#appearance-1][Appearance]]
  - [[#behavior-1][Behavior]]
- [[#which-key][Which-Key]]
  - [[#package-1][Package]]
  - [[#fixes][Fixes]]
- [[#doom-modeline][Doom Modeline]]
  - [[#package-2][Package]]
  - [[#appearance-2][Appearance]]
- [[#doom-dashboard][Doom Dashboard]]
  - [[#package-3][Package]]
  - [[#keybinds-1][Keybinds]]
- [[#persp-mode][Persp-Mode]]
  - [[#package-4][Package]]
  - [[#fixes-1][Fixes]]
- [[#vertico][Vertico]]
  - [[#package-5][Package]]
  - [[#behavior-2][Behavior]]
  - [[#keybinds-2][Keybinds]]
- [[#company][Company]]
  - [[#package-6][Package]]
  - [[#behavior-3][Behavior]]
- [[#yasnippet][Yasnippet]]
  - [[#package-7][Package]]
  - [[#resources-1][Resources]]
  - [[#behavior-4][Behavior]]
- [[#projectile][Projectile]]
  - [[#package-8][Package]]
  - [[#variables-1][Variables]]
  - [[#behavior-5][Behavior]]
  - [[#keybinds-3][Keybinds]]
- [[#treemacs][Treemacs]]
  - [[#package-9][Package]]
  - [[#appearance-3][Appearance]]
  - [[#behavior-6][Behavior]]
- [[#magit][Magit]]
  - [[#package-10][Package]]
  - [[#behavior-7][Behavior]]
- [[#vterm][Vterm]]
  - [[#package-11][Package]]
  - [[#keybinds-4][Keybinds]]
- [[#visual-fill-column][Visual Fill Column]]
  - [[#package-12][Package]]
- [[#org][Org]]
  - [[#package-13][Package]]
  - [[#variables-2][Variables]]
  - [[#appearance-4][Appearance]]
  - [[#behavior-8][Behavior]]
  - [[#fixes-2][Fixes]]
- [[#org-agenda][Org Agenda]]
  - [[#package-14][Package]]
  - [[#appearance-5][Appearance]]
  - [[#behavior-9][Behavior]]
  - [[#keybinds-5][Keybinds]]
  - [[#helpers][Helpers]]
- [[#org-capture][Org Capture]]
  - [[#package-15][Package]]
  - [[#variables-3][Variables]]
  - [[#behavior-10][Behavior]]
  - [[#keybinds-6][Keybinds]]
  - [[#fixes-3][Fixes]]
- [[#org-roam][Org Roam]]
  - [[#package-16][Package]]
  - [[#variables-4][Variables]]
  - [[#behavior-11][Behavior]]
  - [[#keybinds-7][Keybinds]]
- [[#org-roam-ui][Org Roam UI]]
  - [[#package-17][Package]]
  - [[#appearance-6][Appearance]]
  - [[#behavior-12][Behavior]]
  - [[#keybinds-8][Keybinds]]
- [[#org-appear][Org Appear]]
  - [[#package-18][Package]]
  - [[#appearance-7][Appearance]]
- [[#org-fragtog][Org Fragtog]]
  - [[#package-19][Package]]
- [[#org-modern][Org Modern]]
  - [[#package-20][Package]]
  - [[#appearance-8][Appearance]]
- [[#org-modern-indent][Org Modern Indent]]
  - [[#package-21][Package]]
- [[#toc-org][TOC Org]]
  - [[#package-22][Package]]
  - [[#behavior-13][Behavior]]
- [[#org-noter][Org Noter]]
  - [[#package-23][Package]]
  - [[#behavior-14][Behavior]]
- [[#pdf-tools][PDF Tools]]
  - [[#package-24][Package]]
  - [[#fixes-4][Fixes]]
- [[#plantuml][PlantUML]]
  - [[#package-25][Package]]
  - [[#behavior-15][Behavior]]
- [[#ox-org-export][Ox (Org Export)]]
  - [[#package-26][Package]]
  - [[#appearance-9][Appearance]]
  - [[#behavior-16][Behavior]]
  - [[#keybinds-9][Keybinds]]
- [[#ox-latex][Ox Latex]]
  - [[#package-27][Package]]
  - [[#appearance-10][Appearance]]
  - [[#behavior-17][Behavior]]
- [[#engrave-faces][Engrave Faces]]
  - [[#package-28][Package]]
- [[#lsp-clangd][LSP-Clangd]]
  - [[#package-29][Package]]
  - [[#behavior-18][Behavior]]
#+END_QUOTE
#+html:</details>

* Doom
:PROPERTIES:
:VISIBILITY: children
:END:

This section is for "global" or top-level configuration. Outside of this section, each section is dedicated to specific package configuration.

This section is for "global" or top-level configuration. Outside of this section, each section is dedicated to specific package configuration.

** Resources
:PROPERTIES:
:VISIBILITY: children
:END:

Doom and Emacs (Linux in general) configuration is somewhat of an art. Here are a some configurations to learn from.

*** Doom User Configs
- [[https://github.com/tecosaur/emacs-config][Tecosaur]]
- [[https://github.com/zzamboni/dot-doom/blob/master/doom.org][Zzamboni]]
- [[https://github.com/elken/doom][Elken]]
- [[https://github.com/hieutkt/dotfiles/tree/main/emacs/.doom.d][Nguyen Duc Hieu]]
- [[https://github.com/slano-ls/Doom-Emacs-Config][Saihaj Law]]
- [[https://github.com/hlissner/.doom.d/tree/master][Henrik Lissner]]
- [[https://github.com/tefkah/doom-emacs-config][Tefkah]]

*** Emacs User Configs
- [[https://github.com/daviwil/dotfiles/tree/guix-home][David Wilson]]
- [[https://github.com/rougier/dotemacs/blob/master/dotemacs.org][Nicolas P. Rougier]]
- [[https://github.com/jimeh/.emacs.d][Emacs Siren]]
- [[https://github.com/howardabrams/hamacs][Howard Abrams]]
- [[https://github.com/chrisbarrett/.emacs.d/blob/master/config.org][Chris Barrett]]

** Doom Configs
:PROPERTIES:
:VISIBILITY: children
:END:

Doom only uses three config files. I keep their headers here.

*** Init.el

#+begin_quote
Defines which of Doom’s modules are loaded.
#+end_quote

#+html:<details><summary>No Web Assembly</summary>
#+begin_src emacs-lisp :tangle "init.el" :noweb tangle
<<init-header>>

<<early-init>>

<<modules>>
#+end_src
#+html:</details>

#+html:<details><summary>Header</summary>
#+begin_src emacs-lisp :tangle no :noweb-ref init-header
;;; init.el -*- lexical-binding: t; -*-

;; This file controls what Doom modules are enabled and what order they load
;; in. Remember to run 'doom sync' after modifying it!

;; NOTE Press 'SPC h d h' (or 'C-h d h' for non-vim users) to access Doom's
;;      documentation. There you'll find a link to Doom's Module Index where all
;;      of our modules are listed, including what flags they support.

;; NOTE Move your cursor over a module's name (or its flags) and press 'K' (or
;;      'C-c c k' for non-vim users) to view its documentation. This works on
;;      flags as well (those symbols that start with a plus).
;;
;;      Alternatively, press 'gd' (or 'C-c c d') on a module to browse its
;;      directory (for easy access to its source code).
#+end_src
#+html:</details>


#+html:<details><summary>Module List</summary>
#+begin_src emacs-lisp :tangle no :noweb-ref modules
(doom! :input
       ;;bidi              ; (tfel ot) thgir etirw uoy gnipleh
       ;;chinese
       ;;japanese
       ;;layout            ; auie,ctsrnm is the superior home row

       :completion
       (company)           ; the ultimate code completion backend
       ;;helm              ; the *other* search engine for love and life
       ;;ido               ; the other *other* search engine...
       ;;ivy               ; a search engine for love and life
       (vertico +icons)    ; the search engine of the future

       :ui
       ;;deft              ; notational velocity for Emacs
       doom                ; what makes DOOM look the way it does
       doom-dashboard      ; a nifty splash screen for Emacs
       ;;doom-quit         ; DOOM quit-message prompts when you quit Emacs
       (emoji              ; 🙂
        +unicode
        +github)
       hl-todo             ; highlight TODO/FIXME/NOTE/DEPRECATED/HACK/REVIEW
       ;;hydra
       ;;indent-guides     ; highlighted indent columns
       ;;ligatures         ; ligatures and symbols to make your code pretty again
       ;;minimap           ; show a map of the code on the side
       modeline            ; snazzy, Atom-inspired modeline, plus API
       ;nav-flash           ; blink cursor line after big motions
       ;;neotree           ; a project drawer, like NERDTree for vim
       ophints             ; highlight the region an operation acts on
       (popup +defaults)   ; tame sudden yet inevitable temporary windows
       ;;tabs              ; a tab bar for Emacs
       treemacs            ; a project drawer, like neotree but cooler
       ;;unicode           ; extended unicode support for various languages
       (vc-gutter +pretty) ; vcs diff in the fringe
       vi-tilde-fringe     ; fringe tildes to mark beyond EOB
       ;;window-select     ; visually switch windows
       workspaces          ; tab emulation, persistence & separate workspaces
       zen                 ; distraction-free coding or writing

       :editor
       (evil +everywhere)  ; come to the dark side, we have cookies
       file-templates      ; auto-snippets for empty files
       fold                ; (nigh) universal code folding
       ;;(format +onsave)  ; automated prettiness
       ;;god               ; run Emacs commands without modifier keys
       ;;lispy             ; vim for lisp, for people who don't like vim
       ;;multiple-cursors  ; editing in many places at once
       ;;objed             ; text object editing for the innocent
       ;;parinfer          ; turn lisp into python, sort of
       ;;rotate-text       ; cycle region at point between text candidates
       snippets            ; my elves. They type so I don't have to
       word-wrap           ; soft wrapping with language-aware indent

       :emacs              ; making dired pretty [functional]
       (dired
        +icons
        +ranger)
       electric            ; smarter, keyword-based electric-indent
       (ibuffer +icons)    ; interactive buffer management
       undo                ; persistent, smarter undo for your inevitable mistakes
       vc                  ; version-control and Emacs, sitting in a tree

       :term
       ;;eshell            ; the elisp shell that works everywhere
       ;;shell             ; simple shell REPL for Emacs
       ;;term              ; basic terminal emulator for Emacs
       vterm               ; the best terminal emulation in Emacs

       :checkers
       syntax              ; tasing you for every semicolon you forget
       ;;(spell +flyspell) ; tasing you for misspelling mispelling
       ;;grammar           ; tasing grammar mistake every you make

       :tools
       ;;ansible
       ;;biblio            ; Writes a PhD for you (citation needed)
       ;;debugger          ; FIXME stepping through code, to help you add bugs
       ;;direnv
       ;;docker
       ;;editorconfig      ; let someone else argue about tabs vs spaces
       ;;ein               ; tame Jupyter notebooks with emacs
       (eval +overlay)     ; run code, run (also, repls)
       ;;gist              ; interacting with github gists
       lookup              ; navigate your code and its documentation
       lsp                 ; M-x vscode
       magit               ; a git porcelain for Emacs
       ;;make              ; run make tasks from Emacs
       ;;pass              ; password manager for nerds
       pdf                 ; pdf enhancements
       ;;prodigy           ; FIXME managing external services & code builders
       ;;rgb               ; creating color strings
       ;;taskrunner        ; taskrunner for all your projects
       ;;terraform         ; infrastructure as code
       ;;tmux              ; an API for interacting with tmux
       ;;tree-sitter       ; syntax and parsing, sitting in a tree...
       ;;upload            ; map local to remote projects via ssh/ftp

       :os
       (:if IS-MAC macos)  ; improve compatibility with macOS
       tty                 ; improve the terminal Emacs experience

       :lang
       ;;agda              ; types of types of types of types...
       ;;beancount         ; mind the GAAP
       (cc +lsp)           ; C > C++ == 1
       ;;clojure           ; java with a lisp
       ;;common-lisp       ; if you've seen one lisp, you've seen them all
       ;;coq               ; proofs-as-programs
       ;;crystal           ; ruby at the speed of c
       ;;csharp            ; unity, .NET, and mono shenanigans
       ;;data              ; config/data formats
       ;;(dart +flutter)   ; paint ui and not much else
       ;;dhall
       ;;elixir            ; erlang done right
       ;;elm               ; care for a cup of TEA?
       emacs-lisp          ; drown in parentheses
       ;;erlang            ; an elegant language for a more civilized age
       ;;ess               ; emacs speaks statistics
       ;;factor
       ;;faust             ; dsp, but you get to keep your soul
       ;;fortran           ; in FORTRAN, GOD is REAL (unless declared INTEGER)
       ;;fsharp            ; ML stands for Microsoft's Language
       ;;fstar             ; (dependent) types and (monadic) effects and Z3
       ;;gdscript          ; the language you waited for
       ;;(go +lsp)         ; the hipster dialect
       ;;(graphql +lsp)    ; Give queries a REST
       ;;(haskell +lsp)    ; a language that's lazier than I am
       ;;hy                ; readability of scheme w/ speed of python
       ;;idris             ; a language you can depend on
       ;;json              ; At least it ain't XML
       ;;(java +lsp)       ; the poster child for carpal tunnel syndrome
       ;;javascript        ; all(hope(abandon(ye(who(enter(here))))))
       ;;julia             ; a better, faster MATLAB
       ;;kotlin            ; a better, slicker Java(Script)
       (latex              ; writing papers in Emacs has never been so fun
        +cdlatex           ; Enable cdlatex for fast math insertion
        +fold              ; Use TeX-fold to fold LaTeX macros to unicode
        +latexmk)          ; Use laexMk instead of Latex to compile documents
       ;;lean              ; for folks with too much to prove
       ;;ledger            ; be audit you can be
       ;;lua               ; one-based indices? one-based indices
       markdown            ; writing docs for people to ignore
       ;;nim               ; python + lisp at the speed of c
       ;;nix               ; I hereby declare "nix geht mehr!"
       ;;ocaml             ; an objective camel
       (org                ; organize your plain life in plain text
        +noter
        +dragndrop
        +roam2
        +gnuplot)
       ;;php               ; perl's insecure younger brother
       plantuml            ; diagrams for confusing people more
       ;;purescript        ; javascript, but functional
       ;;python            ; beautiful is better than ugly
       ;;qt                ; the 'cutest' gui framework ever
       ;;racket            ; a DSL for DSLs
       ;;raku              ; the artist formerly known as perl6
       ;;rest              ; Emacs as a REST client
       ;;rst               ; ReST in peace
       ;;(ruby +rails)     ; 1.step {|i| p "Ruby is #{i.even? ? 'love' : 'life'}"}
       ;;(rust +lsp)       ; Fe2O3.unwrap().unwrap().unwrap().unwrap()
       ;;scala             ; java, but good
       ;;(scheme +guile)   ; a fully conniving family of lisps
       sh                  ; she sells {ba,z,fi}sh shells on the C xor
       ;;sml
       ;;solidity          ; do you need a blockchain? No.
       ;;swift             ; who asked for emoji variables?
       ;;terra             ; Earth and Moon in alignment for performance.
       ;;web               ; the tubes
       ;;yaml              ; JSON, but readable
       ;;zig               ; C, but simpler

       :email
       ;;(mu4e +org +gmail)
       ;;notmuch
       ;;(wanderlust +gmail)

       :app
       ;;calendar
       ;;emms
       ;;everywhere        ; *leave* Emacs!? You must be joking
       ;;irc               ; how neckbeards socialize
       ;;(rss +org)        ; emacs as an RSS reader
       ;;twitter           ; twitter client https://twitter.com/vnought

       :config
       literate
       (default +bindings +smartparens))
#+end_src
#+html:</details>

*** Packages.el

#+begin_quote
Defines which external pacakges are loaded.
#+end_quote

#+html:<details><summary>Header</summary>
#+begin_src emacs-lisp :tangle packages.el
;; -*- no-byte-compile: t; -*-
;;; $DOOMDIR/packages.el

;; To install a package with Doom you must declare them here and run 'doom sync'
;; on the command line, then restart Emacs for the changes to take effect -- or
;; use 'M-x doom/reload'.


;; To install SOME-PACKAGE from MELPA, ELPA or emacsmirror:
;(package! some-package)

;; To install a package directly from a remote git repo, you must specify a
;; `:recipe'. You'll find documentation on what `:recipe' accepts here:
;; https://github.com/radian-software/straight.el#the-recipe-format
;(package! another-package
;  :recipe (:host github :repo "username/repo"))

;; If the package you are trying to install does not contain a PACKAGENAME.el
;; file, or is located in a subdirectory of the repo, you'll need to specify
;; `:files' in the `:recipe':
;(package! this-package
;  :recipe (:host github :repo "username/repo"
;           :files ("some-file.el" "src/lisp/*.el")))

;; If you'd like to disable a package included with Doom, you can do so here
;; with the `:disable' property:
;(package! builtin-package :disable t)

;; You can override the recipe of a built in package without having to specify
;; all the properties for `:recipe'. These will inherit the rest of its recipe
;; from Doom or MELPA/ELPA/Emacsmirror:
;(package! builtin-package :recipe (:nonrecursive t))
;(package! builtin-package-2 :recipe (:repo "myfork/package"))

;; Specify a `:branch' to install a package from a particular branch or tag.
;; This is required for some packages whose default branch isn't 'master' (which
;; our package manager can't deal with; see radian-software/straight.el#279)
;(package! builtin-package :recipe (:branch "develop"))

;; Use `:pin' to specify a particular commit to install.
;(package! builtin-package :pin "1a2b3c4d5e")


;; Doom's packages are pinned to a specific commit and updated from release to
;; release. The `unpin!' macro allows you to unpin single packages...
;(unpin! pinned-package)
;; ...or multiple packages
;(unpin! pinned-package another-pinned-package)
;; ...Or *all* packages (NOT RECOMMENDED; will likely break things)
;(unpin! t)
#+end_src
#+html:</details>

*** Config.el

#+begin_quote
Defines the user's custom configuration.
#+end_quote

#+html:<details><summary>Header</summary>
#+begin_src emacs-lisp
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-

;; Place your private configuration here!

;; sync' after modifying this file!
;; Whenever you reconfigure a package, make sure to wrap your config in an
;; `after!' block, otherwise Doom's defaults may override your settings. E.g.
;;
;;   (after! PACKAGE
;;     (setq x y))
;;
;; The exceptions to this rule:
;;
;;   - Setting file/directory variables (like `org-directory')
;;   - Setting variables which explicitly tell you to set them before their
;;     package is loaded (see 'C-h v VARIABLE' to look up their documentation).
;;   - Setting doom variables (which start with 'doom-' or '+').
;;
;; Here are some additional functions/macros that will help you configure Doom.
;;
;; - `load!' for loading external *.el files relative to this one
;; - `use-package!' for configuring packages
;; - `after!' for running code after a package has loaded
;; - `add-load-path!' for adding directories to the `load-path', relative to
;;   this file. Emacs searches the `load-path' when you load packages with
;;   `require' or `use-package'.
;; - `map!' for binding new keys
;;
;; To get information about any of these functions/macros, move the cursor over
;; the highlighted symbol at press 'K' (non-evil users must press 'C-c c k').
;; This will open documentation for it, including demos of how they are used.
;; Alternatively, use `C-h o' to look up a symbol (functions, variables, faces,
;; etc).
;;
;; You can also try 'gd' (or 'C-c c d') to jump to their definition and see how
;; they are implemented.
#+end_src
#+html:</details>

** Variables
*** TODO Personal Information

Define an identity for use with GPG, email, and file templates/snippets.

#+begin_src emacs-lisp
(setq user-full-name "Jake Turner"
      user-mail-address "john@doe.com")
#+end_src

** Appearance
*** Theme

I typically use the [[https://draculatheme.com/][Dracula]] theme, but I'm experimenting with others:

#+html:<details><summary>Themes I Like</summary>
- Doom One
- Doom Vibrant
- Doom Iosvkem
- Doom Dracula
- Doom Palenight
- Doom Henna
- Doom Ayu-Mirage and Doom Ayu-Dark
- Doom Material Dark
- Doom Molokai
- Doom Monokai
- Doom Old Hope
- Doom Horizon
- Doom 1337
- Doom Material
- Doom Oceanic Next
- Doom Xcode
#+html:</details>

#+begin_src emacs-lisp
(setq doom-theme 'doom-Iosvkem)
#+end_src

#+begin_src emacs-lisp :tangle no
;(setq doom-theme 'doom-dracula
;      doom-dracula-brighter-modeline t
;      doom-dracula-colorful-headers t)
#+end_src

*** Font

I'm also experimenting with fonts. Although, Jetbrains Mono and Fira Code are staples.

#+begin_src emacs-lisp
(when IS-MAC
  (setq doom-font (font-spec :family "Jetbrains Mono" :size 12)
        doom-big-font (font-spec :family "Jetbrains Mono" :size 16)
        doom-variable-pitch-font (font-spec :family "Overpass" :size 14)
        doom-unicode-font (font-spec :family "JuliaMono")
        doom-serif-font (font-spec :family "IBM Plex Mono" :size 10 :weight 'light)))
#+end_src

#+begin_src emacs-lisp
(when IS-LINUX
  (setq doom-font (font-spec :family "Jetbrains Mono" :size 12)
        doom-big-font (font-spec :family "Jetbrains Mono" :size 16)
        ;;doom-variable-pitch-font (font-spec :family "Overpass" :size 14)
        ;;doom-unicode-font (font-spec :family "JuliaMono")
        ;;doom-serif-font (font-spec :family "IBM Plex Mono" :size 10 :weight 'light)
        ))
#+end_src

*** Cursor

Draw the block cursor as wide as the glyph under it.

#+begin_src emacs-lisp
(setq-default x-stretch-cursor t)
#+end_src

*** Frames
**** Add Transparency

I add transparency to Doom's window to allow my wallpaper to show through it.

On Linux, this effect probably requires a compositor. I use [[https://github.com/yshui/picom][Picom]].

#+begin_src emacs-lisp
(add-to-list 'default-frame-alist '(alpha . 93)) ; [0-100]
#+end_src

**** Start Maximized

#+begin_src emacs-lisp
(add-to-list 'default-frame-alist '(fullscreen . maximized))
#+end_src

*** Line Numbers

I use relative visual line numbers to move around.

#+begin_src emacs-lisp
(setq display-line-numbers-type 'visual)
#+end_src

** Behavior
*** Enable Evil Fine Undo

By default, all changes made while using insert mode are considered one. This setting enables a more granular undo scheme.

#+begin_src emacs-lisp
(setq evil-want-fine-undo t)
#+end_src

*** Enable Subword Mode

Allows iterating through CamelCase words.

#+begin_src emacs-lisp
(global-subword-mode 1)
#+end_src

*** Enable Evil Visual Line Movement

Allow lines that wrap around the edge of the screen (visual lines) to count as "physical" lines. Enables you to use =j= and =k= to move up and down through wrapped lines.

First, enable the following in =init.el=:

#+begin_src emacs-lisp :tangle no :noweb-ref early-init
(setq evil-respect-visual-line-mode t)
#+end_src

**** Fix Evil's Visual Line Over/Undershooting

There's a long standing issue between =visual lines= and =Evil=. When using a prefix argument (line count) with Evil's next/previous visual line, often it will over or under shoot the desired line. As far as I have researched, there is no next/previous line commands that just work.

To solve this, I created two commands to repeatedly run Evil's visual line commands instead of letting those commands repeat themselves. This works perfectly to solve the issue and I always reach my desired line.

#+begin_src emacs-lisp
(defun noncog/evil-previous-visual-line (&optional count)
  "Repeat evil-previous-visual-line COUNT times."
  (interactive "P")
  (let ((total (or count 1))
        (counter 0))
    (while (< counter total)
      (evil-previous-visual-line)
      (setq counter (+ counter 1)))))
#+end_src

#+begin_src emacs-lisp
(defun noncog/evil-next-visual-line (&optional count)
  "Repeat evil-next-visual-line COUNT times."
  (interactive "P")
  (let ((total (or count 1))
        (counter 0))
    (while (< counter total)
      (evil-next-visual-line)
      (setq counter (+ counter 1)))))
#+end_src

#+begin_src emacs-lisp
(define-key evil-motion-state-map "j" 'noncog/evil-next-visual-line)
(define-key evil-motion-state-map "k" 'noncog/evil-previous-visual-line)
#+end_src

#+begin_src emacs-lisp
(define-key evil-normal-state-map "j" 'noncog/evil-next-visual-line)
(define-key evil-normal-state-map "k" 'noncog/evil-previous-visual-line)
#+end_src

#+begin_src emacs-lisp
;; TODO: Add evil-visual-state-map binds.
#+end_src

*** Prevent Pasting From Adding to Kill Ring

Whenever you overwrite text in visual mode, prevent adding that text to the kill ring. This enables you to paste the same thing multiple times without losing it.

#+begin_src emacs-lisp
(setq evil-kill-on-visual-paste nil)
#+end_src

*** Focus Windows After Splitting

These settings causes the newly created split windows to gain focus.

#+begin_src emacs-lisp
(setq evil-split-window-below t
      evil-vsplit-window-right t)
#+end_src

*** Autoload File Changes

#+begin_src emacs-lisp
(global-auto-revert-mode 1)
#+end_src

*** Change Literate Config Name

I change my Org literate config file name from =config.org= to =README.org= in =init.el= for displaying it on GitHub.

#+begin_src emacs-lisp :tangle no :noweb-ref early-init
(setq +literate-config-file "~/.config/doom/README.org")
#+end_src

*** Scrolling

This is an area of contention for me. Eventually I would like to overhaul this behavior entirely.

#+begin_src emacs-lisp
(define-minor-mode prot/scroll-center-cursor-mode
  "Toggle centred cursor scrolling behavior"
  :init-value nil
  :lighter " S="
  :global nil
  (if prot/scroll-center-cursor-mode
      (setq-local scroll-margin (* (frame-height) 2)
                  scroll-conservatively 0
                  maximum-scroll-margin 0.5)
    (dolist (local '(scroll-preserve-screen-position
                     scroll-conservatively
                     maximum-scroll-margin
                     scroll-margin))
      (kill-local-variable `,local))))
#+end_src

**** Set Scroll Amount

#+begin_src emacs-lisp
(setq-default evil-scroll-count 5)
#+end_src
*** Window Manager Integration

I love tiling window managers. I currently use [[https://i3wm.org][i3]] on Linux and [[https://github.com/koekeishiya/yabai][Yabai]] on macOS. These configs allow me to seamlessly use some of their windowing controls inside of Emacs.

**** How It Works

This method requires some way for your window manager to pass the keybinds to Emacs whenever it's the focused window. Then, you just bind those keys in Emacs to the windowing functions defined here.

=NOTE=: i3 requires the use of a [[https://github.com/noncog/.dotfiles/blob/main/.config/i3/scripts/i3-emacs-mode.pl][script]] and a dedicated Emacs mode to know when Emacs is the focused window and change use different keybinds. Yabai supports this natively.

**** Functions

When a window can't be found in that direction in Emacs, it passes the window focusing command to the window manager.

#+begin_src emacs-lisp
(defun wm-focus-on-error (direction move-fn)
    (when IS-LINUX
     (condition-case nil (funcall move-fn)
       (user-error (start-process "wm" nil "i3-msg" "focus" direction))))
     (when IS-MAC
      (condition-case nil (funcall move-fn)
        (user-error (start-process "wm" nil "yabai" "-m" "window" "--focus" direction)))))
#+end_src

#+begin_src emacs-lisp
(defun wm-window-left ()
  (interactive)
  (let ((direction (cond (IS-LINUX "left") (IS-MAC "west"))))
    (wm-focus-on-error direction #'windmove-left)))

(defun wm-window-right ()
  (interactive)
  (let ((direction (cond (IS-LINUX "right") (IS-MAC "east"))))
    (wm-focus-on-error direction #'windmove-right)))

(defun wm-window-up ()
  (interactive)
  (let ((direction (cond (IS-LINUX "up") (IS-MAC "north"))))
    (wm-focus-on-error direction #'windmove-up)))

(defun wm-window-down ()
  (interactive)
  (let ((direction (cond (IS-LINUX "down") (IS-MAC "south"))))
    (wm-focus-on-error direction #'windmove-down)))
#+end_src

**** Keybinds
***** macOS

#+begin_src emacs-lisp
(when IS-MAC
  (map! "s-h" #'wm-window-left
        "s-j" #'wm-window-down
        "s-k" #'wm-window-up
        "s-l" #'wm-window-right
        "s-=" #'balance-windows
        "s-v" #'evil-window-vsplit
        "s-s" #'evil-window-split
        "s-Q" #'evil-quit))
#+end_src

***** Linux

#+begin_src emacs-lisp
(when IS-LINUX
  (map! "s-h" #'wm-window-left
        "s-j" #'wm-window-down
        "s-k" #'wm-window-up
        "s-l" #'wm-window-right
        ;; add workspace balancing python script.
        ;; add window splitting.
        "s-Q" #'evil-quit))
#+end_src

***** Emacs to Other Windows

These binds allow you to use Doom's window switching commands to focus windows outside of Emacs.

#+begin_src emacs-lisp
(map! :leader "w h" #'wm-window-left)
(map! :leader "w j" #'wm-window-down)
(map! :leader "w k" #'wm-window-up)
(map! :leader "w l" #'wm-window-right)
#+end_src

** Keybinds
*** Mac Modifier Keys

I translate the Mac modifier keys to be equivalent to my Linux/Windows modifiers.

#+begin_src emacs-lisp
(when IS-MAC (setq mac-command-modifier 'control ; Maps Command -> Control
                    mac-control-modifier 'meta   ; Maps Control -> Alt (Meta)
                    mac-option-modifier 'super)) ; Maps Option -> Super
#+end_src

* Beacon
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
[[https://github.com/Malabarba/beacon][Beacon]] is a minor mode that highlights the current line after jumping around. Never lose your cursor (point) again!
#+end_quote

** Package

#+html:<details><summary>Source</summary>
#+begin_src emacs-lisp :tangle packages.el
(package! beacon
  :recipe (:host github :repo "Malabarba/beacon")
  :pin "85261a928ae0ec3b41e639f05291ffd6bf7c231c")
#+end_src
#+html:</details>

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :noweb yes
(use-package! beacon
  :init
  <<beacon-init>>
  )
(beacon-mode 1)
#+end_src
#+html:</details>

** Appearance

#+begin_src emacs-lisp :tangle no :noweb-ref beacon-init
;; Appearance
#+end_src

*** Color

#+begin_src emacs-lisp :tangle no :noweb-ref beacon-init
(setq beacon-color "#61bfff")
#+end_src

** Behavior

#+begin_src emacs-lisp :tangle no :noweb-ref beacon-init
;; Behavior
#+end_src

*** Size and Duration

#+begin_src emacs-lisp :tangle no :noweb-ref beacon-init
(setq beacon-size 40
      beacon-blink-duration 0.3
      beacon-blink-delay 0.5)
#+end_src

*** When To Blink

#+begin_src emacs-lisp :tangle no :noweb-ref beacon-init
(setq beacon-blink-when-buffer-changes t
      beacon-blink-when-window-scrolls nil
      beacon-blink-when-focused nil)
#+end_src

* Which-Key
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
[[https://github.com/justbur/emacs-which-key][Which-Key]] is a minor-mode for Emacs that displays keybinds for your currently unfinished inputs.
#+end_quote

** Package

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :noweb yes
(use-package! which-key
  :defer t
  :config
  <<which-key-config>>
  )
#+end_src
#+html:</details>

** Fixes

#+begin_src emacs-lisp :tangle no :noweb-ref which-key-config
;; Fixes
#+end_src

*** Fix Height Issue

I was having an issue using =emacsclient= where which-key was being cut off below the modeline. A simple solution ([[https://github.com/justbur/emacs-which-key/issues/231#issuecomment-627503184][source]]) is to add spaces below the keybinds. Realistically, this doesn't work everywhere but it's good enough for now.

#+begin_src emacs-lisp :tangle no :noweb-ref which-key-config
;; Add an extra line to work around bug in which-key imprecise
(defun add-which-key-line (f &rest r) (progn (apply f (list (cons (+ 1 (car (car r))) (cdr (car r)))))))
(advice-add 'which-key--show-popup :around #'add-which-key-line)
#+end_src

*** Remove Evil Prefixes

Replace long evil function names with a unicode symbol.

#+begin_src emacs-lisp :tangle no :noweb-ref which-key-config
(setq which-key-allow-multiple-replacements t)
(pushnew!
 which-key-replacement-alist
 '(("" . "\\`+?evil[-:]?\\(?:a-\\)?\\(.*\\)") . (nil . " \\1"))
 '(("\\`g s" . "\\`evilem--?motion-\\(.*\\)") . (nil . " \\1")))
#+end_src

* Doom Modeline
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
[[https://github.com/seagle0128/doom-modeline][Doom-Modeline]] is a fancy and fast mode-line inspired by minimalism design.
#+end_quote

** Package

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :noweb yes
(use-package! doom-modeline
  :defer t
  :config
  <<doom-modeline-config>>
  )
#+end_src
#+html:</details>

** Appearance

#+begin_src emacs-lisp :tangle no :noweb-ref doom-modeline-config
;; Appearance
#+end_src

*** General

#+begin_src emacs-lisp :tangle no :noweb-ref doom-modeline-config
(setq doom-modeline-height 35
      doom-modeline-major-mode-icon (display-graphic-p)
      doom-modeline-major-mode-color-icon (display-graphic-p)
      auto-revert-check-vc-info t
      doom-modeline-vcs-max-length 60
      ;doom-modeline-github t
      ;doom-modeline-github-interval 60
      ;doom-modeline-buffer-file-name-style 'relative-to-project
      doom-modeline-display-default-persp-name t
      doom-modeline-persp-name t
      doom-modeline-persp-icon t
    ;;   (doom-modeline-def-modeline 'main
    ;;     '(bar modals workspace-name window-number persp-name buffer-position selection-info buffer-info matches remote-host debug vcs matches)
    ;; '(github mu4e grip gnus checker misc-info repl lsp " "))
      )
#+end_src

* Doom Dashboard
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
Doom-Dashboard adds a customizable dashboard as the default buffer.
#+end_quote

** Package

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :noweb yes
(use-package! doom-dashboard
  :defer t
  :config
  <<doom-dashboard-config>>
  )
#+end_src
#+html:</details>

** Keybinds

#+begin_src emacs-lisp :tangle no :noweb-ref doom-dashboard-config
;; Keybinds
#+end_src

*** Open the Dashboard

#+begin_src emacs-lisp :tangle no :noweb-ref doom-dashboard-config
(map! :leader :desc "Dashboard" "d" #'+doom-dashboard/open)
#+end_src

* Persp-Mode
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
[[https://github.com/Bad-ptr/persp-mode.el][Persp-Mode]] is used by Doom to manage workspaces across frames.
#+end_quote

** Package

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :noweb yes
(use-package! persp-mode
  :defer t
  :config
  <<persp-config>>
  )
#+end_src
#+html:</details>

** Fixes

#+begin_src emacs-lisp :tangle no :noweb-ref persp-config
;; Fixes
#+end_src

*** Prevent New Workspaces on New Frames

By default, when using =emacsclient=, Doom creates a new workspace for each client frame. I don't want this clutter, I'll make a workspace if I need one.

#+begin_src emacs-lisp :tangle no :noweb-ref persp-config
(setq persp-emacsclient-init-frame-behaviour-override nil)
#+end_src

* Vertico
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
[[https://github.com/minad/vertico][Vertico]] provides a performant and compatible vertical completion UI for Emacs. It's mostly used for completions in the minibuffer.
#+end_quote

** Package

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :noweb yes
(use-package! vertico
  :defer t
  :config
  <<vertico-config>>
  )
#+end_src
#+html:</details>

** Behavior

#+begin_src emacs-lisp :tangle no :noweb-ref vertico-config
;; Behavior
#+end_src

*** Alphabetical Sort Order

#+begin_src emacs-lisp :tangle no :noweb-ref vertico-config
(setq vertico-sort-function #'vertico-sort-history-alpha)
#+end_src

** Keybinds

#+begin_src emacs-lisp :tangle no :noweb-ref vertico-config
;; Keybinds
#+end_src

*** Add Emacs Style Scroll Keys to Minibuffer

Add "regular" style scrolling keybinds to Vertico for the minibuffer.

#+begin_src emacs-lisp :tangle no :noweb-ref vertico-config
(map! :map vertico-map "C-u" #'scroll-down-command
      :map vertico-map "C-d" #'scroll-up-command)
#+end_src

* Company
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
[[http://company-mode.github.io][Company]] (complete anything) is a text completion framework for Emacs. It uses frontends and backends to retrieve and display completion candidates. It's mostly used for in-buffer completions.
#+end_quote

** Package

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :noweb yes
(use-package! company
  :defer t
  :config
  <<company-config>>
  )
#+end_src
#+html:</details>

** Behavior

#+begin_src emacs-lisp :tangle no :noweb-ref company-config
;; Behavior
#+end_src

*** General

#+begin_src emacs-lisp :tangle no :noweb-ref company-config
(setq company-idle-delay 0.3
      company-tooltip-limit 10
      company-minimum-prefix-length 1)
#+end_src

*** Org-mode Backend

#+begin_src emacs-lisp :tangle no :noweb-ref company-config
(set-company-backend! 'org-mode
  '(company-capf company-files :with company-yasnippet))
#+end_src

*** Sh-mode Backend

#+begin_src emacs-lisp :tangle no :noweb-ref company-config
(set-company-backend! 'sh-mode
  '(company-shell company-files :with company-yasnippet))
#+end_src

* Yasnippet
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
[[https://github.com/joaotavora/yasnippet][Yasnippet]] is a template system for Emacs. It allows you to type an abbreviation and automatically expand it.
#+end_quote

** Package

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :noweb yes
(use-package! yasnippet
  :defer t
  :config
  <<yasnippet-config>>
  )
#+end_src
#+html:</details>

** Resources
- [[https://joaotavora.github.io/yasnippet/index.html][Yasnippet Documentation]]
- [[https://github.com/doomemacs/snippets][Doom Snippets]]

** Behavior

#+begin_src emacs-lisp :tangle no :noweb-ref yasnippet-config
;; Behavior
#+end_src

*** Enable Nested Snippets

#+begin_src emacs-lisp :tangle no :noweb-ref yasnippet-config
(setq yas-triggers-in-field t)
#+end_src

* Projectile
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
[[https://github.com/bbatsov/projectile][Projectile]] is a project interaction library for Emacs. It provides easy project management and navigation.
#+end_quote

** Package

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :noweb yes
<<pre-projectile>>

(use-package! projectile
  :defer t
  :config
  <<projectile-config>>
  )

<<post-projectile>>
#+end_src
#+html:</details>

** Variables

#+begin_src emacs-lisp :tangle no :noweb-ref projectile-config
;; Variables
#+end_src

*** Projects Directory

I use the same convention for project location on each OS I use.

#+begin_src emacs-lisp :tangle no :noweb-ref pre-projectile
(setq projectile-project-search-path '("~/Projects"))
#+end_src

** Behavior

#+begin_src emacs-lisp :tangle no :noweb-ref projectile-config
;; Behavior
#+end_src

*** Compile C++ CMake Project in Vterm

This is a quick and dirty setup I did to get a dumb C++ project going. I need to actually setup my compile commands.

#+begin_src emacs-lisp :tangle no :noweb-ref projectile-config
(defun +my/compile-in-vterm ()
  "Run `compile-command' in vterm in current project's root directory"
  (interactive)
  (projectile-run-vterm)
  (vterm-send-string "cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug && cmake --build build --config Release && ./build/intelligent-motion")
  (vterm-send-return))
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref post-projectile
(defun +mypopup-kill (some-popup-window)
  (progn (+popup--kill-buffer (window-buffer some-popup-window) 0.1)) t)
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref post-projectile
(defun +mypopup-resize (some-popup-window)
  (fit-window-to-buffer some-popup-window nil 19 nil nil t))
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref post-projectile
(map! :map project-prefix-map
      :leader
      :desc "Run project in vterm"
      "p v" #'+my/compile-in-vterm)
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref post-projectile
(set-popup-rule! "^*vterm intelligent-motion*" :size #'+mypopup-resize :quit #'+mypopup-kill :autosave 'ignore)
#+end_src

** Keybinds

#+begin_src emacs-lisp :tangle no :noweb-ref projectile-config
;; Keybinds
#+end_src

*** List Uncommitted Projects

I add a keybind to quickly view which projects have uncommitted changes.

#+begin_src emacs-lisp :tangle no :noweb-ref post-projectile
(map! :map project-prefix-map
      :leader
      :desc "List dirty projects"
      "p l" #'projectile-browse-dirty-projects)
#+end_src

* Treemacs
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
[[https://github.com/Alexander-Miller/treemacs][Treemacs]] is a file and project explorer in a tree sidebar similar to Neotree and Nerdtree for Vim.
#+end_quote

** Package

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :noweb yes
(use-package! treemacs
  :defer t
  :config
  <<treemacs-config>>
  )
#+end_src
#+html:</details>

** Appearance

#+begin_src emacs-lisp :tangle no :noweb-ref treemacs-config
;; Appearance
#+end_src

*** Enable Doom Themes Colors

#+begin_src emacs-lisp :tangle no :noweb-ref treemacs-config
(setq doom-themes-treemacs-theme "doom-colors")
#+end_src

** Behavior

#+begin_src emacs-lisp :tangle no :noweb-ref treemacs-config
;; Behavior
#+end_src

*** Enable Follow Mode

#+begin_src emacs-lisp :tangle no :noweb-ref treemacs-config
(treemacs-follow-mode 1)
(treemacs-tag-follow-mode 1)
#+end_src

*** Reduce Follow Delay

#+begin_src emacs-lisp :tangle no :noweb-ref treemacs-config
(setq treemacs-file-follow-delay 0.2
      treemacs-tag-follow-delay 0.3)
#+end_src

*** Recenter After Following

#+begin_src emacs-lisp :tangle no :noweb-ref treemacs-config
;; (setq treemacs-recenter-after-tag-follow 'always
;;       treemacs-recenter-after-file-follow 'always
;;       treemacs-recenter-distance 0.9
;;       treemacs-follow-recenter-distance 0.9)
#+end_src

* Magit
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
[[https://magit.vc][Magit]] is a powerful Git interface for Emacs. "It fills the glaring gap between the Git command-line interface and various GUIs, letting you perform trivial as well as elaborate version control tasks with just a couple of mnemonic key presses."
#+end_quote

** Package

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :noweb yes
(use-package! magit
  :defer t
  :config
  <<magit-config>>
  )
#+end_src
#+html:</details>

** Behavior

#+begin_src emacs-lisp :tangle no :noweb-ref magit-config
;; Behavior
#+end_src

*** Define Repositories Directory

Defining this directory enables =magit-status= to search for a repository when not inside of one already. It also enables =magit-list-repositories= through the keybind =SPC g l r=.

#+begin_src emacs-lisp :tangle no :noweb-ref magit-config
(setq magit-repository-directories
      '(("~/Projects" . 1)))
#+end_src

*** Dotfiles Git Bare Repository Support

Out of the box Magit doesn't support =--bare= repositories, which are commonly used to manage dotfiles. I've extended an old method of loading the corresponding Git environment variables when relevant directories are open. It simply gets a list of all your dotfiles from the repository and whenever you're in their releveant directory it modifies the Magit/Git environment variable to support the bare repository whenever you need it.

This method works everywhere and seamlessly integrates managing my dotfiles into Magit. It could easily be extended to support multiple bare repositories as well.

#+begin_src emacs-lisp :tangle no :noweb-ref magit-config
(defun my/magit-process-environment (env)
  "Detect and set git -bare repo env vars when in tracked dotfile directories."
  (let* ((default (file-name-as-directory (expand-file-name default-directory)))
         (git-dir (expand-file-name "~/.dotfiles/"))
         (work-tree (expand-file-name "~/"))
         (dotfile-dirs
          (-map (apply-partially 'concat work-tree)
                (-uniq (-keep #'file-name-directory (split-string (shell-command-to-string
                (format "/usr/bin/git --git-dir=%s --work-tree=%s ls-tree --full-tree --name-only -r HEAD"
                        git-dir work-tree))))))))
    (push work-tree dotfile-dirs)
    (when (member default dotfile-dirs)
      (push (format "GIT_WORK_TREE=%s" work-tree) env)
      (push (format "GIT_DIR=%s" git-dir) env)))
  env)
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref magit-config
(advice-add 'magit-process-environment
            :filter-return #'my/magit-process-environment)
#+end_src
*** Commit Linter

I've developed a custom Git commit linter based on [[https://github.com/angular/angular/blob/main/CONTRIBUTING.md#-commit-message-format][Angular]] and [[https://www.conventionalcommits.org/][Conventional Commits]]. The code is based on this [[https://www.adventuresinwhy.com/post/commit-message-linting/][this]] post but highly modified to conform to my chosen conventions.

**** Define Convention Checks

This option parallels =git-commit-style-convention-checks= from Magit. This is a custom list of checks that allows the user to specify which will be performed by our checker. It's currently set to check all of my conventions.

#+begin_src emacs-lisp :tangle no :noweb-ref magit-config
(defcustom my-git-commit-style-convention-checks '(summary-has-type
                                                   summary-type-lowercase
                                                   summary-has-separator
                                                   summary-scope-lowercase
                                                   summary-title-starts-with-lowercase
                                                   summary-title-uses-imperative-verb
                                                   summary-title-not-end-in-punctuation)
  "List of checks performed by `my-git-commit-check-style-conventions'.
Valid members are `summary-has-type',  `summary-type-lowercase',
`summary-has-separator', `summary-scope-lowercase',
`summary-title-starts-with-lowercase', `summary-title-uses-imperative-verb', and
`summary-title-not-end-in-punctuation'.
That function is a member of `git-commit-finish-query-functions'."
  :options '(summary-has-type
             summarty-type-lowercase
             summary-has-separator
             summary-scope-lowercase
             summary-title-starts-with-lowercase
             summary-title-uses-imperative-verb
             summary-title-not-end-in-punctuation)
  :type '(list :convert-widget custom-hook-convert-widget)
  :group 'git-commit)
#+end_src

**** Define Convention Checker

This function parallels =git-commit-check-style-conventions= from Magit. It checks each convention present in the list defined above.

#+begin_src emacs-lisp :tangle no :noweb-ref magit-config
(defun my-git-commit-check-style-conventions (&optional force) ; TODO check using force
  "Check for violations of certain basic style conventions.

For each violation ask the user if she wants to proceed anyway.
Option `my-git-commit-check-style-conventions' controls which
conventions are checked."
  (save-excursion
    (goto-char (point-min))
    (re-search-forward (git-commit-summary-regexp) nil t)
    (let* ((summary (match-string 1))
           (commit-type (substring summary 0 (string-match-p "[()!:]" summary)))
           (commit-separator-check (string-match-p "^.*[^[:blank:]]:" summary))
           (commit-separator-location (string-match-p ":" summary))
           (commit-scope (if (string-match-p "(.*)[!:]" summary) (substring summary (1+ (string-match-p "(" summary)) (string-match-p ")!?:?" summary)) nil))
           (commit-title (if commit-separator-check (substring summary (+ commit-separator-location 2)) "undetectable-title"))
           (lowercase-title-first-word (downcase (substring commit-title 0 (string-match-p "[[:blank:]]" commit-title)))))
      (and (or (not (memq 'summary-type-lowercase my-git-commit-style-convention-checks))
               (let ((case-fold-search nil)) (string-match-p "^[[:lower:]]*$" commit-type))
               (y-or-n-p "Commit type is not lowercase. Commit anyway?"))
           (or (not (memq 'summary-has-type my-git-commit-style-convention-checks))
               (car (member commit-type (get-commit-types)))
               (when (y-or-n-p "Commit type is invalid. Commit anyway?")
                 (when (y-or-n-p (format "Add `%s' to list of commit types?" commit-type))
                   (with-temp-buffer
                     (insert commit-type)
                     (insert "\n")
                     (write-region (point-min) (point-max) commit-types-file t))) t))
           (or (not (memq 'summary-has-separator my-git-commit-style-convention-checks))
               (not (null commit-separator-check))
               (y-or-n-p "Commit title has invalid separator. Commit anyway?"))
           (or (not (memq 'summary-scope-lowercase my-git-commit-style-convention-checks))
               (when (or (not commit-scope) (string-empty-p commit-scope)) (y-or-n-p "Commit scope is empty. Commit anyway?"))
               (when commit-scope (if (let ((case-fold-search nil)) (string-match-p "^[[:lower:]]*$" commit-scope)) t
                                    (y-or-n-p "Commit scope invalid. Only lowercase letters allowed. Commit anyway?"))))
           (or (not (memq 'summary-title-starts-with-lowercase my-git-commit-style-convention-checks))
               (if (not commit-separator-check) (y-or-n-p "Title undetectable. Commit anyway?") (let ((case-fold-search nil))
                 (string-match-p "^[[:lower:]]" commit-title)))
               (y-or-n-p "Commit title does not start with lowercase letter. Commit anyway?"))
           (or (not (memq 'summary-title-uses-imperative-verb my-git-commit-style-convention-checks))
               (if (not commit-separator-check) (y-or-n-p "Imperative verb undetectable. Commit anyway?")
                 (car (member lowercase-title-first-word (get-imperative-verbs))))
               (when (y-or-n-p "Commit title should use imperative verb. Does it?")
                 (when (y-or-n-p (format "Add `%s' to list of commit types?" lowercase-title-first-word))
                   (with-temp-buffer
                     (insert lowercase-title-first-word)
                     (insert "\n")
                     (write-region (point-min) (point-max) imperative-verbs-file t))) t))
           (or (not (memq 'summary-title-not-end-in-punctuation my-git-commit-style-convention-checks))
              (not (string-match-p "[\\.!\\?;,:]$" commit-title))
              (y-or-n-p "Commit title ends with punctuation. Commit anyway?"))))))
#+end_src

**** Commit Types File Loader

To check for compliance with my conventions, two lists must be kept to compare words in the commit summary message against. Those are: the commit types and imperative verbs lists.

#+begin_src emacs-lisp :tangle no :noweb-ref magit-config
(setq commit-types-file "~/.config/git/commit/commit-types")
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref magit-config
(defun get-commit-types ()
  "Return a list of commit types."
  (let ((file-path commit-types-file))
    (with-temp-buffer
      (insert-file-contents file-path)
      (split-string (buffer-string) "\n" t))))
#+end_src

**** Imperative Verbs File Loader

#+begin_src emacs-lisp :tangle no :noweb-ref magit-config
(setq imperative-verbs-file "~/.config/git/commit/imperative-verbs")
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref magit-config
(defun get-imperative-verbs ()
  "Return a list of imperative verbs."
  (let ((file-path imperative-verbs-file))
    (with-temp-buffer
      (insert-file-contents file-path)
      (split-string (buffer-string) "\n" t))))
#+end_src

**** Commit Template

I add the following template to my Git commit message to remind me of my commits standard. This is not meant to be exhaustive, only a detailed reminder.

#+begin_example

#------------------------------------------------------------------------
# Subject line: type(scope): description
#------------------------------------------------------------------------
# Types: Required noun describing commit type.
#
#    build - Changes build system or external dependencies.
#    chore - Changes external user won't see. (configs/internal task)
#       ci - Changes CI configuration files or scripts.
#     docs - Changes documentation only.
#     feat - A new feature.
#      fix - A bug fix.
#     perf - Change that improves performance.
# refactor - Change that neither fixes a bug nor adds a feature.
#   revert - Change that corrects a commit.
#    style - Changes don't affect meaning. (white-space, format, etc.)
#     test - Adds test or corrects existing test.
#
#------------------------------------------------------------------------
# Scope:       Optional noun describing relevant section of codebase.
#              Must be inside parenthesis if used.
#------------------------------------------------------------------------
# Description: Required short summary of the changes.
#              Must follow a colon after type or scope.
#              No ending punctuation.
#------------------------------------------------------------------------
# Body:        Optional longer description providing additional context.
#              Must begin one blank line after subject/title.
#              Free-form, may consist of newlines and paragraphs.
#------------------------------------------------------------------------
# Footer:      Optional git trailer.
#              Must begin one blank line after body paragraph.
#              Tokens must use '-' in place of white-space.
#              May contain spaces and newlines.
#
# References:  Links information/issues/commits/PRs.
#              Closed issues should be listed on separate line.
#
# BREAKING CHANGE: Must be indicated in title or footer.
#                  If title: Indicate using ! before colon. (!:)
#                            Must use body to describe.
#                  If footer: Must be uppercase text.
#                             Must have a colon and spaced description.
#                             Description should be lowercase.
#------------------------------------------------------------------------
#+end_example

And I enable it in my Git config using this.

#+begin_example
[commit]
    template = ~/.config/git/commit-message
#+end_example

**** Set Max Lengths

These are commonly enforced commit message length standards and the last of my standard's requirements.

#+begin_src emacs-lisp :tangle no :noweb-ref magit-config
(setq git-commit-summary-max-length 50)                  ; Maximum title (summary) length.
(setq git-commit-fill-column 72)                         ; Description column limit.
#+end_src

**** Hook Commit Linter

And finally, the custom standards checker is hooked into Magit's finish commit function.

#+begin_src emacs-lisp :tangle no :noweb-ref magit-config
(add-hook 'after-save-hook 'magit-after-save-refresh-status t)
(add-to-list 'git-commit-finish-query-functions
             #'my-git-commit-check-style-conventions)
#+end_src

* Vterm
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
[[https://github.com/akermu/emacs-libvterm][Vterm]] is the most capable Emacs terminal emulator with unrivaled performance and compatibility.
#+end_quote

** Package

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :noweb yes
(use-package! vterm
  :defer t
  :config
  <<vterm-config>>
  )
#+end_src
#+html:</details>

** Keybinds

#+begin_src emacs-lisp :tangle no :noweb-ref vterm-config
;; Keybinds
#+end_src

*** Fix =C-backspace=

I love this keybind, more things should use it. Including vterm... [[https://github.com/elken/doom#fix-c-backspace][Source]]

#+begin_src emacs-lisp :tangle no :noweb-ref vterm-config
(define-key vterm-mode-map (kbd "<C-backspace>") (lambda () (interactive) (vterm-send-key (kbd "C-w"))))
#+end_src

* Visual Fill Column
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
[[https://codeberg.org/joostkremers/visual-fill-column][Visual-Fill-Column]] is an Emacs minor mode that enables word wrapping at a column and centering the buffer content.
#+end_quote

I use this to center buffers (org-mode) primarily. I get this package by enabling the =wordwrap= module.

** Package

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :noweb yes
(use-package! visual-fill-column
  :custom
  (visual-fill-column-width 120)
  (visual-fill-column-center-text t)
  :hook (org-mode . visual-fill-column-mode))
#+end_src
#+html:</details>

* Org
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
[[https://orgmode.org/][Org Mode]] describes itself as, "a GNU Emacs major mode for keeping notes, authoring documents, computational notebooks, literate programming, maintaining to-do lists, planning projects, and more — in a fast and effective plain text system."
#+end_quote

** Package

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :noweb yes
<<pre-org>>

(use-package! org
  :defer t
  :config
  <<org-config>>
  )

<<post-org>>
#+end_src
#+html:</details>

** Variables

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
;; Variables
#+end_src

*** Org Directory

#+begin_src emacs-lisp :tangle no :noweb-ref pre-org
(setq org-directory "~/Projects/brain/")
#+end_src

*** Keywords

I have excess keywords and will likely simplify them when I decide their best use.

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(setq org-todo-keywords
      '((sequence
         "TODO(t!)"                          ; Task that needs doing & is ready to do.
         "NEXT(n!)"                          ; Task that needs doing & is ready to do.
         "STRT(s!)"                          ; Task that is in progress.
         "WAIT(w@/!)"                        ; Something external is holding this up.
         "HOLD(h@/!)"                        ; Task is paused because of me.
         "PROJ(p!)"                          ; A project, which contains other tasks.
         "IDEA(i!)"                          ; An unconfirmed task or notion.
         "NOTE(N!)"                          ; A fleeting note, in person, idea, or link.
         "APPT(a!)"                          ; An appointment.
         "MEET(m!)"                          ; A meeting.
         "READ(r!)"                          ; Something to read.
         "LINK(l!)"                          ; A link I want to note.
         "|"
         "DONE(d!)"                          ; Task successfully completed.
         "KILL(k@/!)")                       ; Task cancelled or not applicable.
        (sequence                            ; For nesting headings like lists.
         "[ ](T)"                            ; A task that needs doing.
         "[-](S!)"                           ; Task is in progress.
         "[?](W@/!)"                         ; Task is being held up or paused.
         "|"
         "[X](D)"))                          ; Task was completed.
      org-todo-keyword-faces
      '(("[-]"  . +org-todo-active)
        ("STRT" . +org-todo-active)
        ("NOTE" . +org-todo-active)
        ("[?]"  . +org-todo-onhold)
        ("WAIT" . +org-todo-onhold)
        ("HOLD" . +org-todo-onhold)
        ("PROJ" . +org-todo-project)
        ("KILL" . +org-todo-cancel)))
#+end_src

** Appearance

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
;; Appearance
#+end_src

*** General

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(setq org-hide-emphasis-markers t            ; Hide syntax for emphasis. (Use org-appear)
      org-pretty-entities t                  ; Show sub/superscript as UTF8.
      org-src-preserve-indentation t)        ; Don't change whitespace in source blocks.
#+end_src

*** Headings

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(setq org-ellipsis " ▾ "                     ; Use a custom ellipsis for folded headings.
      org-hide-leading-stars t               ; Remove excess heading stars.
      org-hidden-keywords nil)               ; Can use to hide certain keywords.
#+end_src

*** LaTeX Previews

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(setq org-startup-with-latex-preview nil)    ; Show rendered LaTeX in the buffers.
#+end_src

*** LaTeX Syntax Highlighting

Add syntax highlighting to LaTeX in orgmode buffers. [[https://github.com/tecosaur/emacs-config/blob/master/config.org#prettier-highlighting][Source]].

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(setq org-highlight-latex-and-related '(native script entities))
#+end_src

Unfortunately, when using =native= highlighting the =org-block= face is used as the background color. Remove it using:

#+begin_src emacs-lisp :tangle no :noweb-ref post-org
(require 'org-src)
(add-to-list 'org-src-block-faces '("latex" (:inherit default :extend t)))
#+end_src

*** Images

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(setq org-image-actual-width '(0.9)          ; Use an in-buffer width closer to export's
      org-startup-with-inline-images t)      ; Show images at startup.
#+end_src

** Behavior

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
;; Behavior
#+end_src

*** General

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(setq org-imenu-depth 10                     ; Allow imenu to search deeply in org docs.
      org-use-property-inheritance t         ; Sub-headings inherit parent properties.
      org-insert-heading-respect-content nil ; Insert heading here, not at end of list.
      org-use-fast-todo-selection 'auto)     ; Method to select TODO heading keywords.
#+end_src

*** Logging

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(setq org-log-done 'time                     ; Add completion time to DONE items.
      org-log-into-drawer t                  ; Log times into a drawer to hide them.
      org-log-states-order-reversed nil)     ; Log state changes chronologically.
#+end_src

*** Lists

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(setq org-list-allow-alphabetical t)         ; Enable use of alphabet as list bullets.
#+end_src

*** Links

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(setq org-return-follows-link t)             ; Pressing enter opens links.
#+end_src

*** Habits

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(add-to-list 'org-modules 'org-habit t)      ; Enable repeated task tracking/graphing!
#+end_src

*** Calendar

Enable Evil bindings in org's calendar.

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(setq evil-collection-calendar-want-org-bindings t)
#+end_src
** Fixes

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
;; Fixes
#+end_src

*** Use Overlays for Folds

Org recently updated their folding style to text-properties from overlays. For now, this breaks org-roam on Doom Emacs. So, we use the old style.

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(setq org-fold-core-style 'overlays)         ; Bugfix: Hide IDs in org-roam backlinks.
#+end_src

* Org Agenda
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
Org Agenda collects, creates, and displays an overview of actionable tasks your org files.
#+end_quote

** Package

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :noweb yes
<<pre-org-agenda>>

(use-package! org-agenda
  :defer t
  :config
  <<org-agenda-config>>
  )

<<post-org-agenda>>
#+end_src
#+html:</details>

** Appearance

#+begin_src emacs-lisp :tangle no :noweb-ref org-agenda-config
;; Appearance
#+end_src

*** Habits

#+begin_src emacs-lisp :tangle no :noweb-ref org-agenda-config
(setq org-habit-show-habits-only-for-today t ; Only show habits in one section.
      org-habit-show-all-today t)            ; Keep habits visible even if done.
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref org-agenda-config
;(setq +org-habit-min-width)
;(setq +org-habit-graph-padding)
;(setq +org-habit-graph-window-ratio)
;(setq org-habit-graph-column)
;(setq org-habit-today-glyph)
;(setq org-habit-completed-glyph)
;(setq org-habit-show-done-always-green)
#+end_src

*** Section Title Face

Make agenda section titles slightly more bold.

#+begin_src emacs-lisp :tangle no :noweb-ref org-agenda-config
(custom-set-faces!
  '(org-agenda-structure
    :height 1.3 :weight bold))
#+end_src

*** Remove Empty Agenda Sections

If one of my agenda blocks has no information, I don't want to see it.

#+begin_src emacs-lisp :tangle no :noweb-ref post-org-agenda
(defun noncog/agenda-remove-empty ()
  "A simple function to remove empty agenda sections. Scans for blank lines.
Blank sections defined by having two consecutive blank lines.
Not compatible with the block separator."
  (interactive)
  (setq buffer-read-only nil)
  ;; initializes variables and scans first line.
  (goto-char (point-min))
  (let* ((agenda-blank-line "[[:blank:]]*$")
         (content-line-count (if (looking-at-p agenda-blank-line) 0 1))
         (content-blank-line-count (if (looking-at-p agenda-blank-line) 1 0))
         (start-pos (point)))
    ;; step until the end of the buffer
    (while (not (eobp))
      (forward-line 1)
       (cond
        ;; delete region if previously found two blank lines
        ((when (> content-blank-line-count 1)
          (delete-region start-pos (point))
          (setq content-blank-line-count 0)
          (setq start-pos (point))))
        ;; if found a non-blank line
        ((not (looking-at-p agenda-blank-line))
         (setq content-line-count (1+ content-line-count))
         (setq start-pos (point))
         (setq content-blank-line-count 0))
        ;; if found a blank line
        ((looking-at-p agenda-blank-line)
         (setq content-blank-line-count (1+ content-blank-line-count)))))
    ;; final blank line check at end of file
    (when (> content-blank-line-count 1)
      (delete-region start-pos (point))
      (setq content-blank-line-count 0)))
  ;; return to top and finish
  (goto-char (point-min))
  (setq buffer-read-only t))
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref post-org-agenda
(add-hook! 'org-agenda-finalize-hook #'noncog/agenda-remove-empty)
#+end_src

*** Tags Column

#+begin_src emacs-lisp :tangle no :noweb-ref org-agenda-config
(setq noncog/agenda-width 70)
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref org-agenda-config
(setq org-agenda-tags-column (+ 10 (* -1 noncog/agenda-width)))
#+end_src

*** My Custom Agenda

#+begin_src emacs-lisp :tangle no :noweb-ref org-agenda-config
(setq org-agenda-custom-commands
      '(
        ("o" "My Agenda" (
         (agenda
          ""
          ( ;; Today
           ;(org-agenda-overriding-header "Today\n")
           (org-agenda-overriding-header " Agenda\n")
           (org-agenda-day-face-function (lambda (date) 'org-agenda-date))
           (org-agenda-block-separator nil)
           (org-agenda-format-date " %a, %b %-e %y")  ; american date format
           (org-agenda-start-on-weekday nil)          ; start today
           (org-agenda-start-day nil)                 ; don't show previous days
           (org-agenda-span 1)                        ; only show today
           (org-scheduled-past-days 0)                ; don't show overdue
           (org-deadline-warning-days 0)              ; don't show deadlines for the future
           (org-agenda-time-leading-zero t)           ; unify times formatting
           (org-agenda-remove-tags t)
           (org-agenda-time-grid '((today remove-match) (800 1000 1200 1400 1600 1800 2000 2200) "" ""))
           ;(org-agenda-todo-keyword-format "%-4s")
           (org-agenda-prefix-format '((agenda . " %8:c %-5t ")))
           (org-agenda-dim-blocked-tasks nil)
           (org-agenda-skip-function '(noncog/skip-tag "inbox"))
           (org-agenda-entry-types '(:timestamp :deadline :scheduled))
           ))
         (agenda
          ""
          ( ;; Next Three Days
           ;(org-agenda-overriding-header "\nNext Three Days\n")
           (org-agenda-overriding-header "")
           (org-agenda-day-face-function (lambda (date) 'org-agenda-date))
           (org-agenda-block-separator nil)
           (org-agenda-format-date " %a %b %-e")
           (org-agenda-start-on-weekday nil)
           (org-agenda-start-day "+1d")
           (org-agenda-span 3)
           (org-scheduled-past-days 0)
           (org-deadline-warning-days 0)
           (org-agenda-time-leading-zero t)
           (org-agenda-skip-function '(or (noncog/skip-tag "inbox") (org-agenda-skip-entry-if 'todo '("DONE" "KILL"))))
           (org-agenda-entry-types '(:deadline :scheduled))
           (org-agenda-time-grid '((daily weekly) () "" ""))
           (org-agenda-prefix-format '((agenda . "  %?-9:c%t ")))
           ;(org-agenda-todo-keyword-format "%-4s")
           (org-agenda-dim-blocked-tasks nil)
           ))
         (agenda
          ""
          ( ;; Upcoming Deadlines
           (org-agenda-overriding-header "\n Coming Up\n")
           (org-agenda-day-face-function (lambda (date) 'org-agenda-date))
           (org-agenda-block-separator nil)
           (org-agenda-format-date " %a %b %-e")
           (org-agenda-start-on-weekday nil)
           (org-agenda-start-day "+4d")
           (org-agenda-span 14)
           (org-scheduled-past-days 0)
           (org-deadline-warning-days 0)
           (org-agenda-time-leading-zero t)
           (org-agenda-time-grid nil)
           (org-agenda-prefix-format '((agenda . "  %?-5t %?-9:c")))
           ;(org-agenda-todo-keyword-format "%-4s")
           (org-agenda-skip-function '(or (noncog/skip-tag "inbox") (org-agenda-skip-entry-if 'todo '("DONE" "KILL"))))
           (org-agenda-entry-types '(:deadline :scheduled))
           (org-agenda-show-all-dates nil)
           (org-agenda-dim-blocked-tasks nil)
           ))
         (agenda
          ""
          ( ;; Past Due
           (org-agenda-overriding-header "\n Past Due\n")
           (org-agenda-day-face-function (lambda (date) 'org-agenda-date))
           (org-agenda-block-separator nil)
           (org-agenda-format-date "%a %b %-e")
           (org-agenda-start-on-weekday nil)
           (org-agenda-start-day "-60d")
           (org-agenda-span 60)
           (org-scheduled-past-days 60)
           (org-deadline-past-days 60)
           (org-deadline-warning-days 0)
           (org-agenda-time-leading-zero t)
           (org-agenda-time-grid nil)
           (org-agenda-prefix-format '((agenda . "  %?-9:c%t ")))
           ;(org-agenda-todo-keyword-format "%-4s")
           (org-agenda-skip-function '(or (noncog/skip-tag "inbox") (org-agenda-skip-entry-if 'todo '("DONE" "KILL"))))
           (org-agenda-entry-types '(:deadline :scheduled))
           (org-agenda-show-all-dates nil)
           (org-agenda-dim-blocked-tasks nil)
           ))
         (todo
          ""
          ( ;; Important Tasks No Date
           (org-agenda-overriding-header "\n Important Tasks - No Date\n")
           (org-agenda-block-separator nil)
           (org-agenda-skip-function '(org-agenda-skip-entry-if 'timestamp 'notregexp "\\[\\#A\\]"))
           (org-agenda-block-separator nil)
           (org-agenda-time-grid nil)
           (org-agenda-prefix-format '((todo . "  %?:c ")))
           ;(org-agenda-todo-keyword-format "%-4s")
           (org-agenda-dim-blocked-tasks nil)
           ))
         (todo
          ""
          ( ;; Next
           (org-agenda-overriding-header "\n Next\n")
           (org-agenda-block-separator nil)
           (org-agenda-skip-function '(org-agenda-skip-entry-if 'nottodo '("NEXT" "STRT")))
           (org-agenda-block-separator nil)
           (org-agenda-time-grid nil)
           (org-agenda-prefix-format '((todo . "  %?:c ")))
           ;(org-agenda-todo-keyword-format "%-4s")
           (org-agenda-dim-blocked-tasks nil)
           ))
         (tags-todo
          "inbox"
          ( ;; Inbox
           (org-agenda-overriding-header (propertize "\n Inbox\n" 'help-echo "Effort: 'c e' Refile: 'SPC m r'")) ; Ads mouse hover tooltip.
           ;(org-agenda-remove-tags t)
           (org-agenda-block-separator nil)
           (org-agenda-prefix-format "  %?-4e ")
           ;(org-agenda-todo-keyword-format "%-4s")
           ))
         ))))
#+end_src

*** Agenda Popup Window

I use Doom's popup window rules to create a dedicated agenda window on the right side.

I use a custom width variable to ensure the formatting as I can't trust auto-align.


#+begin_src emacs-lisp :tangle no :noweb-ref org-agenda-config
(set-popup-rule! "^*Org Agenda*" :side 'right :vslot 1 :width 70 :modeline nil :select t :quit t)
#+end_src

** Behavior

#+begin_src emacs-lisp :tangle no :noweb-ref org-agenda-config
;; Behavior
#+end_src

*** Logging

#+begin_src emacs-lisp :tangle no :noweb-ref org-agenda-config
(setq org-agenda-start-with-log-mode t)      ; Show 'completed' items in agenda.
#+end_src

*** Integrate Org-Roam

By using org-roam, we may have thousands of files to search to display tasks in the agenda. To combat this, we can dynamically update the =org-agenda-files= variable to check for org-roam files that contain certain tags. I'm using the =task= and =schedule= tags. Org-roam files are automatically marked =task= long as it has a TODO heading. Files with =schedule= tags are assigned manually. [[https://d12frosted.io/posts/2021-01-16-task-management-with-roam-vol5.html][Source1]], [[https://github.com/hieutkt/dotfiles/tree/main/emacs/.doom.d][Source2]]

#+begin_src emacs-lisp :tangle no :noweb-ref post-org-agenda
(after! (org-agenda org-roam)
  (defun vulpea-task-p ()
    "Return non-nil if current buffer has any todo entry.

TODO entries marked as done are ignored, meaning the this
function returns nil if current buffer contains only completed
tasks."
    (seq-find                                 ; (3)
     (lambda (type)
       (eq type 'todo))
     (org-element-map                         ; (2)
         (org-element-parse-buffer 'headline) ; (1)
         'headline
       (lambda (h)
         (org-element-property :todo-type h)))))

  (defun vulpea-task-update-tag ()
    "Update task tag in the current buffer."
    (when (and (not (active-minibuffer-window))
               (vulpea-buffer-p))
      (save-excursion
        (goto-char (point-min))
        (let* ((tags (vulpea-buffer-tags-get))
               (original-tags tags))
          (if (vulpea-task-p)
              (setq tags (cons "task" tags))
            (setq tags (remove "task" tags)))

          ;; cleanup duplicates
          (setq tags (seq-uniq tags))

          ;; update tags if changed
          (when (or (seq-difference tags original-tags)
                    (seq-difference original-tags tags))
            (apply #'vulpea-buffer-tags-set tags))))))

  (defun vulpea-buffer-p ()
    "Return non-nil if the currently visited buffer is a note."
    (and buffer-file-name
         (string-prefix-p
          (expand-file-name (file-name-as-directory org-roam-directory))
          (file-name-directory buffer-file-name))))

  (defun vulpea-task-files ()
    "Return a list of note files containing 'task' tag." ;
    (seq-uniq
     (seq-map
      #'car
      (org-roam-db-query
       [:select [nodes:file]
        :from tags
        :left-join nodes
        :on (= tags:node-id nodes:id)
        :where (or (like tag (quote "%\"task\"%"))
                   (like tag (quote "%\"schedule\"%")))]))))

  (defun vulpea-agenda-files-update (&rest _)
    "Update the value of `org-agenda-files'."
    (setq org-agenda-files (vulpea-task-files)))

  (add-hook 'find-file-hook #'vulpea-task-update-tag)
  (add-hook 'before-save-hook #'vulpea-task-update-tag)

  (advice-add 'org-agenda :before #'vulpea-agenda-files-update)
  (advice-add 'org-todo-list :before #'vulpea-agenda-files-update)

  ;; functions borrowed from `vulpea' library
  ;; https://github.com/d12frosted/vulpea/blob/6a735c34f1f64e1f70da77989e9ce8da7864e5ff/vulpea-buffer.el

  (defun vulpea-buffer-tags-get ()
    "Return filetags value in current buffer."
    (vulpea-buffer-prop-get-list "filetags" "[ :]"))

  (defun vulpea-buffer-tags-set (&rest tags)
    "Set TAGS in current buffer.

If filetags value is already set, replace it."
    (if tags
        (vulpea-buffer-prop-set
         "filetags" (concat ":" (string-join tags ":") ":"))
      (vulpea-buffer-prop-remove "filetags")))

  (defun vulpea-buffer-tags-add (tag)
    "Add a TAG to filetags in current buffer."
    (let* ((tags (vulpea-buffer-tags-get))
           (tags (append tags (list tag))))
      (apply #'vulpea-buffer-tags-set tags)))

  (defun vulpea-buffer-tags-remove (tag)
    "Remove a TAG from filetags in current buffer."
    (let* ((tags (vulpea-buffer-tags-get))
           (tags (delete tag tags)))
      (apply #'vulpea-buffer-tags-set tags)))

  (defun vulpea-buffer-prop-set (name value)
    "Set a file property called NAME to VALUE in buffer file.
If the property is already set, replace its value."
    (setq name (downcase name))
    (org-with-point-at 1
      (let ((case-fold-search t))
        (if (re-search-forward (concat "^#\\+" name ":\\(.*\\)")
                               (point-max) t)
            (replace-match (concat "#+" name ": " value) 'fixedcase)
          (while (and (not (eobp))
                      (looking-at "^[#:]"))
            (if (save-excursion (end-of-line) (eobp))
                (progn
                  (end-of-line)
                  (insert "\n"))
              (forward-line)
              (beginning-of-line)))
          (insert "#+" name ": " value "\n")))))

  (defun vulpea-buffer-prop-set-list (name values &optional separators)
    "Set a file property called NAME to VALUES in current buffer.
VALUES are quoted and combined into single string using
`combine-and-quote-strings'.
If SEPARATORS is non-nil, it should be a regular expression
matching text that separates, but is not part of, the substrings.
If nil it defaults to `split-string-default-separators', normally
\"[ \f\t\n\r\v]+\", and OMIT-NULLS is forced to t.
If the property is already set, replace its value."
    (vulpea-buffer-prop-set
     name (combine-and-quote-strings values separators)))

  (defun vulpea-buffer-prop-get (name)
    "Get a buffer property called NAME as a string."
    (org-with-point-at 1
      (when (re-search-forward (concat "^#\\+" name ": \\(.*\\)")
                               (point-max) t)
        (buffer-substring-no-properties
         (match-beginning 1)
         (match-end 1)))))

  (defun vulpea-buffer-prop-get-list (name &optional separators)
    "Get a buffer property NAME as a list using SEPARATORS.
If SEPARATORS is non-nil, it should be a regular expression
matching text that separates, but is not part of, the substrings.
If nil it defaults to `split-string-default-separators', normally
\"[ \f\t\n\r\v]+\", and OMIT-NULLS is forced to t."
    (let ((value (vulpea-buffer-prop-get name)))
      (when (and value (not (string-empty-p value)))
        (split-string-and-unquote value separators))))

  (defun vulpea-buffer-prop-remove (name)
    "Remove a buffer property called NAME."
    (org-with-point-at 1
      (when (re-search-forward (concat "\\(^#\\+" name ":.*\n?\\)")
                               (point-max) t)
        (replace-match ""))))
  )
#+end_src

** Keybinds

#+begin_src emacs-lisp :tangle no :noweb-ref post-org-agenda
;; Keybinds
#+end_src

*** My Custom Agenda Launcher

#+begin_src emacs-lisp :tangle no :noweb-ref post-org-agenda
(defun noncog/my-agenda ()
  "My custom agenda launcher."
  (interactive)
  (org-agenda nil "o"))
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref pre-org-agenda
(map! :leader :desc "My agenda" "o a o" #'noncog/my-agenda)
#+end_src

** Helpers

#+begin_src emacs-lisp :tangle no :noweb-ref post-org-agenda
;; Helpers
#+end_src

*** Find and Skip Tags

#+begin_src emacs-lisp :tangle no :noweb-ref post-org-agenda
(defun noncog/skip-tag (tag)
  "Skip trees with this tag."
  (let* ((next-headline (save-excursion (or (outline-next-heading) (point-max))))
         (current-headline (or (and (org-at-heading-p) (point))
                               (save-excursion (org-back-to-heading)))))
    (if (member tag (org-get-tags current-headline))
        next-headline nil)))
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref post-org-agenda
(defun noncog/skip-all-but-this-tag (tag)
  "Skip trees that are not this tag."
  (let ((subtree-end (save-excursion (org-end-of-subtree t))))
    (if (re-search-forward (concat ":" tag ":") subtree-end t)
        nil          ; tag found, do not skip
      subtree-end))) ; tag not found, continue after end of subtree
#+end_src

* Org Capture
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
Org Capture lets you quickly insert into your org documents.
#+end_quote

** Package

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :noweb yes
(use-package! org-capture
  :defer t
  :config
  <<org-capture-config>>
  )
#+end_src
#+html:</details>

** Variables

#+begin_src emacs-lisp :tangle no :noweb-ref org-capture-config
;; Variables
#+end_src

*** Capture Templates

I'm currently only using one template that sends all captured headings to an inbox. This increases speed by capturing now and organizing later.

#+begin_src emacs-lisp :tangle no :noweb-ref org-capture-config
(setq org-capture-templates
      `(("i" "Inbox" entry
         (file+headline "inbox.org" "Inbox")
         "* %?\n%i\n" :prepend t)
        ("l" "Link" entry
         (file+headline "inbox.org" "Inbox")
         "* LINK %?\n%i\n" :prepend t)))
#+end_src

** Behavior

#+begin_src emacs-lisp :tangle no :noweb-ref org-capture-config
;; Behavior
#+end_src

*** Don't Add to Bookmarks

#+begin_src emacs-lisp :tangle no :noweb-ref org-capture-config
(setq org-capture-bookmark nil)
#+end_src

** Keybinds

#+begin_src emacs-lisp :tangle no :noweb-ref org-capture-config
;; Keybinds
#+end_src

*** Switch Doom's Default Capture Binds

I switch Doom's default scratch buffer and org-capture keybinds. With this, I can quickly capture something with =SPC x=.

#+begin_src emacs-lisp :tangle no :noweb-ref org-capture-config
(map! :leader :desc "Org capture" "x" #'org-capture
      :leader :desc "Pop up scratch buffer" "X" #'doom/open-scratch-buffer)
#+end_src

** Fixes

#+begin_src emacs-lisp :tangle no :noweb-ref org-capture-config
;; Fixes
#+end_src

*** Fix Org Capture Window Breaking

Sometimes the capture window breaks when the agenda or agenda files are already open. This fix reloads org-mode during captures. [[https://github.com/doomemacs/doomemacs/issues/5714][Source]]

#+begin_src emacs-lisp :tangle no :noweb-ref org-capture-config
(defadvice! my/+org--restart-mode-h-careful-restart (fn &rest args)
  :around #'+org--restart-mode-h
  (let ((old-org-capture-current-plist
         (and (bound-and-true-p org-capture-mode)
              (bound-and-true-p org-capture-current-plist))))
    (apply fn args)
    (when old-org-capture-current-plist
      (setq-local org-capture-current-plist old-org-capture-current-plist)
      (org-capture-mode +1))))
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref org-capture-config
(add-hook! 'org-capture-after-finalize-hook (org-element-cache-reset t))
#+end_src

* Org Roam
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
[[https://github.com/org-roam/org-roam][Org Roam]] is a plain-text knowledge management system. It provides a solution for non-hierarchical note-taking and linking.
#+end_quote

** Package

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :noweb yes
<<pre-org-roam>>

(use-package! org-roam
  :defer t
  :config
  <<org-roam-config>>
  )
#+end_src
#+html:</details>

** Variables

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-config
;; Variables
#+end_src

*** Roam Directory

#+begin_src emacs-lisp :tangle no :noweb-ref pre-org-roam
(setq org-roam-directory (file-truename "~/Projects/brain"))
#+end_src

*** Database Location

#+begin_src emacs-lisp :tangle no :noweb-ref pre-org-roam
(setq org-roam-db-location (file-truename "~/Projects/brain/brain.db"))
#+end_src

*** Attachments Directory

#+begin_src emacs-lisp :tangle no :noweb-ref pre-org-roam
(setq org-attach-id-dir (file-truename "~/Projects/brain/.attachments"))
#+end_src

*** Exclude Directories

Currently not excluding any. This is a place holder for when I do.

#+begin_src emacs-lisp :tangle no :noweb-ref pre-org-roam
;(setq org-roam-file-exclude-regexp (rx (or "data/" "inbox.org")) )
#+end_src

** Behavior

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-config
;; Behavior
#+end_src

*** Disable If No Roam Directory

Don't use Org Roam if the directory isn't present to avoid errors.

See [[file:config.el][config.el]] to understand how this works. Thanks Teco.

#+begin_src emacs-lisp :tangle (if (file-exists-p "~/Projects/brain") "no" "packages.el")
(package! org-roam :disable t)
#+end_src

*** Always Open the Backlinks Buffer

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-config
;(setq +org-roam-auto-backlinks-buffer t)
#+end_src

*** Capture Templates

Currently just using the default captures template. This area still needs a lot of work. I need to decide how to use roam-capture and org-capture.

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-config
(setq org-roam-capture-templates
      '(("n" "node" plain
         "%?"
         :target
         (file+head "nodes/${slug}.org" "#+title: ${title}\n#+filetags: :draft:\n")
         :immediate-finish t
         :unnarrowed t)))
#+end_src

*** Enable Autosync

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-config
(org-roam-db-autosync-mode)
#+end_src

** Keybinds

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-config
;; Keybinds
#+end_src

*** Find Random Draft Nodes

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-config
(defun noncog/org-roam-is-draft-p (node)
  "Is this org-roam node a draft?"
  (member "draft" (org-roam-node-tags node)))
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-config
(defun noncog/org-roam-random-draft ()
  "Get a random node with the draft tag. "
  (interactive)
  (org-roam-node-random nil #'noncog/org-roam-is-draft-p))
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-config
(map! :leader :desc "Random draft node" "n r u" #'noncog/org-roam-random-draft)
#+end_src

* Org Roam UI
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
[[https://github.com/org-roam/org-roam-ui][org-roam-ui]] is a frontend for exploring and interacting with your org-roam notes.
#+end_quote

** Package

#+html:<details><summary>Source</summary>
#+begin_src emacs-lisp :tangle packages.el
(unpin! org-roam) ; NOTE: org-roam-ui requires latest org-roam.
(package! org-roam-ui
  :recipe (:host github :repo "org-roam/org-roam-ui"))
#+end_src
#+html:</details>

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :noweb yes
(use-package! websocket
    :after org-roam)
#+end_src

#+begin_src emacs-lisp :noweb yes
<<pre-org-roam-ui>>

(use-package! org-roam-ui
  ;:defer t
  :after org-roam
  ;; :hook ((org-roam . org-roam-ui-mode)
  ;;        (org-roam-ui-mode . #'org-roam-ui-always-sync-theme))
  :hook (org-roam . org-roam-ui-mode)
  ;:defines org-roam-ui-port
  :init
  <<org-roam-ui-init>>
  :config
  <<org-roam-ui-config>>
  )
#+end_src
#+html:</details>

** Appearance

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-ui-config
;; Appearance
#+end_src

*** Enable Doom Themes

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-ui-config
(setq org-roam-ui-sync-theme t)
#+end_src

** Behavior

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-ui-config
;; Behavior
#+end_src

*** General

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-ui-config
(setq org-roam-ui-follow t
      org-roam-ui-update-on-save t)
#+end_src

*** Use Xwidgets Instead of Browsers

The following enables org-roam-ui to open within Emacs using xwidgets instead of using a browser.

Prevent from opening the default graph on start and replace the browser function with an xwidgets function.

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-ui-config
(setq org-roam-ui-open-on-start nil
      org-roam-ui-browser-function #'+lookup-xwidget-webkit-open-url-fn)
#+end_src

Add a function to kill the xwidgets buffer and exit org-roam-ui-mode when we close the graph window.

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-ui-config
(defun +org-roam-ui-popup-kill (roam-ui-popup-buffer)
  (progn (+popup--kill-buffer roam-ui-popup-buffer 0.1) (org-roam-ui-mode -1)))
#+end_src

Set the window's popup rules. This configuration opens the graph above the backlinks buffer splitting the vertical height equally.

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-ui-config
(setq display-buffer-mark-dedicated t)
(set-popup-rule! "^\\*xwidget" :side 'right :ttl #'+org-roam-ui-popup-kill :slot -1 :width 0.33 :height 0.5 :quit 'current :select nil :modeline nil)
#+end_src

Additionally, you can take control of roam's poppup rules for further customization.

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-ui-config
;; (set-popup-rule! (regexp-quote org-roam-buffer) ; persistent org-roam buffer
;;      :side 'right :width 0.33 :height 0.5 :ttl nil :modeline nil :quit nil :slot 1)
;; (set-popup-rule! "^\\*org-roam: " ; node dedicated org-roam buffer
;;      :side 'right :width 0.33 :height 0.5 :ttl nil :modeline nil :quit nil :slot 2)
#+end_src

*** Don't Open Nodes in Side Windows

By default org-roam-ui attempts to open nodes by splitting the newest window. This won't work with side windows. So, a function is needed to more carefully choose a window to split. I simply force it to open the node in the latest regular window.

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-ui-config
(defadvice! my/+org-roam-ui--on-msg-open-node (data)
  "Open a node CAREFULLY when receiving DATA from the websocket."
  :override #'org-roam-ui--on-msg-open-node
  (let* ((id (alist-get 'id data))
         (node (org-roam-node-from-id id))
         (pos (org-roam-node-point node))
         (buf (find-file-noselect (org-roam-node-file node))))
    (run-hook-with-args 'org-roam-ui-before-open-node-functions id)
    (unless (window-live-p org-roam-ui--window)
      (if-let ((windows (cl-set-difference (doom-visible-windows) (list (minibuffer-window))))
               (newest-window (car (seq-sort-by #'window-use-time #'> windows))))
          (setq org-roam-ui--window newest-window)
        (setq org-roam-ui--window newest-window)))
    (set-window-buffer org-roam-ui--window buf)
    (select-window org-roam-ui--window)
    (goto-char pos)
    (run-hook-with-args 'org-roam-ui-after-open-node-functions id)))
#+end_src

*** Ensure Doom Theme Colors Always

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-ui-config
                                        ;jqq(add-hook! 'org-roam-ui-mode-hook :append (org-roam-ui-always-sync-theme))
                                        ;(add-hook! 'org-roam-ui-mode-hook :append (org-roam-ui-always-sync-theme))
                                        ;(add-hook 'org-roam-ui-mode-hook #'org-roam-ui-always-sync-theme)
                                        ;(add-hook! 'org-roam-ui-mode-hook :append (when org-roam-ui-mode (org-roam-ui-sync-theme)))
;; (after! org-roam-ui
;;   (defun org-roam-ui-always-sync-theme ()
;;     (if org-roam-ui-mode (org-roam-ui-sync-theme) nil)
;;     )
;;   (defadvice! my/+org-roam-ui-sync-theme ()
;;     "Always sync the theme after opening the org-roam-ui graph."
;;     :after #'org-roam-ui-open
;;     (org-roam-ui-always-sync-theme)))

;; (defadvice! my/+org-roam-ui-sync-theme (fn &rest args)
;;   "Always sync the theme after opening the org-roam-ui graph."
;;   :around #'org-roam-ui-open
;;   (prog1 (apply fn args) (when (and (org-roam-ui-mode () org-roam-ui-sync-theme)))
                                        ;(org-roam-ui-sync-theme)

;; (defadvice! org-roam-ui-always-sync-theme ()
;;   "Always sync the theme after opening the org-roam-ui graph."
;;   :after #'org-roam-ui-open
;;   (defer-until! (ignore-errors (get-buffer-window-list "*xwidget webkit: ORUI *")) (org-roam-ui-sync-theme)))
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-ui-config
;; (defun org-roam-ui-always-sync-theme ()
;;   "Always sync the theme..."
;;   (interactive)
;;   ;;(when (ignore-errors (get-buffer-window-list "*xwidget webkit: ORUI *")) (org-roam-ui-sync-theme))
;;   )


(defadvice! +org-roam-ui-always-sync-theme ()
  "Always sync da theme..."
  :after #'org-roam-ui-open

  (while (when (ignore-errors (get-buffer-window-list "*xwidget webkit: ORUI *")) (websocket-send-text org-roam-ui-ws-socket (json-encode `((type . "theme") (data . ,(org-roam-ui--update-theme)))))))
  ;(org-roam-ui-always-sync-theme)
  ;;(when (ignore-errors (get-buffer-window-list "*xwidget webkit: ORUI *")) (org-roam-ui-sync-theme))
  )
;(add-hook! 'org-roam-ui-mode-hook #'org-roam-ui-always-sync-theme)
  ;; (let)
  ;; (while )
  ;; (while (if-let ((windows (window-list))
  ;;          (roam-ui-window
  ;;           (seq-filter (lambda (window)
  ;;                         (string-prefix-p "*xwidget" (buffer-name (window-buffer window)))) windows)))
  ;;            (when (and org-roam-ui-mode roam-ui-window) t) nil)))

;; (defadvice! org-roam-ui-always-sync-theme ()
;;   "Always sync the theme after opening the org-roam-ui graph."
;;   :after #'org-roam-ui-open
;;   (while (if-let ((windows (window-list))
;;            (roam-ui-window
;;             (seq-filter (lambda (window)
;;                           (string-prefix-p "*xwidget" (buffer-name (window-buffer window)))) windows)))
;;              (when (and org-roam-ui-mode roam-ui-window) t) nil)))
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-ui-init
;; (defun my/org-roam-ui-open ()
;;   "Ensure `org-roam-ui' is running, then open the `org-roam-ui' webpage."
;;   (interactive)
;;   (funcall org-roam-ui-browser-function
;;                   (format "http://localhost:%d" org-roam-ui-port))
;;   (progn (unless org-roam-ui-mode (org-roam-ui-mode)) (org-roam-ui-sync-theme)))
#+end_src

** Keybinds

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-ui-config
;; Keybinds
#+end_src

*** Replace Doom's Default Org Roam Graph Keybind

Use the org-roam-ui and xwidget popup window instead.

#+begin_src emacs-lisp :tangle no :noweb-ref pre-org-roam-ui
(map! :leader "n r g" #'org-roam-ui-open)
#+end_src

* Org Appear
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
[[https://github.com/awth13/org-appear][Org Appear]] makes invisible Org elements like emphasis markers magically appear.
#+end_quote

** Package

#+html:<details><summary>Source</summary>
#+begin_src emacs-lisp :tangle packages.el
(package! org-appear
  :recipe (:host github :repo "awth13/org-appear")
  :pin "eb9f9db40aa529fe4b977235d86494b115281d17")
#+end_src
#+html:</details>

#+html:<details><summary>Source</summary>
#+begin_src emacs-lisp :noweb yes
(use-package! org-appear
  :hook (org-mode . org-appear-mode)
  :config
  <<org-appear-config>>
  )
#+end_src
#+html:</details>

** Appearance

#+begin_src emacs-lisp :tangle no :noweb-ref org-appear-config
;; Appearance
#+end_src

*** General

#+begin_src emacs-lisp :tangle no :noweb-ref org-appear-config
(setq org-appear-autoemphasis t              ; Show emphasis markup.
      org-appear-autosubmarkers t            ; Show sub/superscript
      org-appear-autoentities t              ; Show LaTeX like Org pretty entities.
      org-appear-autolinks nil               ; Shows Org links.
      org-appear-autokeywords nil            ; Shows hidden Org keywords.
      org-appear-inside-latex nil)           ; Show LaTeX code. Use Fragtog instead.
#+end_src

* Org Fragtog
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
[[https://github.com/io12/org-fragtog][Org Fragtog]] toggles LaTeX fragments as the cursor enters and exits them. It's org-appear for LaTeX!
#+end_quote

** Package

#+html:<details><summary>Source</summary>
#+begin_src emacs-lisp :tangle packages.el
(package! org-fragtog
  :pin "c675563af3f9ab5558cfd5ea460e2a07477b0cfd")
#+end_src
#+html:</details>

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :noweb yes
(use-package! org-fragtog
  :hook (org-mode . org-fragtog-mode))
#+end_src
#+html:</details>

* Org Modern
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
[[https://github.com/minad/org-modern][Org Modern]] implements a “modern” style for your Org buffers using font locking and text properties.
#+end_quote

** Package

#+html:<details><summary>Source</summary>
#+begin_src emacs-lisp :tangle packages.el
(package! org-modern
  :pin "b614ad31d72c49f9eb29d3836995fd7fb0d1fd4a")
#+end_src
#+html:</details>

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :noweb yes
(use-package! org-modern
  :hook (org-mode . org-modern-mode)
  :config
  <<org-modern-config>>
  )
#+end_src
#+html:</details>

** Appearance

#+begin_src emacs-lisp :tangle no :noweb-ref org-modern-config
;; Appearance
#+end_src

*** General

These settings will need sorted into their own headings eventually.

#+begin_src emacs-lisp :tangle no :noweb-ref org-modern-config
(setq org-modern-hide-stars nil              ; Let Org handle hiding the stars.
      org-modern-table-vertical 1            ; Use thinner lines than default.
      org-modern-table-horizontal 0.2        ; Unify line thickness with vertical line.
      org-modern-progress nil                ; Use default progress face.
      org-modern-priority nil                ; Use default priority face.
      org-modern-todo-faces                  ; Inherit Doom's Org faces.
      '(("TODO" :inverse-video t :inherit org-todo)
        ("PROJ" :inverse-video t :inherit +org-todo-project)
        ("STRT" :inverse-video t :inherit +org-todo-active)
        ("[-]"  :inverse-video t :inherit +org-todo-active)
        ("HOLD" :inverse-video t :inherit +org-todo-onhold)
        ("WAIT" :inverse-video t :inherit +org-todo-onhold)
        ("[?]"  :inverse-video t :inherit +org-todo-onhold)
        ("KILL" :inverse-video t :inherit +org-todo-cancel)
        ("NO"   :inverse-video t :inherit +org-todo-cancel))
      org-modern-star '("◉" "○" "✸" "✿" "✤" "✜" "◆" "▶")
      org-modern-horizontal-rule (make-string 80 ?─))
#+end_src

* Org Modern Indent
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
[[https://github.com/jdtsmith/org-modern-indent][Org-modern-indent]] adds back the source block "bracket" to org-modern, which is normally broken by the use of indentation.
#+end_quote

** Package

#+html:<details><summary>Source</summary>
#+begin_src emacs-lisp :tangle packages.el
(package! org-modern-indent
  :recipe (:host github :repo "jdtsmith/org-modern-indent")
  :pin "c5a50f302dc1053d5b498e0ea2bc0ee233e8e1b8")
#+end_src
#+html:</details>

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :noweb yes
(use-package! org-modern-indent
  :config ; add late to hook
  (add-hook 'org-mode-hook #'org-modern-indent-mode 1))
#+end_src
#+html:</details>

* TOC Org
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
[[https://github.com/snosov1/toc-org][TOC-Org]] creates an up-to-date table of contents in an Org file, useful primarily for READMEs on GitHub.
#+end_quote

** Package

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :noweb yes
(use-package! toc-org
  :defer t
  :config
  <<toc-org-config>>
  )
#+end_src
#+html:</details>

** Behavior

#+begin_src emacs-lisp :tangle no :noweb-ref toc-org-config
;; Behavior
#+end_src

*** Set Default Depth

#+begin_src emacs-lisp :tangle no :noweb-ref toc-org-config
(setq org-toc-default-depth 2)
#+end_src

*** Add Code Folding to Quoted TOC

When I use GitHub for literate documentation, I want to add the HTML =details= tag around the table of content to create a hidden table of contents that the user can expand if they wish to. This is done by creating and advising a function that replaces the string used in the quoted table of contents to include the details tag.

#+begin_src emacs-lisp :tangle no :noweb-ref toc-org-config
(defadvice! my/+toc-org-insert-toc-folded (&optional dry-run)
  "An advised function to extend 'toc-org-insert-toc to add html details tags."
  :override #'toc-org-insert-toc
  (interactive)
  (let ((dry-run nil))
  (save-excursion
    (goto-char (point-min))
    (let* ((case-fold-search t)
           (markdown-syntax-p (derived-mode-p 'markdown-mode))
           (heading-symbol-regexp (if markdown-syntax-p "^#" "^\\*")))
      ;; find the first heading with the :TOC: tag
      (when (re-search-forward (concat heading-symbol-regexp toc-org-toc-org-regexp) (point-max) t)
        (let* ((tag (match-string 2))
               (depth (if tag
                          (- (aref tag 1) ?0) ;; is there a better way to convert char to number?
                        toc-org-max-depth))
               (hrefify-tag (if (and tag (>= (length tag) 4))
                                (downcase (substring tag 3))
                              toc-org-hrefify-default))
               (hrefify-string (concat "toc-org-hrefify-" hrefify-tag))
               (hrefify (intern-soft hrefify-string))
               (put-quote (save-match-data (string-match toc-org-quote-tag-regexp (match-string 0))))
               (toc-prefix (if put-quote (if markdown-syntax-p "```\n" "#+html:<details><summary>Table of Contents</summary>\n#+BEGIN_QUOTE\n")  ""))
               (toc-suffix (if put-quote (if markdown-syntax-p "```\n" "#+END_QUOTE\n#+html:</details>\n") "")))
          (if hrefify
              (let ((new-toc
                     (concat toc-prefix
                             (toc-org-hrefify-toc
                              (toc-org-flush-subheadings (toc-org-raw-toc markdown-syntax-p) depth)
                              hrefify
                              markdown-syntax-p
                              (when toc-org-hrefify-hash
                                (clrhash toc-org-hrefify-hash)))
                             toc-suffix)))
                (unless dry-run
                  (newline (forward-line 1))

                  ;; skip drawers
                  (let ((end
                         (save-excursion ;; limit to next heading
                           (search-forward-regexp heading-symbol-regexp (point-max) 'skip))))
                    (while (re-search-forward toc-org-drawer-regexp end t)
                      (skip-chars-forward "[:space:]")))
                  (beginning-of-line)

                  ;; insert newline if TOC is currently empty
                  (when (looking-at heading-symbol-regexp)
                    (open-line 1))

                  ;; find TOC boundaries
                  (let ((beg (point))
                        (end
                         (save-excursion
                           (when (search-forward-regexp heading-symbol-regexp (point-max) 'skip)
                             (forward-line -1))
                           (end-of-line)
                           (point))))
                    ;; update the TOC, but only if it's actually different
                    ;; from the current one
                    (unless (equal
                             (buffer-substring-no-properties beg end)
                             new-toc)
                      (delete-region beg end)
                      (insert new-toc)))))
            (message (concat "Hrefify function " hrefify-string " is not found")))))))))
#+end_src

* Org Noter
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
[[https://github.com/weirdNox/org-noter][Org Noter]] creates org notes that are kept in sync with PDF pages as you scroll.
#+end_quote

** Package

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :noweb yes
(use-package! org-noter
  :defer t
  :config
  <<org-noter-config>>
  )
#+end_src
#+html:</details>

** Behavior

#+begin_src emacs-lisp :tangle no :noweb-ref org-noter-config
;; Behavior
#+end_src

*** Frame

#+begin_src emacs-lisp :tangle no :noweb-ref org-noter-config
(setq org-noter-always-create-frame nil        ; Don't create a new frame for the session.
      org-noter-kill-frame-at-session-end nil) ; Don't kill any frames since none created.
#+end_src

*** Notes

#+begin_src emacs-lisp :tangle no :noweb-ref org-noter-config
(setq org-noter-separate-notes-from-heading t) ; Adds line between headings and notes.
#+end_src

* PDF Tools
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
[[https://github.com/vedang/pdf-tools][PDF Tools]] is a replacement PDF viewer for the default, DocView, in Emacs. It's required for =org-noter=.
#+end_quote

** Package

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :noweb yes
(use-package! pdf-tools
  :defer t
  :config
  <<pdf-tools-config>>
  )
  (pdf-tools-install)
#+end_src
#+html:</details>

** Fixes

#+begin_src emacs-lisp :tangle no :noweb-ref pdf-tools-config
;; Fixes
#+end_src

*** Prevent Crash on macOS Ventura

Apparently this is required. [[https://github.com/vedang/pdf-tools/issues/173#issuecomment-1341882242][Source]]

#+begin_src emacs-lisp :tangle no :noweb-ref pdf-tools-config
(when IS-MAC (add-hook 'pdf-tools-enabled-hook 'pdf-view-dark-minor-mode))
#+end_src

* PlantUML
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
[[https://plantuml.com][PlantUML]] is a component that allows you to quickly write several types of UML diagrams using its language. This integrates well with org mode for generating UML diagrams from source blocks.
#+end_quote

** Package

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :noweb yes
(use-package! plantuml-mode
  :defer t
  :config
  <<plantuml-mode-config>>
  )
#+end_src
#+html:</details>

** Behavior

#+begin_src emacs-lisp :tangle no :noweb-ref plantuml-mode-config
;; Behavior
#+end_src

*** Execution Mode

I use a local jar executable instead of contacting the website.

#+begin_src emacs-lisp :tangle no :noweb-ref plantuml-mode-config
(setq plantuml-default-exec-mode 'jar)
#+end_src

*** Ensure Local Installation

Downloads the jar file if it's not on the system.

#+begin_src emacs-lisp :tangle no :noweb-ref plantuml-mode-config
(unless (file-exists-p plantuml-jar-path)
  (plantuml-download-jar))
#+end_src

* Ox (Org Export)
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
Ox (Org Export) implements a generic export engine for Org. It uses different backends to change the translation of org documents into various other formats.
#+end_quote

** Package

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :noweb yes
(use-package! ox
  :defer t
  :config
  <<ox-config>>
  )
#+end_src
#+html:</details>

** Appearance

#+begin_src emacs-lisp :tangle no :noweb-ref ox-config
;; Appearance
#+end_src

*** Creator String

I like to include this on my LaTeX exports to allude to the tools that I like to use.

#+begin_src emacs-lisp :tangle no :noweb-ref ox-config
(setq org-export-with-creator t
      org-export-creator-string (format "Doom Emacs %s (Org mode %s)" emacs-version org-version))
#+end_src

** Behavior

#+begin_src emacs-lisp :tangle no :noweb-ref ox-config
;; Behavior
#+end_src

*** Ignore Headings but Keep Content in Exports

This setting allows you to use the =:ignore:= tag to remove a heading from an export but keep its contents.

#+begin_src emacs-lisp :tangle no :noweb-ref ox-config
(require 'ox-extra)
(ox-extras-activate '(ignore-headlines))
#+end_src

*** Export Depth

By default only the first three headings, including titles are exported. Five levels of depth seems like a reasonable value for LaTeX and HTML exports. Tecosaur reasoned that HTML5 has six heading levels but Org exports start at the second, leaving us with just five to use. It should also challenge/prevent me from overly nesting information.

#+begin_src emacs-lisp :tangle no :noweb-ref ox-config
(setq org-export-headline-levels 5)
#+end_src

** Keybinds

#+begin_src emacs-lisp :tangle no :noweb-ref ox-config
;; Keybinds
#+end_src

*** View Exported Org File

[[https://github.com/tecosaur/emacs-config/blob/master/config.org#view-exported-file][Tecosaur]] created a function and keybind to view the recently exported org-file.

#+begin_src emacs-lisp
(defun org-view-output-file (&optional org-file-path)
  "Visit buffer open on the first output file (if any),
found, using `org-view-output-file-extensions'."
  (interactive)
  (let* ((org-file-path (or org-file-path (buffer-file-name) ""))
         (dir (file-name-directory org-file-path))
         (basename (file-name-base org-file-path))
         (output-file nil))
    (dolist (ext org-view-output-file-extensions)
      (unless output-file
        (when (file-exists-p
               (concat dir basename "." ext))
          (setq output-file (concat dir basename "." ext)))))
    (if output-file
        (if (member (file-name-extension output-file) org-view-external-file-extensions)
            (browse-url-xdg-open output-file)
          (pop-to-buffer (or (find-buffer-visiting output-file)
                             (find-file-noselect output-file))))
      (message "No exported file found"))))

(defvar org-view-output-file-extensions '("pdf" "md" "rst" "txt" "tex" "html")
  "Find output files with these extensions, in order, viewing the first match.")
(defvar org-view-external-file-extensions '("html")
  "File formats that should be opened externally.")
#+end_src

#+begin_src emacs-lisp
(map! :map org-mode-map
      :localleader
      :desc "View exported file"
      "v" #'org-view-output-file)
#+end_src

* Ox Latex
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
Ox Latex is the LaTeX backend for the Org Export Engine.
#+end_quote

** Package

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :noweb yes
(use-package! ox-latex
  :defer t
  :config
  <<ox-latex-config>>
  )
#+end_src
#+html:</details>

** Appearance

#+begin_src emacs-lisp :tangle no :noweb-ref ox-latex-config
;; Appearance
#+end_src

*** Set Source Block Backend

This adds theming and syntax highlighting to our source blocks in latex exports.

#+begin_src emacs-lisp :tangle no :noweb-ref ox-latex-config
(setq org-latex-src-block-backend 'engraved)
#+end_src

*** Custom Document Class

#+begin_src emacs-lisp :tangle no :noweb-ref ox-latex-config
(add-to-list 'org-latex-classes
             '("notes"
               "\\documentclass{article}
                [NO-DEFAULT-PACKAGES]
                [PACKAGES]
                [EXTRA]"
               ("\\section{%s}" . "\\section*{%s}")
               ("\\subsection{%s}" . "\\subsection*{%s}")
               ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
               ("\\paragraph{%s}" . "\\paragraph*{%s}")
               ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))
#+end_src

** Behavior

#+begin_src emacs-lisp :tangle no :noweb-ref ox-latex-config
;; Behavior
#+end_src

*** Set PDF Process

#+begin_src emacs-lisp :tangle no :noweb-ref ox-latex-config
(setq org-latex-pdf-process '("LC_ALL=en_US.UTF-8 latexmk -f -pdf -%latex -shell-escape -interaction=nonstopmode -output-directory=%o %f"))
#+end_src

* Engrave Faces
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
[[https://github.com/tecosaur/engrave-faces][Engrave Faces]] is a generic exporter that passes a fontified buffer to an org backend to be exported to a particular format. It provides theming and syntax highlighting in code blocks for our org-mode html and latex exports!
#+end_quote

** Package

#+html:<details><summary>Source</summary>
#+begin_src emacs-lisp :tangle packages.el
(package! engrave-faces
  :recipe (:host github :repo "tecosaur/engrave-faces")
  :pin "2c72619195d489a4f6d5370f70dd7f6aa11801c3")
#+end_src
#+html:</details>


#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :noweb yes
(use-package! engrave-faces-latex
  :after ox-latex)
#+end_src

#+begin_src emacs-lisp :noweb yes
(use-package! engrave-faces-html
  :after ox-html)
#+end_src
#+html:</details>

* LSP-Clangd
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote

#+end_quote

** Package

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :noweb yes
(use-package! lsp-clangd
  :defer t
  :config
  <<lsp-clangd-config>>
  )
#+end_src
#+html:</details>

** Behavior

#+begin_src emacs-lisp :tangle no :noweb-ref lsp-clangd-config
;; Behavior
#+end_src

*** Set Clangd Args

#+begin_src emacs-lisp :tangle no :noweb-ref lsp-clangd-config
(setq lsp-clients-clangd-args
      '("-j=3"
        "--background-index"
        "--clang-tidy"
        "--completion-style=detailed"
        "--header-insertion=never"
        "--header-insertion-decorators=0"))
(set-lsp-priority! 'clangd 2)
#+end_src
