#+html:<h1 align="center">Doom Emacs</h1>
#+html: <p align="center"><a href="https://www.gnu.org/software/emacs/emacs.html#Releases"><img src="https://img.shields.io/badge/Emacs-27.1-blueviolet.svg?style=flat-square&logo=GNU%20Emacs&logoColor=white"></a> <a href="https://orgmode.org"><img src="https://img.shields.io/badge/Org-literate%20config-%2377aa99?style=flat-square&logo=org&logoColor=white"></a></p>
#+html:<p align="center"><a href="https://github.com/Schievel1/doom-emacs-splash"><img src="https://github.com/Schievel1/doom-emacs-splash/blob/main/svg/doom/doomEmacsDracula.svg" height="300"></a></p>
#+html: <p align="center"><a href="https://creativecommons.org/licenses/by-sa/4.0/"><img src="https://img.shields.io/badge/CC--BY--SA-161b22?style=for-the-badge&logo=Creative%20Commons&logoColor=white"></a></p>
#+html:<p align="center">This is my <code><a href="https://github.com/doomemacs/doomemacs">Doom</a></code>... <code><a href="https://github.com/hlissner">Henrik</a></code> has doomed us all!</p>
#+startup: show3levels

#+begin_example :tangle no :exports none
test if github shows tags on headings.

org publish
ox-publish
figure out the creator and email string and inserting it into the correct location.


Set the org directories for the agenda to be directory based instead of file based to not expose files.

fix the scrolling so that it shows images better. Currently have issues with latex preview in org buffers that are taller than the screens.
rename doom snippets.
setup noweb-ref use-package snippet to insert package name and use-package! call inside of it.
org-present
Setup variable pitch fonts for org-present
https://systemcrafters.net/emacs-tips/presentations-with-org-present/

add this note about switching the pdf compiler.
https://github.com/tecosaur/emacs-config/blob/master/config.org#latex-export

Consider using olivetti mode instead of visual fill column, since it breaks Doom's popup windowing in side windows.
Consider showing final output in folded GitHub sections as well as a note on noweb-ref and dual output locally, short, and informative, as well as complete all available.
teco has great latex snippets
https://github.com/tecosaur/emacs-config/tree/master/snippets/latex-mode
org-format-latex
org-latex-color-format
org-format-latex-header
org-format-latex-options
https://github.com/tecosaur/emacs-config/blob/master/config.org#visuals-2

Some really nice visual settings from teco.

Can change org babel results keyword.

Look into org-present-read-only
Consider org-present read only and org-present hide cursor
and org-present-startup-folded
org-present-trim-string can remove arbitrary white space.
Can do something with org present after nav as well.

Yasnippet
- rename snippets to be more clear

LSP
- enable module
- install lsp servers

Neotree
- Test and see if will use

Org-mode
- org-image-actual-width

Add this:
- zero width spaces.

- org-list-demote-modify-bullet

- Setup capture templates, potentially using doct.

- Setup capturing into brain inbox.

- Add nicer org return or better creation of org-elements.

For org present may need to save current view level and return to it after exit.

evil-move-beyond-eol to t

#+end_example

* Doom Info

[[https://github.com/doomemacs/doomemacs/blob/d217ae334392b6abf0e23424516a37b4cd8ac261/docs/getting_started.org][Getting Started Guide]]

[[https://github.com/doomemacs/doomemacs/tree/master/modules][Modules]]

#+begin_src emacs-lisp :tangle no :exports none
;; whenever you reconfigure a package, make sure to wrap your config in an
;; `after!' block, otherwise doom's defaults may override your settings. e.g.
;;
;;   (after! package
;;     (setq x y))
;;
;; the exceptions to this rule:
;;
;;   - setting file/directory variables (like `org-directory')
;;   - setting variables which explicitly tell you to set them before their
;;     package is loaded (see 'c-h v variable' to look up their documentation).
;;   - setting doom variables (which start with 'doom-' or '+').
;;
;; here are some additional functions/macros that will help you configure doom.
;;
;; - `load!' for loading external *.el files relative to this one
;; - `use-package!' for configuring packages
;; - `after!' for running code after a package has loaded
;; - `add-load-path!' for adding directories to the `load-path', relative to
;;   this file. emacs searches the `load-path' when you load packages with
;;   `require' or `use-package'.
;; - `map!' for binding new keys
;;
;; to get information about any of these functions/macros, move the cursor over
;; the highlighted symbol at press 'k' (non-evil users must press 'c-c c k').
;; this will open documentation for it, including demos of how they are used.
;; alternatively, use `c-h o' to look up a symbol (functions, variables, faces,
;; etc).
;;
;; you can also try 'gd' (or 'c-c c d') to jump to their definition and see how
;; they are implemented.
#+end_src

* About

It should be noted that I use a [[https://leanpub.com/lit-config/read][literate configuration]]. This enables me to have a single annotated file for a particular configuration which automatically writes out the actual configuration file from the .org file.

*** README.org != config.el

#+BEGIN_QUOTE
*Warning:* README.org does not represent the actual elisp code because of my use of =noweb= blocks. This is done to better share the features I use, not how I write elisp. To see 'under the hood', refer to =config.el= and the raw README.org file. For example, I cleverly split up use-package! declarations into more visually appealing and better documented code blocks for viewing here on GitHub.
#+END_QUOTE

The [[https://orgmode.org/manual/Noweb-Reference-Syntax.html][org-mode manual]] documentation on this topic is extremely useful for understanding the ways you can use this.

* Doom Global

In this section I setup Doom and "global" things. Otherwise, package specific settings are in the [[#packages][Packages]] section.

** Initial Setup
*** Enable Lexical Binding

Supposedly makes this file run slightly faster...

#+begin_src emacs-lisp
;;; $doomdir/config.el -*- lexical-binding: t; -*-
#+end_src

*** Personal Information

Needs updated with secure private public email.

#+begin_src emacs-lisp
;; some functions use this to identify you, e.g. gpg configuration, email
;; clients, file templates and snippets. it is optional.
(setq user-full-name "Jake Turner"
      user-mail-address "john@doe.com")
#+end_src

** Behavior
*** Autoload File Changes

#+begin_src emacs-lisp
(global-auto-revert-mode 1)
#+end_src

** Appearance
*** Theme

I use [[https://draculatheme.com/][Dracula]] theme everywhere I can.

#+begin_src emacs-lisp
(setq doom-theme 'doom-dracula)
(setq doom-dracula-brighter-modeline t)
(setq doom-dracula-colorful-headers t)
#+end_src

*** Cursor Color

This syntax allows me to choose any of the doom-theme colors defined in my theme as my new cursor color.

#+begin_src emacs-lisp
(custom-set-faces!
 `(cursor :background ,(doom-color 'magenta)))
#+end_src

*** Font

#+begin_src emacs-lisp :tangle no :exports none
;; doom exposes five (optional) variables for controlling fonts in doom:
;;
;; - `doom-font' -- the primary font to use
;; - `doom-variable-pitch-font' -- a non-monospace font (where applicable)
;; - `doom-big-font' -- used for `doom-big-font-mode'; use this for
;;   presentations or streaming.
;; - `doom-unicode-font' -- for unicode glyphs
;; - `doom-serif-font' -- for the `fixed-pitch-serif' face
;;
;; see 'c-h v doom-font' for documentation and more examples of what they
;; accept. for example:
;;
#+end_src

#+begin_src emacs-lisp
(setq doom-font (font-spec :family "fira code" :size 14))
(setq doom-unicode-font (font-spec :family "fira code" :size 16))
#+end_src

*** Frame Opacity

Adds transparency to Doom, allowing my wallpaper to show through. Primarily increases visual appeal of presentations and screen sharing. Probably requires a compositor. I use [[https://github.com/yshui/picom][Picom]].

#+begin_src emacs-lisp
(add-to-list 'default-frame-alist '(alpha . 96)) ; [0-100]
#+end_src

*** Disable Global Line Numbers

These are known to reduce performance.

When I want them, I can turn them on per mode or using Doom's toggle, but I don't want them everywhere.

#+begin_src emacs-lisp
(after! display-line-numbers
  (setq display-line-numbers-type nil))
#+end_src

*** Show Time in Modeline

#+begin_src emacs-lisp
(display-time-mode 1)
#+end_src

** Keybinds

#+begin_src emacs-lisp
(map! :leader :desc "Dashboard" "d" #'+doom-dashboard/open)
#+end_src

* Packages

This section modifies all configurations for packages, including Emacs itself.

#+begin_src emacs-lisp :tangle no :exports none :noweb-ref use-package-end
)
#+end_src

** Emacs

#+begin_src emacs-lisp :tangle no :noweb-ref use-package-emacs :exports none
(use-package! emacs
  :defer
  :config
#+end_src

*** Behavior
**** Scroll Margin

The number of lines relative to the top and bottom of the screen, at which you should scroll the buffer. This provides room to see what is coming and prevents you from passing up your desired information.

#+begin_src emacs-lisp :tangle no :noweb-ref use-package-emacs-config
(setq scroll-margin 5)
#+end_src

*** Keybinds

#+begin_src emacs-lisp :tangle no :noweb-ref use-package-emacs-config
;; scroll buffer by a line
(global-set-key (kbd "M-p") #'scroll-down-line)
(global-set-key (kbd "M-n") #'scroll-up-line)
#+end_src

#+begin_src emacs-lisp :noweb yes :exports none
(after! emacs
  <<use-package-emacs>>
    <<use-package-emacs-config>>
    <<use-package-end>>
  )
#+end_src

** [[https://orgmode.org/][Org]]

#+begin_src emacs-lisp :tangle no :noweb-ref use-package-org :exports none
(use-package! org
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref use-package-org-config :exports none
:config
#+end_src

*** Directory

According to Doom, org's directory must be set early due to it's loading process. Therfore it's not inside the package configuration.

#+begin_src emacs-lisp
(setq org-directory "~/documents/org/")
#+end_src

*** Modules

#+begin_src emacs-lisp :tangle no :noweb-ref use-package-org-config
(add-to-list 'org-modules 'org-habit t)             ; enable org-habit
#+end_src

*** Agenda Files

I only check these documents for my agenda items, instead of an entire directory.

#+begin_src emacs-lisp :tangle no :noweb-ref use-package-org-config
(setq org-agenda-files (quote ("~/documents/org/brain.org"
                               "~/documents/org/university/linear-algebra-3720"
                               "~/documents/org/university/data-structures-and-algorithms-5870"
                               "~/documents/org/university/network-concepts-and-administration-3723"
                               "~/documents/org/university/software-engineering-5801"
                               "~/documents/org/university/information-assurance-3755")))
#+end_src

*** Habit Settings

#+begin_src emacs-lisp :tangle no :noweb-ref use-package-org-config
(setq org-habit-show-habits-only-for-today t)       ; ensure habits only shown in one section
(setq org-habit-show-all-today t)                   ; keep habits visible even if done today
#+end_src

*** Logging

#+begin_src emacs-lisp :tangle no :noweb-ref use-package-org-config
(setq org-log-done 'time)                           ; add completion time to DONE items.
(setq org-log-into-drawer t)                        ; puts log times into a drawer to hide them
#+end_src

*** Behavior

This section needs separated...

#+begin_src emacs-lisp :tangle no :noweb-ref use-package-org-config
(setq org-return-follows-link t)                    ; enter opens links in org
(setq org-capture-bookmark nil)                     ; prevent org capture from adding to bookmarks
(setq org-insert-heading-respect-content nil)       ; insert the heading at cursor, not at end
(setq org-imenu-depth 10)                           ; allow imenu to search deeply in org docs
(setq org-use-property-inheritance t)               ; sub-headings inherit parent properties
(setq org-use-fast-todo-selection 'auto)            ; method used for org-todo
;(setq org-use-fast-todo-selection 'expert)
;(setq org-use-fast-todo-selection nil)
(setq evil-collection-calendar-want-org-bindings t) ; add evil bindings to org's calendar
;; these should be moved to ox-latex
(setq org-latex-src-block-backend 'engraved)        ; add syntax highlighting to org latex exports
;(setq org-babel-results-keyword "OUTPUT")           ; a possible workaround, can change this instead of results block exporting, allow to not use :exports both and instead use the result from within the code document, possibly reducing export time. Need to understand more. org babel result shows many variables to play with.
(setq org-highlight-latex-and-related '(native script entities)) ; supposedly teco had other issues with this but I haven't found them...
#+end_src

*** Appearance

#+begin_src emacs-lisp :tangle no :noweb-ref use-package-org-config
(setq org-ellipsis " ▾ ")                           ; set custom ellipsis
(setq org-src-preserve-indentation t)               ; prevent adding spaces/indents
(setq org-hide-emphasis-markers t)                  ; hide formatting for markup
(setq org-hide-leading-stars t)                     ; remove excess heading stars
(setq org-fontify-quote-and-verse-blocks nil)
(setq org-fontify-whole-heading-line nil)
#+end_src

*** Custom Functions
**** Brain Buffer Viewer

This function gives me access to my main org document anywhere in Emacs.

It opens the file if it isn't already and shows it to me. Because it's a toggle, it also closes the buffer upon repeating it's command.

#+begin_src emacs-lisp
(defconst noncog/brain-file "/home/jake/documents/org/brain.org")
(defvar noncog/brain-visible nil)

(defun noncog/toggle-brain ()
  "A function for toggling the view of the your chosen file in a side window."
  (interactive)
  (if (and noncog/brain-visible (get-buffer-window (get-file-buffer noncog/brain-file)) t)
      ;; buffer is visible
      (let ((buffer (get-file-buffer noncog/brain-file)))
        (delete-window (get-buffer-window buffer))
        (kill-buffer buffer)
        (setq noncog/brain-visible nil))
    ;; buffer not visible
    (progn
      (display-buffer (find-file-noselect noncog/brain-file))
      (setq noncog/brain-visible t))))
#+end_src

Now, let's use Doom's popup windowing to control the displaying of the buffer.

#+begin_src emacs-lisp
;; set it's window behavior
(set-popup-rule! "^brain.org" :side 'right :vslot -1 :width 70 :modeline t :select t :quit nil)
#+end_src

And then set a keybind to call my brain viewer.

#+begin_src emacs-lisp
;; evil style
(map! :leader :desc "Brain.org" "b t" #'noncog/toggle-brain)
;; emacs style
(global-set-key (kbd "C-c b") #'noncog/toggle-brain)
#+end_src

**** Unfold Org Headings in Consult Search

This fixes a bug where consult searches can't display the heading you want, only the nearest visible to it.

#+begin_src emacs-lisp
(after! consult
  (defadvice! org-show-entry-consult-a (fn &rest args)
    :around #'consult-line
    :around #'consult-org-heading
    :around #'consult--grep
    (when-let ((pos (apply fn args)))
      (and (derived-mode-p 'org-mode) (org-fold-reveal '(4))))))
#+end_src

**** View Exported Org File

[[https://github.com/tecosaur/emacs-config/blob/master/config.org#view-exported-file][Tecosaur]] has provided us with a function and keybind to view the recently exported org-file.

#+begin_src emacs-lisp
(map! :map org-mode-map
      :localleader
      :desc "View exported file" "v" #'org-view-output-file)

(defun org-view-output-file (&optional org-file-path)
  "Visit buffer open on the first output file (if any) found, using `org-view-output-file-extensions'"
  (interactive)
  (let* ((org-file-path (or org-file-path (buffer-file-name) ""))
         (dir (file-name-directory org-file-path))
         (basename (file-name-base org-file-path))
         (output-file nil))
    (dolist (ext org-view-output-file-extensions)
      (unless output-file
        (when (file-exists-p
               (concat dir basename "." ext))
          (setq output-file (concat dir basename "." ext)))))
    (if output-file
        (if (member (file-name-extension output-file) org-view-external-file-extensions)
            (browse-url-xdg-open output-file)
          (pop-to-buffer (or (find-buffer-visiting output-file)
                             (find-file-noselect output-file))))
      (message "No exported file found"))))

(defvar org-view-output-file-extensions '("pdf" "md" "rst" "txt" "tex" "html")
  "Search for output files with these extensions, in order, viewing the first that matches")
(defvar org-view-external-file-extensions '("html")
  "File formats that should be opened externally.")
#+end_src

#+begin_src emacs-lisp :noweb yes :exports none
(after! org
  <<use-package-org>>
    <<use-package-org-config>>
    <<use-package-end>>
  )
#+end_src

** Org-Agenda

#+begin_src emacs-lisp :tangle no :noweb-ref use-package-org-agenda :exports none
(use-package! org-agenda
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref use-package-org-agenda-config :exports none
:config
#+end_src

*** Behavior

#+begin_src emacs-lisp :tangle no :noweb-ref use-package-org-agenda-config
(setq org-agenda-start-with-log-mode t)             ; show 'completed' done items in agenda
#+end_src

*** Appearance
**** Popup Windowing

Doom allows me to control my agenda windowing to popup temporarily on the right of my screen.

#+begin_src emacs-lisp :tangle no :noweb-ref use-package-org-agenda-config
(set-popup-rule! "^*Org Agenda*" :side 'right :vslot 1 :width 67 :modeline nil :select t :quit t)
#+end_src

**** Custom Faces

I want the titles of agenda sections to be slightly bigger to more easily differentiate them.

#+begin_src emacs-lisp :tangle no :noweb-ref use-package-org-agenda-config
(custom-set-faces!
  '(org-agenda-structure
    :height 1.3 :weight bold))
;(set-face-attribute 'org-agenda-structure nil :height 120 :weight 'bold)
#+end_src

*** Custom Agenda

This is my custom agenda viewer. It has everything I want and nothing more. I see no need for another agenda package, consider writing your own!

#+begin_src emacs-lisp :tangle no :noweb-ref use-package-org-agenda-config
(setq org-agenda-custom-commands
      '(
        ("o" "My Agenda" (
         (agenda "" ( ;; Today
                     (org-agenda-overriding-header "Today\n")
                     (org-agenda-day-face-function (lambda (date) 'org-agenda-date))
                     (org-agenda-block-separator nil)
                     (org-agenda-format-date "%a, %b %-e %y")   ; american date format
                     (org-agenda-start-on-weekday nil)          ; start today
                     (org-agenda-start-day nil)                 ; don't show previous days
                     (org-agenda-span 1)                        ; only show today
                     (org-scheduled-past-days 0)                ; don't show overdue
                     (org-deadline-warning-days 0)              ; don't show deadlines for the future
                     (org-agenda-time-leading-zero t)           ; unify times formatting
                     (org-agenda-time-grid '((daily today remove-match) (800 1000 1200 1400 1600 1800 2000) "" ""))
                     (org-agenda-prefix-format '((agenda . "  %?-5t %?-9:c")))
                     (org-agenda-dim-blocked-tasks nil)
                     (org-agenda-skip-function '(org-agenda-skip-entry-if 'regexp ":STYLE:.*habit"))
                     ))
          (agenda ""( ;; Next Three Days
                     (org-agenda-overriding-header "\nNext Three Days\n")
                     (org-agenda-day-face-function (lambda (date) 'org-agenda-date))
                     (org-agenda-block-separator nil)
                     (org-agenda-format-date "%a %b %-e")
                     (org-agenda-start-on-weekday nil)
                     (org-agenda-start-day "+1d")
                     (org-agenda-span 3)
                     (org-scheduled-past-days 0)
                     (org-deadline-warning-days 0)
                     (org-agenda-time-leading-zero t)
                     (org-agenda-time-grid '((daily weekly) () "" ""))
                     (org-agenda-prefix-format '((agenda . "  %?-9:c%t ")))
                     (org-agenda-skip-function '(org-agenda-skip-entry-if 'todo 'done))
                     (org-agenda-dim-blocked-tasks nil)
                     ))
          (agenda ""( ;; Upcoming Deadlines
                     (org-agenda-overriding-header "\nUpcoming Deadlines\n")
                     (org-agenda-day-face-function (lambda (date) 'org-agenda-date))
                     (org-agenda-block-separator nil)
                     (org-agenda-format-date "%a %b %-e")
                     (org-agenda-start-on-weekday nil)
                     (org-agenda-start-day "+4d")
                     (org-agenda-span 14)
                     (org-scheduled-past-days 0)
                     (org-deadline-warning-days 0)
                     (org-agenda-time-leading-zero t)
                     (org-agenda-time-grid nil)
                     (org-agenda-prefix-format '((agenda . "  %?-5t %?-9:c")))
                     (org-agenda-skip-function '(org-agenda-skip-entry-if 'todo 'done))
                     (org-agenda-entry-types '(:deadline))
                     (org-agenda-show-all-dates nil)
                     (org-agenda-dim-blocked-tasks nil)
                     ))
          (agenda ""( ;; Past Due
                     (org-agenda-overriding-header "\nPast Due\n")
                     (org-agenda-day-face-function (lambda (date) 'org-agenda-date))
                     (org-agenda-block-separator nil)
                     (org-agenda-format-date "%a %b %-e")
                     (org-agenda-start-on-weekday nil)
                     (org-agenda-start-day "-60d")
                     (org-agenda-span 60)
                     (org-scheduled-past-days 60)
                     (org-deadline-past-days 60)
                     (org-deadline-warning-days 0)
                     (org-agenda-time-leading-zero t)
                     (org-agenda-time-grid nil)
                     (org-agenda-prefix-format '((agenda . "  %?-9:c%t ")))
                     (org-agenda-skip-function '(org-agenda-skip-entry-if 'todo 'done))
                     (org-agenda-entry-types '(:deadline :scheduled))
                     (org-agenda-show-all-dates nil)
                     (org-agenda-dim-blocked-tasks nil)
                     ))
          (agenda ""( ;; Habits
                     (org-agenda-overriding-header "\nHabits")
                     (org-agenda-day-face-function (lambda (date) 'org-agenda-date))
                     (org-agenda-block-separator nil)
                     (org-agenda-format-date "")
                     (org-agenda-start-on-weekday nil)
                     (org-agenda-start-day nil)
                     (org-agenda-span 1)
                     (org-agenda-time-grid nil)
                     (org-agenda-prefix-format '((agenda . "  %?-5t %?-7:c")))
                     (org-agenda-dim-blocked-tasks nil)
                     (org-agenda-skip-function '(org-agenda-skip-entry-if 'notregexp ":STYLE:.*habit"))
                     ))
          (todo "" ( ;; Important Tasks No Date
                    (org-agenda-overriding-header "\nImportant Tasks - No Date\n")
                    (org-agenda-block-separator nil)
                    (org-agenda-skip-function '(org-agenda-skip-entry-if 'timestamp 'notregexp "\\[\\#A\\]"))
                    (org-agenda-block-separator nil)
                    (org-agenda-time-grid nil)
                    (org-agenda-prefix-format '((todo . "  %?:c ")))
                    (org-agenda-dim-blocked-tasks nil)
                    ))
         ))))

(add-hook! 'org-agenda-finalize-hook #'noncog/agenda-remove-empty)
#+end_src

**** Remove Empty Agenda Sections

If one of my agenda blocks has no information, I don't want to see it. I call this function when displaying my agenda to delete empty sections.

#+begin_src emacs-lisp
(defun noncog/agenda-remove-empty ()
  "A simple function to remove empty agenda sections. Scans for blank lines. Blank sections defined by having two consecutive blank lines. Not compatible with the block separator."
  (interactive)
  (setq buffer-read-only nil)
  ;; initializes variables and scans first line.
  (goto-char (point-min))
  (let* ((agenda-blank-line "[[:blank:]]*$")
         (content-line-count (if (looking-at-p agenda-blank-line) 0 1))
         (content-blank-line-count (if (looking-at-p agenda-blank-line) 1 0))
         (start-pos (point)))
    ;; step until the end of the buffer
    (while (not (eobp))
      (forward-line 1)
       (cond
        ;; delete region if previously found two blank lines
        ((when (> content-blank-line-count 1)
          (delete-region start-pos (point))
          (setq content-blank-line-count 0)
          (setq start-pos (point))))
        ;; if found a non-blank line
        ((not (looking-at-p agenda-blank-line))
         (setq content-line-count (1+ content-line-count))
         (setq start-pos (point))
         (setq content-blank-line-count 0))
        ;; if found a blank line
        ((looking-at-p agenda-blank-line)
         (setq content-blank-line-count (1+ content-blank-line-count)))))
    ;; final blank line check at end of file
    (when (> content-blank-line-count 1)
      (delete-region start-pos (point))
      (setq content-blank-line-count 0)))
  ;; return to top and finish
  (goto-char (point-min))
  (setq buffer-read-only t)
)
#+end_src

**** Agenda Launcher

I define a function to call my agenda either from M-x or through a keybind.

#+begin_src emacs-lisp
(defun noncog/my-agenda ()
  "My custom agenda launcher."
  (interactive)
  (org-agenda nil "o"))
#+end_src

Then I define a keybind to call my agenda viewer.

#+begin_src emacs-lisp
(map! :leader :desc "My agenda" "o a o" #'noncog/my-agenda)
#+end_src

#+begin_src emacs-lisp :noweb yes :exports none
(after! org-agenda
  <<use-package-org-agenda>>
    <<use-package-org-agenda-config>>
    <<use-package-end>>
  )
#+end_src

** [[https://github.com/weirdNox/org-noter][Org-Noter]]

Allows you to keep org notes that are synced to pdf files! As you scroll your pdf, your notes scroll too!

#+begin_src emacs-lisp :tangle no :noweb-ref use-package-org-noter :exports none
(use-package! org-noter
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref use-package-org-noter-config :exports none
:config
#+end_src

*** Directory

#+begin_src emacs-lisp :tangle no :noweb-ref use-package-org-noter-config
(setq org-noter-notes-search-path '("~/documents/org/noter"))
#+end_src

*** Behavior

#+begin_src emacs-lisp :tangle no :noweb-ref use-package-org-noter-config
(setq org-noter-separate-notes-from-heading t)      ; Adds a blank line between headings and notes
(setq org-noter-auto-save-last-location t)          ; remembers where I left off in pdfs and notes
#+end_src

*** Appearance

#+begin_src emacs-lisp :tangle no :noweb-ref use-package-org-noter-config
;; don't touch my frames...
(setq org-noter-always-create-frame nil)
(setq org-noter-kill-frame-at-session-end nil)
#+end_src

*** Custom Functions
**** Better Org-Noter Exit

I had issues with Doom and org-noter not closing pdf buffers and returning my windowing back to normal. This function solves that.

#+begin_src emacs-lisp
(defun noncog/kill-org-noter-session ()
  "Fully exits the noter-session and the pdf buffers it used, leaving the org file."
  (interactive)
  (let ((pdf-fname (buffer-file-name (org-noter--session-doc-buffer org-noter--session))) (ses-id (org-noter--session-id org-noter--session))) (set-window-dedicated-p (get-buffer-window (get-file-buffer pdf-fname)) nil) (call-interactively #'org-noter-kill-session ses-id) (doom/kill-this-buffer-in-all-windows (get-file-buffer pdf-fname))))
#+end_src

Then I define a keybind to call my org-noter kill function.

#+begin_src emacs-lisp
(map! :leader :desc "Kill org noter session" "n k" #'noncog/kill-org-noter-session)
#+end_src

#+begin_src emacs-lisp :noweb yes :exports none
(after! org-noter
  <<use-package-org-noter>>
    <<use-package-org-noter-config>>
    <<use-package-end>>
  )
#+end_src

** [[https://github.com/rlister/org-present][Org-Present]]

Is a minimal presentation tool for org-mode. It's designed around each slide being contained in a top-level header.

Because it's so minimal, I do a bit of customization to make it more usable and pleasant to view.

#+begin_src emacs-lisp :tangle no :noweb-ref use-package-org-present :exports none
(use-package! org-present
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref use-package-org-present-config :exports none
:config
#+end_src

*** Keybinds

Evil collection has a set of default binds for this mode that I disagree with, so we'll disable it.

#+begin_src emacs-lisp
(add-to-list '+evil-collection-disabled-list 'org-present)
#+end_src

Then, we set binds that make more sense for this mode.

#+begin_src emacs-lisp :tangle no :noweb-ref use-package-org-present-config
(map! :map org-mode-map :localleader "m" #'org-present)
(map! :map org-present-mode-keymap "C-q" #'org-present-quit)
(map! :map org-present-mode-keymap "C-g" #'org-present-beginning)
(map! :map org-present-mode-keymap "C-j" #'noncog/org-show-next-heading-tidily)
(map! :map org-present-mode-keymap "C-k" #'noncog/org-show-previous-heading-tidily)
#+end_src

*** Custom Functions
**** Fold Entries Per Top Heading

This creates a tidy view of each "section" of the org presentation as I enter them.

#+begin_src emacs-lisp
(defun noncog/org-present-prepare-slide (buffer-name heading)
  ;; Show only top-level headlines
  (org-overview)

  ;; Unfold the current entry
  (org-show-entry)

  ;; Show only direct subheadings of the slide but don't expand them
  (org-show-children)
  )

(add-hook 'org-present-after-navigate-functions 'noncog/org-present-prepare-slide)
#+end_src

**** Active Folding For Next Heading

The holy grail to making org-present actually usable. This should be included by default.

These functions allow me to advance through the headings, folding previous ones, only showing the current heading's information tidily.

#+begin_example :tangle no :exports none
I am considering writing other functions to change the method of progressing through the slide. These methods affect the way in which the document must be laid out and how one progresses through it. Multiple functions will allow the user to lay out the document in a way that makes sense for their project, or generate more freedom in using the project document itself as the presentation instead of making another org document just for the presentation.

I'm considering skipping headlines without a present tag.

TODO - add example image/gif.
#+end_example

#+begin_src emacs-lisp
(setq recenter-positions '(top bottom))

(defun noncog/org-show-next-heading-tidily ()
  "Show next entry, keeping other entries closed."
  (interactive)
  (if (save-excursion (end-of-line) (outline-invisible-p))
      (progn (org-fold-show-entry) (outline-show-children))
    (unless (org-before-first-heading-p) (outline-next-heading))
    (unless (and (bolp) (org-at-heading-p))
      ;(org-up-heading-safe)
      ;(hide-subtree)
      ;(error "Boundary reached")
      ;(if (eobp) (error "end of slide") (org-present-next))
      (org-present-next)
      )
    (org-overview)
    (org-reveal t)
    (org-fold-show-entry)
    (recenter-top-bottom)
    (outline-show-children)
    (recenter-top-bottom)))

(defun noncog/org-show-previous-heading-tidily ()
  "Show previous entry, keeping other entries closed."
  (interactive)
  (let ((pos (point)))
    (outline-previous-heading)
    (unless (and (< (point) pos) (bolp) (org-at-heading-p))
      (goto-char pos)
      (org-present-prev)
      )
    (org-overview)
    (org-reveal t)
    (org-fold-show-entry)
    (recenter-top-bottom)
    (outline-show-children)
    (recenter-top-bottom)))
#+end_src

**** Start/End Presentation Hooks

These functions control any formatting done upon entering and exiting the presentation mode.

#+begin_src emacs-lisp
(defun noncog/org-present-start ()
  (setq-local display-line-numbers nil)
  (setq-local header-line-format " ")
  (org-display-inline-images)
  ;; add space to the top of the screen
  ;; default inherits from the modeline, which for me, is colored
  (custom-set-faces!
    '(header-line :inherit nil :height 2.0))
  (doom-big-font-mode 1)
  ;; (setq visual-fill-column-width 110)               ; sets the text width of the centered buffer
  ;; (setq visual-fill-column-center-text t)           ; centers the buffer
  ;; (visual-fill-column-mode 1)
  ;; (visual-line-mode 1)
  )
(add-hook! 'org-present-mode-hook #'noncog/org-present-start)
#+end_src

#+begin_src emacs-lisp
(defun noncog/org-present-end ()
  (setq-local display-line-numbers 'visual)
  (setq-local header-line-format nil)
  (org-remove-inline-images)
  (custom-set-faces!
    '(header-line :height 1.0))
  (+org/show-next-fold-level)
  (doom-big-font-mode 0)
  ;; (setq visual-fill-column-width 0)               ; sets the text width of the centered buffer
  ;; (setq visual-fill-column-center-text nil)           ; centers the buffer
  ;; (visual-fill-column-mode 0)
  ;; (visual-line-mode 0)
  )
(add-hook! 'org-present-mode-quit-hook #'noncog/org-present-end)
#+end_src

#+begin_src emacs-lisp :noweb yes :exports none
<<use-package-org-present>>
  <<use-package-org-present-config>>
  <<use-package-end>>
#+end_src

** [[https://orgmode.org/manual/Org-Plot.html][Org-Plot]]

Produces 2D/3D graphs from org tables using [[http://www.gnuplot.info/][gnuplot]] and [[https://github.com/mkmcc/gnuplot-mode][gnuplot-mode]].

*** Appearance

[[https://github.com/tecosaur/emacs-config/blob/master/config.org#org-plot][Tecosaur]] provides us with a way to use our Doom theme colors for org-plot!

#+begin_src emacs-lisp
(defvar +org-plot-term-size '(1050 . 650)
  "The size of the GNUPlot terminal, in the form (WIDTH . HEIGHT).")

(after! org-plot
  (defun +org-plot-generate-theme (_type)
    "Use the current Doom theme colours to generate a GnuPlot preamble."
    (format "
fgt = \"textcolor rgb '%s'\" # foreground text
fgat = \"textcolor rgb '%s'\" # foreground alt text
fgl = \"linecolor rgb '%s'\" # foreground line
fgal = \"linecolor rgb '%s'\" # foreground alt line

# foreground colors
set border lc rgb '%s'
# change text colors of  tics
set xtics @fgt
set ytics @fgt
# change text colors of labels
set title @fgt
set xlabel @fgt
set ylabel @fgt
# change a text color of key
set key @fgt

# line styles
set linetype 1 lw 2 lc rgb '%s' # red
set linetype 2 lw 2 lc rgb '%s' # blue
set linetype 3 lw 2 lc rgb '%s' # green
set linetype 4 lw 2 lc rgb '%s' # magenta
set linetype 5 lw 2 lc rgb '%s' # orange
set linetype 6 lw 2 lc rgb '%s' # yellow
set linetype 7 lw 2 lc rgb '%s' # teal
set linetype 8 lw 2 lc rgb '%s' # violet

# border styles
set tics out nomirror
set border 3

# palette
set palette maxcolors 8
set palette defined ( 0 '%s',\
1 '%s',\
2 '%s',\
3 '%s',\
4 '%s',\
5 '%s',\
6 '%s',\
7 '%s' )
"
            (doom-color 'fg)
            (doom-color 'fg-alt)
            (doom-color 'fg)
            (doom-color 'fg-alt)
            (doom-color 'fg)
            ;; colours
            (doom-color 'red)
            (doom-color 'blue)
            (doom-color 'green)
            (doom-color 'magenta)
            (doom-color 'orange)
            (doom-color 'yellow)
            (doom-color 'teal)
            (doom-color 'violet)
            ;; duplicated
            (doom-color 'red)
            (doom-color 'blue)
            (doom-color 'green)
            (doom-color 'magenta)
            (doom-color 'orange)
            (doom-color 'yellow)
            (doom-color 'teal)
            (doom-color 'violet)))

  (defun +org-plot-gnuplot-term-properties (_type)
    (format "background rgb '%s' size %s,%s"
            (doom-color 'bg) (car +org-plot-term-size) (cdr +org-plot-term-size)))

  (setq org-plot/gnuplot-script-preamble #'+org-plot-generate-theme)
  (setq org-plot/gnuplot-term-extra #'+org-plot-gnuplot-term-properties))
#+end_src

** Ox

Controls the exporting of org documents.

#+begin_src emacs-lisp
(after! ox
  (setq org-export-headline-levels 7)
  (setq org-export-with-creator t)
  (setq org-export-creator-string (concat "Doom Emacs " emacs-version " (Org mode " org-version ")" ))
  )
#+end_src

** Ox-Latex

#+begin_src emacs-lisp
(use-package! ox-latex
  :init
  (setq org-latex-pdf-process '("LC_ALL=en_US.UTF-8 latexmk -f -pdf -%latex -shell-escape -interaction=nonstopmode -output-directory=%o %f"))
  )
#+end_src

** [[https://github.com/vedang/pdf-tools][PDF-Tools]]

A better meta package of tools for viewing and interacting with PDFs. This is required to use org-noter.

#+begin_src emacs-lisp
(after! pdf-tools
  (setq-default pdf-view-display-size 'fit-page))
#+end_src

** [[https://github.com/tecosaur/engrave-faces][Engrave-Faces]]

Provides syntax code block highlighting and theming to our org-latex pdf exports!

We just need to load this package after ox-latex for our latex pdf exports.

#+begin_src emacs-lisp
(use-package! engrave-faces-latex
  :after ox-latex
)
#+end_src

** [[https://github.com/protesilaos/pulsar][Pulsar]]

This wonderful package blinks and highlights the current line. I primarily use it on window switching to never lose track of the cursor/point again.

#+begin_src emacs-lisp :tangle no :noweb-ref use-package-pulsar :exports none
(use-package! pulsar
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref use-package-pulsar-config :exports none
:config
#+end_src

*** Behavior

Setup the basic pulse configuration.

#+begin_src emacs-lisp :tangle no :noweb-ref use-package-pulsar-config
(setq pulsar-pulse t)
(setq pulsar-delay 0.095)
(setq pulsar-iterations 12)
#+end_src

*** Appearance

#+begin_src emacs-lisp :tangle no :noweb-ref use-package-pulsar-config
(setq pulsar-face 'pulsar-magenta)                  ; used by pulsar-pulse-line
(setq pulsar-highlight-face 'pulsar-yellow)         ; used by pulsar-highlight-*
#+end_src

*** Add to Evil

#+begin_src emacs-lisp :tangle no :noweb-ref use-package-pulsar-config
(add-to-list 'pulsar-pulse-functions 'evil-scroll-up)
(add-to-list 'pulsar-pulse-functions 'evil-scroll-down)

(add-to-list 'pulsar-pulse-functions 'evil-window-left)
(add-to-list 'pulsar-pulse-functions 'evil-window-down)
(add-to-list 'pulsar-pulse-functions 'evil-window-up)
(add-to-list 'pulsar-pulse-functions 'evil-window-right)

(add-to-list 'pulsar-pulse-functions 'evil-window-next)
(add-to-list 'pulsar-pulse-functions 'evil-window-prev)
#+end_src

*** Recentering
**** Middle Recenter

#+begin_src emacs-lisp
(defun noncog/pulsar-scroll-recenter-middle (&rest _args)
  (pulsar-recenter-middle))
#+end_src

**** After Scrolling Recenter Middle

#+begin_src emacs-lisp :tangle no :noweb-ref use-package-pulsar-config
(advice-add 'evil-scroll-up :after #'noncog/pulsar-scroll-recenter-middle)
(advice-add 'evil-scroll-down :after #'noncog/pulsar-scroll-recenter-middle)
#+end_src

**** After Jumping Recenter Top

#+begin_src emacs-lisp :tangle no :noweb-ref use-package-pulsar-config
(add-hook 'consult-after-jump-hook #'pulsar-recenter-top)
(add-hook 'imenu-after-jump-hook #'pulsar-recenter-top)
(add-hook 'imenu-after-jump-hook #'pulsar-reveal-entry)
#+end_src

*** Enable

#+begin_src emacs-lisp
(pulsar-global-mode 1)
#+end_src

#+begin_src emacs-lisp :noweb yes :exports none
<<use-package-pulsar>>
  <<use-package-pulsar-config>>
  <<use-package-end>>
#+end_src

** [[https://company-mode.github.io/][Company]]

This is the completion framework that Doom uses. It uses back-ends to retrieve and display completion candidates.

#+begin_src emacs-lisp :tangle no :noweb-ref use-package-company :exports none
(use-package! company
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref use-package-company-config :exports none
:config
#+end_src

*** Behavior

#+begin_src emacs-lisp :tangle no :noweb-ref use-package-company-config
(setq company-idle-delay 0.1)
(setq company-tooltip-limit 10)
(setq company-minimum-prefix-length 1)
#+end_src

*** Package Settings
**** Text-mode

Text-mode is often inherited by other modes like org-mode. I would rather be able to control modes explicitly instead of use inheritance.

I disable company for text-mode then remove it's backend from the alist.

#+begin_src emacs-lisp :tangle no :noweb-ref use-package-company-config
(setq company-global-modes '(not text-mode erc-mode circe-mode message-mode help-mode gud-mode vterm-mode))
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref use-package-company-config
(setq +company-backend-alist (assq-delete-all 'text-mode +company-backend-alist))
#+end_src

**** Org-mode

#+begin_src emacs-lisp :tangle no :noweb-ref use-package-company-config
(set-company-backend! 'org-mode
  '(company-capf company-files :with company-yasnippet))
#+end_src

**** Sh-mode

#+begin_src emacs-lisp :tangle no :noweb-ref use-package-company-config
(set-company-backend! 'sh-mode
  '(company-shell company-files :with company-yasnippet))
#+end_src

#+begin_src emacs-lisp :noweb yes :exports none
(after! company
  <<use-package-company>>
    <<use-package-company-config>>
    <<use-package-end>>
  )
#+end_src

** [[https://github.com/abo-abo/ace-window][Ace-Window]]

Gives us quicker window switching when other-window just won't cut it. Allows us to jump to specific windows instead of cycle our way there.

#+begin_src emacs-lisp
(after! ace-window
  ;; customize face used for indicators
  (custom-set-faces!
    '(aw-leading-char-face :foreground "magenta" :background "bg" :weight bold :height 180 :box (:line-width 1 :color "magenta")))
  (setq aw-keys '(?h ?j ?k ?l ?a ?s ?d ?f))
  (setq aw-mnibuffer-flag t)
  (setq aw-scope 'global)
  )
#+end_src

** [[https://github.com/bbatsov/projectile][Projectile]]

Provides project level interaction.

The only real modification I make is to have it ignore my Doom installation directory.

#+begin_src emacs-lisp :tangle no :noweb-ref projectile-config
(setq projectile-ignored-projects '("/opt/doom-emacs/"))
#+end_src

And I had a keybind to view the projects with uncommited changes.

#+begin_src emacs-lisp :tangle no :noweb-ref projectile-config
(map! :leader :desc "List dirty projects" "p l" #'projectile-browse-dirty-projects)
#+end_src

#+begin_src emacs-lisp :noweb yes :exports none
(after! projectile
  <<projectile-config>>
  )
#+end_src

** [[https://codeberg.org/joostkremers/visual-fill-column][Visual-Fill Column]]

This package adds centering to buffers, amongst other things.

This package is incompatible with Doom's popup window rules so I'm looking for an alternative.

#+begin_src emacs-lisp :tangle no
(use-package! visual-fill-column
  :init
  (setq visual-fill-column-center-text t)           ; centers the buffer
)
#+end_src

** [[https://github.com/joaotavora/yasnippet][Yasnippet]]
*** Information

[[https://github.com/doomemacs/snippets][Doom Snippets]]

[[https://joaotavora.github.io/yasnippet/snippet-development.html][Yasnippet Development]]

#+begin_src emacs-lisp :tangle no :noweb-ref use-package-yasnippet :exports none
(use-package! yasnippet
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref use-package-yasnippet-config :exports none
:config
#+end_src

*** Directory

#+begin_src emacs-lisp :tangle no :noweb-ref use-package-yasnippet-config
(setq yas-snippet-dirs '("~/.config/doom/snippets/"))
#+end_src

*** Behavior

#+begin_src emacs-lisp :tangle no :noweb-ref use-package-yasnippet-config
(setq yas-indent-line 'fixed)                       ; prevent yasnippet from changing my indents
#+end_src

#+begin_src emacs-lisp :noweb yes :exports none
(after! yasnippet
  <<use-package-yasnippet>>
    <<use-package-yasnippet-config>>
    <<use-package-end>>
  )
#+end_src

** Python

#+begin_src emacs-lisp :tangle no :exports none :noweb-ref use-package-python :exports none
(use-package! python
#+end_src

#+begin_src emacs-lisp :tangle no :exports none :noweb-ref use-package-python-config :exports none
:init
#+end_src

*** Behavior

#+begin_src emacs-lisp :tangle no :noweb-ref use-package-python-config
(setq python-shell-interpreter "python3")
#+end_src

#+begin_src emacs-lisp :noweb yes :exports none
<<use-package-python>>
  <<use-package-python-config>>
  <<use-package-end>>
#+end_src

