#+tags: export noexport
#+export_select_tags: export
#+export_exclude_tags: exclude noexport

#+begin_html
<div align="center">

<!-- Shields -->
<p><a href="https://www.gnu.org/software/emacs/emacs.html#Releases"><img src="https://img.shields.io/badge/Emacs-27.1+-blueviolet.svg?style=flat-square&logo=GNU%20Emacs&logoColor=white"></a> <a href="https://orgmode.org"><img src="https://img.shields.io/badge/Org-literate%20config-%2377aa99?style=flat-square&logo=org&logoColor=white"></a></p>

<!-- Doom Logo -->
<p><a href="https://github.com/Schievel1/doom-emacs-splash"><img src="https://github.com/Schievel1/doom-emacs-splash/blob/main/svg/doom/doomEmacsDracula.svg" height="300"></a></p>

<p><a href="https://creativecommons.org/licenses/by-sa/4.0/"><img src="https://img.shields.io/badge/CC--BY--SA-161b22?style=for-the-badge&logo=Creative%20Commons&logoColor=white"></a></p>

<!-- Description -->
<p><code>This is my <a href="https://github.com/doomemacs/doomemacs">Doom</a> <a href="https://www.gnu.org/software/emacs/">Emacs</a> configuration.</code></p>

</div>
#+end_html

* Table of Contents :TOC:QUOTE:
:PROPERTIES:
#+html:<details><summary>Table of Contents</summary>
#+BEGIN_QUOTE
  - [[#doom][Doom]]
  - [[#doom-configs][Doom Configs]]
  - [[#variables][Variables]]
  - [[#appearance][Appearance]]
  - [[#behavior][Behavior]]
  - [[#keybinds][Keybinds]]
- [[#beacon][Beacon]]
  - [[#package][Package]]
  - [[#appearance-1][Appearance]]
  - [[#behavior-1][Behavior]]
- [[#which-key][Which-Key]]
  - [[#package-1][Package]]
  - [[#behavior-2][Behavior]]
  - [[#fixes][Fixes]]
- [[#avy][Avy]]
  - [[#package-2][Package]]
  - [[#behavior-3][Behavior]]
- [[#helpful][Helpful]]
  - [[#package-3][Package]]
  - [[#behavior-4][Behavior]]
  - [[#keybinds-1][Keybinds]]
- [[#doom-modeline][Doom Modeline]]
  - [[#package-4][Package]]
  - [[#appearance-2][Appearance]]
- [[#doom-dashboard][Doom Dashboard]]
  - [[#package-5][Package]]
  - [[#appearance-3][Appearance]]
  - [[#behavior-5][Behavior]]
  - [[#keybinds-2][Keybinds]]
- [[#persp-mode][Persp-Mode]]
  - [[#package-6][Package]]
  - [[#fixes-1][Fixes]]
- [[#vertico][Vertico]]
  - [[#package-7][Package]]
  - [[#behavior-6][Behavior]]
  - [[#keybinds-3][Keybinds]]
- [[#marginalia][Marginalia]]
  - [[#package-8][Package]]
  - [[#appearance-4][Appearance]]
- [[#company][Company]]
  - [[#package-9][Package]]
  - [[#behavior-7][Behavior]]
- [[#yasnippet][Yasnippet]]
  - [[#package-10][Package]]
  - [[#resources][Resources]]
  - [[#behavior-8][Behavior]]
- [[#projectile][Projectile]]
  - [[#package-11][Package]]
  - [[#variables-1][Variables]]
  - [[#behavior-9][Behavior]]
  - [[#keybinds-4][Keybinds]]
- [[#treemacs][Treemacs]]
  - [[#package-12][Package]]
  - [[#appearance-5][Appearance]]
  - [[#behavior-10][Behavior]]
- [[#magit][Magit]]
  - [[#package-13][Package]]
  - [[#behavior-11][Behavior]]
- [[#vterm][Vterm]]
  - [[#package-14][Package]]
  - [[#keybinds-5][Keybinds]]
- [[#visual-fill-column][Visual Fill Column]]
  - [[#package-15][Package]]
- [[#org][Org]]
  - [[#package-16][Package]]
  - [[#variables-2][Variables]]
  - [[#appearance-6][Appearance]]
  - [[#behavior-12][Behavior]]
- [[#org-agenda][Org Agenda]]
  - [[#package-17][Package]]
  - [[#appearance-7][Appearance]]
  - [[#behavior-13][Behavior]]
  - [[#keybinds-6][Keybinds]]
  - [[#helpers][Helpers]]
- [[#org-capture][Org Capture]]
  - [[#package-18][Package]]
  - [[#variables-3][Variables]]
  - [[#behavior-14][Behavior]]
  - [[#keybinds-7][Keybinds]]
  - [[#fixes-2][Fixes]]
- [[#org-roam][Org Roam]]
  - [[#package-19][Package]]
  - [[#resources-1][Resources]]
  - [[#variables-4][Variables]]
  - [[#appearance-8][Appearance]]
  - [[#behavior-15][Behavior]]
  - [[#keybinds-8][Keybinds]]
- [[#org-roam-ui][Org Roam UI]]
  - [[#package-20][Package]]
  - [[#appearance-9][Appearance]]
  - [[#behavior-16][Behavior]]
  - [[#keybinds-9][Keybinds]]
- [[#vulpea][Vulpea]]
  - [[#package-21][Package]]
  - [[#helpers-1][Helpers]]
- [[#org-gtd][Org GTD]]
  - [[#package-22][Package]]
  - [[#variables-5][Variables]]
  - [[#behavior-17][Behavior]]
  - [[#keybinds-10][Keybinds]]
- [[#org-appear][Org Appear]]
  - [[#package-23][Package]]
  - [[#appearance-10][Appearance]]
- [[#org-fragtog][Org Fragtog]]
  - [[#package-24][Package]]
- [[#org-modern][Org Modern]]
  - [[#package-25][Package]]
  - [[#appearance-11][Appearance]]
- [[#org-modern-indent][Org Modern Indent]]
  - [[#package-26][Package]]
- [[#toc-org][TOC Org]]
  - [[#package-27][Package]]
  - [[#behavior-18][Behavior]]
- [[#org-noter][Org Noter]]
  - [[#package-28][Package]]
  - [[#variables-6][Variables]]
  - [[#behavior-19][Behavior]]
- [[#pdf-tools][PDF Tools]]
  - [[#package-29][Package]]
  - [[#behavior-20][Behavior]]
  - [[#fixes-3][Fixes]]
- [[#plantuml][PlantUML]]
  - [[#package-30][Package]]
  - [[#behavior-21][Behavior]]
- [[#ox-org-export][Ox (Org Export)]]
  - [[#package-31][Package]]
  - [[#appearance-12][Appearance]]
  - [[#behavior-22][Behavior]]
  - [[#keybinds-11][Keybinds]]
- [[#ox-latex][Ox Latex]]
  - [[#package-32][Package]]
  - [[#appearance-13][Appearance]]
  - [[#behavior-23][Behavior]]
- [[#engrave-faces][Engrave Faces]]
  - [[#package-33][Package]]
- [[#lsp-clangd][LSP-Clangd]]
  - [[#package-34][Package]]
  - [[#behavior-24][Behavior]]
#+END_QUOTE
#+html:</details>

** Doom
:PROPERTIES:
:VISIBILITY: children
:END:
Place-holder text.
#+begin_quote
[[https://github.com/doomemacs/doomemacs][Doom]] is a configuration framework for GNU Emacs tailored for Emacs bankruptcy veterans who want less framework in their frameworks, a modicum of stability (and reproducibility) from their package manager, and the performance of a hand rolled config (or better). It can be a foundation for your own config or a resource for Emacs enthusiasts to learn more about our favorite operating system.
#+end_quote

** Doom Configs
:PROPERTIES:
:VISIBILITY: children
:END:

Doom only uses three config files, loaded in a specific order. I use Org's literate programming technique known as 'tangling' to generate them from this =README.org= file. This allows me to describe my configuration in a different order than it would actually appears in Doom's configs:

*** Init.el

#+html:<details><summary>Defines which of Doom’s modules are enabled and their load order.</summary>

**** Enable Lexical Binding

#+begin_src emacs-lisp :tangle init.el
;;; init.el -*- lexical-binding: t; -*-
#+end_src

**** Early Init

Some settings (very few) need to be loaded before Doom's modules. They're tangled to here from other sections of my configuration using =noweb= referenced code blocks.

#+begin_src emacs-lisp :tangle "init.el" :noweb tangle
<<early-init>>
#+end_src

**** Modules

#+begin_src emacs-lisp :tangle init.el
(doom! :input
       ;;bidi              ; (tfel ot) thgir etirw uoy gnipleh
       ;;chinese
       ;;japanese
       ;;layout            ; auie,ctsrnm is the superior home row

       :completion
       (company)           ; the ultimate code completion backend
        ;+childframe)       ; display completions in a childframe...
       ;;helm              ; the *other* search engine for love and life
       ;;ido               ; the other *other* search engine...
       ;;ivy               ; a search engine for love and life
       (vertico +icons)    ; the search engine of the future

       :ui
       ;;deft              ; notational velocity for Emacs
       doom                ; what makes DOOM look the way it does
       doom-dashboard      ; a nifty splash screen for Emacs
       ;;doom-quit         ; DOOM quit-message prompts when you quit Emacs
       (emoji              ; 🙂
        +unicode
        +github)
       hl-todo             ; highlight TODO/FIXME/NOTE/DEPRECATED/HACK/REVIEW
       ;;hydra
       ;;indent-guides     ; highlighted indent columns
       ;;ligatures         ; ligatures and symbols to make your code pretty again
       ;;minimap           ; show a map of the code on the side
       modeline            ; snazzy, Atom-inspired modeline, plus API
       ;nav-flash          ; blink cursor line after big motions
       ;;neotree           ; a project drawer, like NERDTree for vim
       ophints             ; highlight the region an operation acts on
       (popup +defaults)   ; tame sudden yet inevitable temporary windows
       ;;tabs              ; a tab bar for Emacs
       treemacs            ; a project drawer, like neotree but cooler
       ;;unicode           ; extended unicode support for various languages
       (vc-gutter +pretty) ; vcs diff in the fringe
       vi-tilde-fringe     ; fringe tildes to mark beyond EOB
       ;;window-select     ; visually switch windows
       workspaces          ; tab emulation, persistence & separate workspaces
       zen                 ; distraction-free coding or writing

       :editor
       (evil +everywhere)  ; come to the dark side, we have cookies
       file-templates      ; auto-snippets for empty files
       fold                ; (nigh) universal code folding
       ;;(format +onsave)  ; automated prettiness
       ;;god               ; run Emacs commands without modifier keys
       ;;lispy             ; vim for lisp, for people who don't like vim
       ;;multiple-cursors  ; editing in many places at once
       ;;objed             ; text object editing for the innocent
       ;;parinfer          ; turn lisp into python, sort of
       ;;rotate-text       ; cycle region at point between text candidates
       snippets            ; my elves. They type so I don't have to
       word-wrap           ; soft wrapping with language-aware indent

       :emacs
       (dired              ; making dired pretty [functional]
        +icons             ; use icons for file types
        +ranger)           ; emulate the famous vim-based file manager
       electric            ; smarter, keyword-based electric-indent
       (ibuffer +icons)    ; interactive buffer management
       undo                ; persistent, smarter undo for your inevitable mistakes
       vc                  ; version-control and Emacs, sitting in a tree

       :term
       ;;eshell            ; the elisp shell that works everywhere
       ;;shell             ; simple shell REPL for Emacs
       ;;term              ; basic terminal emulator for Emacs
       vterm               ; the best terminal emulation in Emacs

       :checkers
       syntax              ; tasing you for every semicolon you forget
       ;;(spell +flyspell) ; tasing you for misspelling mispelling
       ;;grammar           ; tasing grammar mistake every you make

       :tools
       ;;ansible
       ;;biblio            ; Writes a PhD for you (citation needed)
       ;;debugger          ; FIXME stepping through code, to help you add bugs
       ;;direnv
       ;;docker
       ;;editorconfig      ; let someone else argue about tabs vs spaces
       ;;ein               ; tame Jupyter notebooks with emacs
       (eval +overlay)     ; run code, run (also, repls)
       ;;gist              ; interacting with github gists
       lookup              ; navigate your code and its documentation
       lsp                 ; M-x vscode
       magit               ; a git porcelain for Emacs
       ;;make              ; run make tasks from Emacs
       ;;pass              ; password manager for nerds
       pdf                 ; pdf enhancements
       ;;prodigy           ; FIXME managing external services & code builders
       ;;rgb               ; creating color strings
       ;;taskrunner        ; taskrunner for all your projects
       ;;terraform         ; infrastructure as code
       ;;tmux              ; an API for interacting with tmux
       ;;tree-sitter       ; syntax and parsing, sitting in a tree...
       ;;upload            ; map local to remote projects via ssh/ftp

       :os
       (:if IS-MAC macos)  ; improve compatibility with macOS
       tty                 ; improve the terminal Emacs experience

       :lang
       ;;agda              ; types of types of types of types...
       ;;beancount         ; mind the GAAP
       (cc +lsp)           ; C > C++ == 1
       ;;clojure           ; java with a lisp
       ;;common-lisp       ; if you've seen one lisp, you've seen them all
       ;;coq               ; proofs-as-programs
       ;;crystal           ; ruby at the speed of c
       ;;csharp            ; unity, .NET, and mono shenanigans
       ;;data              ; config/data formats
       ;;(dart +flutter)   ; paint ui and not much else
       ;;dhall
       ;;elixir            ; erlang done right
       ;;elm               ; care for a cup of TEA?
       emacs-lisp          ; drown in parentheses
       ;;erlang            ; an elegant language for a more civilized age
       ;;ess               ; emacs speaks statistics
       ;;factor
       ;;faust             ; dsp, but you get to keep your soul
       ;;fortran           ; in FORTRAN, GOD is REAL (unless declared INTEGER)
       ;;fsharp            ; ML stands for Microsoft's Language
       ;;fstar             ; (dependent) types and (monadic) effects and Z3
       ;;gdscript          ; the language you waited for
       ;;(go +lsp)         ; the hipster dialect
       ;;(graphql +lsp)    ; Give queries a REST
       ;;(haskell +lsp)    ; a language that's lazier than I am
       ;;hy                ; readability of scheme w/ speed of python
       ;;idris             ; a language you can depend on
       ;;json              ; At least it ain't XML
       ;;(java +lsp)       ; the poster child for carpal tunnel syndrome
       ;;javascript        ; all(hope(abandon(ye(who(enter(here))))))
       ;;julia             ; a better, faster MATLAB
       ;;kotlin            ; a better, slicker Java(Script)
       (latex              ; writing papers in Emacs has never been so fun
        +cdlatex           ; Enable cdlatex for fast math insertion
        +fold              ; Use TeX-fold to fold LaTeX macros to unicode
        +latexmk)          ; Use laexMk instead of Latex to compile documents
       ;;lean              ; for folks with too much to prove
       ;;ledger            ; be audit you can be
       ;;lua               ; one-based indices? one-based indices
       markdown            ; writing docs for people to ignore
       ;;nim               ; python + lisp at the speed of c
       ;;nix               ; I hereby declare "nix geht mehr!"
       ;;ocaml             ; an objective camel
       (org                ; organize your plain life in plain text
        +noter
        +dragndrop
        +roam2
        +gnuplot)
       ;;php               ; perl's insecure younger brother
       plantuml            ; diagrams for confusing people more
       ;;purescript        ; javascript, but functional
       ;;python            ; beautiful is better than ugly
       ;;qt                ; the 'cutest' gui framework ever
       ;;racket            ; a DSL for DSLs
       ;;raku              ; the artist formerly known as perl6
       ;;rest              ; Emacs as a REST client
       ;;rst               ; ReST in peace
       ;;(ruby +rails)     ; 1.step {|i| p "Ruby is #{i.even? ? 'love' : 'life'}"}
       ;;(rust +lsp)       ; Fe2O3.unwrap().unwrap().unwrap().unwrap()
       ;;scala             ; java, but good
       ;;(scheme +guile)   ; a fully conniving family of lisps
       sh                  ; she sells {ba,z,fi}sh shells on the C xor
       ;;sml
       ;;solidity          ; do you need a blockchain? No.
       ;;swift             ; who asked for emoji variables?
       ;;terra             ; Earth and Moon in alignment for performance.
       ;;web               ; the tubes
       ;;yaml              ; JSON, but readable
       ;;zig               ; C, but simpler

       :email
       ;;(mu4e +org +gmail)
       ;;notmuch
       ;;(wanderlust +gmail)

       :app
       ;;calendar
       ;;emms
       ;;everywhere        ; *leave* Emacs!? You must be joking
       ;;irc               ; how neckbeards socialize
       ;;(rss +org)        ; emacs as an RSS reader
       ;;twitter           ; twitter client https://twitter.com/vnought

       :config
       literate
       (default +bindings +smartparens))
#+end_src

#+html:</details>

*** Packages.el

#+html:<details><summary>Defines which external packages are loaded by the user.</summary>

**** Disable Byte Compiling

#+begin_src emacs-lisp :tangle no :noweb-ref packages
;; -*- no-byte-compile: t; -*-
;;; $DOOMDIR/packages.el
#+end_src

**** User Packages

External packages are added by the user here. Each package's =package!= source recipe is defined in its relevant package configuration secion and is tangled here using =noweb= referenced code blocks.

#+begin_src emacs-lisp :tangle "packages.el" :noweb tangle
<<packages>>
#+end_src

**** Basic Use Instructions

#+begin_src emacs-lisp :tangle no
;; To install SOME-PACKAGE from MELPA, ELPA or emacsmirror:
;(package! some-package)

;; To install a package directly from a remote git repo, you must specify a
;; `:recipe'. You'll find documentation on what `:recipe' accepts here:
;; https://github.com/radian-software/straight.el#the-recipe-format
;(package! another-package
;  :recipe (:host github :repo "username/repo"))

;; If the package you are trying to install does not contain a PACKAGENAME.el
;; file, or is located in a subdirectory of the repo, you'll need to specify
;; `:files' in the `:recipe':
;(package! this-package
;  :recipe (:host github :repo "username/repo"
;           :files ("some-file.el" "src/lisp/*.el")))

;; If you'd like to disable a package included with Doom, you can do so here
;; with the `:disable' property:
;(package! builtin-package :disable t)

;; You can override the recipe of a built in package without having to specify
;; all the properties for `:recipe'. These will inherit the rest of its recipe
;; from Doom or MELPA/ELPA/Emacsmirror:
;(package! builtin-package :recipe (:nonrecursive t))
;(package! builtin-package-2 :recipe (:repo "myfork/package"))

;; Specify a `:branch' to install a package from a particular branch or tag.
;; This is required for some packages whose default branch isn't 'master' (which
;; our package manager can't deal with; see radian-software/straight.el#279)
;(package! builtin-package :recipe (:branch "develop"))

;; Use `:pin' to specify a particular commit to install.
;(package! builtin-package :pin "1a2b3c4d5e")

;; Doom's packages are pinned to a specific commit and updated from release to
;; release. The `unpin!' macro allows you to unpin single packages...
;(unpin! pinned-package)
;; ...or multiple packages
;(unpin! pinned-package another-pinned-package)
;; ...Or *all* packages (NOT RECOMMENDED; will likely break things)
;(unpin! t)
#+end_src

#+html:</details>

*** Config.el

#+html:<details><summary>Defines the user's custom configuration.</summary>

**** Enable Lexical Binding

#+begin_src emacs-lisp :tangle config.el
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-
#+end_src

**** User Config

Most of the configuration is done here. Each code block is defined in its relevant section and is tangled here using =noweb= referenced code blocks.

#+begin_src emacs-lisp :tangle "config.el" :noweb tangle
<<config>>
#+end_src

**** Basic Use Instructions

#+begin_src emacs-lisp :tangle no
;; Whenever you reconfigure a package, make sure to wrap your config in an
;; `after!' block, otherwise Doom's defaults may override your settings. E.g.
;;
;;   (after! PACKAGE
;;     (setq x y))
;;
;; The exceptions to this rule:
;;
;;   - Setting file/directory variables (like `org-directory')
;;   - Setting variables which explicitly tell you to set them before their
;;     package is loaded (see 'C-h v VARIABLE' to look up their documentation).
;;   - Setting doom variables (which start with 'doom-' or '+').
;;
;; Here are some additional functions/macros that will help you configure Doom.
;;
;; - `load!' for loading external *.el files relative to this one
;; - `use-package!' for configuring packages
;; - `after!' for running code after a package has loaded
;; - `add-load-path!' for adding directories to the `load-path', relative to
;;   this file. Emacs searches the `load-path' when you load packages with
;;   `require' or `use-package'.
;; - `map!' for binding new keys
#+end_src

#+html:</details>
*** Organization

This file is structured to promote discoverability and comprehension. In general, it follows this scheme:

*Section*
- Variables
- Appearance
- Behavior
- Keybinds
- Etc.

You're currently reading the Doom section. I configure 'global' settings here.

All other sections are dedicated to individul package configuration.

*** Resources

#+html:<details><summary>Other Emacs User Configs</summary>

**** Doom User
- [[https://github.com/tecosaur/emacs-config][Tecosaur]]
- [[https://github.com/zzamboni/dot-doom/blob/master/doom.org][Zzamboni]]
- [[https://github.com/elken/doom][Elken]]
- [[https://github.com/hieutkt/dotfiles/tree/main/emacs/.doom.d][Nguyen Duc Hieu]]
- [[https://github.com/slano-ls/Doom-Emacs-Config][Saihaj Law]]
- [[https://github.com/hlissner/.doom.d/tree/master][Henrik Lissner]]
- [[https://github.com/tefkah/doom-emacs-config][Tefkah]]

**** Emacs User
- [[https://github.com/daviwil/dotfiles/tree/guix-home][David Wilson]]
- [[https://github.com/rougier/dotemacs/tree/master][Nicolas P. Rougier]]
- [[https://github.com/jimeh/.emacs.d][Emacs Siren]]
- [[https://github.com/howardabrams/hamacs][Howard Abrams]]
- [[https://github.com/chrisbarrett/.emacs.d/blob/master/config.org][Chris Barrett]]
- [[https://github.com/novoid/dot-emacs/blob/master/config.org][Novoid]]
- [[https://github.com/ianyepan/.wsl-emacs.d][Ian Y.E. Pan]]

#+html:</details>

** Variables
*** TODO Personal Information

Define an identity for use with GPG, email, and file templates/snippets.

#+begin_src emacs-lisp :tangle no :noweb-ref config
(setq user-full-name "Jake Turner"
      user-mail-address "john@doe.com")
#+end_src

*** Change Literate Config Name

I change my Org literate config file name from =config.org= to =README.org= in =init.el= for displaying it on GitHub.

#+begin_src emacs-lisp :tangle no :noweb-ref early-init
(setq +literate-config-file "~/.config/doom/README.org")
#+end_src

*** Lookup Providers

I don't use most of the default providers (Google) so I set my own.

#+begin_src emacs-lisp :tangle no :noweb-ref config
(setq +lookup-provider-url-alist
      '(("DuckDuckGo" +lookup--online-backend-duckduckgo "https://duckduckgo.com/?q=%s")
        ("Github" "https://github.com/search?ref=simplesearch&q=%s")
        ("Youtube" "https://youtube.com/results?aq=f&oq=&search_query=%s")
        ("Wikipedia" "https://wikipedia.org/search-redirect.php?language=en&go=Go&search=%s")
        ("StackOverflow" "https://stackoverflow.com/search?q=%s")
        ("Doom Issues" "https://github.com/hlissner/doom-emacs/issues?q=is%%3Aissue+%s")
        ("Internet archive" "https://web.archive.org/web/*/%s")
        ("Project Gutenberg" "http://www.gutenberg.org/ebooks/search/?query=%s")
        ("MDN" "https://developer.mozilla.org/en-US/search?q=%s")
        ("Arch Wiki" "https://wiki.archlinux.org/index.php?search=%s&title=Special%3ASearch&wprov=acrw1")
        ("AUR" "https://aur.archlinux.org/packages?O=0&K=%s")))
#+end_src

** Appearance
*** Theme

I typically use the [[https://draculatheme.com/][Dracula]] theme, but I'm experimenting with others:

#+html:<details><summary>Themes I Like</summary>
- Doom One
- Doom Vibrant
- Doom Iosvkem
- Doom Dracula
- Doom Palenight
- Doom Henna
- Doom Ayu-Mirage and Doom Ayu-Dark
- Doom Material Dark
- Doom Molokai
- Doom Monokai
- Doom Old Hope
- Doom Horizon
- Doom 1337
- Doom Material
- Doom Oceanic Next
- Doom Xcode
#+html:</details>

#+begin_src emacs-lisp :tangle no :noweb-ref config
(setq doom-theme 'doom-vibrant)
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref config
;(setq doom-theme 'doom-Iosvkem)
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref config
;(setq doom-theme 'doom-dracula
;      doom-dracula-brighter-modeline t
;      doom-dracula-colorful-headers t)
#+end_src

*** Font

I'm also experimenting with fonts. Although, Jetbrains Mono and Fira Code are staples.

#+begin_src emacs-lisp :tangle no :noweb-ref config
(when IS-MAC
  (setq doom-font (font-spec :family "Jetbrains Mono" :size 12)
        doom-big-font (font-spec :family "Jetbrains Mono" :size 16)
        ;; doom-variable-pitch-font (font-spec :family "Overpass" :size 14)
        ;; doom-unicode-font (font-spec :family "JuliaMono")
        ;; doom-serif-font (font-spec :family "IBM Plex Mono" :size 10 :weight 'light)
        ))
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref config
(when IS-LINUX
  (setq doom-font (font-spec :family "Jetbrains Mono" :size 12)
        doom-big-font (font-spec :family "Jetbrains Mono" :size 16)
        ;;doom-variable-pitch-font (font-spec :family "Overpass" :size 14)
        ;;doom-unicode-font (font-spec :family "JuliaMono")
        ;;doom-serif-font (font-spec :family "IBM Plex Mono" :size 10 :weight 'light)
        ))
#+end_src

*** Cursor

Draw the block cursor as wide as the glyph under it.

#+begin_src emacs-lisp :tangle no :noweb-ref config
(setq-default x-stretch-cursor t)
#+end_src

*** Frames
**** Add Transparency

I add transparency to Doom's window to allow my wallpaper to show through it.

On Linux, this effect probably requires a compositor. I use [[https://github.com/yshui/picom][Picom]].

Currently disabled as I find it somewhat distracting with my tiny little brain. 

#+begin_src emacs-lisp :tangle no :noweb-ref config
;(add-to-list 'default-frame-alist '(alpha . 93)) ; [0-100]
#+end_src

**** Start Maximized

#+begin_src emacs-lisp :tangle no :noweb-ref config
(add-to-list 'default-frame-alist '(fullscreen . maximized))
#+end_src

**** Prevent Frame Resizing Due to Font/Face Changes

#+begin_src emacs-lisp :tangle no :noweb-ref config
(setq frame-inhibit-implied-resize '(font font-backend tab-bar-lines))
#+end_src

*** Line Numbers

I use relative visual line numbers to move around.

#+begin_src emacs-lisp :tangle no :noweb-ref config
(setq display-line-numbers-type 'visual)
#+end_src

Prevent shifting the buffer content whenever the line number count increases in column width.

#+begin_src emacs-lisp :tangle no :noweb-ref config
(setq display-line-numbers-grow-only t)
#+end_src

** Behavior
*** Enable Evil Fine Undo

By default, all changes made while using insert mode are considered one. This setting enables a more granular undo scheme.

#+begin_src emacs-lisp :tangle no :noweb-ref config
(setq evil-want-fine-undo t)
#+end_src

*** Enable Subword Mode

Allows iterating through CamelCase words.

#+begin_src emacs-lisp :tangle no :noweb-ref config
(global-subword-mode 1)
#+end_src

*** Enable Evil Visual Line Movement

Allow lines that wrap around the edge of the screen (visual lines) to count as "physical" lines. Enables you to use =j= and =k= to move up and down through wrapped lines.

First, enable the following in =init.el=:

#+begin_src emacs-lisp :tangle no :noweb-ref early-init
(setq evil-respect-visual-line-mode t)
#+end_src

**** Fix Evil's Visual Line Over/Undershooting

There's a long standing issue between =visual lines= and =Evil=. When using a prefix argument (line count) with Evil's next/previous visual line, often it will over or under shoot the desired line. As far as I have researched, there is no next/previous line commands that just works.

To solve this, I created a function that handles repeating the desired function instead of letting it repeat itself. And then I use it to advise evil's visual line commands. This works perfectly to solve the issue and I always reach my desired line.

#+begin_src emacs-lisp :tangle no :noweb-ref config
(defun noncog/repeat-function-count (fn &optional count)
  "Repeat given function COUNT times."
  (let ((total (or count 1))
        (counter 0))
    (while (< counter total)
      (funcall fn)
      (setq counter (+ counter 1)))))
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref config
(advice-add 'evil-previous-visual-line :around #'noncog/repeat-function-count)
(advice-add 'evil-next-visual-line :around #'noncog/repeat-function-count)
#+end_src

*** Prevent Pasting From Adding to Kill Ring

Whenever you overwrite text in visual mode, prevent adding that text to the kill ring. This enables you to paste the same thing multiple times without losing it.

#+begin_src emacs-lisp :tangle no :noweb-ref config
(setq evil-kill-on-visual-paste nil)
#+end_src

*** Focus New Windows After Splitting

#+begin_src emacs-lisp :tangle no :noweb-ref config
(setq evil-split-window-below t
      evil-vsplit-window-right t)
#+end_src

*** Autoload File Changes

#+begin_src emacs-lisp :tangle no :noweb-ref config
(global-auto-revert-mode 1)
#+end_src

*** Scrolling

This is an area of contention for me. Eventually I would like to overhaul this behavior entirely.

**** Set Scroll Amount

#+begin_src emacs-lisp :tangle no :noweb-ref config
;(setq-default evil-scroll-count 5)
#+end_src

**** Center Scroll Mode

#+begin_src emacs-lisp :tangle no :noweb-ref config
(define-minor-mode prot/scroll-center-cursor-mode
  "Toggle centred cursor scrolling behavior"
  :init-value nil
  :lighter " S="
  :global nil
  (if prot/scroll-center-cursor-mode
      (setq-local scroll-margin (* (frame-height) 2)
                  scroll-conservatively 0
                  maximum-scroll-margin 0.5)
    (dolist (local '(scroll-preserve-screen-position
                     scroll-conservatively
                     maximum-scroll-margin
                     scroll-margin))
      (kill-local-variable `,local))))
#+end_src

*** Window Manager Integration

I love tiling window managers. I currently use [[https://i3wm.org][i3]] on Linux and [[https://github.com/koekeishiya/yabai][Yabai]] on macOS. These configs allow me to seamlessly use some of their windowing controls inside of Emacs.

**** How It Works

This method requires some way for your window manager to pass the keybinds to Emacs whenever it's the focused window. Then, you just bind those keys in Emacs to the windowing functions defined here.

=NOTE=: i3 requires the use of a [[https://github.com/noncog/.dotfiles/blob/main/.config/i3/scripts/i3-emacs-mode.pl][script]] and a dedicated Emacs mode to know when Emacs is the focused window and change use different keybinds. Yabai supports this natively.

**** Functions

When a window can't be found in that direction in Emacs, it passes the window focusing command to the window manager.

#+begin_src emacs-lisp :tangle no :noweb-ref config
(defun wm-focus-on-error (direction move-fn)
    (when IS-LINUX
     (condition-case nil (funcall move-fn)
       (user-error (start-process "wm" nil "i3-msg" "focus" direction))))
     (when IS-MAC
      (condition-case nil (funcall move-fn)
        (user-error (start-process "wm" nil "yabai" "-m" "window" "--focus" direction)))))
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref config
(defun wm-window-left ()
  (interactive)
  (let ((direction (cond (IS-LINUX "left") (IS-MAC "west"))))
    (wm-focus-on-error direction #'windmove-left)))

(defun wm-window-right ()
  (interactive)
  (let ((direction (cond (IS-LINUX "right") (IS-MAC "east"))))
    (wm-focus-on-error direction #'windmove-right)))

(defun wm-window-up ()
  (interactive)
  (let ((direction (cond (IS-LINUX "up") (IS-MAC "north"))))
    (wm-focus-on-error direction #'windmove-up)))

(defun wm-window-down ()
  (interactive)
  (let ((direction (cond (IS-LINUX "down") (IS-MAC "south"))))
    (wm-focus-on-error direction #'windmove-down)))
#+end_src

**** Keybinds
***** macOS

#+begin_src emacs-lisp :tangle no :noweb-ref config
(when IS-MAC
  (map! "s-h" #'wm-window-left
        "s-j" #'wm-window-down
        "s-k" #'wm-window-up
        "s-l" #'wm-window-right
        "s-=" #'balance-windows
        "s-v" #'evil-window-vsplit
        "s-s" #'evil-window-split
        "s-Q" #'evil-quit))
#+end_src

***** Linux

#+begin_src emacs-lisp :tangle no :noweb-ref config
(when IS-LINUX
  (map! "s-h" #'wm-window-left
        "s-j" #'wm-window-down
        "s-k" #'wm-window-up
        "s-l" #'wm-window-right
        ;; TODO: add workspace balancing python script.
        ;; TODO: add window splitting.
        "s-Q" #'evil-quit))
#+end_src

***** Emacs to Other Windows

These binds allow you to use Doom's window switching commands to focus windows outside of Emacs.

#+begin_src emacs-lisp :tangle no :noweb-ref config
(map! :leader "w h" #'wm-window-left)
(map! :leader "w j" #'wm-window-down)
(map! :leader "w k" #'wm-window-up)
(map! :leader "w l" #'wm-window-right)
#+end_src

** Keybinds
*** Mac Modifier Keys

I translate the Mac modifier keys to be equivalent to my Linux/Windows modifiers.

#+begin_src emacs-lisp :tangle no :noweb-ref config
(when IS-MAC (setq mac-command-modifier 'control ; Maps Command -> Control
                    mac-control-modifier 'meta   ; Maps Control -> Alt (Meta)
                    mac-option-modifier 'super)) ; Maps Option -> Super
#+end_src

* Beacon
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
[[https://github.com/Malabarba/beacon][Beacon]] is a minor mode that highlights the current line after jumping around. Never lose your cursor (point) again!
#+end_quote

** Package

#+html:<details><summary>Source</summary>
#+begin_src emacs-lisp :tangle no :noweb-ref packages
(package! beacon
  :recipe (:host github :repo "Malabarba/beacon")
  :pin "85261a928ae0ec3b41e639f05291ffd6bf7c231c")
#+end_src
#+html:</details>

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :tangle no :noweb-ref config :noweb yes
(use-package! beacon
  :config
  <<beacon-config>>
  )
#+end_src
#+html:</details>

** Appearance

#+begin_src emacs-lisp :tangle no :noweb-ref beacon-config :exports none
;; Appearance
#+end_src

*** Color

#+begin_src emacs-lisp :tangle no :noweb-ref beacon-config
(setq beacon-color "#61bfff")
#+end_src

*** Size and Duration

#+begin_src emacs-lisp :tangle no :noweb-ref beacon-config
(setq beacon-size 40
      beacon-blink-duration 0.3
      beacon-blink-delay 0.5)
#+end_src

** Behavior

#+begin_src emacs-lisp :tangle no :noweb-ref beacon-config :exports none
;; Behavior
#+end_src

*** When To Blink

#+begin_src emacs-lisp :tangle no :noweb-ref beacon-config
(setq beacon-blink-when-buffer-changes t
      beacon-blink-when-window-scrolls nil
      beacon-blink-when-point-moves-vertically nil
      beacon-blink-when-focused nil)
#+end_src

*** Enable Beacon

#+begin_src emacs-lisp :tangle no :noweb-ref beacon-config
(beacon-mode 1)
#+end_src

* Which-Key
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
[[https://github.com/justbur/emacs-which-key][Which-Key]] is a minor mode that displays keybinds for your currently unfinished inputs.
#+end_quote

** Package

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :tangle no :noweb-ref config :noweb yes
(use-package! which-key
  :defer t
  :config
  <<which-key-config>>
  )
#+end_src
#+html:</details>

** Behavior

#+begin_src emacs-lisp :tangle no :noweb-ref which-key-config :exports none
;; Behavior
#+end_src

*** Reduce Idle Delay

#+begin_src emacs-lisp :tangle no :noweb-ref which-key-config
(setq which-key-idle-delay 0.5)
#+end_src

*** Use C-h Map

Enable the use of the default which-key-c-h map to get paging keybinds. =Note=: One can use =SPC C-h= to see a searchable list of global leader keybinds and =C-h= in which key

#+begin_src emacs-lisp :tangle no :noweb-ref which-key-config
;(setq which-key-use-C-h-commands t)
#+end_src

** Fixes

#+begin_src emacs-lisp :tangle no :noweb-ref which-key-config :exports none
;; Fixes
#+end_src

*** Ensure Window Height

I was having an issue using =emacsclient= where which-key was being cut off below the modeline. There are two solutions, use whichever works for you:

**** Allow Imprecise Fit

This setting may fix the issue perfectly or cause crashing.

#+begin_src emacs-lisp :tangle no :noweb-ref which-key-config
(setq which-key-allow-imprecise-window-fit nil)
#+end_src

**** Add Lines Below the Keybinds

A simple solution is to add spaces below the keybinds. Realistically, this doesn't work everywhere but it's good enough for now. ([[https://github.com/justbur/emacs-which-key/issues/231#issuecomment-627503184][Source]])

#+begin_src emacs-lisp :tangle no :noweb-ref which-key-config
;; (defun add-which-key-line (f &rest r) (progn (apply f (list (cons (+ 1 (car (car r))) (cdr (car r)))))))
;; (advice-add 'which-key--show-popup :around #'add-which-key-line)
#+end_src

*** Shorten Long Function Prefixes

It's possible to reduce the description length for functions shown by which-key. To do so, enable multiple replacements, then add them for each prefix you want to remove.

**** Enable Multiple Replacements

#+begin_src emacs-lisp :tangle no :noweb-ref which-key-config
(setq which-key-allow-multiple-replacements t)
#+end_src

**** Evil

#+begin_src emacs-lisp :tangle no :noweb-ref which-key-config
(pushnew!
 which-key-replacement-alist
 '(("" . "\\`+?evil[-:]?\\(?:a-\\)?\\(.*\\)") . (nil . " \\1"))
 '(("\\`g s" . "\\`evilem--?motion-\\(.*\\)") . (nil . " \\1")))
#+end_src

**** Org Agenda

#+begin_src emacs-lisp :tangle no :noweb-ref which-key-config
(pushnew!
 which-key-replacement-alist
 '(("" . "\\`org-agenda-\\(.*\\)") . (nil . " \\1")))
#+end_src

**** Treemacs

#+begin_src emacs-lisp :tangle no :noweb-ref which-key-config
(pushnew!
 which-key-replacement-alist
 '(("" . "\\`treemacs-\\(.*\\)") . (nil . " \\1")))
#+end_src

* Avy
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
[[https://github.com/abo-abo/avy][Avy]] is a package for jumping to visible text using a char-based decision tree. Quickly jump to anything you see on your screen!
#+end_quote

** Package

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :tangle no :noweb-ref config :noweb yes
(use-package! avy
  :defer t
  :config
  <<avy-config>>
  )
  #+end_src
#+html:</details>

** Behavior

#+begin_src emacs-lisp :tangle no :noweb-ref avy-config :exports none
;; Behavior
#+end_src

*** Enable Jumping to All Visible Windows

#+begin_src emacs-lisp :tangle no :noweb-ref avy-config :exports none
(setq avy-all-windows t)
#+end_src

* Helpful
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
[[https://github.com/Wilfred/helpful][Helpful]] is an alternative to the built-in Emacs help that provides much more contextual information.
#+end_quote

** Package

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :tangle no :noweb-ref config :noweb yes
(use-package! helpful
  :defer t
  :config
  <<helpful-config>>
  )
#+end_src
#+html:</details>

** Behavior

#+begin_src emacs-lisp :tangle no :noweb-ref helpful-config
;; Behavior
#+end_src

*** Increase Max Window Count

I increase the window count to be able to move back and forth between more help windows using the keybinds that I set.

#+begin_src emacs-lisp :tangle no :noweb-ref helpful-config
(setq helpful-max-buffers 10)
#+end_src

*** Show Documentation At Top Line

By default, Doom centers the page when you visit a source file. Often, I can't see the information behind the helpful window, so I remove the old advice and update it to display at the top of the screen.

#+begin_src emacs-lisp :tangle no :noweb-ref helpful-config
(advice-remove 'helpful--navigate #'+popup--helpful-open-in-origin-window-a)
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref helpful-config
(defadvice! my/+popup--helpful-open-in-origin-window-a (button)
  "Open links in non-popup, originating window rather than helpful's window."
  :override #'helpful--navigate
  (let ((path (substring-no-properties (button-get button 'path)))
        enable-local-variables
        origin)
    (save-popups!
     (find-file path)
     (when-let (pos (get-text-property button 'position
                                       (marker-buffer button)))
       (goto-char pos))
     (setq origin (selected-window))
     (recenter 0)) ; Added argument 0 to cause recenter to top of screen.
    (select-window origin)))
#+end_src

** Keybinds

#+begin_src emacs-lisp :tangle no :noweb-ref helpful-config :exports none
;; Keybinds
#+end_src

*** Cycle Through Visited Help Pages

Doom lacks the ability to move through previously viewed pages in the helpful buffer. So, we can add them using winner mode. These keybinds fit well with the rest and make sense logically. Now, I can move "left" and "right" through history.

#+begin_src emacs-lisp :tangle no :noweb-ref helpful-config
(map! :map helpful-mode-map "C-h" #'winner-undo
      :map helpful-mode-map "C-l" #'winner-redo)
#+end_src

* Doom Modeline
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
[[https://github.com/seagle0128/doom-modeline][Doom-Modeline]] is a fancy and fast mode-line inspired by minimalism design.
#+end_quote

** Package

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :tangle no :noweb-ref config :noweb yes
(use-package! doom-modeline
  :defer t
  :config
  <<doom-modeline-config>>
  )
#+end_src
#+html:</details>

** Appearance

#+begin_src emacs-lisp :tangle no :noweb-ref doom-modeline-config :exports none
;; Appearance
#+end_src

*** Dimensions

#+begin_src emacs-lisp :tangle no :noweb-ref doom-modeline-config
(setq doom-modeline-height 35)
#+end_src

*** Major Mode

#+begin_src emacs-lisp :tangle no :noweb-ref doom-modeline-config
(setq doom-modeline-major-mode-icon (display-graphic-p)
      doom-modeline-major-mode-color-icon (display-graphic-p))
#+end_src

*** Version Control

#+begin_src emacs-lisp :tangle no :noweb-ref doom-modeline-config
(setq doom-modeline-vcs-max-length 60
      auto-revert-check-vc-info t)
#+end_src

*** Persp Mode

#+begin_src emacs-lisp :tangle no :noweb-ref doom-modeline-config
(setq doom-modeline-persp-name t
      doom-modeline-display-default-persp-name t
      doom-modeline-persp-icon t)
#+end_src

* Doom Dashboard
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
Doom-Dashboard adds a customizable dashboard as the default buffer.
#+end_quote

** Package

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :tangle no :noweb-ref config :noweb yes
(use-package! doom-dashboard
  :defer t
  :init
  <<doom-dashboard-init>>
  )
#+end_src
#+html:</details>

** Appearance

#+begin_src emacs-lisp :tangle no :noweb-ref doom-dashboard-init :exports none
;; Appearance
#+end_src

*** Remove Footer

#+begin_src emacs-lisp :tangle no :noweb-ref doom-dashboard-init
(remove-hook '+doom-dashboard-functions #'doom-dashboard-widget-footer)
#+end_src

** Behavior

#+begin_src emacs-lisp :tangle no :noweb-ref doom-dashboard-init :exports none
;; Behavior
#+end_src

*** Default to =$HOME=

Doom typically sets your Dashboard's directory to the latest of the recent file list. It's supposed to be convenient, but the use-case it was designed around rarely happens. Let's remove it.

#+begin_src emacs-lisp :tangle no :noweb-ref doom-dashboard-init
(setq +doom-dashboard-pwd-policy "~")
#+end_src

** Keybinds

#+begin_src emacs-lisp :tangle no :noweb-ref doom-dashboard-init :exports none
;; Keybinds
#+end_src

*** Open the Dashboard

#+begin_src emacs-lisp :tangle no :noweb-ref doom-dashboard-init
(map! :leader :desc "Dashboard" "d" #'+doom-dashboard/open)
#+end_src

* Persp-Mode
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
[[https://github.com/Bad-ptr/persp-mode.el][Persp-Mode]] is used by Doom to manage workspaces across frames.
#+end_quote

** Package

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :tangle no :noweb-ref config :noweb yes
(use-package! persp-mode
  :defer t
  :config
  <<persp-config>>
  )
#+end_src
#+html:</details>

** Fixes

#+begin_src emacs-lisp :tangle no :noweb-ref persp-config :exports none
;; Fixes
#+end_src

*** Prevent New Workspaces in New Frames

By default, when using =emacsclient=, Doom creates a new workspace for each client frame. I don't want this clutter, I'll make a workspace if I need one.

#+begin_src emacs-lisp :tangle no :noweb-ref persp-config
(setq persp-emacsclient-init-frame-behaviour-override nil)
#+end_src

* Vertico
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
[[https://github.com/minad/vertico][Vertico]] provides a performant and compatible vertical completion UI for Emacs. It's mostly used for completions in the minibuffer.
#+end_quote

** Package

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :tangle no :noweb-ref config :noweb yes
(use-package! vertico
  :defer t
  :config
  <<vertico-config>>
  )
#+end_src
#+html:</details>

** Behavior

#+begin_src emacs-lisp :tangle no :noweb-ref vertico-config :exports none
;; Behavior
#+end_src

*** Sorting Order

I like to sort by history first and then alphabetically.

#+begin_src emacs-lisp :tangle no :noweb-ref vertico-config
(setq vertico-sort-function #'vertico-sort-history-alpha)
#+end_src

** Keybinds

#+begin_src emacs-lisp :tangle no :noweb-ref vertico-config :exports none
;; Keybinds
#+end_src

*** Add Scrolling Keybinds to Minibuffer

Luckily Doom doesn't use these yet and they can just be added.

#+begin_src emacs-lisp :tangle no :noweb-ref vertico-config
(map! :map vertico-map "C-u" #'scroll-down-command
      :map vertico-map "C-d" #'scroll-up-command)
#+end_src

* Marginalia
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
[[https://github.com/minad/marginalia][Marginalia]] adds marks or annotations (marginalia) to the margin of the minibuffer for your completion candidates.
#+end_quote

** Package

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :tangle no :noweb-ref config :noweb yes
(use-package! marginalia
  :defer t
  :config
  <<marginalia-config>>
  )
#+end_src
#+html:</details>

** Appearance

#+begin_src emacs-lisp :tangle no :noweb-ref marginalia-config :exports none
;; Appearance
#+end_src

*** Add Colors and Modify File Marginalia

This adds the following:
- Color to indicate file size.
- Replace recent files' date string with last used time.
- Colored file attributes.
- Removes user group info.

([[https://github.com/tecosaur/emacs-config/blob/master/config.org#marginalia][Source]])

#+begin_src emacs-lisp :tangle no :noweb-ref marginalia-config
(defadvice! +marginalia--anotate-local-file-colorful (cand)
  "Just a more colourful version of `marginalia--anotate-local-file'."
  :override #'marginalia--annotate-local-file
  (when-let (attrs (file-attributes (substitute-in-file-name
                                     (marginalia--full-candidate cand))
                                    'integer))
    (marginalia--fields
     ((marginalia--file-owner attrs)
      :width 12 :face 'marginalia-file-owner)
     ((marginalia--file-modes attrs))
     ((+marginalia-file-size-colorful (file-attribute-size attrs))
      :width 7)
     ((+marginalia--time-colorful (file-attribute-modification-time attrs))
      :width 12))))
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref marginalia-config
(defun +marginalia--time-colorful (time)
  (let* ((seconds (float-time (time-subtract (current-time) time)))
         (color (doom-blend
                 (face-attribute 'marginalia-date :foreground nil t)
                 (face-attribute 'marginalia-documentation :foreground nil t)
                 (/ 1.0 (log (+ 3 (/ (+ 1 seconds) 345600.0)))))))
    ;; 1 - log(3 + 1/(days + 1)) % grey
    (propertize (marginalia--time time) 'face (list :foreground color))))
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref marginalia-config
(defun +marginalia-file-size-colorful (size)
  (let* ((size-index (/ (log10 (+ 1 size)) 7.0))
         (color (if (< size-index 10000000) ; 10m
                    (doom-blend 'orange 'green size-index)
                  (doom-blend 'red 'orange (- size-index 1)))))
    (propertize (file-size-human-readable size) 'face (list :foreground color))))
#+end_src

* Company
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
[[http://company-mode.github.io][Company]] (complete anything) is a text completion framework for Emacs. It uses frontends and backends to retrieve and display completion candidates. It's mostly used for in-buffer completions.
#+end_quote

** Package

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :tangle no :noweb-ref config :noweb yes
(use-package! company
  :defer t
  :config
  <<company-config>>
  )
#+end_src
#+html:</details>

** Behavior

#+begin_src emacs-lisp :tangle no :noweb-ref company-config :exports none
;; Behavior
#+end_src

*** General

#+begin_src emacs-lisp :tangle no :noweb-ref company-config
(setq company-idle-delay 0.3
      company-tooltip-limit 10
      company-minimum-prefix-length 1)
#+end_src

*** Org-mode Backend

#+begin_src emacs-lisp :tangle no :noweb-ref company-config
(set-company-backend! 'org-mode
  '(company-capf company-files :with company-yasnippet))
#+end_src

*** Sh-mode Backend

#+begin_src emacs-lisp :tangle no :noweb-ref company-config
(set-company-backend! 'sh-mode
  '(company-shell company-files :with company-yasnippet))
#+end_src

* Yasnippet
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
[[https://github.com/joaotavora/yasnippet][Yasnippet]] is a template system for Emacs. It allows you to type an abbreviation and automatically expand it.
#+end_quote

** Package

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :tangle no :noweb-ref config :noweb yes
(use-package! yasnippet
  :defer t
  :config
  <<yasnippet-config>>
  )
#+end_src
#+html:</details>

** Resources
- [[https://joaotavora.github.io/yasnippet/index.html][Yasnippet Documentation]]
- [[https://github.com/doomemacs/snippets][Doom Snippets]]

** Behavior

#+begin_src emacs-lisp :tangle no :noweb-ref yasnippet-config :exports none
;; Behavior
#+end_src

*** Enable Nested Snippets

#+begin_src emacs-lisp :tangle no :noweb-ref yasnippet-config
(setq yas-triggers-in-field t)
#+end_src

* Projectile
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
[[https://github.com/bbatsov/projectile][Projectile]] is a project interaction library for Emacs. It provides easy project management and navigation.
#+end_quote

** Package

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :tangle no :noweb-ref config :noweb yes
(use-package! projectile
  :defer t
  :init
  <<projectile-init>>
  :config
  <<projectile-config>>
  )
#+end_src
#+html:</details>

** Variables

#+begin_src emacs-lisp :tangle no :noweb-ref projectile-config :exports none
;; Variables
#+end_src

*** Projects Directory

I use the same convention for project location on each OS that I use.

#+begin_src emacs-lisp :tangle no :noweb-ref projectile-config
(setq projectile-project-search-path '("~/Projects"))
#+end_src

** Behavior

#+begin_src emacs-lisp :tangle no :noweb-ref projectile-config :exports none
;; Behavior
#+end_src

*** Disable Automatic Project Discovery

I've had a long-standing issue where Projectile won't obey my ignored directories, so I disable auto discovery. To update the project list, the project must be in =projectile-project-search-path= and then you manually run =projectile-discover-projects-in-search-path= or for projects not in that variable you can run =projectile-discover-projects-in-directory=.

#+begin_src emacs-lisp :tangle no :noweb-ref projectile-config
(setq projectile-auto-discover nil
      projectile-track-known-projects-automatically nil)
#+end_src

** Keybinds

#+begin_src emacs-lisp :tangle no :noweb-ref projectile-init :exports none
;; Keybinds
#+end_src

*** List Uncommitted Projects

I add a keybind to quickly view which projects have uncommitted changes.

#+begin_src emacs-lisp :tangle no :noweb-ref projectile-init
(map! :map project-prefix-map
      :leader
      :desc "List dirty projects"
      "p l" #'projectile-browse-dirty-projects)
#+end_src

* Treemacs
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
[[https://github.com/Alexander-Miller/treemacs][Treemacs]] is a file and project explorer in a tree sidebar similar to Neotree and Nerdtree for Vim.
#+end_quote

** Package

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :tangle no :noweb-ref config :noweb yes
(use-package! treemacs
  :defer t
  :config
  <<treemacs-config>>
  )
#+end_src
#+html:</details>

** Appearance

#+begin_src emacs-lisp :tangle no :noweb-ref treemacs-config :exports none
;; Appearance
#+end_src

*** Enable Doom Themes Colors

#+begin_src emacs-lisp :tangle no :noweb-ref treemacs-config
(setq doom-themes-treemacs-theme "doom-colors")
#+end_src

** Behavior

#+begin_src emacs-lisp :tangle no :noweb-ref treemacs-config :exports none
;; Behavior
#+end_src

*** Enable Follow Mode

Enable Treemacs to sync itself to the releveant file you're in.

#+begin_src emacs-lisp :tangle no :noweb-ref treemacs-config
(treemacs-follow-mode 1)
#+end_src

*** Fold Projects When Leaving

In workspaces with multiple projects, fold the previous project upon switching to a new one.

#+begin_src emacs-lisp :tangle no :noweb-ref treemacs-config
(setq treemacs-project-follow-cleanup t)
#+end_src

* Magit
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
[[https://magit.vc][Magit]] is a powerful Git interface for Emacs. "It fills the glaring gap between the Git command-line interface and various GUIs, letting you perform trivial as well as elaborate version control tasks with just a couple of mnemonic key presses."
#+end_quote

** Package

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :tangle no :noweb-ref config :noweb yes
(use-package! magit
  :defer t
  :config
  <<magit-config>>
  )
#+end_src
#+html:</details>

** Behavior

#+begin_src emacs-lisp :tangle no :noweb-ref magit-config :exports none
;; Behavior
#+end_src

*** Define Repositories Directory

Defining this directory enables =magit-status= to search for a repository when not inside of one already. It also enables =magit-list-repositories= through the keybind =SPC g l r=.

#+begin_src emacs-lisp :tangle no :noweb-ref magit-config
(setq magit-repository-directories
      '(("~/Projects" . 1)))
#+end_src

*** Dotfiles Git Bare Repository Support

Out of the box Magit doesn't support =--bare= repositories, which are commonly used to manage dotfiles. I've extended an old method of loading the corresponding Git environment variables when relevant directories are open. It simply gets a list of all your dotfiles from the repository and whenever you're in their releveant directory it modifies the Magit/Git environment variable to support the bare repository whenever you need it.

This method works everywhere and seamlessly integrates managing my dotfiles into Magit. It could easily be extended to support multiple bare repositories as well.

#+begin_src emacs-lisp :tangle no :noweb-ref magit-config
(defun my/magit-process-environment (env)
  "Detect and set git -bare repo env vars when in tracked dotfile directories."
  (let* ((default (file-name-as-directory (expand-file-name default-directory)))
         (git-dir (expand-file-name "~/.dotfiles/"))
         (work-tree (expand-file-name "~/"))
         (dotfile-dirs
          (-map (apply-partially 'concat work-tree)
                (-uniq (-keep #'file-name-directory (split-string (shell-command-to-string
                (format "/usr/bin/git --git-dir=%s --work-tree=%s ls-tree --full-tree --name-only -r HEAD"
                        git-dir work-tree))))))))
    (push work-tree dotfile-dirs)
    (when (member default dotfile-dirs)
      (push (format "GIT_WORK_TREE=%s" work-tree) env)
      (push (format "GIT_DIR=%s" git-dir) env)))
  env)
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref magit-config
(advice-add 'magit-process-environment
            :filter-return #'my/magit-process-environment)
#+end_src

*** Commit Linter

I've developed a custom Git commit linter based on [[https://github.com/angular/angular/blob/main/CONTRIBUTING.md#-commit-message-format][Angular]] and [[https://www.conventionalcommits.org/][Conventional Commits]]. The code is based on this [[https://www.adventuresinwhy.com/post/commit-message-linting/][this]] post but highly modified to conform to my chosen conventions.

**** Define Convention Checks

This option parallels =git-commit-style-convention-checks= from Magit. This is a custom list of checks that allows the user to specify which will be performed by our checker. It's currently set to check all of my conventions.

#+begin_src emacs-lisp :tangle no :noweb-ref magit-config
(defcustom my-git-commit-style-convention-checks '(summary-has-type
                                                   summary-type-lowercase
                                                   summary-has-separator
                                                   summary-scope-lowercase
                                                   summary-title-starts-with-lowercase
                                                   summary-title-uses-imperative-verb
                                                   summary-title-not-end-in-punctuation)
  "List of checks performed by `my-git-commit-check-style-conventions'.
Valid members are `summary-has-type',  `summary-type-lowercase',
`summary-has-separator', `summary-scope-lowercase',
`summary-title-starts-with-lowercase', `summary-title-uses-imperative-verb', and
`summary-title-not-end-in-punctuation'.
That function is a member of `git-commit-finish-query-functions'."
  :options '(summary-has-type
             summarty-type-lowercase
             summary-has-separator
             summary-scope-lowercase
             summary-title-starts-with-lowercase
             summary-title-uses-imperative-verb
             summary-title-not-end-in-punctuation)
  :type '(list :convert-widget custom-hook-convert-widget)
  :group 'git-commit)
#+end_src

**** Define Convention Checker

This function parallels =git-commit-check-style-conventions= from Magit. It checks each convention present in the list defined above.

#+begin_src emacs-lisp :tangle no :noweb-ref magit-config
(defun my-git-commit-check-style-conventions (&optional force) ; TODO check using force
  "Check for violations of certain basic style conventions.

For each violation ask the user if she wants to proceed anyway.
Option `my-git-commit-check-style-conventions' controls which
conventions are checked."
  (save-excursion
    (goto-char (point-min))
    (re-search-forward (git-commit-summary-regexp) nil t)
    (let* ((summary (match-string 1))
           (commit-type (substring summary 0 (string-match-p "[()!:]" summary)))
           (commit-separator-check (string-match-p "^.*[^[:blank:]]:" summary))
           (commit-separator-location (string-match-p ":" summary))
           (commit-scope (if (string-match-p "(.*)[!:]" summary) (substring summary (1+ (string-match-p "(" summary)) (string-match-p ")!?:?" summary)) nil))
           (commit-title (if commit-separator-check (substring summary (+ commit-separator-location 2)) "undetectable-title"))
           (lowercase-title-first-word (downcase (substring commit-title 0 (string-match-p "[[:blank:]]" commit-title)))))
      (and (or (not (memq 'summary-type-lowercase my-git-commit-style-convention-checks))
               (let ((case-fold-search nil)) (string-match-p "^[[:lower:]]*$" commit-type))
               (y-or-n-p "Commit type is not lowercase. Commit anyway?"))
           (or (not (memq 'summary-has-type my-git-commit-style-convention-checks))
               (car (member commit-type (get-commit-types)))
               (when (y-or-n-p "Commit type is invalid. Commit anyway?")
                 (when (y-or-n-p (format "Add `%s' to list of commit types?" commit-type))
                   (with-temp-buffer
                     (insert commit-type)
                     (insert "\n")
                     (write-region (point-min) (point-max) commit-types-file t))) t))
           (or (not (memq 'summary-has-separator my-git-commit-style-convention-checks))
               (not (null commit-separator-check))
               (y-or-n-p "Commit title has invalid separator. Commit anyway?"))
           (or (not (memq 'summary-scope-lowercase my-git-commit-style-convention-checks))
               (when (or (not commit-scope) (string-empty-p commit-scope)) (y-or-n-p "Commit scope is empty. Commit anyway?"))
               (when commit-scope (if (let ((case-fold-search nil)) (string-match-p "^[[:lower:]]*$" commit-scope)) t
                                    (y-or-n-p "Commit scope invalid. Only lowercase letters allowed. Commit anyway?"))))
           (or (not (memq 'summary-title-starts-with-lowercase my-git-commit-style-convention-checks))
               (if (not commit-separator-check) (y-or-n-p "Title undetectable. Commit anyway?") (let ((case-fold-search nil))
                 (string-match-p "^[[:lower:]]" commit-title)))
               (y-or-n-p "Commit title does not start with lowercase letter. Commit anyway?"))
           (or (not (memq 'summary-title-uses-imperative-verb my-git-commit-style-convention-checks))
               (if (not commit-separator-check) (y-or-n-p "Imperative verb undetectable. Commit anyway?")
                 (car (member lowercase-title-first-word (get-imperative-verbs))))
               (when (y-or-n-p "Commit title should use imperative verb. Does it?")
                 (when (y-or-n-p (format "Add `%s' to list of commit types?" lowercase-title-first-word))
                   (with-temp-buffer
                     (insert lowercase-title-first-word)
                     (insert "\n")
                     (write-region (point-min) (point-max) imperative-verbs-file t))) t))
           (or (not (memq 'summary-title-not-end-in-punctuation my-git-commit-style-convention-checks))
              (not (string-match-p "[\\.!\\?;,:]$" commit-title))
              (y-or-n-p "Commit title ends with punctuation. Commit anyway?"))))))
#+end_src

**** Commit Types File Loader

To check for compliance with my conventions, two lists must be kept to compare words in the commit summary message against. Those are: the commit types and imperative verbs lists.

#+begin_src emacs-lisp :tangle no :noweb-ref magit-config
(defvar commit-types-file "~/.config/git/commit/commit-types"
  "A list of commit types to be checked by: TODO: link functions.")
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref magit-config
(defun get-commit-types ()
  "Return a list of commit types."
  (let ((file-path commit-types-file))
    (with-temp-buffer
      (insert-file-contents file-path)
      (split-string (buffer-string) "\n" t))))
#+end_src

**** Imperative Verbs File Loader

#+begin_src emacs-lisp :tangle no :noweb-ref magit-config
(defvar imperative-verbs-file "~/.config/git/commit/imperative-verbs"
  "A list of imperative verbs used in git commits to be checked by: TODO: link functions.")
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref magit-config
(defun get-imperative-verbs ()
  "Return a list of imperative verbs."
  (let ((file-path imperative-verbs-file))
    (with-temp-buffer
      (insert-file-contents file-path)
      (split-string (buffer-string) "\n" t))))
#+end_src

**** Commit Template

I add the following template to my Git commit message to remind me of my commits standard. This is not meant to be exhaustive, only a detailed reminder.

#+begin_example

#------------------------------------------------------------------------
# Subject line: type(scope): description
#------------------------------------------------------------------------
# Types: Required noun describing commit type.
#
#    build - Changes build system or external dependencies.
#    chore - Changes external user won't see. (configs/internal task)
#       ci - Changes CI configuration files or scripts.
#     docs - Changes documentation only.
#     feat - A new feature.
#      fix - A bug fix.
#     perf - Change that improves performance.
# refactor - Change that neither fixes a bug nor adds a feature.
#   revert - Change that corrects a commit.
#    style - Changes don't affect meaning. (white-space, format, etc.)
#     test - Adds test or corrects existing test.
#
#------------------------------------------------------------------------
# Scope:       Optional noun describing relevant section of codebase.
#              Must be inside parenthesis if used.
#------------------------------------------------------------------------
# Description: Required short summary of the changes.
#              Must follow a colon after type or scope.
#              No ending punctuation.
#------------------------------------------------------------------------
# Body:        Optional longer description providing additional context.
#              Must begin one blank line after subject/title.
#              Free-form, may consist of newlines and paragraphs.
#------------------------------------------------------------------------
# Footer:      Optional git trailer.
#              Must begin one blank line after body paragraph.
#              Tokens must use '-' in place of white-space.
#              May contain spaces and newlines.
#
# References:  Links information/issues/commits/PRs.
#              Closed issues should be listed on separate line.
#
# BREAKING CHANGE: Must be indicated in title or footer.
#                  If title: Indicate using ! before colon. (!:)
#                            Must use body to describe.
#                  If footer: Must be uppercase text.
#                             Must have a colon and spaced description.
#                             Description should be lowercase.
#------------------------------------------------------------------------
#+end_example

And I enable it in my Git config using this.

#+begin_example
[commit]
    template = ~/.config/git/commit-message
#+end_example

**** Set Max Lengths

These are commonly enforced commit message length standards and the last of my standard's requirements.

#+begin_src emacs-lisp :tangle no :noweb-ref magit-config
(setq git-commit-summary-max-length 50) ; Maximum title (summary) length.
(setq git-commit-fill-column 72)        ; Description column limit.
#+end_src

**** Hook Commit Linter

And finally, the custom standards checker is hooked into Magit's finish commit function.

#+begin_src emacs-lisp :tangle no :noweb-ref magit-config
(add-hook 'after-save-hook 'magit-after-save-refresh-status t)
(add-to-list 'git-commit-finish-query-functions
             #'my-git-commit-check-style-conventions)
#+end_src

* Vterm
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
[[https://github.com/akermu/emacs-libvterm][Vterm]] is the most capable Emacs terminal emulator with unrivaled performance and compatibility.
#+end_quote

** Package

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :tangle no :noweb-ref config :noweb yes
(use-package! vterm
  :defer t
  :config
  <<vterm-config>>
  )
#+end_src
#+html:</details>

** Keybinds

#+begin_src emacs-lisp :tangle no :noweb-ref vterm-config :exports none
;; Keybinds
#+end_src

*** Fix =C-backspace=

I love this keybind, more things should use it. Including vterm... ([[https://github.com/elken/doom#fix-c-backspace][Source]])

#+begin_src emacs-lisp :tangle no :noweb-ref vterm-config
(define-key vterm-mode-map (kbd "<C-backspace>") (lambda () (interactive) (vterm-send-key (kbd "C-w"))))
#+end_src

* Visual Fill Column
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
[[https://codeberg.org/joostkremers/visual-fill-column][Visual-Fill-Column]] is an Emacs minor mode that enables word wrapping at a column and centering the buffer content.
#+end_quote

I use this package to center buffers, you can load it in Doom by enabling the =wordwrap= module.

** Package

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :tangle no :noweb-ref config :noweb yes
(use-package! visual-fill-column
  :custom
  (visual-fill-column-width 120)
  (visual-fill-column-center-text t)
  :hook (org-mode . visual-fill-column-mode)
  :config
  (advice-add #'text-scale-adjust :after #'visual-fill-column-adjust)
  )
#+end_src
#+html:</details>

* Org
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
[[https://orgmode.org/][Org Mode]] describes itself as, "a GNU Emacs major mode for keeping notes, authoring documents, computational notebooks, literate programming, maintaining to-do lists, planning projects, and more — in a fast and effective plain text system."
#+end_quote

** Package

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :tangle no :noweb-ref config :noweb yes
(use-package! org
  :defer t
  :init
  <<org-init>>
  :config
  <<org-config>>
  )
#+end_src
#+html:</details>

** Variables

#+begin_src emacs-lisp :tangle no :noweb-ref org-init :exports none
;; Variables
#+end_src

*** Org Directory

#+begin_src emacs-lisp :tangle no :noweb-ref org-init
(setq org-directory "~/Documents/org/")
#+end_src

*** Keywords

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(setq org-todo-keywords
      '((sequence
         "TODO(t!)"     ; Task that needs doing & is ready to do.
         "NEXT(N!)"     ; Task that needs doing & is ready to do.
         "WAIT(w@/!)"   ; Something is holding this up.
         "|"
         "DONE(d!)"     ; Task successfully completed.
         "KILL(k@/!)")  ; Task cancelled or not applicable.
        (type
         "NOTE(n!)"     ; A fleeting note, in person, idea, or link.
         "LINK(l!)"     ; A link I want to note.
         "APPT(a!)"     ; An appointment.
         "|"))
      org-todo-keyword-faces
      '(("PROJ" . +org-todo-project)
        ("NEXT" . +org-todo-active)
        ("WAIT" . +org-todo-onhold)
        ("NOTE" . +org-todo-active)
        ("KILL" . +org-todo-cancel)))
#+end_src

** Appearance

#+begin_src emacs-lisp :tangle no :noweb-ref org-config :exports none
;; Appearance
#+end_src

*** General

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(setq org-hide-emphasis-markers t            ; Hide syntax for emphasis. (Use org-appear)
      org-pretty-entities t                  ; Show sub/superscript as UTF8.
      org-src-preserve-indentation t)        ; Don't change whitespace in source blocks.
#+end_src

*** Headings

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(setq org-ellipsis " ▾ "                     ; Use a custom ellipsis for folded headings.
      org-hide-leading-stars t               ; Remove excess heading stars.
      org-hidden-keywords nil)               ; Can use to hide certain keywords.
#+end_src

*** Images

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(setq org-image-actual-width '(0.9)          ; Use an in-buffer width closer to export's
      org-startup-with-inline-images t)      ; Show images at startup.
#+end_src

*** LaTeX

**** Previews

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(setq org-startup-with-latex-preview nil)    ; Show rendered LaTeX in the buffers.
#+end_src

**** Syntax Highlighting

Add syntax highlighting to LaTeX in orgmode buffers. ([[https://github.com/tecosaur/emacs-config/blob/master/config.org#prettier-highlighting][Source]])

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(setq org-highlight-latex-and-related '(native script entities))
#+end_src

Unfortunately, when using =native= highlighting the =org-block= face is used as the background color. Remove it using:

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(require 'org-src)
(add-to-list 'org-src-block-faces '("latex" (:inherit default :extend t)))
#+end_src

** Behavior

#+begin_src emacs-lisp :tangle no :noweb-ref org-config :exports none
;; Behavior
#+end_src

*** General

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(setq org-imenu-depth 10                     ; Allow imenu to search deeply in org docs.
      org-use-property-inheritance t         ; Sub-headings inherit parent properties.
      org-insert-heading-respect-content nil ; Insert heading here, not at end of list.
      org-use-fast-todo-selection 'auto)     ; Method to select TODO heading keywords.
#+end_src

*** Logging

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(setq org-log-done 'time                     ; Add completion time to DONE items.
      org-log-into-drawer t                  ; Log times into a drawer to hide them.
      org-log-states-order-reversed nil)     ; Log state changes chronologically.
#+end_src

*** Lists

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(setq org-list-allow-alphabetical t)         ; Enable use of alphabet as list bullets.
#+end_src

*** Links

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(setq org-return-follows-link t)             ; Pressing enter opens links.
#+end_src

*** Habits

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(add-to-list 'org-modules 'org-habit t)      ; Enable repeated task tracking/graphing!
#+end_src

*** Calendar

Enable Evil bindings in org's calendar.

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(setq evil-collection-calendar-want-org-bindings t)
#+end_src

* Org Agenda
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
Org Agenda collects, creates, and displays an overview of actionable tasks your org files.
#+end_quote

** Package

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :tangle no :noweb-ref config :noweb yes
(use-package! org-agenda
  :defer t
  :init
  <<org-agenda-init>>
  :config
  <<org-agenda-config>>
  )
#+end_src
#+html:</details>

** Appearance

#+begin_src emacs-lisp :tangle no :noweb-ref org-agenda-config :exports none
;; Appearance
#+end_src

*** Habits

#+begin_src emacs-lisp :tangle no :noweb-ref org-agenda-config
(setq org-habit-show-habits-only-for-today t ; Only show habits in one section.
      org-habit-show-all-today t)            ; Keep habits visible even if done.
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref org-agenda-config
;(setq +org-habit-min-width)
;(setq +org-habit-graph-padding)
;(setq +org-habit-graph-window-ratio)
;(setq org-habit-graph-column)
;(setq org-habit-today-glyph)
;(setq org-habit-completed-glyph)
;(setq org-habit-show-done-always-green)
#+end_src

*** Section Title Face

Make agenda section titles slightly more bold.

#+begin_src emacs-lisp :tangle no :noweb-ref org-agenda-config
(custom-set-faces!
  '(org-agenda-structure
    :height 1.3 :weight bold))
#+end_src

*** Remove Empty Agenda Sections

If one of my agenda blocks has no information, I don't want to see it.

#+begin_src emacs-lisp :tangle no :noweb-ref org-agenda-config
(defun noncog/agenda-remove-empty ()
  "A simple function to remove empty agenda sections. Scans for blank lines.
Blank sections defined by having two consecutive blank lines.
Not compatible with the block separator."
  (interactive)
  (setq buffer-read-only nil)
  ;; initializes variables and scans first line.
  (goto-char (point-min))
  (let* ((agenda-blank-line "[[:blank:]]*$")
         (content-line-count (if (looking-at-p agenda-blank-line) 0 1))
         (content-blank-line-count (if (looking-at-p agenda-blank-line) 1 0))
         (start-pos (point)))
    ;; step until the end of the buffer
    (while (not (eobp))
      (forward-line 1)
       (cond
        ;; delete region if previously found two blank lines
        ((when (> content-blank-line-count 1)
          (delete-region start-pos (point))
          (setq content-blank-line-count 0)
          (setq start-pos (point))))
        ;; if found a non-blank line
        ((not (looking-at-p agenda-blank-line))
         (setq content-line-count (1+ content-line-count))
         (setq start-pos (point))
         (setq content-blank-line-count 0))
        ;; if found a blank line
        ((looking-at-p agenda-blank-line)
         (setq content-blank-line-count (1+ content-blank-line-count)))))
    ;; final blank line check at end of file
    (when (> content-blank-line-count 1)
      (delete-region start-pos (point))
      (setq content-blank-line-count 0)))
  ;; return to top and finish
  (goto-char (point-min))
  (setq buffer-read-only t))
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref org-agenda-init
(add-hook! 'org-agenda-finalize-hook #'noncog/agenda-remove-empty)
#+end_src

*** Tags Column

#+begin_src emacs-lisp :tangle no :noweb-ref org-agenda-config
(setq noncog/agenda-width 70)
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref org-agenda-config
(setq org-agenda-tags-column (+ 10 (* -1 noncog/agenda-width)))
#+end_src

*** My Custom Agenda

#+begin_src emacs-lisp :tangle no :noweb-ref org-agenda-config
(setq org-agenda-custom-commands
      '(
        ("o" "My Agenda" (
         (agenda
          ""
          ( ;; Today
           ;(org-agenda-overriding-header "Today\n")
           (org-agenda-overriding-header " Agenda\n")
           (org-agenda-day-face-function (lambda (date) 'org-agenda-date))
           (org-agenda-block-separator nil)
           (org-agenda-format-date " %a, %b %-e %y")  ; american date format
           (org-agenda-start-on-weekday nil)          ; start today
           (org-agenda-start-day nil)                 ; don't show previous days
           (org-agenda-span 1)                        ; only show today
           (org-scheduled-past-days 0)                ; don't show overdue
           (org-deadline-warning-days 0)              ; don't show deadlines for the future
           (org-agenda-time-leading-zero t)           ; unify times formatting
           (org-agenda-remove-tags t)
           (org-agenda-time-grid '((today remove-match) (800 1000 1200 1400 1600 1800 2000 2200) "" ""))
           ;(org-agenda-todo-keyword-format "%-4s")
           (org-agenda-prefix-format '((agenda . " %8:c %-5t ")))
           (org-agenda-dim-blocked-tasks nil)
           (org-agenda-skip-function '(noncog/skip-tag "inbox"))
           (org-agenda-entry-types '(:timestamp :deadline :scheduled))
           ))
         (agenda
          ""
          ( ;; Next Three Days
           ;(org-agenda-overriding-header "\nNext Three Days\n")
           (org-agenda-overriding-header "")
           (org-agenda-day-face-function (lambda (date) 'org-agenda-date))
           (org-agenda-block-separator nil)
           (org-agenda-format-date " %a %b %-e")
           (org-agenda-start-on-weekday nil)
           (org-agenda-start-day "+1d")
           (org-agenda-span 3)
           (org-scheduled-past-days 0)
           (org-deadline-warning-days 0)
           (org-agenda-time-leading-zero t)
           (org-agenda-skip-function '(or (noncog/skip-tag "inbox") (org-agenda-skip-entry-if 'todo '("DONE" "KILL"))))
           (org-agenda-entry-types '(:deadline :scheduled))
           (org-agenda-time-grid '((daily weekly) () "" ""))
           (org-agenda-prefix-format '((agenda . "  %?-9:c%t ")))
           ;(org-agenda-todo-keyword-format "%-4s")
           (org-agenda-dim-blocked-tasks nil)
           ))
         (agenda
          ""
          ( ;; Upcoming Deadlines
           (org-agenda-overriding-header "\n Coming Up\n")
           (org-agenda-day-face-function (lambda (date) 'org-agenda-date))
           (org-agenda-block-separator nil)
           (org-agenda-format-date " %a %b %-e")
           (org-agenda-start-on-weekday nil)
           (org-agenda-start-day "+4d")
           (org-agenda-span 14)
           (org-scheduled-past-days 0)
           (org-deadline-warning-days 0)
           (org-agenda-time-leading-zero t)
           (org-agenda-time-grid nil)
           (org-agenda-prefix-format '((agenda . "  %?-5t %?-9:c")))
           ;(org-agenda-todo-keyword-format "%-4s")
           (org-agenda-skip-function '(or (noncog/skip-tag "inbox") (org-agenda-skip-entry-if 'todo '("DONE" "KILL"))))
           (org-agenda-entry-types '(:deadline :scheduled))
           (org-agenda-show-all-dates nil)
           (org-agenda-dim-blocked-tasks nil)
           ))
         (agenda
          ""
          ( ;; Past Due
           (org-agenda-overriding-header "\n Past Due\n")
           (org-agenda-day-face-function (lambda (date) 'org-agenda-date))
           (org-agenda-block-separator nil)
           (org-agenda-format-date "%a %b %-e")
           (org-agenda-start-on-weekday nil)
           (org-agenda-start-day "-60d")
           (org-agenda-span 60)
           (org-scheduled-past-days 60)
           (org-deadline-past-days 60)
           (org-deadline-warning-days 0)
           (org-agenda-time-leading-zero t)
           (org-agenda-time-grid nil)
           (org-agenda-prefix-format '((agenda . "  %?-9:c%t ")))
           ;(org-agenda-todo-keyword-format "%-4s")
           (org-agenda-skip-function '(or (noncog/skip-tag "inbox") (org-agenda-skip-entry-if 'todo '("DONE" "KILL"))))
           (org-agenda-entry-types '(:deadline :scheduled))
           (org-agenda-show-all-dates nil)
           (org-agenda-dim-blocked-tasks nil)
           ))
         (todo
          ""
          ( ;; Important Tasks No Date
           (org-agenda-overriding-header "\n Important Tasks - No Date\n")
           (org-agenda-block-separator nil)
           (org-agenda-skip-function '(org-agenda-skip-entry-if 'timestamp 'notregexp "\\[\\#A\\]"))
           (org-agenda-block-separator nil)
           (org-agenda-time-grid nil)
           (org-agenda-prefix-format '((todo . "  %?:c ")))
           ;(org-agenda-todo-keyword-format "%-4s")
           (org-agenda-dim-blocked-tasks nil)
           ))
         (todo
          ""
          ( ;; Next
           (org-agenda-overriding-header "\n Next\n")
           (org-agenda-block-separator nil)
           (org-agenda-skip-function '(org-agenda-skip-entry-if 'nottodo '("NEXT" "STRT")))
           (org-agenda-block-separator nil)
           (org-agenda-time-grid nil)
           (org-agenda-prefix-format '((todo . "  %?:c ")))
           ;(org-agenda-todo-keyword-format "%-4s")
           (org-agenda-dim-blocked-tasks nil)
           ))
         (tags-todo
          "inbox"
          ( ;; Inbox
           (org-agenda-overriding-header (propertize "\n Inbox\n" 'help-echo "Effort: 'c e' Refile: 'SPC m r'")) ; Ads mouse hover tooltip.
           ;(org-agenda-remove-tags t)
           (org-agenda-block-separator nil)
           (org-agenda-prefix-format "  %?-4e ")
           ;(org-agenda-todo-keyword-format "%-4s")
           ))
         ))))
#+end_src

*** Agenda Popup Window

I use Doom's popup window rules to create a dedicated agenda window on the right side.

I use a custom width variable to ensure the formatting as I can't trust auto-align.


#+begin_src emacs-lisp :tangle no :noweb-ref org-agenda-config
;;(set-popup-rule! "^*Org Agenda*" :side 'right :vslot 1 :width 70 :modeline nil :select t :quit t)
(set-popup-rule! "^*Org Agenda*" :side 'right :vslot 1 :width 70 :modeline nil :select t :quit 'current)
#+end_src

** Behavior

#+begin_src emacs-lisp :tangle no :noweb-ref org-agenda-config :exports none
;; Behavior
#+end_src

*** Logging

#+begin_src emacs-lisp :tangle no :noweb-ref org-agenda-config
(setq org-agenda-start-with-log-mode t)      ; Show 'completed' items in agenda.
#+end_src

** Keybinds

#+begin_src emacs-lisp :tangle no :noweb-ref org-agenda-init :exports none
;; Keybinds
#+end_src

*** My Custom Agenda Launcher

#+begin_src emacs-lisp :tangle no :noweb-ref org-agenda-init
(defun noncog/my-agenda ()
  "My custom agenda launcher."
  (interactive)
  (org-agenda nil "o"))
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref org-agenda-init
(map! :leader :desc "My agenda" "o a o" #'noncog/my-agenda)
#+end_src

** Helpers

#+begin_src emacs-lisp :tangle no :noweb-ref org-agenda-init :exports none
;; Helpers
#+end_src

*** Find and Skip Tags

#+begin_src emacs-lisp :tangle no :noweb-ref org-agenda-config
(defun noncog/skip-tag (tag)
  "Skip trees with this tag."
  (let* ((next-headline (save-excursion (or (outline-next-heading) (point-max))))
         (current-headline (or (and (org-at-heading-p) (point))
                               (save-excursion (org-back-to-heading)))))
    (if (member tag (org-get-tags current-headline))
        next-headline nil)))
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref org-agenda-config
(defun noncog/skip-all-but-this-tag (tag)
  "Skip trees that are not this tag."
  (let ((subtree-end (save-excursion (org-end-of-subtree t))))
    (if (re-search-forward (concat ":" tag ":") subtree-end t)
        nil          ; tag found, do not skip
      subtree-end))) ; tag not found, continue after end of subtree
#+end_src

* Org Capture
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
Org Capture lets you quickly insert into your org documents.
#+end_quote

** Package

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :tangle no :noweb-ref config :noweb yes
(use-package! org-capture
  :defer t
  :init
  <<org-capture-init>>
  :config
  <<org-capture-config>>
  )
#+end_src
#+html:</details>

** Variables

#+begin_src emacs-lisp :tangle no :noweb-ref org-capture-config :exports none
;; Variables
#+end_src

*** Capture Templates

I'm currently only using one template that sends all captured headings to an inbox. This increases speed by capturing now and organizing later.

#+begin_src emacs-lisp :tangle no :noweb-ref org-capture-config
(setq org-capture-templates
      `(("i" "Inbox" entry
         (file "inbox.org")
         "* %?\n%i\n" :prepend t)
        ("l" "Link" entry
         (file "inbox.org")
         "* LINK %?\n%i\n" :prepend t)))
#+end_src

** Behavior

#+begin_src emacs-lisp :tangle no :noweb-ref org-capture-config :exports none
;; Behavior
#+end_src

*** Don't Add to Bookmarks

#+begin_src emacs-lisp :tangle no :noweb-ref org-capture-config
(setq org-capture-bookmark nil)
#+end_src

** Keybinds

#+begin_src emacs-lisp :tangle no :noweb-ref org-capture-config :exports none
;; Keybinds
#+end_src

*** Switch Doom's Default Capture Binds

I switch Doom's default scratch buffer and org-capture keybinds. With this, I can quickly capture something with =SPC x=.

#+begin_src emacs-lisp :tangle no :noweb-ref org-capture-config
(map! :leader :desc "Org capture" "x" #'org-capture
      :leader :desc "Pop up scratch buffer" "X" #'doom/open-scratch-buffer)
#+end_src

** Fixes

#+begin_src emacs-lisp :tangle no :noweb-ref org-capture-config :exports none
;; Fixes
#+end_src

*** Prevent Breaking Org Capture Window

Sometimes the capture window breaks when the agenda or agenda files are already open. This fix reloads org-mode during captures. ([[https://github.com/doomemacs/doomemacs/issues/5714][Source]])

#+begin_src emacs-lisp :tangle no :noweb-ref org-capture-config
(defadvice! my/+org--restart-mode-h-careful-restart (fn &rest args)
  :around #'+org--restart-mode-h
  (let ((old-org-capture-current-plist
         (and (bound-and-true-p org-capture-mode)
              (bound-and-true-p org-capture-current-plist))))
    (apply fn args)
    (when old-org-capture-current-plist
      (setq-local org-capture-current-plist old-org-capture-current-plist)
      (org-capture-mode +1))))
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref org-capture-config
(add-hook! 'org-capture-after-finalize-hook (org-element-cache-reset t))
#+end_src

*** Increase Windowing Compatibility

By default, Doom sets the =:vslot= and =:slot= window parameters to 0 for any popup windows. The capturing popup window is a choice for these values. This means that it's popup behavior was unpredictable. Setting just =:vslot= to -1 causes the capture window to appear below most other popups, including the helpful window.

#+begin_src emacs-lisp :tangle no :noweb-ref org-capture-init
(set-popup-rule! "^\\*Capture\\*$\\|CAPTURE-.*$" :side 'bottom :height 0.3 :vslot -1 :quit nil :select t :autosave 'ignore)
#+end_src

* Org Roam
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
[[https://github.com/org-roam/org-roam][Org Roam]] is a plain-text knowledge management system. It provides a solution for non-hierarchical note-taking and linking.
#+end_quote

** Package

#+html:<details><summary>Source</summary>
#+begin_src emacs-lisp :tangle no :noweb-ref packages
;(unpin! org-roam)
;(package! org-roam
;  :recipe (:host github :repo "org-roam/org-roam-ui")
;  :pin "5c06471c3a11348342719fd9011486455adeb701")
#+end_src
#+html:</details>

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :tangle no :noweb-ref config :noweb yes
(use-package! org-roam
  :defer t
  :if (file-exists-p "~/Documents/org") ; Only load if the directory exists.
  :init
  <<org-roam-init>>
  :config
  <<org-roam-config>>
  )
#+end_src
#+html:</details>
** Resources
- [[https://www.orgroam.com/manual.html][Org-roam User Manual]]
- [[https://org-roam.discourse.group][Org-roam Discourse]]
** Variables

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-init :exports none
;; Variables
#+end_src

*** Roam Directory

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-init
(setq org-roam-directory org-directory)
#+end_src

*** Database Location

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-init
(setq org-roam-db-location (file-truename "~/Documents/org/org.db"))
#+end_src

*** Attachments Directory

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-init
(setq org-attach-id-dir (file-truename "~/Documents/org/.attachments"))
#+end_src

*** Exclude Directories

Currently not excluding any. This is a place holder for when I do.

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-init
;(setq org-roam-file-exclude-regexp (rx (or "data/" "inbox.org")) )
#+end_src

** Appearance

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-config :exports none
;; Appearance
#+end_src

*** Completion Candidates

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-config
;(setq org-roam-node-display-template)
#+end_src

** Behavior

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-config :exports none
;; Behavior
#+end_src

*** Capture Template

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-config
(setq org-roam-capture-templates
      '(("n" "node" plain
         "%?"
         :target
         (file+head "nodes/${slug}.org" "#+title: ${title}\n#+filetags: :draft:\n")
         :immediate-finish t
         :unnarrowed t)))
#+end_src

*** Enable Autosync

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-config
(org-roam-db-autosync-mode)
#+end_src

** Keybinds

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-config :exports none
;; Keybinds
#+end_src

*** Find Random Draft Nodes

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-config
(defun noncog/org-roam-is-draft-p (node)
  "Is this org-roam node a draft?"
  (member "draft" (org-roam-node-tags node)))
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-config
(defun noncog/org-roam-random-draft ()
  "Get a random node with the draft tag. "
  (interactive)
  (org-roam-node-random nil #'noncog/org-roam-is-draft-p))
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-config
(map! :leader :desc "Random draft node" "n r u" #'noncog/org-roam-random-draft)
#+end_src

* Org Roam UI
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
[[https://github.com/org-roam/org-roam-ui][org-roam-ui]] is a frontend for exploring and interacting with your org-roam notes.
#+end_quote

** Package

#+html:<details><summary>Source</summary>
#+begin_src emacs-lisp :tangle no :noweb-ref packages
(package! org-roam-ui
  :recipe (:host github :repo "org-roam/org-roam-ui"))
#+end_src
#+html:</details>

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :tangle no :noweb-ref config :noweb yes
(use-package! websocket
    :after org-roam)
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref config :noweb yes
(use-package! org-roam-ui
  :after org-roam
  :hook (org-roam . org-roam-ui-mode)
  :init
  <<org-roam-ui-init>>
  :config
  <<org-roam-ui-config>>
  )
#+end_src
#+html:</details>

** Appearance

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-ui-config :exports none
;; Appearance
#+end_src

*** Enable Doom Themes

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-ui-config
(setq org-roam-ui-sync-theme t)
#+end_src

** Behavior

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-ui-config :exports none
;; Behavior
#+end_src

*** General

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-ui-config
(setq org-roam-ui-follow t
      org-roam-ui-update-on-save t)
#+end_src

*** Use Xwidgets Instead of Regular Web Browser

The following enables org-roam-ui to open within Emacs using xwidgets instead of using a browser.

Prevent from opening the default graph on start and replace the browser function with an xwidgets function.

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-ui-config
(setq org-roam-ui-open-on-start nil
      org-roam-ui-browser-function #'+lookup-xwidget-webkit-open-url-fn)
#+end_src

Add a function to kill the xwidgets buffer and exit org-roam-ui-mode when we close the graph window.

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-ui-config
(defun +org-roam-ui-popup-kill (roam-ui-popup-buffer)
  (progn (+popup--kill-buffer roam-ui-popup-buffer 0.1) (org-roam-ui-mode -1)))
#+end_src

Set the window's popup rules. This configuration opens the graph above the backlinks buffer splitting the vertical height equally.

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-ui-config
(setq display-buffer-mark-dedicated t)
(set-popup-rule! "^\\*xwidget" :side 'right :ttl #'+org-roam-ui-popup-kill :slot -1 :width 0.33 :height 0.5 :quit 'current :select nil :modeline nil)
#+end_src

Additionally, you can take control of roam's poppup rules for further customization.

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-ui-config
;; (set-popup-rule! (regexp-quote org-roam-buffer) ; persistent org-roam buffer
;;      :side 'right :width 0.33 :height 0.5 :ttl nil :modeline nil :quit nil :slot 1)
;; (set-popup-rule! "^\\*org-roam: " ; node dedicated org-roam buffer
;;      :side 'right :width 0.33 :height 0.5 :ttl nil :modeline nil :quit nil :slot 2)
#+end_src

*** Don't Open Nodes in Side Windows

By default org-roam-ui attempts to open nodes by splitting the newest window. This won't work with side windows. So, a function is needed to more carefully choose a window to split. I simply force it to open the node in the latest regular window.

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-ui-config
(defadvice! my/+org-roam-ui--on-msg-open-node (data)
  "Open a node CAREFULLY when receiving DATA from the websocket."
  :override #'org-roam-ui--on-msg-open-node
  (let* ((id (alist-get 'id data))
         (node (org-roam-node-from-id id))
         (pos (org-roam-node-point node))
         (buf (find-file-noselect (org-roam-node-file node))))
    (run-hook-with-args 'org-roam-ui-before-open-node-functions id)
    (unless (window-live-p org-roam-ui--window)
      (if-let ((windows (cl-set-difference (doom-visible-windows) (list (minibuffer-window))))
               (newest-window (car (seq-sort-by #'window-use-time #'> windows))))
          (setq org-roam-ui--window newest-window)
        (setq org-roam-ui--window newest-window)))
    (set-window-buffer org-roam-ui--window buf)
    (select-window org-roam-ui--window)
    (goto-char pos)
    (run-hook-with-args 'org-roam-ui-after-open-node-functions id)))
#+end_src

*** Ensure Doom Theme Colors Always

This works nearly perfectly. Unfortunately you have to open the graph twice for your theme to update. But, this really isn't a big deal, at least it updates, and most users wont switch themes often.

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-ui-config
(defadvice! +org-roam-ui-always-sync-theme ()
  "Always sync da theme..."
  :after #'org-roam-ui-open
  (while (when (and org-roam-ui-mode (ignore-errors (get-buffer-window-list "*xwidget webkit: ORUI *"))) (websocket-send-text org-roam-ui-ws-socket (json-encode `((type . "theme") (data . ,(org-roam-ui--update-theme)))))))
  )
#+end_src

** Keybinds

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-ui-init :exports none
;; Keybinds
#+end_src

*** Replace Doom's Default Org Roam Graph Keybind

Use the org-roam-ui and xwidget popup window instead.

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-ui-init
(map! :leader "n r g" #'org-roam-ui-open)
#+end_src

* Vulpea
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
[[https://github.com/d12frosted/vulpea][Vulpea]] is a collection of functions (library) for note taking based on Org and Org Roam.
#+end_quote

** Package

#+begin_src emacs-lisp :tangle no :noweb-ref packages
(package! vulpea
  :recipe (:host github :repo "d12frosted/vulpea")
  :pin "f4d3448b6ccdb314c5fe3defea66e750e1371a10")
#+end_src
#+html:</details>

#+html:<details><summary>Package</summary>
#+begin_src emacs-lisp :tangle no :noweb-ref config :noweb yes
(use-package! vulpea
  :after org-roam
  :config
  <<vulpea-config>>
  )
#+end_src
#+html:</details>

** Helpers

#+begin_src emacs-lisp :tangle no :noweb-ref vulpea-config :exports none
;; Helpers
#+end_src

*** Org Agenda
**** Integrate Org Roam Nodes

By using org-roam, we may have thousands of files to search in order to display tasks in the agenda. To combat this, we can dynamically update the =org-agenda-files= variable to check for org-roam files that contain certain tags. I'm using the =agenda= tag. Org-roam files are automatically marked as long as it has a TODO heading, a scheduled item, or a refile tag. ([[https://d12frosted.io/posts/2021-01-16-task-management-with-roam-vol5.html][Source1]], [[https://github.com/hieutkt/dotfiles/tree/main/emacs/.doom.d][Source2]], [[https://github.com/d12frosted/environment/blob/f48e6d91be48b7e1d6126cde6f39c39a92a288ab/emacs/lisp/lib-vulpea-agenda.el#L81][Source3]],[[https://github.com/d12frosted/environment/blob/f48e6d91be48b7e1d6126cde6f39c39a92a288ab/emacs/lisp/lib-vulpea.el#L51][Source4]])

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(add-to-list 'org-tags-exclude-from-inheritance "agenda")
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref vulpea-config
(defun vulpea-agenda-file-p ()
  "Return non-nil if current buffer has todo keywords or scheduled items.
TODO entries marked as done are ignored, meaning the this
function returns nil if current buffer contains only completed
tasks. The only exception is headings tagged as REFILE."
  (org-element-map
      (org-element-parse-buffer 'headline)
      'headline
    (lambda (h)
      (let ((todo-type (org-element-property :todo-type h)))
        (or
         ;; any headline with some todo keyword
         (eq 'todo todo-type)
         ;; any headline with REFILE tag (no inheritance)
         (seq-contains-p (org-element-property :tags h) "REFILE")
         ;; any non-todo headline with an active timestamp
         (and
          (not (eq 'done todo-type))
          (org-element-property :contents-begin h)
          (save-excursion
            (goto-char (org-element-property :contents-begin h))
            (let ((end (save-excursion
                         ;; we must look for active timestamps only
                         ;; before then next heading, even if it's
                         ;; child, but org-element-property
                         ;; :contents-end includes all children
                         (or
                          (re-search-forward org-element-headline-re
                                             (org-element-property :contents-end h)
                                             ':noerror)
                          (org-element-property :contents-end h)))))
              (re-search-forward org-ts-regexp end 'noerror)))))))
    nil 'first-match))
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref vulpea-config
(defun vulpea-ensure-filetag ()
  "Add missing FILETAGS to the current node."
  (let* ((tags (vulpea-buffer-tags-get))
               (original-tags tags))
    ;; TODO: Add other tag processing capabilities.
    ;; process agenda tags
    (if (vulpea-agenda-file-p)
        (setq tags (cons "agenda" tags))
      (setq tags (remove "agenda" tags)))
    ;; cleanup duplicates
    (setq tags (seq-uniq tags))
    ;; update tags if changed
    (when (or (seq-difference tags original-tags)
              (seq-difference original-tags tags))
      (apply #'vulpea-buffer-tags-set (seq-uniq tags)))))
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref vulpea-config
(defun vulpea-pre-save-hook ()
  "Update 'org-agenda-files' when org-roam file is saved."
  (when (and (not (active-minibuffer-window))
             (org-roam-buffer-p))
    (vulpea-ensure-filetag)))
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref vulpea-config
(add-hook 'before-save-hook #'vulpea-pre-save-hook)
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref vulpea-config
(defun vulpea-agenda-files ()
  "Return a list of node files containing the 'agenda' tag." ;
  ;; TODO Switch to vulpea-db-query
  (seq-uniq
   (seq-map
    #'car
    (org-roam-db-query
     [:select [nodes:file]
      :from tags
      :left-join nodes
      :on (= tags:node-id nodes:id)
      :where (or (like tag (quote "%\"agenda\"%"))
                 (like tag (quote "%\"agenda\"%")))])))) ;; TODO: Remove double agenda add other tags.
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref vulpea-config
(defun vulpea-agenda-files-update (&rest _)
  "A hook function to update the value of `org-agenda-files'."
  (setq org-agenda-files (vulpea-agenda-files)))
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref vulpea-config
(advice-add 'org-agenda :before #'vulpea-agenda-files-update)
(advice-add 'org-todo-list :before #'vulpea-agenda-files-update)
#+end_src

* Org GTD
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
[[https://github.com/Trevoke/org-gtd.el][Org-GTD]] is a package that tries to replicate the 'Getting Things Done' workflow as closely as possible in Org mode.
#+end_quote

** Package

#+html:<details><summary>Source</summary>
#+begin_src emacs-lisp :tangle no :noweb-ref packages
(package! org-edna)
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref packages
(package! org-gtd
  :recipe (:host github :repo "Trevoke/org-gtd.el")
  :pin "218fba0931cfd666591b09273f9ea8f6a6d8d8f9")
#+end_src
#+html:</details>

#+html:<details><summary>Package</summary>
#+begin_src emacs-lisp :tangle no :noweb-ref config :noweb yes
(use-package! org-gtd
  ;:defer t
  :after org
  :init
  <<org-gtd-init>>
  :custom
  <<org-gtd-custom>>
  :config
  <<org-gtd-config>>
)
#+end_src
#+html:</details>

** Variables

#+begin_src emacs-lisp :tangle no :noweb-ref org-gtd-config :exports none
;; Variables
#+end_src

*** Prevent Startup Warnings

#+begin_src emacs-lisp :tangle no :noweb-ref org-gtd-init
(setq org-gtd-update-ack "3.0.0")
#+end_src

*** Org GTD Directory

#+begin_src emacs-lisp :tangle no :noweb-ref org-gtd-custom
(org-gtd-directory "~/Documents/org/")
#+end_src

*** Default File Name

#+begin_src emacs-lisp :tangle no :noweb-ref org-gtd-config
;(setq org-gtd-default-file-name "~/Documents/org/nodes")
#+end_src

** Behavior

#+begin_src emacs-lisp :tangle no :noweb-ref org-gtd-config :exports none
;; Behavior
#+end_src

*** Setup Org Edna Inheritance

#+begin_src emacs-lisp :tangle no :noweb-ref org-gtd-custom
(org-edna-use-inheritance t)
#+end_src

*** Setup Org-GTD Organize Hooks

#+begin_src emacs-lisp :tangle no :noweb-ref org-gtd-custom
(org-gtd-organize-hooks '(org-gtd-set-area-of-focus org-set-tags-command))
#+end_src

*** Enable Org Edna

#+begin_src emacs-lisp :tangle no :noweb-ref org-gtd-config
(org-edna-mode)
#+end_src

** Keybinds

#+begin_src emacs-lisp :tangle no :noweb-ref org-gtd-config :exports none
;; Keybinds
#+end_src

*** Set All Binds

#+begin_src emacs-lisp :tangle no :noweb-ref org-gtd-config
(map! :leader
      :prefix ("n g" . "org-gtd")
      :desc "Capture"        "c"  #'org-gtd-capture
      :desc "Engage"         "e"  #'org-gtd-engage
      :desc "Process inbox"  "p"  #'org-gtd-process-inbox
      :desc "Show all next"  "n"  #'org-gtd-show-all-next
      :desc "Stuck projects" "s"  #'org-gtd-show-stuck-projects)
(map! :map org-gtd-process-map
      :desc "Choose" "C-c c" #'org-gtd-choose)
#+end_src

* Org Appear
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
[[https://github.com/awth13/org-appear][Org Appear]] makes invisible Org elements like emphasis markers magically appear.
#+end_quote

** Package

#+html:<details><summary>Source</summary>
#+begin_src emacs-lisp :tangle no :noweb-ref packages
(package! org-appear
  :recipe (:host github :repo "awth13/org-appear")
  :pin "eb9f9db40aa529fe4b977235d86494b115281d17")
#+end_src
#+html:</details>

#+html:<details><summary>Source</summary>
#+begin_src emacs-lisp :tangle no :noweb-ref config :noweb yes
(use-package! org-appear
  :hook (org-mode . org-appear-mode)
  :config
  <<org-appear-config>>
  )
#+end_src
#+html:</details>

** Appearance

#+begin_src emacs-lisp :tangle no :noweb-ref org-appear-config :exports none
;; Appearance
#+end_src

*** General

#+begin_src emacs-lisp :tangle no :noweb-ref org-appear-config
(setq org-appear-autoemphasis t              ; Show emphasis markup.
      org-appear-autosubmarkers t            ; Show sub/superscript
      org-appear-autoentities t              ; Show LaTeX like Org pretty entities.
      org-appear-autolinks nil               ; Shows Org links.
      org-appear-autokeywords nil            ; Shows hidden Org keywords.
      org-appear-inside-latex nil)           ; Show LaTeX code. Use Fragtog instead.
#+end_src

* Org Fragtog
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
[[https://github.com/io12/org-fragtog][Org Fragtog]] toggles LaTeX fragments as the cursor enters and exits them. It's org-appear for LaTeX!
#+end_quote

** Package

#+html:<details><summary>Source</summary>
#+begin_src emacs-lisp :tangle no :noweb-ref packages
(package! org-fragtog
  :pin "c675563af3f9ab5558cfd5ea460e2a07477b0cfd")
#+end_src
#+html:</details>

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :tangle no :noweb-ref config :noweb yes
(use-package! org-fragtog
  :hook (org-mode . org-fragtog-mode))
#+end_src
#+html:</details>

* Org Modern
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
[[https://github.com/minad/org-modern][Org Modern]] implements a “modern” style for your Org buffers using font locking and text properties.
#+end_quote

** Package

#+html:<details><summary>Source</summary>
#+begin_src emacs-lisp :tangle no :noweb-ref packages
(package! org-modern
  :pin "b614ad31d72c49f9eb29d3836995fd7fb0d1fd4a")
#+end_src
#+html:</details>

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :tangle no :noweb-ref config :noweb yes
(use-package! org-modern
  :hook
  (org-mode . org-modern-mode)
  (org-agenda-finalize . org-modern-agenda)
  :config
  <<org-modern-config>>
  )
#+end_src
#+html:</details>

** Appearance

#+begin_src emacs-lisp :tangle no :noweb-ref org-modern-config :exports none
;; Appearance
#+end_src

*** General

These settings will need sorted into their own headings eventually.

#+begin_src emacs-lisp :tangle no :noweb-ref org-modern-config
(setq org-modern-hide-stars nil              ; Let Org handle hiding the stars.
      org-modern-table-vertical 1            ; Use thinner lines than default.
      org-modern-table-horizontal 0.2        ; Unify line thickness with vertical line.
      org-modern-progress nil                ; Use default progress face.
      org-modern-priority nil                ; Use default priority face.
      org-modern-todo-faces                  ; Inherit Doom's Org faces.
      '(("TODO" :inverse-video t :inherit org-todo)
        ("PROJ" :inverse-video t :inherit +org-todo-project)
        ("STRT" :inverse-video t :inherit +org-todo-active)
        ("[-]"  :inverse-video t :inherit +org-todo-active)
        ("HOLD" :inverse-video t :inherit +org-todo-onhold)
        ("WAIT" :inverse-video t :inherit +org-todo-onhold)
        ("[?]"  :inverse-video t :inherit +org-todo-onhold)
        ("KILL" :inverse-video t :inherit +org-todo-cancel)
        ("NO"   :inverse-video t :inherit +org-todo-cancel))
      org-modern-star '("◉" "○" "✸" "✿" "✤" "✜" "◆" "▶")
      org-modern-horizontal-rule (make-string 80 ?─))
#+end_src

* Org Modern Indent
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
[[https://github.com/jdtsmith/org-modern-indent][Org-modern-indent]] adds back the source block "bracket" to org-modern, which is normally broken by the use of indentation.
#+end_quote

** Package

#+html:<details><summary>Source</summary>
#+begin_src emacs-lisp :tangle no :noweb-ref packages
(package! org-modern-indent
  :recipe (:host github :repo "jdtsmith/org-modern-indent")
  :pin "c5a50f302dc1053d5b498e0ea2bc0ee233e8e1b8")
#+end_src
#+html:</details>

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :tangle no :noweb-ref config :noweb yes
(use-package! org-modern-indent
  :config ; add late to hook
  (add-hook 'org-mode-hook #'org-modern-indent-mode 1))
#+end_src
#+html:</details>

* TOC Org
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
[[https://github.com/snosov1/toc-org][TOC-Org]] creates an up-to-date table of contents in an Org file, useful primarily for READMEs on GitHub.
#+end_quote

** Package

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :tangle no :noweb-ref config :noweb yes
(use-package! toc-org
  :defer t
  :config
  <<toc-org-config>>
  )
#+end_src
#+html:</details>

** Behavior

#+begin_src emacs-lisp :tangle no :noweb-ref toc-org-config :exports none
;; Behavior
#+end_src

*** Set Default Depth

#+begin_src emacs-lisp :tangle no :noweb-ref toc-org-config
(setq org-toc-default-depth 2)
#+end_src

*** Add Code Folding to Quoted TOC

When I use GitHub for literate documentation, I want to add the HTML =details= tag around the table of content to create a hidden table of contents that the user can expand if they wish to. This is done by creating and advising a function that replaces the string used in the quoted table of contents to include the details tag.

#+begin_src emacs-lisp :tangle no :noweb-ref toc-org-config
(defadvice! my/+toc-org-insert-toc-folded (&optional dry-run)
  "An advised function to extend 'toc-org-insert-toc to add html details tags."
  :override #'toc-org-insert-toc
  (interactive)
  (let ((dry-run nil))
  (save-excursion
    (goto-char (point-min))
    (let* ((case-fold-search t)
           (markdown-syntax-p (derived-mode-p 'markdown-mode))
           (heading-symbol-regexp (if markdown-syntax-p "^#" "^\\*")))
      ;; find the first heading with the :TOC: tag
      (when (re-search-forward (concat heading-symbol-regexp toc-org-toc-org-regexp) (point-max) t)
        (let* ((tag (match-string 2))
               (depth (if tag
                          (- (aref tag 1) ?0) ;; is there a better way to convert char to number?
                        toc-org-max-depth))
               (hrefify-tag (if (and tag (>= (length tag) 4))
                                (downcase (substring tag 3))
                              toc-org-hrefify-default))
               (hrefify-string (concat "toc-org-hrefify-" hrefify-tag))
               (hrefify (intern-soft hrefify-string))
               (put-quote (save-match-data (string-match toc-org-quote-tag-regexp (match-string 0))))
               (toc-prefix (if put-quote (if markdown-syntax-p "```\n" "#+html:<details><summary>Table of Contents</summary>\n#+BEGIN_QUOTE\n")  ""))
               (toc-suffix (if put-quote (if markdown-syntax-p "```\n" "#+END_QUOTE\n#+html:</details>\n") "")))
          (if hrefify
              (let ((new-toc
                     (concat toc-prefix
                             (toc-org-hrefify-toc
                              (toc-org-flush-subheadings (toc-org-raw-toc markdown-syntax-p) depth)
                              hrefify
                              markdown-syntax-p
                              (when toc-org-hrefify-hash
                                (clrhash toc-org-hrefify-hash)))
                             toc-suffix)))
                (unless dry-run
                  (newline (forward-line 1))

                  ;; skip drawers
                  (let ((end
                         (save-excursion ;; limit to next heading
                           (search-forward-regexp heading-symbol-regexp (point-max) 'skip))))
                    (while (re-search-forward toc-org-drawer-regexp end t)
                      (skip-chars-forward "[:space:]")))
                  (beginning-of-line)

                  ;; insert newline if TOC is currently empty
                  (when (looking-at heading-symbol-regexp)
                    (open-line 1))

                  ;; find TOC boundaries
                  (let ((beg (point))
                        (end
                         (save-excursion
                           (when (search-forward-regexp heading-symbol-regexp (point-max) 'skip)
                             (forward-line -1))
                           (end-of-line)
                           (point))))
                    ;; update the TOC, but only if it's actually different
                    ;; from the current one
                    (unless (equal
                             (buffer-substring-no-properties beg end)
                             new-toc)
                      (delete-region beg end)
                      (insert new-toc)))))
            (message (concat "Hrefify function " hrefify-string " is not found")))))))))
#+end_src

* Org Noter
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
[[https://github.com/weirdNox/org-noter][Org Noter]] creates org notes that are kept in sync with PDF pages as you scroll.
#+end_quote

** Package

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :tangle no :noweb-ref config :noweb yes
(use-package! org-noter
  :defer t
  :init
  <<org-noter-init>>
  :config
  <<org-noter-config>>
  )
#+end_src
#+html:</details>

** Variables

#+begin_src emacs-lisp :tangle no :noweb-ref org-noter-init :exports none
;; Variables
#+end_src

*** Set Notes Directory

#+begin_src emacs-lisp :tangle no :noweb-ref org-noter-init
(setq org-noter-notes-search-path (file-truename "~/Documents/org/references"))
#+end_src

** Behavior

#+begin_src emacs-lisp :tangle no :noweb-ref org-noter-config :exports none
;; Behavior
#+end_src

*** Frame

#+begin_src emacs-lisp :tangle no :noweb-ref org-noter-config
(setq org-noter-always-create-frame nil        ; Don't create a new frame for the session.
      org-noter-kill-frame-at-session-end nil) ; Don't kill any frames since none created.
#+end_src

*** Notes

#+begin_src emacs-lisp :tangle no :noweb-ref org-noter-config
(setq org-noter-separate-notes-from-heading t) ; Adds line between headings and notes.
#+end_src

* PDF Tools
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
[[https://github.com/vedang/pdf-tools][PDF Tools]] is a replacement PDF viewer for the default, DocView, in Emacs. It's required for =org-noter=.
#+end_quote

** Package

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :tangle no :noweb-ref config :noweb yes
(use-package! pdf-tools
  :defer t
  :config
  <<pdf-tools-config>>
  )
#+end_src
#+html:</details>

** Behavior

#+begin_src emacs-lisp :tangle no :noweb-ref pdf-tools-config :exports none
;; Behavior
#+end_src

*** Build If Necessary

#+begin_src emacs-lisp :tangle no :noweb-ref pdf-tools-config
(pdf-tools-install t)
#+end_src

** Fixes

#+begin_src emacs-lisp :tangle no :noweb-ref pdf-tools-config :exports none
;; Fixes
#+end_src

*** Prevent Crash on macOS Ventura

Apparently this is required. ([[https://github.com/vedang/pdf-tools/issues/173#issuecomment-1341882242][Source]])

#+begin_src emacs-lisp :tangle no :noweb-ref pdf-tools-config
(when IS-MAC (add-hook 'pdf-tools-enabled-hook 'pdf-view-dark-minor-mode))
#+end_src

* PlantUML
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
[[https://plantuml.com][PlantUML]] is a component that allows you to quickly write several types of UML diagrams using its language. This integrates well with org mode for generating UML diagrams from source blocks.
#+end_quote

** Package

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :tangle no :noweb-ref config :noweb yes
(use-package! plantuml-mode
  :defer t
  :config
  <<plantuml-mode-config>>
  )
#+end_src
#+html:</details>

** Behavior

#+begin_src emacs-lisp :tangle no :noweb-ref plantuml-mode-config :exports none
;; Behavior
#+end_src

*** Execution Mode

I use a local jar executable instead of contacting the website.

#+begin_src emacs-lisp :tangle no :noweb-ref plantuml-mode-config
(setq plantuml-default-exec-mode 'jar)
#+end_src

*** Ensure Local Installation

Downloads the jar file if it's not on the system.

#+begin_src emacs-lisp :tangle no :noweb-ref plantuml-mode-config
(unless (file-exists-p plantuml-jar-path)
  (plantuml-download-jar))
#+end_src

* Ox (Org Export)
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
Ox (Org Export) implements a generic export engine for Org. It uses different backends to change the translation of org documents into various other formats.
#+end_quote

** Package

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :tangle no :noweb-ref config :noweb yes
(use-package! ox
  :defer t
  :init
  <<ox-init>>
  :config
  <<ox-config>>
  )
#+end_src
#+html:</details>

** Appearance

#+begin_src emacs-lisp :tangle no :noweb-ref ox-config :exports none
;; Appearance
#+end_src

*** Creator String

I like to include this on my LaTeX exports to allude to the tools that I like to use.

#+begin_src emacs-lisp :tangle no :noweb-ref ox-config
(setq org-export-with-creator t
      org-export-creator-string (format "Doom Emacs %s (Org mode %s)" emacs-version org-version))
#+end_src

** Behavior

#+begin_src emacs-lisp :tangle no :noweb-ref ox-config :exports none
;; Behavior
#+end_src

*** Ignore Headings but Keep Content in Exports

This setting allows you to use the =:ignore:= tag to remove a heading from an export but keep its contents.

#+begin_src emacs-lisp :tangle no :noweb-ref ox-config
(require 'ox-extra)
(ox-extras-activate '(ignore-headlines))
#+end_src

*** Export Depth

By default only the first three headings, including titles are exported. Five levels of depth seems like a reasonable value for LaTeX and HTML exports. Tecosaur reasoned that HTML5 has six heading levels but Org exports start at the second, leaving us with just five to use. It should also challenge/prevent me from overly nesting information.

#+begin_src emacs-lisp :tangle no :noweb-ref ox-config
(setq org-export-headline-levels 5)
#+end_src

** Keybinds

#+begin_src emacs-lisp :tangle no :noweb-ref ox-init :exports none
;; Keybinds
#+end_src

*** View Exported Org File

[[https://github.com/tecosaur/emacs-config/blob/master/config.org#view-exported-file][Tecosaur]] created a function and keybind to view the recently exported org-file.

#+begin_src emacs-lisp :tangle no :noweb-ref ox-init
(defun org-view-output-file (&optional org-file-path)
  "Visit buffer open on the first output file (if any),
found, using `org-view-output-file-extensions'."
  (interactive)
  (let* ((org-file-path (or org-file-path (buffer-file-name) ""))
         (dir (file-name-directory org-file-path))
         (basename (file-name-base org-file-path))
         (output-file nil))
    (dolist (ext org-view-output-file-extensions)
      (unless output-file
        (when (file-exists-p
               (concat dir basename "." ext))
          (setq output-file (concat dir basename "." ext)))))
    (if output-file
        (if (member (file-name-extension output-file) org-view-external-file-extensions)
            (browse-url-xdg-open output-file)
          (pop-to-buffer (or (find-buffer-visiting output-file)
                             (find-file-noselect output-file))))
      (message "No exported file found"))))
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref ox-init
(defvar org-view-output-file-extensions '("pdf" "md" "rst" "txt" "tex" "html")
  "Find output files with these extensions, in order, viewing the first match.")
(defvar org-view-external-file-extensions '("html")
  "File formats that should be opened externally.")
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref ox-init
(map! :map org-mode-map
      :localleader
      :desc "View exported file"
      "v" #'org-view-output-file)
#+end_src

* Ox Latex
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
Ox Latex is the LaTeX backend for the Org Export Engine.
#+end_quote

** Package

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :tangle no :noweb-ref config :noweb yes
(use-package! ox-latex
  :defer t
  :config
  <<ox-latex-config>>
  )
#+end_src
#+html:</details>

** Appearance

#+begin_src emacs-lisp :tangle no :noweb-ref ox-latex-config :exports none
;; Appearance
#+end_src

*** Set Source Block Backend

This adds theming and syntax highlighting to our source blocks in latex exports.

#+begin_src emacs-lisp :tangle no :noweb-ref ox-latex-config
(setq org-latex-src-block-backend 'engraved)
#+end_src

*** Custom Document Class

#+begin_src emacs-lisp :tangle no :noweb-ref ox-latex-config
(add-to-list 'org-latex-classes
             '("notes"
               "\\documentclass{article}
                [NO-DEFAULT-PACKAGES]
                [PACKAGES]
                [EXTRA]"
               ("\\section{%s}" . "\\section*{%s}")
               ("\\subsection{%s}" . "\\subsection*{%s}")
               ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
               ("\\paragraph{%s}" . "\\paragraph*{%s}")
               ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))
#+end_src

** Behavior

#+begin_src emacs-lisp :tangle no :noweb-ref ox-latex-config :exports none
;; Behavior
#+end_src

*** Set PDF Process

#+begin_src emacs-lisp :tangle no :noweb-ref ox-latex-config
(setq org-latex-pdf-process '("LC_ALL=en_US.UTF-8 latexmk -f -pdf -%latex -shell-escape -interaction=nonstopmode -output-directory=%o %f"))
#+end_src

* Engrave Faces
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote
[[https://github.com/tecosaur/engrave-faces][Engrave Faces]] is a generic exporter that passes a fontified buffer to an org backend to be exported to a particular format. It provides theming and syntax highlighting in code blocks for our org-mode html and latex exports!
#+end_quote

** Package

#+html:<details><summary>Source</summary>
#+begin_src emacs-lisp :tangle no :noweb-ref packages
(package! engrave-faces
  :recipe (:host github :repo "tecosaur/engrave-faces")
  :pin "2c72619195d489a4f6d5370f70dd7f6aa11801c3")
#+end_src
#+html:</details>


#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :tangle no :noweb-ref config :noweb yes
(use-package! engrave-faces-latex
  :after ox-latex)
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref config :noweb yes
(use-package! engrave-faces-html
  :after ox-html)
#+end_src
#+html:</details>

* LSP-Clangd
:PROPERTIES:
:VISIBILITY: children
:END:

#+begin_quote

#+end_quote

** Package

#+html:<details><summary>Configuration</summary>
#+begin_src emacs-lisp :tangle no :noweb-ref config :noweb yes
(use-package! lsp-clangd
  :defer t
  :config
  <<lsp-clangd-config>>
  )
#+end_src
#+html:</details>

** Behavior

#+begin_src emacs-lisp :tangle no :noweb-ref lsp-clangd-config :exports none
;; Behavior
#+end_src

*** Set Clangd Args

#+begin_src emacs-lisp :tangle no :noweb-ref lsp-clangd-config
(setq lsp-clients-clangd-args
      '("-j=3"
        "--background-index"
        "--clang-tidy"
        "--completion-style=detailed"
        "--header-insertion=never"
        "--header-insertion-decorators=0"))
(set-lsp-priority! 'clangd 2)
#+end_src
