#+tags: export noexport
#+export_select_tags: export
#+export_exclude_tags: exclude noexport
#+options: todo:nil
#+startup: show2levels

#+html:<div align="center">
#+begin_html
<p><a href="https://www.gnu.org/software/emacs/emacs.html#Releases"><img src="https://img.shields.io/badge/Emacs-27.1+-blueviolet.svg?style=flat-square&logo=GNU%20Emacs&logoColor=white"></a> <a href="https://orgmode.org"><img src="https://img.shields.io/badge/Org-literate%20config-%2377aa99?style=flat-square&logo=org&logoColor=white"></a></p>

<p><a href="https://github.com/Schievel1/doom-emacs-splash"><img src="https://github.com/Schievel1/doom-emacs-splash/blob/main/svg/doom/doomEmacsDracula.svg" height="300"></a></p>

<p><a href="https://creativecommons.org/licenses/by-sa/4.0/"><img src="https://img.shields.io/badge/CC--BY--SA-161b22?style=for-the-badge&logo=Creative%20Commons&logoColor=white"></a></p>

<p><code>This is my <a href="https://github.com/doomemacs/doomemacs">Doom</a> <a href="https://www.gnu.org/software/emacs/">Emacs</a> configuration.</code></p>
#+end_html
#+html:</div>

* Table of Contents :TOC_2:
:PROPERTIES:
:CUSTOM_ID: table-of-contents
:END:
- [[#doom][Doom]]
  - [[#resources][Resources]]
  - [[#doom-configs][Doom Configs]]
  - [[#doom-modules][Doom Modules]]
  - [[#variables][Variables]]
  - [[#appearance][Appearance]]
  - [[#behavior][Behavior]]
  - [[#keybinds][Keybinds]]
- [[#org][Org]]
  - [[#variables-1][Variables]]
  - [[#appearance-1][Appearance]]
  - [[#behavior-1][Behavior]]
- [[#org-agenda][Org Agenda]]
  - [[#variables-2][Variables]]
  - [[#appearance-2][Appearance]]
  - [[#behavior-2][Behavior]]
  - [[#keybinds-1][Keybinds]]
  - [[#fixes-and-helpers][Fixes and Helpers]]
- [[#org-capture][Org Capture]]
  - [[#variables-3][Variables]]
  - [[#behavior-3][Behavior]]
  - [[#keybinds-2][Keybinds]]
  - [[#fixes][Fixes]]
- [[#org-roam][Org Roam]]
  - [[#variables-4][Variables]]
  - [[#behavior-4][Behavior]]
  - [[#keybinds-3][Keybinds]]
- [[#org-roam-ui][Org Roam UI]]
  - [[#appearance-3][Appearance]]
  - [[#behavior-5][Behavior]]
  - [[#keybinds-4][Keybinds]]
- [[#org-modern][Org Modern]]
  - [[#appearance-4][Appearance]]
- [[#org-modern-indent][Org Modern Indent]]
- [[#org-appear][Org Appear]]
  - [[#appearance-5][Appearance]]
- [[#org-fragtog][Org Fragtog]]
- [[#ox-org-export][Ox (Org Export)]]
  - [[#appearance-6][Appearance]]
  - [[#behavior-6][Behavior]]
  - [[#keybinds-5][Keybinds]]
- [[#ox-latex][Ox Latex]]
  - [[#appearance-7][Appearance]]
  - [[#behavior-7][Behavior]]
- [[#engrave-faces][Engrave Faces]]
- [[#org-noter][Org Noter]]
  - [[#behavior-8][Behavior]]
- [[#projectile][Projectile]]
  - [[#variables-5][Variables]]
  - [[#behavior-9][Behavior]]
  - [[#keybinds-6][Keybinds]]
- [[#plantuml][PlantUML]]
  - [[#behavior-10][Behavior]]
- [[#pdf-tools][PDF Tools]]
  - [[#fixes-1][Fixes]]
- [[#yasnippet][Yasnippet]]
  - [[#resources-1][Resources]]
  - [[#behavior-11][Behavior]]
- [[#magit][Magit]]
  - [[#behavior-12][Behavior]]
- [[#company][Company]]
  - [[#behavior-13][Behavior]]
- [[#vterm][Vterm]]
  - [[#keybinds-7][Keybinds]]
- [[#which-key][Which-Key]]
  - [[#fixes-2][Fixes]]
- [[#persp-mode][Persp-Mode]]
  - [[#fixes-3][Fixes]]
- [[#visual-fill-column][Visual Fill Column]]
  - [[#behavior-14][Behavior]]
- [[#treemacs][Treemacs]]
  - [[#appearance-8][Appearance]]
- [[#vertico][Vertico]]
  - [[#behavior-15][Behavior]]
  - [[#keybinds-8][Keybinds]]
- [[#doom-modeline][Doom Modeline]]
  - [[#appearance-9][Appearance]]
- [[#nav-flash][Nav-flash]]
  - [[#appearance-10][Appearance]]
- [[#doom-dashboard][Doom Dashboard]]
  - [[#keybinds-9][Keybinds]]
- [[#lsp-clangd][Lsp-Clangd]]
  - [[#behavior-16][Behavior]]

* Doom
** Resources
** Doom Configs

Doom Emacs uses three config files:

- =init.el= - Defines which of Doom's modules are loaded.
- =packages.el= - Defines which external pacakges are loaded.
- =config.el= - The user's custom configuration.

#+begin_src emacs-lisp :tangle init.el :exports none
;;; init.el -*- lexical-binding: t; -*-

;; This file controls what Doom modules are enabled and what order they load
;; in. Remember to run 'doom sync' after modifying it!

;; NOTE Press 'SPC h d h' (or 'C-h d h' for non-vim users) to access Doom's
;;      documentation. There you'll find a link to Doom's Module Index where all
;;      of our modules are listed, including what flags they support.

;; NOTE Move your cursor over a module's name (or its flags) and press 'K' (or
;;      'C-c c k' for non-vim users) to view its documentation. This works on
;;      flags as well (those symbols that start with a plus).
;;
;;      Alternatively, press 'gd' (or 'C-c c d') on a module to browse its
;;      directory (for easy access to its source code).
#+end_src

#+begin_src emacs-lisp :tangle packages.el :exports none
;; -*- no-byte-compile: t; -*-
;;; $DOOMDIR/packages.el

;; To install a package with Doom you must declare them here and run 'doom sync'
;; on the command line, then restart Emacs for the changes to take effect -- or
;; use 'M-x doom/reload'.


;; To install SOME-PACKAGE from MELPA, ELPA or emacsmirror:
;(package! some-package)

;; To install a package directly from a remote git repo, you must specify a
;; `:recipe'. You'll find documentation on what `:recipe' accepts here:
;; https://github.com/radian-software/straight.el#the-recipe-format
;(package! another-package
;  :recipe (:host github :repo "username/repo"))

;; If the package you are trying to install does not contain a PACKAGENAME.el
;; file, or is located in a subdirectory of the repo, you'll need to specify
;; `:files' in the `:recipe':
;(package! this-package
;  :recipe (:host github :repo "username/repo"
;           :files ("some-file.el" "src/lisp/*.el")))

;; If you'd like to disable a package included with Doom, you can do so here
;; with the `:disable' property:
;(package! builtin-package :disable t)

;; You can override the recipe of a built in package without having to specify
;; all the properties for `:recipe'. These will inherit the rest of its recipe
;; from Doom or MELPA/ELPA/Emacsmirror:
;(package! builtin-package :recipe (:nonrecursive t))
;(package! builtin-package-2 :recipe (:repo "myfork/package"))

;; Specify a `:branch' to install a package from a particular branch or tag.
;; This is required for some packages whose default branch isn't 'master' (which
;; our package manager can't deal with; see radian-software/straight.el#279)
;(package! builtin-package :recipe (:branch "develop"))

;; Use `:pin' to specify a particular commit to install.
;(package! builtin-package :pin "1a2b3c4d5e")


;; Doom's packages are pinned to a specific commit and updated from release to
;; release. The `unpin!' macro allows you to unpin single packages...
;(unpin! pinned-package)
;; ...or multiple packages
;(unpin! pinned-package another-pinned-package)
;; ...Or *all* packages (NOT RECOMMENDED; will likely break things)
;(unpin! t)
#+end_src

#+begin_src emacs-lisp :tangle config.el :exports none
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-

;; Place your private configuration here!

;; sync' after modifying this file!
;; Whenever you reconfigure a package, make sure to wrap your config in an
;; `after!' block, otherwise Doom's defaults may override your settings. E.g.
;;
;;   (after! PACKAGE
;;     (setq x y))
;;
;; The exceptions to this rule:
;;
;;   - Setting file/directory variables (like `org-directory')
;;   - Setting variables which explicitly tell you to set them before their
;;     package is loaded (see 'C-h v VARIABLE' to look up their documentation).
;;   - Setting doom variables (which start with 'doom-' or '+').
;;
;; Here are some additional functions/macros that will help you configure Doom.
;;
;; - `load!' for loading external *.el files relative to this one
;; - `use-package!' for configuring packages
;; - `after!' for running code after a package has loaded
;; - `add-load-path!' for adding directories to the `load-path', relative to
;;   this file. Emacs searches the `load-path' when you load packages with
;;   `require' or `use-package'.
;; - `map!' for binding new keys
;;
;; To get information about any of these functions/macros, move the cursor over
;; the highlighted symbol at press 'K' (non-evil users must press 'C-c c k').
;; This will open documentation for it, including demos of how they are used.
;; Alternatively, use `C-h o' to look up a symbol (functions, variables, faces,
;; etc).
;;
;; You can also try 'gd' (or 'C-c c d') to jump to their definition and see how
;; they are implemented.
#+end_src

** Doom Modules

#+html:<details><summary>Module List</summary>
#+begin_src emacs-lisp :tangle init.el
(setq +literate-config-file "~/.config/doom/README.org")

(doom! :input
       ;;bidi              ; (tfel ot) thgir etirw uoy gnipleh
       ;;chinese
       ;;japanese
       ;;layout            ; auie,ctsrnm is the superior home row

       :completion
       (company)           ; the ultimate code completion backend
       ;;helm              ; the *other* search engine for love and life
       ;;ido               ; the other *other* search engine...
       ;;ivy               ; a search engine for love and life
       vertico             ; the search engine of the future

       :ui
       ;;deft              ; notational velocity for Emacs
       doom                ; what makes DOOM look the way it does
       doom-dashboard      ; a nifty splash screen for Emacs
       ;;doom-quit         ; DOOM quit-message prompts when you quit Emacs
       (emoji              ; 🙂
        +unicode
        +github)
       hl-todo             ; highlight TODO/FIXME/NOTE/DEPRECATED/HACK/REVIEW
       ;;hydra
       ;;indent-guides     ; highlighted indent columns
       ;;ligatures         ; ligatures and symbols to make your code pretty again
       ;;minimap           ; show a map of the code on the side
       modeline            ; snazzy, Atom-inspired modeline, plus API
       nav-flash           ; blink cursor line after big motions
       ;;neotree           ; a project drawer, like NERDTree for vim
       ophints             ; highlight the region an operation acts on
       (popup +defaults)   ; tame sudden yet inevitable temporary windows
       ;;tabs              ; a tab bar for Emacs
       treemacs            ; a project drawer, like neotree but cooler
       ;;unicode           ; extended unicode support for various languages
       (vc-gutter +pretty) ; vcs diff in the fringe
       vi-tilde-fringe     ; fringe tildes to mark beyond EOB
       ;;window-select     ; visually switch windows
       workspaces          ; tab emulation, persistence & separate workspaces
       zen                 ; distraction-free coding or writing

       :editor
       (evil +everywhere)  ; come to the dark side, we have cookies
       file-templates      ; auto-snippets for empty files
       fold                ; (nigh) universal code folding
       ;;(format +onsave)  ; automated prettiness
       ;;god               ; run Emacs commands without modifier keys
       ;;lispy             ; vim for lisp, for people who don't like vim
       ;;multiple-cursors  ; editing in many places at once
       ;;objed             ; text object editing for the innocent
       ;;parinfer          ; turn lisp into python, sort of
       ;;rotate-text       ; cycle region at point between text candidates
       snippets            ; my elves. They type so I don't have to
       ;;word-wrap         ; soft wrapping with language-aware indent

       :emacs              ; making dired pretty [functional]
       (dired
        +icons
        +ranger)
       electric            ; smarter, keyword-based electric-indent
       (ibuffer +icons)    ; interactive buffer management
       undo                ; persistent, smarter undo for your inevitable mistakes
       vc                  ; version-control and Emacs, sitting in a tree

       :term
       ;;eshell            ; the elisp shell that works everywhere
       ;;shell             ; simple shell REPL for Emacs
       ;;term              ; basic terminal emulator for Emacs
       vterm               ; the best terminal emulation in Emacs

       :checkers
       syntax              ; tasing you for every semicolon you forget
       ;;(spell +flyspell) ; tasing you for misspelling mispelling
       ;;grammar           ; tasing grammar mistake every you make

       :tools
       ;;ansible
       ;;biblio            ; Writes a PhD for you (citation needed)
       ;;debugger          ; FIXME stepping through code, to help you add bugs
       ;;direnv
       ;;docker
       ;;editorconfig      ; let someone else argue about tabs vs spaces
       ;;ein               ; tame Jupyter notebooks with emacs
       (eval +overlay)     ; run code, run (also, repls)
       ;;gist              ; interacting with github gists
       lookup              ; navigate your code and its documentation
       lsp                 ; M-x vscode
       magit               ; a git porcelain for Emacs
       ;;make              ; run make tasks from Emacs
       ;;pass              ; password manager for nerds
       pdf                 ; pdf enhancements
       ;;prodigy           ; FIXME managing external services & code builders
       ;;rgb               ; creating color strings
       ;;taskrunner        ; taskrunner for all your projects
       ;;terraform         ; infrastructure as code
       ;;tmux              ; an API for interacting with tmux
       tree-sitter         ; syntax and parsing, sitting in a tree...
       ;;upload            ; map local to remote projects via ssh/ftp

       :os
       (:if IS-MAC macos)  ; improve compatibility with macOS
       tty                 ; improve the terminal Emacs experience

       :lang
       ;;agda              ; types of types of types of types...
       ;;beancount         ; mind the GAAP
       (cc +lsp)           ; C > C++ == 1
       ;;clojure           ; java with a lisp
       ;;common-lisp       ; if you've seen one lisp, you've seen them all
       ;;coq               ; proofs-as-programs
       ;;crystal           ; ruby at the speed of c
       ;;csharp            ; unity, .NET, and mono shenanigans
       ;;data              ; config/data formats
       ;;(dart +flutter)   ; paint ui and not much else
       ;;dhall
       ;;elixir            ; erlang done right
       ;;elm               ; care for a cup of TEA?
       emacs-lisp          ; drown in parentheses
       ;;erlang            ; an elegant language for a more civilized age
       ;;ess               ; emacs speaks statistics
       ;;factor
       ;;faust             ; dsp, but you get to keep your soul
       ;;fortran           ; in FORTRAN, GOD is REAL (unless declared INTEGER)
       ;;fsharp            ; ML stands for Microsoft's Language
       ;;fstar             ; (dependent) types and (monadic) effects and Z3
       ;;gdscript          ; the language you waited for
       ;;(go +lsp)         ; the hipster dialect
       ;;(graphql +lsp)    ; Give queries a REST
       ;;(haskell +lsp)    ; a language that's lazier than I am
       ;;hy                ; readability of scheme w/ speed of python
       ;;idris             ; a language you can depend on
       ;;json              ; At least it ain't XML
       ;;(java +lsp)       ; the poster child for carpal tunnel syndrome
       ;;javascript        ; all(hope(abandon(ye(who(enter(here))))))
       ;;julia             ; a better, faster MATLAB
       ;;kotlin            ; a better, slicker Java(Script)
       (latex              ; writing papers in Emacs has never been so fun
        +cdlatex           ; Enable cdlatex for fast math insertion
        +fold              ; Use TeX-fold to fold LaTeX macros to unicode
        +latexmk)          ; Use laexMk instead of Latex to compile documents
       ;;lean              ; for folks with too much to prove
       ;;ledger            ; be audit you can be
       ;;lua               ; one-based indices? one-based indices
       markdown            ; writing docs for people to ignore
       ;;nim               ; python + lisp at the speed of c
       ;;nix               ; I hereby declare "nix geht mehr!"
       ;;ocaml             ; an objective camel
       (org                ; organize your plain life in plain text
        +noter
        +dragndrop
        +roam2
        +gnuplot)
       ;;php               ; perl's insecure younger brother
       plantuml            ; diagrams for confusing people more
       ;;purescript        ; javascript, but functional
       ;;python            ; beautiful is better than ugly
       ;;qt                ; the 'cutest' gui framework ever
       ;;racket            ; a DSL for DSLs
       ;;raku              ; the artist formerly known as perl6
       ;;rest              ; Emacs as a REST client
       ;;rst               ; ReST in peace
       ;;(ruby +rails)     ; 1.step {|i| p "Ruby is #{i.even? ? 'love' : 'life'}"}
       ;;(rust +lsp)       ; Fe2O3.unwrap().unwrap().unwrap().unwrap()
       ;;scala             ; java, but good
       ;;(scheme +guile)   ; a fully conniving family of lisps
       sh                  ; she sells {ba,z,fi}sh shells on the C xor
       ;;sml
       ;;solidity          ; do you need a blockchain? No.
       ;;swift             ; who asked for emoji variables?
       ;;terra             ; Earth and Moon in alignment for performance.
       ;;web               ; the tubes
       ;;yaml              ; JSON, but readable
       ;;zig               ; C, but simpler

       :email
       ;;(mu4e +org +gmail)
       ;;notmuch
       ;;(wanderlust +gmail)

       :app
       ;;calendar
       ;;emms
       ;;everywhere        ; *leave* Emacs!? You must be joking
       ;;irc               ; how neckbeards socialize
       ;;(rss +org)        ; emacs as an RSS reader
       ;;twitter           ; twitter client https://twitter.com/vnought

       :config
       literate
       (default +bindings +smartparens))
#+end_src
#+html:</details>

** Variables
*** TODO Personal Information

Define an identity for use with GPG, email, and file templates/snippets.

#+begin_src emacs-lisp
(setq user-full-name "Jake Turner"
      user-mail-address "john@doe.com")
#+end_src

** Appearance
*** Theme

I typically use the [[https://draculatheme.com/][Dracula]] theme, but I'm experimenting with others:

- Doom One
- Doom Vibrant
- Doom Iosvkem
- Doom Dracula
- Doom Palenight
- Doom Ayu-Mirage and Doom Ayu-Dark
- Doom Horizon
- Doom Material
- Doom Oceanic Next
- Doom Xcode

#+begin_src emacs-lisp
(setq doom-theme 'doom-dracula
      doom-dracula-brighter-modeline t
      doom-dracula-colorful-headers t)
#+end_src

*** Font

I'm also experimenting with fonts. Although, Jetbrains Mono and Fira Code are staples.

#+begin_src emacs-lisp
(when IS-MAC
  (setq doom-font (font-spec :family "Jetbrains Mono" :size 12)
        doom-big-font (font-spec :family "Jetbrains Mono" :size 16)
        doom-variable-pitch-font (font-spec :family "Overpass" :size 14)
        doom-unicode-font (font-spec :family "JuliaMono")
        doom-serif-font (font-spec :family "IBM Plex Mono" :size 10 :weight 'light)))
#+end_src

#+begin_src emacs-lisp
(when IS-LINUX
  (setq doom-font (font-spec :family "Jetbrains Mono" :size 12)
        doom-big-font (font-spec :family "Jetbrains Mono" :size 16)
        ;;doom-variable-pitch-font (font-spec :family "Overpass" :size 14)
        ;;doom-unicode-font (font-spec :family "JuliaMono")
        ;;doom-serif-font (font-spec :family "IBM Plex Mono" :size 10 :weight 'light)
        ))
#+end_src

*** Cursor

Draw the block cursor as wide as the glyph under it.

#+begin_src emacs-lisp
(setq-default x-stretch-cursor t)
#+end_src

*** Frames
**** Add Transparency

I add transparency to Doom's window to allow my wallpaper to show through it.

On Linux, this effect probably requires a compositor. I use [[https://github.com/yshui/picom][Picom]].

#+begin_src emacs-lisp
(add-to-list 'default-frame-alist '(alpha . 93)) ; [0-100]
#+end_src

**** Start Maximized

#+begin_src emacs-lisp
(add-to-list 'default-frame-alist '(fullscreen . maximized))
#+end_src

*** Line Numbers

I use relative visual line numbers to move around.

#+begin_src emacs-lisp
(setq display-line-numbers-type 'visual)
#+end_src

** Behavior
*** Scrolling

This is an area of contention for me. Eventually I would like to overhaul this behavior entirely.

**** Set Scroll Amount

#+begin_src emacs-lisp
(setq-default evil-scroll-count 5)
#+end_src

*** Autoload File Changes

#+begin_src emacs-lisp
(global-auto-revert-mode 1)
#+end_src

*** Enable Subword Mode

Allows iterating through CamelCase words.

#+begin_src emacs-lisp
(global-subword-mode 1)
#+end_src

*** TODO Enable Evil Fine Undo
:LOGBOOK:
- State "TODO"       from              [2023-04-21 Fri 17:03]
:END:

By default, all changes made while using insert mode are considered one. This setting enables a more granular undo scheme.

#+begin_src emacs-lisp
(setq evil-want-fine-undo t)
#+end_src

*** TODO Focus Windows After Splitting
:LOGBOOK:
- State "TODO"       from              [2023-04-21 Fri 17:03]
:END:

These settings causes the newly created split windows to gain focus.

#+begin_src emacs-lisp
(setq evil-split-window-below t
      evil-vsplit-window-right t)
#+end_src

*** Window Manager Integration

I love tiling window managers. I currently use [[https://i3wm.org][i3]] on Linux and [[https://github.com/koekeishiya/yabai][Yabai]] on macOS. These configs allow me to seamlessly use some of their windowing controls inside of Emacs.

**** How It Works

This method requires some way for your window manager to pass the keybinds to Emacs whenever it's the focused window. Then, you just bind those keys in Emacs to the windowing functions defined here.

=NOTE=: i3 requires the use of a [[https://github.com/noncog/.dotfiles/blob/main/.config/i3/scripts/i3-emacs-mode.pl][script]] and a dedicated Emacs mode to know when Emacs is the focused window and change use different keybinds. Yabai supports this natively.

**** Functions

When a window can't be found in that direction in Emacs, it passes the window focusing command to the window manager.

#+begin_src emacs-lisp
(defun wm-focus-on-error (direction move-fn)
    (when IS-LINUX
     (condition-case nil (funcall move-fn)
       (user-error (start-process "wm" nil "i3-msg" "focus" direction))))
     (when IS-MAC
      (condition-case nil (funcall move-fn)
        (user-error (start-process "wm" nil "yabai" "-m" "window" "--focus" direction)))))
#+end_src

#+begin_src emacs-lisp
(defun wm-window-left ()
  (interactive)
  (let ((direction (cond (IS-LINUX "left") (IS-MAC "west"))))
    (wm-focus-on-error direction #'windmove-left)))

(defun wm-window-right ()
  (interactive)
  (let ((direction (cond (IS-LINUX "right") (IS-MAC "east"))))
    (wm-focus-on-error direction #'windmove-right)))

(defun wm-window-up ()
  (interactive)
  (let ((direction (cond (IS-LINUX "up") (IS-MAC "north"))))
    (wm-focus-on-error direction #'windmove-up)))

(defun wm-window-down ()
  (interactive)
  (let ((direction (cond (IS-LINUX "down") (IS-MAC "south"))))
    (wm-focus-on-error direction #'windmove-down)))
#+end_src

**** Keybinds
***** macOS

#+begin_src emacs-lisp
(when IS-MAC
  (map! "s-h" #'wm-window-left)
  (map! "s-j" #'wm-window-down)
  (map! "s-k" #'wm-window-up)
  (map! "s-l" #'wm-window-right)
  (map! "s-=" #'balance-windows)
  (map! "s-Q" #'evil-quit))
#+end_src

***** Linux

#+begin_src emacs-lisp
(when IS-LINUX
  (map! "s-h" #'wm-window-left)
  (map! "s-j" #'wm-window-down)
  (map! "s-k" #'wm-window-up)
  (map! "s-l" #'wm-window-right)
  (map! "s-Q" #'evil-quit))
#+end_src

***** Emacs to Other Windows

These binds allow you to use Doom's window switching commands to focus windows outside of Emacs.

#+begin_src emacs-lisp
(map! :leader "w h" #'wm-window-left)
(map! :leader "w j" #'wm-window-down)
(map! :leader "w k" #'wm-window-up)
(map! :leader "w l" #'wm-window-right)
#+end_src

** Keybinds
*** Mac Modifier Keys

I translate the Mac modifier keys to be equivalent to my Linux/Windows modifiers.

#+begin_src emacs-lisp
(when IS-MAC (setq mac-command-modifier 'control ; Maps Command -> Control
                    mac-control-modifier 'meta   ; Maps Control -> Alt (Meta)
                    mac-option-modifier 'super)) ; Maps Option -> Super
#+end_src

* Org

#+begin_quote
[[https://orgmode.org/][Org Mode]] describes itself as, "a GNU Emacs major mode for keeping notes, authoring documents, computational notebooks, literate programming, maintaining to-do lists, planning projects, and more — in a fast and effective plain text system."
#+end_quote

#+begin_src emacs-lisp :exports none :noweb no-export
<<pre-org>>
(after! org
  <<org-config>>
  )
#+end_src

** Variables
*** Org Directory

#+begin_src emacs-lisp :tangle no :noweb-ref pre-org
(setq org-directory "~/Projects/exocortex/")
#+end_src

*** Refile Targets

#+begin_src emacs-lisp :tangle no :noweb-ref pre-org
(setq org-refile-targets
      '(("~/Projects/exocortex/nodes/calendar.org" :maxlevel . 3)))
#+end_src

*** Keywords

I have excess keywords and will likely simplify them when I decide their best use.

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(setq org-todo-keywords
      '((sequence
         "TODO(t!)"    ; A task that needs doing & is ready to do.
         "NEXT(n!)"    ; A task that needs doing & is ready to do.
         "STRT(s!)"    ; A task that is in progress.
         "WAIT(w@/!)"  ; Something external is holding up this task.
         "HOLD(h@/!)"  ; This task is paused/on hold because of me.
         "PROJ(p!)"    ; A project, which usually contains other tasks.
         "IDEA(i!)"    ; An unconfirmed and unapproved task or notion.
         "NOTE(N!)"    ; A fleeting note, in person, idea, link, anything.
         "APPT(a!)"    ; An appointment.
         "MEET(m!)"    ; A meeting.
         "READ(r!)"    ; Something to read.
         "LINK(l!)"    ; A link I want to note.
         "|"           ; Marker signifying remaining are a "completed" states.
         "DONE(d!)"    ; Task successfully completed.
         "KILL(k@/!)") ; Task was cancelled, aborted or is no longer applicable.
        (sequence      ; For nesting headings like lists.
         "[ ](T)"      ; A task that needs doing.
         "[-](S!)"     ; Task is in progress.
         "[?](W@/!)"   ; Task is being held up or paused.
         "|"
         "[X](D)"))    ; Task was completed.
      org-todo-keyword-faces
      '(("[-]"  . +org-todo-active)
        ("STRT" . +org-todo-active)
        ("NOTE" . +org-todo-active)
        ("[?]"  . +org-todo-onhold)
        ("WAIT" . +org-todo-onhold)
        ("HOLD" . +org-todo-onhold)
        ("PROJ" . +org-todo-project)
        ("KILL" . +org-todo-cancel)))
#+end_src

** Appearance
*** General

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(setq org-hide-emphasis-markers t     ; Hide syntax for emphasis markup. See org-appear.
      org-pretty-entities nil         ; Show entities like sub/superscript as UTF8.
      org-src-preserve-indentation t) ; Prevents changes to whitespace in source blocks.
#+end_src

*** Headings

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(setq org-ellipsis " ▾ "              ; Use a custom ellipsis for folded headings.
      org-hide-leading-stars t        ; Remove excess heading stars.
      org-hidden-keywords nil)        ; Can use to hide certain keywords.
#+end_src

*** LaTeX Previews

Show rendered LaTeX within the org buffer.

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(setq org-startup-with-latex-preview nil)
#+end_src

*** LaTeX Syntax Highlighting

Add syntax highlighting to LaTeX in orgmode buffers. [[https://github.com/tecosaur/emacs-config/blob/master/config.org#prettier-highlighting][Source]].

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(setq org-highlight-latex-and-related '(native script entities))
#+end_src

Unfortunately, when using =native= highlighting the =org-block= face is used as the background color. Remove it using:

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(add-to-list 'org-src-block-faces '("latex" (:inherit default :extend t)))
#+end_src

*** Images

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(setq org-image-actual-width '(0.9)           ; Use an in-buffer width closer to export's
      org-startup-with-inline-images t)       ; Show images at startup.
#+end_src

** Behavior
*** General

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(setq org-imenu-depth 10                     ; Allow imenu to search deeply in org docs.
      org-fold-core-style 'overlays          ; Bugfix: Hide IDs in org-roam backlinks.
      org-use-property-inheritance t         ; Sub-headings inherit parent properties.
      org-insert-heading-respect-content nil ; Insert heading here, not at end of list.
      org-use-fast-todo-selection 'auto)     ; Method to select TODO heading keywords.
#+end_src

*** Logging

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(setq org-log-done 'time                     ; Add completion time to DONE items.
      org-log-into-drawer t                  ; Log times into a drawer to hide them.
      org-log-states-order-reversed nil)     ; Log state changes chronologically.
#+end_src

*** Lists

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(setq org-list-allow-alphabetical t)         ; Enable use of alphabet as list bullets.
#+end_src

*** Links

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(setq org-return-follows-link t)             ; Pressing enter opens links.
#+end_src

*** Calendar

Enable Evil bindings in org's calendar.

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(setq evil-collection-calendar-want-org-bindings t)
#+end_src

*** Habits

The =org-habit= module enables repeated task tracking in the agenda!

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(add-to-list 'org-modules 'org-habit t)
#+end_src

* Org Agenda

#+begin_quote
Org Agenda collects, creates, and displays an overview of actionable tasks your org files.
#+end_quote

#+begin_src emacs-lisp :exports none :noweb no-export
<<pre-org-agenda>>
(after! org-agenda
  <<org-agenda-config>>
  )
#+end_src

** Variables
*** Agenda Files

#+begin_src emacs-lisp :tangle no :noweb-ref pre-org-agenda
(setq org-agenda-files (list
                        "~/Projects/exocortex/nodes/calendar.org"))
#+end_src

** Appearance
*** Habits

#+begin_src emacs-lisp :tangle no :noweb-ref org-agenda-config
(setq org-habit-show-habits-only-for-today t ; Only show habits in one section.
      org-habit-show-all-today t)            ; Keep habits visible even if done.
#+end_src

#+begin_src emacs-lisp :tangle no :exports none :noweb-ref org-agenda-config
;(setq +org-habit-min-width)
;(setq +org-habit-graph-padding)
;(setq +org-habit-graph-window-ratio)
;(setq org-habit-graph-column)
;(setq org-habit-today-glyph)
;(setq org-habit-completed-glyph)
;(setq org-habit-show-done-always-green)
#+end_src

*** Section Title Face

Make agenda section titles slightly more bold.

#+begin_src emacs-lisp :tangle no :noweb-ref org-agenda-config
(custom-set-faces!
  '(org-agenda-structure
    :height 1.3 :weight bold))
#+end_src

*** Remove Empty Agenda Sections

If one of my agenda blocks has no information, I don't want to see it.

#+begin_src emacs-lisp :tangle no :noweb-ref org-agenda-config
(defun noncog/agenda-remove-empty ()
  "A simple function to remove empty agenda sections. Scans for blank lines.
Blank sections defined by having two consecutive blank lines.
Not compatible with the block separator."
  (interactive)
  (setq buffer-read-only nil)
  ;; initializes variables and scans first line.
  (goto-char (point-min))
  (let* ((agenda-blank-line "[[:blank:]]*$")
         (content-line-count (if (looking-at-p agenda-blank-line) 0 1))
         (content-blank-line-count (if (looking-at-p agenda-blank-line) 1 0))
         (start-pos (point)))
    ;; step until the end of the buffer
    (while (not (eobp))
      (forward-line 1)
       (cond
        ;; delete region if previously found two blank lines
        ((when (> content-blank-line-count 1)
          (delete-region start-pos (point))
          (setq content-blank-line-count 0)
          (setq start-pos (point))))
        ;; if found a non-blank line
        ((not (looking-at-p agenda-blank-line))
         (setq content-line-count (1+ content-line-count))
         (setq start-pos (point))
         (setq content-blank-line-count 0))
        ;; if found a blank line
        ((looking-at-p agenda-blank-line)
         (setq content-blank-line-count (1+ content-blank-line-count)))))
    ;; final blank line check at end of file
    (when (> content-blank-line-count 1)
      (delete-region start-pos (point))
      (setq content-blank-line-count 0)))
  ;; return to top and finish
  (goto-char (point-min))
  (setq buffer-read-only t)
)
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref org-agenda-config
(add-hook! 'org-agenda-finalize-hook #'noncog/agenda-remove-empty)
#+end_src

*** Agenda Popup Window

I use Doom's popup window rules to create a dedicated agenda window on the right side.

I use a custom width variable to ensure the formatting as I can't trust auto-align.

#+begin_src emacs-lisp :tangle no :noweb-ref pre-org-agenda
(setq noncog/agenda-width 70)
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref pre-org-agenda
(set-popup-rule! "^*Org Agenda*" :side 'right :vslot 1 :width noncog/agenda-width :modeline nil :select t :quit t)
#+end_src

*** Tags Column

#+begin_src emacs-lisp :tangle no :noweb-ref org-agenda-config
(setq org-agenda-tags-column (+ 10 (* -1 noncog/agenda-width)))
#+end_src

*** My Custom Agenda

#+begin_src emacs-lisp :tangle no :noweb-ref org-agenda-config
(setq org-agenda-custom-commands
      '(
        ("o" "My Agenda" (
         (agenda
          ""
          ( ;; Today
           ;(org-agenda-overriding-header "Today\n")
           (org-agenda-overriding-header " Agenda\n")
           (org-agenda-day-face-function (lambda (date) 'org-agenda-date))
           (org-agenda-block-separator nil)
           (org-agenda-format-date " %a, %b %-e %y")  ; american date format
           (org-agenda-start-on-weekday nil)          ; start today
           (org-agenda-start-day nil)                 ; don't show previous days
           (org-agenda-span 1)                        ; only show today
           (org-scheduled-past-days 0)                ; don't show overdue
           (org-deadline-warning-days 0)              ; don't show deadlines for the future
           (org-agenda-time-leading-zero t)           ; unify times formatting
           (org-agenda-remove-tags t)
           (org-agenda-time-grid '((today remove-match) (800 1000 1200 1400 1600 1800 2000 2200) "" ""))
           ;(org-agenda-todo-keyword-format "%-4s")
           (org-agenda-prefix-format '((agenda . " %8:c %-5t ")))
           (org-agenda-dim-blocked-tasks nil)
           (org-agenda-skip-function '(noncog/skip-tag "inbox"))
           (org-agenda-entry-types '(:timestamp :deadline :scheduled))
           ))
         (agenda
          ""
          ( ;; Next Three Days
           ;(org-agenda-overriding-header "\nNext Three Days\n")
           (org-agenda-overriding-header "")
           (org-agenda-day-face-function (lambda (date) 'org-agenda-date))
           (org-agenda-block-separator nil)
           (org-agenda-format-date " %a %b %-e")
           (org-agenda-start-on-weekday nil)
           (org-agenda-start-day "+1d")
           (org-agenda-span 3)
           (org-scheduled-past-days 0)
           (org-deadline-warning-days 0)
           (org-agenda-time-leading-zero t)
           (org-agenda-skip-function '(or (noncog/skip-tag "inbox") (org-agenda-skip-entry-if 'todo '("DONE" "KILL"))))
           (org-agenda-entry-types '(:deadline :scheduled))
           (org-agenda-time-grid '((daily weekly) () "" ""))
           (org-agenda-prefix-format '((agenda . "  %?-9:c%t ")))
           ;(org-agenda-todo-keyword-format "%-4s")
           (org-agenda-dim-blocked-tasks nil)
           ))
         (agenda
          ""
          ( ;; Upcoming Deadlines
           (org-agenda-overriding-header "\n Coming Up\n")
           (org-agenda-day-face-function (lambda (date) 'org-agenda-date))
           (org-agenda-block-separator nil)
           (org-agenda-format-date " %a %b %-e")
           (org-agenda-start-on-weekday nil)
           (org-agenda-start-day "+4d")
           (org-agenda-span 14)
           (org-scheduled-past-days 0)
           (org-deadline-warning-days 0)
           (org-agenda-time-leading-zero t)
           (org-agenda-time-grid nil)
           (org-agenda-prefix-format '((agenda . "  %?-5t %?-9:c")))
           ;(org-agenda-todo-keyword-format "%-4s")
           (org-agenda-skip-function '(or (noncog/skip-tag "inbox") (org-agenda-skip-entry-if 'todo '("DONE" "KILL"))))
           (org-agenda-entry-types '(:deadline :scheduled))
           (org-agenda-show-all-dates nil)
           (org-agenda-dim-blocked-tasks nil)
           ))
         (agenda
          ""
          ( ;; Past Due
           (org-agenda-overriding-header "\n Past Due\n")
           (org-agenda-day-face-function (lambda (date) 'org-agenda-date))
           (org-agenda-block-separator nil)
           (org-agenda-format-date "%a %b %-e")
           (org-agenda-start-on-weekday nil)
           (org-agenda-start-day "-60d")
           (org-agenda-span 60)
           (org-scheduled-past-days 60)
           (org-deadline-past-days 60)
           (org-deadline-warning-days 0)
           (org-agenda-time-leading-zero t)
           (org-agenda-time-grid nil)
           (org-agenda-prefix-format '((agenda . "  %?-9:c%t ")))
           ;(org-agenda-todo-keyword-format "%-4s")
           (org-agenda-skip-function '(or (noncog/skip-tag "inbox") (org-agenda-skip-entry-if 'todo '("DONE" "KILL"))))
           (org-agenda-entry-types '(:deadline :scheduled))
           (org-agenda-show-all-dates nil)
           (org-agenda-dim-blocked-tasks nil)
           ))
         (todo
          ""
          ( ;; Important Tasks No Date
           (org-agenda-overriding-header "\n Important Tasks - No Date\n")
           (org-agenda-block-separator nil)
           (org-agenda-skip-function '(org-agenda-skip-entry-if 'timestamp 'notregexp "\\[\\#A\\]"))
           (org-agenda-block-separator nil)
           (org-agenda-time-grid nil)
           (org-agenda-prefix-format '((todo . "  %?:c ")))
           ;(org-agenda-todo-keyword-format "%-4s")
           (org-agenda-dim-blocked-tasks nil)
           ))
         (todo
          ""
          ( ;; Next
           (org-agenda-overriding-header "\n Next\n")
           (org-agenda-block-separator nil)
           (org-agenda-skip-function '(org-agenda-skip-entry-if 'nottodo '("NEXT" "STRT")))
           (org-agenda-block-separator nil)
           (org-agenda-time-grid nil)
           (org-agenda-prefix-format '((todo . "  %?:c ")))
           ;(org-agenda-todo-keyword-format "%-4s")
           (org-agenda-dim-blocked-tasks nil)
           ))
         (tags-todo
          "inbox"
          ( ;; Inbox
           (org-agenda-overriding-header (propertize "\n Inbox\n" 'help-echo "Effort: 'c e' Refile: 'SPC m r'")) ; Ads mouse hover tooltip.
           ;(org-agenda-remove-tags t)
           (org-agenda-block-separator nil)
           (org-agenda-prefix-format "  %?-4e ")
           ;(org-agenda-todo-keyword-format "%-4s")
           ))
         ))))
#+end_src

** Behavior
*** Logging

#+begin_src emacs-lisp :tangle no :noweb-ref org-agenda-config
(setq org-agenda-start-with-log-mode t)      ; Show 'completed' items in agenda.
#+end_src

** Keybinds
*** My Custom Agenda Launcher

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(defun noncog/my-agenda ()
  "My custom agenda launcher."
  (interactive)
  (org-agenda nil "o"))
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(map! :leader :desc "My agenda" "o a o" #'noncog/my-agenda)
#+end_src

** Fixes and Helpers
*** Tag Finding Helper Functions

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(defun noncog/skip-tag (tag)
  "Skip trees with this tag."
  (let* ((next-headline (save-excursion (or (outline-next-heading) (point-max))))
         (current-headline (or (and (org-at-heading-p) (point))
                               (save-excursion (org-back-to-heading)))))
    (if (member tag (org-get-tags current-headline))
        next-headline nil)))
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(defun noncog/skip-all-but-this-tag (tag)
  "Skip trees that are not this tag."
  (let ((subtree-end (save-excursion (org-end-of-subtree t))))
    (if (re-search-forward (concat ":" tag ":") subtree-end t)
        nil          ; tag found, do not skip
      subtree-end))) ; tag not found, continue after end of subtree
#+end_src

* Org Capture

#+begin_quote
Org Capture lets you quickly insert into your org documents.
#+end_quote

#+begin_src emacs-lisp :exports none :noweb no-export
(after! org-capture
  <<org-capture-config>>
  )
#+end_src

** Variables
*** Capture Templates

I'm currently only using one template that sends all captured headings to an inbox. This increases speed by capturing now and organizing later.

#+begin_src emacs-lisp :tangle no :noweb-ref org-capture-config
(setq org-capture-templates
      `(("i" "Inbox" entry
         (file+headline "inbox.org" "Inbox")
         "* %?\n%i\n" :prepend t)))
#+end_src

** Behavior
*** Don't Add to Bookmarks

#+begin_src emacs-lisp :tangle no :noweb-ref org-capture-config
(setq org-capture-bookmark nil)
#+end_src

** Keybinds
*** Switch Doom's Default Capture Binds

I switch Doom's default scratch buffer and org-capture keybinds.

With this, I can quickly capture something with =SPC x=.

#+begin_src emacs-lisp :tangle no :noweb-ref org-capture-config
(map! :leader :desc "Org capture" "x" #'org-capture
      :leader :desc "Pop up scratch buffer" "X" #'doom/open-scratch-buffer)
#+end_src

** Fixes
*** Fix Org Capture Window Breaking

Sometimes the capture window breaks when the agenda or agenda files are already open. This fix reloads org-mode during captures. [[https://github.com/doomemacs/doomemacs/issues/5714][Source]]

#+begin_src emacs-lisp :tangle no :noweb-ref org-capture-config
(defadvice! my/+org--restart-mode-h-careful-restart (fn &rest args)
  :around #'+org--restart-mode-h
  (let ((old-org-capture-current-plist
         (and (bound-and-true-p org-capture-mode)
              (bound-and-true-p org-capture-current-plist))))
    (apply fn args)
    (when old-org-capture-current-plist
      (setq-local org-capture-current-plist old-org-capture-current-plist)
      (org-capture-mode +1))))
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref org-capture-config
(add-hook! 'org-capture-after-finalize-hook (org-element-cache-reset t))
#+end_src

* Org Roam

#+begin_quote
[[https://github.com/org-roam/org-roam][Org Roam]] is a plain-text knowledge management system. It provides a solution for non-hierarchical note-taking and linking.
#+end_quote

#+begin_src emacs-lisp :exports none :noweb no-export
<<pre-org-roam>>
(use-package! org-roam
  :config
  <<org-roam-config>>
  )
#+end_src

** Variables
*** Roam Directory

#+begin_src emacs-lisp :tangle no :noweb-ref pre-org-roam
(setq org-roam-directory (file-truename "~/Projects/exocortex"))
#+end_src

*** Database Location

#+begin_src emacs-lisp :tangle no :noweb-ref pre-org-roam
(setq org-roam-db-location (file-truename "~/Projects/exocortex/exocortex.db"))
#+end_src

*** Attachments Directory

#+begin_src emacs-lisp :tangle no :noweb-ref pre-org-roam
(setq org-attach-id-dir (file-truename "~/Projects/exocortex/attachments"))
#+end_src

*** Exclude Directories

Currently not excluding any. This is a place holder for when I do.

#+begin_src emacs-lisp :tangle no :noweb-ref pre-org-roam
;(setq org-roam-file-exclude-regexp (rx (or "data/" "inbox.org")) )
#+end_src

** Behavior
*** Disable If No Roam Directory

Don't use Org Roam if the directory isn't present to avoid errors.

See [[file:config.el][config.el]] to understand how this works. Thanks Teco.

#+begin_src emacs-lisp :tangle (if (file-exists-p "~/Projects/exocortex") "no" "packages.el")
(package! org-roam :disable t)
#+end_src

*** Capture Templates

Currently just using the default captures template. This area still needs a lot of work. I need to decide how to use roam-capture and org-capture.

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-config
(setq org-roam-capture-templates
      '(("d" "default" plain
         "%?"
         :target
         (file+head "nodes/${slug}.org"
                    "#+title: ${title}\n#+filetags: :draft:\n")
         :immediate-finish t
         :unnarrowed t)))
#+end_src

*** Enable Autosync

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-config
(org-roam-db-autosync-mode)
#+end_src

** Keybinds
*** Find Random Draft Nodes

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-config
(defun noncog/org-roam-is-draft-p (node)
  "Is this org-roam node a draft?"
  (member "draft" (org-roam-node-tags node)))
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-config
(defun noncog/org-roam-random-draft ()
  "Get a random node with the draft tag. "
  (interactive)
  (org-roam-node-random nil #'noncog/org-roam-is-draft-p))
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-config
(map! :leader :desc "Random draft node" "n r u" #'noncog/org-roam-random-draft)
#+end_src

* Org Roam UI

#+begin_quote
[[https://github.com/org-roam/org-roam-ui][org-roam-ui]] is a frontend for exploring and interacting with your org-roam notes.
#+end_quote

#+begin_src emacs-lisp :tangle packages.el
(unpin! org-roam) ; NOTE: Requires latest org-roam.
(package! org-roam-ui
  :recipe (:host github :repo "org-roam/org-roam-ui"))
#+end_src

#+begin_src emacs-lisp :exports none :noweb no-export
(use-package! websocket
    :after org-roam)

(use-package! org-roam-ui
  :after org-roam
  :hook (org-roam . org-roam-ui-mode)
  :config
  <<org-roam-ui-config>>
  )
#+end_src

** Appearance
*** Theme

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-ui-config
(setq org-roam-ui-sync-theme t)
#+end_src

*** Window

#+begin_src emacs-lisp
(set-popup-rule! "^*xwidget" :ignore t :side 'left :width 120 :vslot 1 :quit t :select t :modeline nil)
#+end_src

** Behavior
*** General

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-ui-config
(setq org-roam-ui-follow t
      org-roam-ui-update-on-save t)
#+end_src

*** Use Xwidgets Instead of Browsers

These functions enables you to open the graph within Emacs instead of an external browser. [[https://github.com/org-roam/org-roam-ui/issues/52#issuecomment-912246556][Source]]

#+begin_src emacs-lisp
(defcustom org-roam-ui-use-webkit t
  "Use embedded webkit to preview.
This requires GNU/Emacs version >= 26 and built with the `--with-xwidgets`
option."
  :type 'boolean
  :group 'roam)

(defun org-roam-ui-browser (url)
  "Use browser specified by user to load URL.
Use default browser if nil."
  (if org-roam-ui-url-browser
      (let ((browse-url-generic-program org-roam-ui-url-browser)
            (browse-url-generic-args roam-url-args))
        (ignore browse-url-generic-program)
        (ignore browse-url-generic-args)
        (browse-url-generic url))
    (browse-url url)))

(defun org-roam-ui-open-url (url)
  "Ask the browser to load URL.
Use default browser unless `xwidget' is available."
  (if (and org-roam-ui-use-webkit
           (featurep 'xwidget-internal))
      (progn
        (save-window-excursion (xwidget-webkit-browse-url url))
        (let ((buf (xwidget-buffer (xwidget-webkit-current-session))))
          (when (buffer-live-p buf) (and (eq buf (current-buffer)) (quit-window)))
          (display-buffer buf)))
            (let (display-buffer-alist) (org-roam-ui-browser url))))
#+end_src

#+begin_src emacs-lisp
;;;###autoload
(define-minor-mode org-roam-ui-open-in-browser
  "open org-roam-ui in the browser"
 :lighter "roam"
 (org-roam-ui-open-url "http://127.0.0.1:35901"))
#+end_src

Don't open the graph using a browser since we use Emacs.

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-ui-config
(setq org-roam-ui-open-on-start nil)
#+end_src

** Keybinds
*** Replace Doom's Default Org Roam Graph Keybinds

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-ui-config
(map! :leader :desc "Roam-UI graph" "n r g" #'org-roam-ui-open-in-browser)
#+end_src

* Org Modern

#+begin_quote
[[https://github.com/minad/org-modern][Org Modern]] implements a “modern” style for your Org buffers using font locking and text properties.
#+end_quote

#+begin_src emacs-lisp :tangle packages.el
(package! org-modern
  :pin "b614ad31d72c49f9eb29d3836995fd7fb0d1fd4a")
#+end_src

#+begin_src emacs-lisp :exports none :noweb no-export
(use-package! org-modern
  :hook (org-mode . org-modern-mode)
  :config
  <<org-modern-config>>
  )
#+end_src

** Appearance
*** General

These settings will need sorted into their own headings eventually.

#+begin_src emacs-lisp :tangle no :noweb-ref org-modern-config
(setq org-modern-hide-stars nil              ; Let Org handle hiding the stars.
      org-modern-table-vertical 1            ; Use thinner lines than default.
      org-modern-table-horizontal 0.2        ; Unify line thickness with vertical line.
      org-modern-progress nil                ; Use default progress face.
      org-modern-priority nil                ; Use default priority face.
      org-modern-todo-faces                  ; Inherit Doom's Org faces.
      '(("TODO" :inverse-video t :inherit org-todo)
        ("PROJ" :inverse-video t :inherit +org-todo-project)
        ("STRT" :inverse-video t :inherit +org-todo-active)
        ("[-]"  :inverse-video t :inherit +org-todo-active)
        ("HOLD" :inverse-video t :inherit +org-todo-onhold)
        ("WAIT" :inverse-video t :inherit +org-todo-onhold)
        ("[?]"  :inverse-video t :inherit +org-todo-onhold)
        ("KILL" :inverse-video t :inherit +org-todo-cancel)
        ("NO"   :inverse-video t :inherit +org-todo-cancel))
      org-modern-star '("◉" "○" "✸" "✿" "✤" "✜" "◆" "▶")
      org-modern-horizontal-rule (make-string 80 ?─)
      )
#+end_src

* Org Modern Indent

#+begin_quote
[[https://github.com/jdtsmith/org-modern-indent][Org-modern-indent]] adds back the source block "bracket" to org-modern, which is normally broken by the use of indentation.
#+end_quote

#+begin_src emacs-lisp :tangle packages.el
(package! org-modern-indent
  :recipe (:host github :repo "jdtsmith/org-modern-indent")
  :pin "c5a50f302dc1053d5b498e0ea2bc0ee233e8e1b8")
#+end_src

#+begin_src emacs-lisp
(use-package! org-modern-indent
  :config ; add late to hook
  (add-hook 'org-mode-hook #'org-modern-indent-mode 1))
#+end_src

* Org Appear

#+begin_quote
[[https://github.com/awth13/org-appear][Org Appear]] makes invisible Org elements like emphasis markers magically appear.
#+end_quote

#+begin_src emacs-lisp :tangle packages.el
(package! org-appear
  :recipe (:host github :repo "awth13/org-appear")
  :pin "eb9f9db40aa529fe4b977235d86494b115281d17")
#+end_src

#+begin_src emacs-lisp :exports none :noweb no-export
(use-package! org-appear
  :hook (org-mode . org-appear-mode)
  :config
  <<org-appear-config>>
  )
#+end_src

** Appearance
*** General

#+begin_src emacs-lisp :tangle no :noweb-ref org-appear-config
(setq org-appear-autoemphasis t              ; Show emphasis markup.
      org-appear-autosubmarkers t            ; Show sub/superscript
      org-appear-autoentities nil            ; Show LaTeX like Org pretty entities.
      org-appear-autolinks nil               ; Shows Org links.
      org-appear-autokeywords nil            ; Shows hidden Org keywords.
      org-appear-inside-latex nil)           ; Show LaTeX code. Use Fragtog instead.
#+end_src

* Org Fragtog

#+begin_quote
[[https://github.com/io12/org-fragtog][Org Fragtog]] toggles LaTeX fragments as the cursor enters and exits them. It's org-appear for LaTeX!
#+end_quote

#+begin_src emacs-lisp :tangle packages.el
(package! org-fragtog
  :pin "c675563af3f9ab5558cfd5ea460e2a07477b0cfd")
#+end_src

#+begin_src emacs-lisp
(use-package! org-fragtog
  :hook (org-mode . org-fragtog-mode))
#+end_src

* Ox (Org Export)

#+begin_quote
This built-in library implements a generic export engine for Org. It uses different backends to change the translation of org documents into various other formats.
#+end_quote

#+begin_src emacs-lisp :exports none :noweb no-export
(after! ox
  <<ox-config>>)
#+end_src

** Appearance
*** Creator String

I like to include this on my LaTeX exports to allude to the tools that I like to use.

#+begin_src emacs-lisp :tangle no :noweb-ref ox-config
(setq org-export-with-creator t
      org-export-creator-string (format "Doom Emacs %s (Org mode %s)" emacs-version org-version))
#+end_src

** Behavior
*** Ignore Headings but Keep Content in Exports

This setting allows you to use the =:ignore:= tag to remove a heading from an export but keep its contents.

#+begin_src emacs-lisp :tangle no :noweb-ref ox-config
(require 'ox-extra)
(ox-extras-activate '(ignore-headlines))
#+end_src

*** Export Depth

By default only the first three headings, including titles are exported. Five levels of depth seems like a reasonable value for LaTeX and HTML exports. Tecosaur reasoned that HTML5 has six heading levels but Org exports start at the second, leaving us with just five to use. It should also challenge/prevent me from overly nesting information.

#+begin_src emacs-lisp :tangle no :noweb-ref ox-config
(setq org-export-headline-levels 5)
#+end_src

** Keybinds
*** View Exported Org File

[[https://github.com/tecosaur/emacs-config/blob/master/config.org#view-exported-file][Tecosaur]] created a function and keybind to view the recently exported org-file.

#+begin_src emacs-lisp
(map! :map org-mode-map
      :localleader
      :desc "View exported file"
      "v" #'org-view-output-file)

(defun org-view-output-file (&optional org-file-path)
  "Visit buffer open on the first output file (if any),
found, using `org-view-output-file-extensions'."
  (interactive)
  (let* ((org-file-path (or org-file-path (buffer-file-name) ""))
         (dir (file-name-directory org-file-path))
         (basename (file-name-base org-file-path))
         (output-file nil))
    (dolist (ext org-view-output-file-extensions)
      (unless output-file
        (when (file-exists-p
               (concat dir basename "." ext))
          (setq output-file (concat dir basename "." ext)))))
    (if output-file
        (if (member (file-name-extension output-file) org-view-external-file-extensions)
            (browse-url-xdg-open output-file)
          (pop-to-buffer (or (find-buffer-visiting output-file)
                             (find-file-noselect output-file))))
      (message "No exported file found"))))

(defvar org-view-output-file-extensions '("pdf" "md" "rst" "txt" "tex" "html")
  "Find output files with these extensions, in order, viewing the first match.")
(defvar org-view-external-file-extensions '("html")
  "File formats that should be opened externally.")
#+end_src

* Ox Latex

This built-in library is the LaTeX backend for the Org Export Engine.

#+begin_src emacs-lisp :exports none :noweb no-export
(after! ox-latex
  <<ox-latex-init>>
  <<ox-latex-config>>
  )
#+end_src

** Appearance
*** Set Source Block Backend

This adds theming and syntax highlighting to our source blocks in latex exports.

#+begin_src emacs-lisp :tangle no :noweb-ref ox-latex-config
(setq org-latex-src-block-backend 'engraved)
#+end_src

*** Custom Document Class

#+begin_src emacs-lisp :tangle no :noweb-ref ox-latex-config
(add-to-list 'org-latex-classes
             '("notes"
               "\\documentclass{article}
                [NO-DEFAULT-PACKAGES]
                [PACKAGES]
                [EXTRA]"
               ("\\section{%s}" . "\\section*{%s}")
               ("\\subsection{%s}" . "\\subsection*{%s}")
               ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
               ("\\paragraph{%s}" . "\\paragraph*{%s}")
               ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))
#+end_src

** Behavior
*** Set PDF Process

#+begin_src emacs-lisp :tangle no :noweb-ref ox-latex-config
(setq org-latex-pdf-process '("LC_ALL=en_US.UTF-8 latexmk -f -pdf -%latex -shell-escape -interaction=nonstopmode -output-directory=%o %f"))
#+end_src

* Engrave Faces

#+begin_quote
[[https://github.com/tecosaur/engrave-faces][Engrave Faces]] is a generic exporter that passes a fontified buffer to an org backend to be exported to a particular format. It provides theming and syntax highlighting in code blocks for our org-mode html and latex exports!
#+end_quote

#+begin_src emacs-lisp :tangle packages.el
(package! engrave-faces
  :recipe (:host github :repo "tecosaur/engrave-faces")
  :pin "2c72619195d489a4f6d5370f70dd7f6aa11801c3")
#+end_src

#+begin_src emacs-lisp
(use-package! engrave-faces-latex
  :after ox-latex)
#+end_src

#+begin_src emacs-lisp
(use-package! engrave-faces-html
  :after ox-html)
#+end_src

* Org Noter

#+begin_quote
[[https://github.com/weirdNox/org-noter][Org Noter]] creates org notes that are kept in sync with PDF pages as you scroll.
#+end_quote

#+begin_src emacs-lisp :exports none :noweb no-export
(after! org-noter
  <<org-noter-config>>
  )
#+end_src

** Behavior
*** Frame

#+begin_src emacs-lisp :tangle no :noweb-ref org-noter-config
(setq org-noter-always-create-frame nil        ; Don't create a new frame for the session.
      org-noter-kill-frame-at-session-end nil) ; Don't kill any frames since none created.
#+end_src

*** Notes

#+begin_src emacs-lisp :tangle no :noweb-ref org-noter-config
(setq org-noter-separate-notes-from-heading t) ; Adds line between headings and notes.
#+end_src

* Projectile

#+begin_quote
[[https://github.com/bbatsov/projectile][Projectile]] is a project interaction library for Emacs. It provides easy project management and navigation.
#+end_quote

#+begin_src emacs-lisp :exports none :noweb no-export
(after! projectile
  <<projectile-config>>
  )
#+end_src

** Variables
*** Projects Directory

I use the same convention for project location on each OS I use.

#+begin_src emacs-lisp :tangle no :noweb-ref projectile-config
(setq projectile-project-search-path '("~/Projects"))
#+end_src

** Behavior
*** Compile C++ CMake Project in Vterm

This is a quick and dirty setup I did to get a dumb C++ project going. I need to actually setup my compile commands.

#+begin_src emacs-lisp :tangle no :noweb-ref projectile-config
(defun +my/compile-in-vterm ()
  "Run `compile-command' in vterm in current project's root directory"
  (interactive)
  (projectile-run-vterm)
  (vterm-send-string "cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug && cmake --build build --config Release && ./build/minimax")
  (vterm-send-return))
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref projectile-config
(defun +mypopup-kill (some-popup-window)
  (progn (+popup--kill-buffer (window-buffer some-popup-window) 0.1) ) t)
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref projectile-config
(defun +mypopup-resize (some-popup-window)
  (fit-window-to-buffer some-popup-window nil 16 nil nil t))
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref projectile-config
(map! :map project-prefix-map
      :leader
      :desc "Run project in vterm"
      "p v" #'+my/compile-in-vterm)
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref projectile-config
(set-popup-rule! "^*vterm minimax*" :size #'+mypopup-resize :quit #'+mypopup-kill :autosave 'ignore)
#+end_src

** Keybinds
*** List Uncommitted Projects

I add a keybind to quickly view which projects have uncommitted changes.

#+begin_src emacs-lisp :tangle no :noweb-ref projectile-config
(map! :map project-prefix-map
      :leader
      :desc "List dirty projects"
      "p l" #'projectile-browse-dirty-projects)
#+end_src

* PlantUML

#+begin_quote
[[https://plantuml.com][PlantUML]] is a component that allows you to quickly write several types of UML diagrams using its language. This integrates well with org mode for generating UML diagrams from source blocks.
#+end_quote

#+begin_src emacs-lisp :exports none :noweb no-export
(after! plantuml-mode
  <<plantuml-mode-config>>
  )
#+end_src

** Behavior
*** Execution Mode

I use a local jar executable instead of contacting the website.

#+begin_src emacs-lisp :tangle no :noweb-ref plantuml-mode-config
(setq plantuml-default-exec-mode 'jar)
#+end_src

*** Ensure Local Installation

Downloads the jar file if it's not on the system.

#+begin_src emacs-lisp :tangle no :noweb-ref plantuml-mode-config
(unless (file-exists-p plantuml-jar-path)
  (plantuml-download-jar))
#+end_src

* PDF Tools

#+begin_quote
[[https://github.com/vedang/pdf-tools][PDF Tools]] is a replacement PDF viewer for the default, DocView, in Emacs. It's required for =org-noter=.
#+end_quote

#+begin_src emacs-lisp :exports none :noweb no-export
(after! pdf-tools
  <<pdf-tools-config>>
  (pdf-tools-install)
  )
#+end_src

** Fixes
*** Prevent Crash on macOS Ventura

Apparently this is required. [[https://github.com/vedang/pdf-tools/issues/173#issuecomment-1341882242][Source]]

#+begin_src emacs-lisp :tangle no :noweb-ref pdf-tools-config
(when IS-MAC (add-hook 'pdf-tools-enabled-hook 'pdf-view-dark-minor-mode))
#+end_src

* Yasnippet

#+begin_quote
[[https://github.com/joaotavora/yasnippet][Yasnippet]] is a template system for Emacs. It allows you to type an abbreviation and automatically expand it.
#+end_quote


#+begin_src emacs-lisp :exports none :noweb no-export
(after! yasnippet
  (use-package! yasnippet
    :config
    <<yasnippet-config>>
    ))
#+end_src

** Resources
- [[https://joaotavora.github.io/yasnippet/index.html][Yasnippet Documentation]]
- [[https://github.com/doomemacs/snippets][Doom Snippets]]

** Behavior
*** Enable Nested Snippets

#+begin_src emacs-lisp :tangle no :noweb-ref yasnippet-config
(setq yas-triggers-in-field t)
#+end_src

* Magit

#+begin_quote
[[https://magit.vc][Magit]] is a powerful user Emacs interface for Git.
#+end_quote

#+begin_src emacs-lisp :exports none :noweb no-export
(after! magit
  <<magit-linter>>
  <<magit-config>>
  )
#+end_src

** Behavior
*** Dotfiles Git Bare Repository Support

Out of the box Magit doesn't support bare repositories, which are commonly used to manage dotfiles. I've extended an old method of loading the corresponding Git environment variables when relevant directories are open. This method works everywhere and seamlessly integrates managing my dotfiles into Magit. It could easily be extended to support multiple bare repositories as well.

It simply gets a list of all your dotfiles from the repository and whenever you're in their releveant directory it modifies the Magit/Git environment variable to support the bare repository whenever you need it.

#+begin_src emacs-lisp :tangle no :noweb-ref magit-config
(defun my/magit-process-environment (env)
  "Detect and set git -bare repo env vars when in tracked dotfile directories."
  (let* ((default (file-name-as-directory (expand-file-name default-directory)))
         (git-dir (expand-file-name "~/.dotfiles/"))
         (work-tree (expand-file-name "~/"))
         (dotfile-dirs
          (-map (apply-partially 'concat work-tree)
                (-uniq (-keep #'file-name-directory (split-string (shell-command-to-string
                (format "/usr/bin/git --git-dir=%s --work-tree=%s ls-tree --full-tree --name-only -r HEAD"
                        git-dir work-tree))))))))
    (push work-tree dotfile-dirs)
    (when (member default dotfile-dirs)
      (push (format "GIT_WORK_TREE=%s" work-tree) env)
      (push (format "GIT_DIR=%s" git-dir) env)))
  env)
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref magit-config
(advice-add 'magit-process-environment
            :filter-return #'my/magit-process-environment)
#+end_src

*** Commit Linter

I've developed a custom Git commit linter based on [[https://github.com/angular/angular/blob/main/CONTRIBUTING.md#-commit-message-format][Angular]] and [[https://www.conventionalcommits.org/][Conventional Commits]].

The code is based on this [[https://www.adventuresinwhy.com/post/commit-message-linting/][this]] post but highly modified to conform to my chosen conventions.

**** Define Convention Checks

This option paralells =git-commit-style-convention-checks= from Magit.

This is a custom list of checks that allows the user to specify which will be performed by our checker.

#+begin_src emacs-lisp :tangle no :noweb-ref magit-linter
(defcustom my-git-commit-style-convention-checks '(summary-has-type
                                                   summary-type-lowercase
                                                   summary-has-separator
                                                   summary-scope-lowercase
                                                   summary-title-starts-with-lowercase
                                                   summary-title-uses-imperative-verb
                                                   summary-title-not-end-in-punctuation)
  "List of checks performed by `my-git-commit-check-style-conventions'.
Valid members are `summary-has-type',  `summary-type-lowercase',
`summary-has-separator', `summary-scope-lowercase',
`summary-title-starts-with-lowercase', `summary-title-uses-imperative-verb', and
`summary-title-not-end-in-punctuation'.
That function is a member of `git-commit-finish-query-functions'."
  :options '(summary-has-type
             summarty-type-lowercase
             summary-has-separator
             summary-scope-lowercase
             summary-title-starts-with-lowercase
             summary-title-uses-imperative-verb
             summary-title-not-end-in-punctuation
             )
  :type '(list :convert-widget custom-hook-convert-widget)
  :group 'git-commit)
#+end_src

**** Define Convention Checker

This function parallels =git-commit-check-style-conventions= from Magit.

#+begin_src emacs-lisp :tangle no :noweb-ref magit-linter
(defun my-git-commit-check-style-conventions (&optional force) ; TODO check using force
  "Check for violations of certain basic style conventions.

For each violation ask the user if she wants to proceed anyway.
Option `my-git-commit-check-style-conventions' controls which
conventions are checked."
  (save-excursion
    (goto-char (point-min))
    (re-search-forward (git-commit-summary-regexp) nil t)
    (let* ((summary (match-string 1))
           (commit-type (substring summary 0 (string-match-p "[()!:]" summary)))
           (commit-separator-check (string-match-p "^.*[^[:blank:]]:" summary))
           (commit-separator-location (string-match-p ":" summary))
           (commit-scope (if (string-match-p "(.*)[!:]" summary) (substring summary (1+ (string-match-p "(" summary)) (string-match-p ")!?:?" summary)) nil))
           (commit-title (if commit-separator-check (substring summary (+ commit-separator-location 2)) "undetectable-title"))
           (lowercase-title-first-word (downcase (substring commit-title 0 (string-match-p "[[:blank:]]" commit-title)))))
      (and (or (not (memq 'summary-type-lowercase my-git-commit-style-convention-checks))
               (let ((case-fold-search nil)) (string-match-p "^[[:lower:]]*$" commit-type))
               (y-or-n-p "Commit type is not lowercase. Commit anyway?"))
           (or (not (memq 'summary-has-type my-git-commit-style-convention-checks))
               (car (member commit-type (get-commit-types)))
               (when (y-or-n-p "Commit type is invalid. Commit anyway?")
                 (when (y-or-n-p (format "Add `%s' to list of commit types?" commit-type))
                   (with-temp-buffer
                     (insert commit-type)
                     (insert "\n")
                     (write-region (point-min) (point-max) commit-types-file t))) t))
           (or (not (memq 'summary-has-separator my-git-commit-style-convention-checks))
               (not (null commit-separator-check))
               (y-or-n-p "Commit title has invalid separator. Commit anyway?"))
           (or (not (memq 'summary-scope-lowercase my-git-commit-style-convention-checks))
               (when (or (not commit-scope) (string-empty-p commit-scope)) (y-or-n-p "Commit scope is empty. Commit anyway?"))
               (when commit-scope (if (let ((case-fold-search nil)) (string-match-p "^[[:lower:]]*$" commit-scope)) t
                                    (y-or-n-p "Commit scope invalid. Only lowercase letters allowed. Commit anyway?"))))
           (or (not (memq 'summary-title-starts-with-lowercase my-git-commit-style-convention-checks))
               (if (not commit-separator-check) (y-or-n-p "Title undetectable. Commit anyway?") (let ((case-fold-search nil))
                 (string-match-p "^[[:lower:]]" commit-title)))
               (y-or-n-p "Commit title does not start with lowercase letter. Commit anyway?"))
           (or (not (memq 'summary-title-uses-imperative-verb my-git-commit-style-convention-checks))
               (if (not commit-separator-check) (y-or-n-p "Imperative verb undetectable. Commit anyway?")
                 (car (member lowercase-title-first-word (get-imperative-verbs))))
               (when (y-or-n-p "Commit title should use imperative verb. Does it?")
                 (when (y-or-n-p (format "Add `%s' to list of commit types?" lowercase-title-first-word))
                   (with-temp-buffer
                     (insert lowercase-title-first-word)
                     (insert "\n")
                     (write-region (point-min) (point-max) imperative-verbs-file t))) t))
           (or (not (memq 'summary-title-not-end-in-punctuation my-git-commit-style-convention-checks))
              (not (string-match-p "[\\.!\\?;,:]$" commit-title))
              (y-or-n-p "Commit title ends with punctuation. Commit anyway?"))))))
#+end_src

**** Commit Types File Loader

#+begin_src emacs-lisp :tangle no :noweb-ref magit-linter
(setq commit-types-file "~/.config/git/commit/commit-types")
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref magit-linter
(defun get-commit-types ()
  "Return a list of commit types."
  (let ((file-path commit-types-file))
    (with-temp-buffer
      (insert-file-contents file-path)
      (split-string (buffer-string) "\n" t))))
#+end_src

**** Imperative Verbs File Loader

#+begin_src emacs-lisp :tangle no :noweb-ref magit-linter
(setq imperative-verbs-file "~/.config/git/commit/imperative-verbs")
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref magit-linter
(defun get-imperative-verbs ()
  "Return a list of imperative verbs."
  (let ((file-path imperative-verbs-file))
    (with-temp-buffer
      (insert-file-contents file-path)
      (split-string (buffer-string) "\n" t))))
#+end_src

**** Commit Template

I add the following template to my Git commit message to remind me of the Conventional Commits standard. This is not meant to be exhaustive, only a reminder.

#+begin_example

#------------------------------------------------------------------------
# Subject line: type(scope): description
#------------------------------------------------------------------------
# Types: Required noun describing commit type.
#
#    build - Changes build system or external dependencies.
#    chore - Changes external user won't see. (configs/internal task)
#       ci - Changes CI configuration files or scripts.
#     docs - Changes documentation only.
#     feat - A new feature.
#      fix - A bug fix.
#     perf - Change that improves performance.
# refactor - Change that neither fixes a bug nor adds a feature.
#   revert - Change that corrects a commit.
#    style - Changes don't affect meaning. (white-space, format, etc.)
#     test - Adds test or corrects existing test.
#
#------------------------------------------------------------------------
# Scope:       Optional noun describing relevant section of codebase.
#              Must be inside parenthesis if used.
#------------------------------------------------------------------------
# Description: Required short summary of the changes.
#              Must follow a colon after type or scope.
#              No ending punctuation.
#------------------------------------------------------------------------
# Body:        Optional longer description providing additional context.
#              Must begin one blank line after subject/title.
#              Free-form, may consist of newlines and paragraphs.
#------------------------------------------------------------------------
# Footer:      Optional git trailer.
#              Must begin one blank line after body paragraph.
#              Tokens must use '-' in place of white-space.
#              May contain spaces and newlines.
#
# References:  Links information/issues/commits/PRs.
#              Closed issues should be listed on separate line.
#
# BREAKING CHANGE: Must be indicated in title or footer.
#                  If title: Indicate using ! before colon. (!:)
#                            Must use body to describe.
#                  If footer: Must be uppercase text.
#                             Must have a colon and spaced description.
#                             Description should be lowercase.
#------------------------------------------------------------------------
#+end_example

And I enable it in my Git config using this.

#+begin_example
[commit]
    template = ~/.config/git/commit-message
#+end_example

**** Set Max Lengths

These are commonly enforced commit length standards.

#+begin_src emacs-lisp :tangle no :noweb-ref magit-config
(setq git-commit-summary-max-length 50)                  ; Maximum title (summary) length.
(setq git-commit-fill-column 72)                         ; Description column limit.
#+end_src

**** Hook Commit Linter

#+begin_src emacs-lisp :tangle no :noweb-ref magit-config
(add-hook 'after-save-hook 'magit-after-save-refresh-status t)
(add-to-list 'git-commit-finish-query-functions
             #'my-git-commit-check-style-conventions)
#+end_src

* Company

#+begin_quote
[[http://company-mode.github.io][Company]] (complete anything) is a text completion framework for Emacs. It uses backends and frontends to retrieve and display completion candidates.
#+end_quote

#+begin_src emacs-lisp :exports none :noweb no-export
(after! company
  <<company-config>>
  )
#+end_src

** Behavior
*** General

#+begin_src emacs-lisp :tangle no :noweb-ref company-config
(setq company-idle-delay 0.3
      company-tooltip-limit 10
      company-minimum-prefix-length 1)
#+end_src

*** Org-mode Backend

#+begin_src emacs-lisp :tangle no :noweb-ref company-config
(set-company-backend! 'org-mode
  '(company-capf company-files :with company-yasnippet))
#+end_src

*** Sh-mode Backend

#+begin_src emacs-lisp :tangle no :noweb-ref company-config
(set-company-backend! 'sh-mode
  '(company-shell company-files :with company-yasnippet))
#+end_src

* Vterm

#+begin_quote
[[https://github.com/akermu/emacs-libvterm][Vterm]] is the most capable Emacs terminal emulator with unrivaled performance and compatibility.
#+end_quote

#+begin_src emacs-lisp :exports none :noweb no-export
(after! vterm
  (use-package! vterm
    :config
    <<vterm-config>>
    ))
#+end_src

** Keybinds
*** Fix =C-backspace=

I love this keybind, more things should use it. Including vterm...

Thanks [[https://github.com/elken/doom#fix-c-backspace][Elken]]!

#+begin_src emacs-lisp :tangle no :noweb-ref vterm-config
(define-key vterm-mode-map (kbd "<C-backspace>") (lambda () (interactive) (vterm-send-key (kbd "C-w"))))
#+end_src

* Which-Key

#+begin_quote
[[https://github.com/justbur/emacs-which-key][Which-Key]] is a minor-mode for Emacs that displays keybinds for your currently unfinished inputs.
#+end_quote

** Fixes
*** Fix Height issue

I was having an issue using =emacsclient= where which-key was being cut off below the modeline. A simple solution (found [[https://github.com/justbur/emacs-which-key/issues/231#issuecomment-627503184][here]]) is to add spaces below the keybinds. Realistically this doesn't work everywhere but it's good enough for now.

#+begin_src emacs-lisp
;; Add an extra line to work around bug in which-key imprecise
(after! which-key
  (defun add-which-key-line (f &rest r) (progn (apply f (list (cons (+ 1 (car (car r))) (cdr (car r)))))))
  (advice-add 'which-key--show-popup :around #'add-which-key-line)
  )
#+end_src

*** Remove Evil Prefixes

#+begin_src emacs-lisp
(setq which-key-allow-multiple-replacements t)
(after! which-key
  (pushnew!
   which-key-replacement-alist
   '(("" . "\\`+?evil[-:]?\\(?:a-\\)?\\(.*\\)") . (nil . " \\1"))
   '(("\\`g s" . "\\`evilem--?motion-\\(.*\\)") . (nil . " \\1"))))
#+end_src

* Persp-Mode

#+begin_quote
[[https://github.com/Bad-ptr/persp-mode.el][Persp-Mode]] is used by Doom to manage workspaces across frames.
#+end_quote

#+begin_src emacs-lisp :exports none :noweb no-export
(after! persp-mode
  <<pers-config>>
  )
#+end_src

** Fixes
*** Prevent New Workspaces on New Frames

By default, when using emacsclient, Doom creates a new workspace for each emacsclient window. I don't want this, so we'll disable it.

#+begin_src emacs-lisp :tangle no :noweb-ref persp-config
(setq persp-emacsclient-init-frame-behaviour-override nil)
#+end_src

* Visual Fill Column

#+begin_quote
[[https://codeberg.org/joostkremers/visual-fill-column][Visual-Fill-Column]] is an Emacs minor mode that enables word wrapping at a column and centering the buffer content.
#+end_quote

I use this to center org-mode buffers primarily. In Doom, I get this package by enabling the zen module.

** Behavior
*** Center Org

#+begin_src emacs-lisp
(defun noncog/org-mode-visual-fill ()
  (setq visual-fill-column-width 100
        visual-fill-column-center-text t)
  (visual-fill-column-mode 1))

(use-package! visual-fill-column
  :hook (org-mode . noncog/org-mode-visual-fill))
#+end_src

* Treemacs

#+begin_quote
[[https://github.com/Alexander-Miller/treemacs][Treemacs]] is a file and project explorer in a tree sidebar similar to Neotree and Nerdtree for Vim.
#+end_quote

#+begin_src emacs-lisp :exports none :noweb no-export
(after! treemacs
  <<treemacs-config>>
  )
#+end_src

** Appearance
*** Use Doom's Theme Colors

#+begin_src emacs-lisp :tangle no :noweb-ref treemacs-config
(setq doom-themes-treemacs-theme "doom-colors")
#+end_src

* Vertico

#+begin_quote
[[https://github.com/minad/vertico][Vertico]] provides a performant and compatible vertical completion UI for Emacs.
#+end_quote

#+begin_src emacs-lisp :exports none :noweb no-export
(after! vertico
  <<vertico-config>>
  )
#+end_src

** Behavior
*** Alphabetical Sort Order

#+begin_src emacs-lisp :tangle no :noweb-ref vertico-config
(setq vertico-sort-function #'vertico-sort-alpha)
#+end_src

** Keybinds
*** Add Scroll Keys to Minibuffer
Add "regular" style scrolling keybinds to Vertico for the minibuffer.

#+begin_src emacs-lisp
(map! :after vertico
      :map vertico-map
      "C-d" #'scroll-up-command)
#+end_src

#+begin_src emacs-lisp
(map! :after vertico
      :map vertico-map
      "C-u" #'scroll-down-command)
#+end_src

* Doom Modeline

#+begin_quote
[[https://github.com/seagle0128/doom-modeline][Doom-Modeline]] is a fancy and fast mode-line inspired by minimalism design.
#+end_quote

#+begin_src emacs-lisp :exports none :noweb no-export
(after! doom-modeline
  <<doom-modeline-config>>
  )
#+end_src

** Appearance
*** General
#+begin_src emacs-lisp
(setq doom-modeline-height 35)
(setq doom-modeline-major-mode-icon t)
(setq doom-modeline-persp-name t)
(setq doom-modeline-display-default-persp-name t)
(setq doom-modeline-persp-icon t)
#+end_src

* Nav-flash

#+begin_quote
[[https://github.com/rolandwalker/nav-flash][Nav-flash]] briefly highlights the currently in Emacs.
#+end_quote

#+begin_src emacs-lisp :exports none :noweb no-export
(after! nav-flash
  <<nav-flash-config>>
  )
#+end_src

** Appearance
*** Set Flash Length

#+begin_src emacs-lisp :tangle no :noweb-ref nav-flash-config
(setq nav-flash-delay 0.75)
#+end_src

* Doom Dashboard

#+begin_quote
Doom-Dashboard adds a customizable dashboard as the default buffer.
#+end_quote

#+begin_src emacs-lisp :exports none :noweb no-export
(after! doom-dashboard
  <<doom-dashboard-config>>
  )
#+end_src

** Keybinds
*** Open the Dashboard

#+begin_src emacs-lisp :tangle no :noweb-ref doom-dashboard-config
(map! :leader :desc "Dashboard" "d" #'+doom-dashboard/open)
#+end_src

* Lsp-Clangd

#+begin_quote

#+end_quote

#+begin_src emacs-lisp :exports none :noweb no-export
(after! lsp-clangd
  <<lsp-clangd-config>>
  )
#+end_src

** Behavior
*** Set Clangd Args

#+begin_src emacs-lisp :tangle no :noweb-ref lsp-clangd-config
(setq lsp-clients-clangd-args
      '("-j=3"
        "--background-index"
        "--clang-tidy"
        "--completion-style=detailed"
        "--header-insertion=never"
        "--header-insertion-decorators=0"))
(set-lsp-priority! 'clangd 2)
#+end_src
