#+html:<div align="center">
* Doom Emacs
#+tags: export noexport #+export_select_tags: export #+export_exclude_tags: exclude
noexport

#+options: todo:nil

#+startup: show2levels

#+begin_html
<p><a href="https://www.gnu.org/software/emacs/emacs.html#Releases"><img src="https://img.shields.io/badge/Emacs-27.1+-blueviolet.svg?style=flat-square&logo=GNU%20Emacs&logoColor=white"></a> <a href="https://orgmode.org"><img src="https://img.shields.io/badge/Org-literate%20config-%2377aa99?style=flat-square&logo=org&logoColor=white"></a></p>

<p><a href="https://github.com/Schievel1/doom-emacs-splash"><img src="https://github.com/Schievel1/doom-emacs-splash/blob/main/svg/doom/doomEmacsDracula.svg" height="300"></a></p>

<p><a href="https://creativecommons.org/licenses/by-sa/4.0/"><img src="https://img.shields.io/badge/CC--BY--SA-161b22?style=for-the-badge&logo=Creative%20Commons&logoColor=white"></a></p>

<p>This is my <code><a href="https://github.com/doomemacs/doomemacs">Doom</a></code>... <code><a href="https://github.com/hlissner">Henrik</a></code> has doomed us all!</p>
#+end_html

#+html:</div>

* About
** Resources
- [[https://github.com/doomemacs/doomemacs/blob/d217ae334392b6abf0e23424516a37b4cd8ac261/docs/getting_started.org][Getting Started Guide]]
- [[https://github.com/doomemacs/doomemacs/tree/master/modules][Modules]]
- [[https://github.com/doomemacs/themes][Doom Themes]]

** Literate Configuration

It should be noted that I use a [[https://leanpub.com/lit-config/read][literate configuration]]. This enables me to have a single annotated file for a particular configuration which automatically writes out the actual configuration file from the .org file.

*** README.org != [[file:config.el][config.el]]

#+begin_quote
*Warning:* README.org does not represent the actual elisp code because of my use of =noweb= blocks. This is done to better share the features I use, not how I write elisp. To see 'under the hood', refer to =config.el= and the raw README.org file. For example, I cleverly split up use-package! declarations into more visually appealing and better documented code blocks for viewing here on GitHub.
#+end_quote

The [[https://orgmode.org/manual/Noweb-Reference-Syntax.html][org-mode manual]] documentation on this topic is extremely useful for understanding the ways you can use this.

* Doom Global

In this section I setup Doom and "global" things. Otherwise, package specific settings are in the [[#packages][Packages]] section.

** Initial Setup
*** Enable Lexical Binding

Supposedly makes this file run slightly faster...

#+begin_src emacs-lisp
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-
#+end_src

*** TODO Personal Information

Some functions use this information to identify you. This can include gpg, email, and file templates/snippets. It's optional, but I'll likely use it for GPG.

#+begin_src emacs-lisp
(setq user-full-name "Jake Turner"
      user-mail-address "john@doe.com")
#+end_src

*** Set Org Directory

According to Doom, org's directory must be set early due to it's loading process. Therefore it's not inside the use-package configuration for org-mode.

#+begin_src emacs-lisp
(setq org-directory "~/Projects/exocortex/")
#+end_src

** Behavior
*** Autoload File Changes

#+begin_src emacs-lisp
(global-auto-revert-mode 1)
#+end_src

*** TODO Scrolling
TODO: Setup pixel scroll
TODO: Setup scroll recentering
TODO: Setup recentering after jumping...
TODO: Setup scroll margin...

#+begin_src emacs-lisp
;;(advice-add 'evil-scroll-page-up :after #'evil-scroll-line-to-center)
;;(setq scroll-margin (* (frame-height) 2))
;;(setq scroll-conservatively 0)
;;(setq maximum-scroll-margin 0.5)
;;(setq scroll-preserve-screen-position t)
#+end_src

*** Focus Window After Splitting

This isn't documented well, but enabling these causes the split to be focused instead of the original window.

#+begin_src emacs-lisp
(setq evil-split-window-below t
      evil-vsplit-window-right t)
#+end_src

*** Enable Subword Mode

Allows iterating through CamelCase words.

#+begin_src emacs-lisp
(global-subword-mode 1)
#+end_src

*** Evil Fine Undo

By default, all changes from insert made are considered one. Enable a more granular undo scheme.

#+begin_src emacs-lisp
(setq evil-want-fine-undo t)
#+end_src

** Appearance
*** Theme

I use the [[https://draculatheme.com/][Dracula]] theme everywhere I can.

#+begin_src emacs-lisp
(setq doom-theme 'doom-dracula)
#+end_src

#+begin_src emacs-lisp
(setq doom-dracula-brighter-modeline t)
#+end_src

#+begin_src emacs-lisp
(setq doom-dracula-colorful-headers t)
#+end_src

#+begin_src emacs-lisp :tangle no :exports none
;; There are two ways to load a theme. Both assume the theme is installed and
;; available. You can either set `doom-theme' or manually load a theme with the
;; `load-theme' function.
#+end_src

*** Font

#+begin_src emacs-lisp :tangle no :exports none
;; doom exposes five (optional) variables for controlling fonts in doom:
;;
;; - `doom-font' -- the primary font to use
;; - `doom-variable-pitch-font' -- a non-monospace font (where applicable)
;; - `doom-big-font' -- used for `doom-big-font-mode'; use this for
;;   presentations or streaming.
;; - `doom-unicode-font' -- for unicode glyphs
;; - `doom-serif-font' -- for the `fixed-pitch-serif' face
;;
;; see 'c-h v doom-font' for documentation and more examples of what they
;; accept. for example:
;;
;; If you or Emacs can't find your font, use 'M-x describe-font' to look them
;; up, `M-x eval-region' to execute elisp code, and 'M-x doom/reload-font' to
;; refresh your font settings. If Emacs still can't find your font, it likely
;; wasn't installed correctly. Font issues are rarely Doom issues!
#+end_src

#+begin_src emacs-lisp
(when IS-MAC
  (setq doom-font (font-spec :family "Jetbrains Mono" :size 12)
        doom-big-font (font-spec :family "Jetbrains Mono" :size 16)
        doom-variable-pitch-font (font-spec :family "Overpass" :size 14)
        doom-unicode-font (font-spec :family "JuliaMono")
        doom-serif-font (font-spec :family "IBM Plex Mono" :size 10 :weight 'light)))
#+end_src

#+begin_src emacs-lisp
(when (string-equal system-type "gnu/linux")
  (setq doom-font (font-spec :family "Jetbrains Mono" :size 12)
        doom-big-font (font-spec :family "Jetbrains Mono" :size 16)
        ;;doom-variable-pitch-font (font-spec :family "Overpass" :size 14)
        ;;doom-unicode-font (font-spec :family "JuliaMono")
        ;;doom-serif-font (font-spec :family "IBM Plex Mono" :size 10 :weight 'light)
        )
)
#+end_src

*** TODO Frame Opacity

I add transparency to Doom's window to allow my wallpaper to show through it. This increases the visual appeal of presentations and screen sharing.

This effect probably requires a compositor on Linux. I use [[https://github.com/yshui/picom][Picom]].

I'm currently contemplating the removal of this effect as I find it somewhat distracting.

#+begin_src emacs-lisp
;(add-to-list 'default-frame-alist '(alpha . 93)) ; [0-100]
#+end_src

*** Display Line Numbers

I use relative visual line numbers to move around. This has a performance cost but I gladly accept the penalty for its benefit.

#+begin_src emacs-lisp
(setq display-line-numbers-type 'visual)
#+end_src

*** Stretch Cursor

Draw block cursor as wide as the glyph under it.

#+begin_src emacs-lisp
(setq-default x-stretch-cursor t)
#+end_src

*** Start Maximized

#+begin_src emacs-lisp
(add-to-list 'default-frame-alist '(fullscreen . maximized))
#+end_src

** Keybinds

I set "global" keybinds here. Other binds are set in their relevant package configurations.

*** macOS

I configure how Mac's modifier keys should be interpreted by Emacs.

#+begin_src emacs-lisp
(when IS-MAC (setq mac-command-modifier 'control    ; Maps Control -> Command (macOS)
                    mac-control-modifier 'meta      ; Maps Alt (Meta) -> Control (macOS)
                    mac-option-modifier 'super
                    ))
#+end_src

*** Global

#+begin_src emacs-lisp
(map! :leader :desc "Dashboard" "d" #'+doom-dashboard/open)
(map! :leader :desc "Pop up scratch buffer" "X" #'doom/open-scratch-buffer) ;Switch the scratch buffer and org-capture default keybind.
(map! :leader :desc "Brain.org" "b t" #'noncog/toggle-brain) ; evil style
#+end_src

** Integrate Windowing with Window Managers
*** TODO Yabai

**** Focus Windows

#+begin_src emacs-lisp
(defun yabai-move-on-error (direction move-fn)
  (interactive)
  (condition-case nil
      (funcall move-fn)
    (user-error (start-process "yabai" nil "yabai" "-m" "window" "--focus" direction))))
#+end_src

#+begin_src emacs-lisp
(defun yabai-window-left ()
  (interactive)
  (yabai-move-on-error "west" #'windmove-left))

(defun yabai-window-right ()
  (interactive)
  (yabai-move-on-error "east" #'windmove-right))

(defun yabai-window-up ()
  (interactive)
  (yabai-move-on-error "north" #'windmove-up))

(defun yabai-window-down ()
  (interactive)
  (yabai-move-on-error "south" #'windmove-down))
#+end_src

#+begin_src emacs-lisp
;; NOTE: Will need to be modified to detect OS and be extended for i3.
(map! "s-h" #'yabai-window-left)
(map! "s-j" #'yabai-window-down)
(map! "s-k" #'yabai-window-up)
(map! "s-l" #'yabai-window-right)
#+end_src

**** Close Windows

#+begin_src emacs-lisp
(map! "s-Q" #'evil-quit)
#+end_src

**** Split Windows

**** Balance Windows

#+begin_src emacs-lisp
(map! "s-=" #'balance-windows)
#+end_src

* Packages

This section is for adding external packages to Doom. This is tangled to [[file:packages.el][packages.el]].

I put the additional packages here instead of in their package configurations so I can easily find and manage the packages that I add.

#+begin_src emacs-lisp :tangle packages.el
; Adds theming to source block exports.
(package! engrave-faces
  :recipe (:host github :repo "tecosaur/engrave-faces")
  :pin "2c72619195d489a4f6d5370f70dd7f6aa11801c3")
; Adds modern look to Org.
(package! org-modern
  :pin "b614ad31d72c49f9eb29d3836995fd7fb0d1fd4a")
; Adds source block fringe but with indentation, unlike org-modern.
(package! org-modern-indent
  :recipe (:host github :repo "jdtsmith/org-modern-indent")
  :pin "c5a50f302dc1053d5b498e0ea2bc0ee233e8e1b8")
; Makes invisible Org elements appear!
(package! org-appear
  :recipe (:host github :repo "awth13/org-appear")
  :pin "eb9f9db40aa529fe4b977235d86494b115281d17")
; Toggles LaTeX previews like org-appear.
(package! org-fragtog
  :pin "c675563af3f9ab5558cfd5ea460e2a07477b0cfd")
; Enable org-roam-ui NOTE: Requires latest org-roam
(unpin! org-roam)
(package! org-roam-ui
  :recipe (:host github :repo "org-roam/org-roam-ui"))
#+end_src

** Adding Packages to Doom :noexport:

#+begin_src emacs-lisp :tangle packages.el :exports none
;; -*- no-byte-compile: t; -*-
;;; $DOOMDIR/packages.el

;; To install a package with Doom you must declare them here and run 'doom sync'
;; on the command line, then restart Emacs for the changes to take effect -- or
;; use 'M-x doom/reload'.


;; To install SOME-PACKAGE from MELPA, ELPA or emacsmirror:
;(package! some-package)

;; To install a package directly from a remote git repo, you must specify a
;; `:recipe'. You'll find documentation on what `:recipe' accepts here:
;; https://github.com/radian-software/straight.el#the-recipe-format
;(package! another-package
;  :recipe (:host github :repo "username/repo"))

;; If the package you are trying to install does not contain a PACKAGENAME.el
;; file, or is located in a subdirectory of the repo, you'll need to specify
;; `:files' in the `:recipe':
;(package! this-package
;  :recipe (:host github :repo "username/repo"
;           :files ("some-file.el" "src/lisp/*.el")))

;; If you'd like to disable a package included with Doom, you can do so here
;; with the `:disable' property:
;(package! builtin-package :disable t)

;; You can override the recipe of a built in package without having to specify
;; all the properties for `:recipe'. These will inherit the rest of its recipe
;; from Doom or MELPA/ELPA/Emacsmirror:
;(package! builtin-package :recipe (:nonrecursive t))
;(package! builtin-package-2 :recipe (:repo "myfork/package"))

;; Specify a `:branch' to install a package from a particular branch or tag.
;; This is required for some packages whose default branch isn't 'master' (which
;; our package manager can't deal with; see radian-software/straight.el#279)
;(package! builtin-package :recipe (:branch "develop"))

;; Use `:pin' to specify a particular commit to install.
;(package! builtin-package :pin "1a2b3c4d5e")


;; Doom's packages are pinned to a specific commit and updated from release to
;; release. The `unpin!' macro allows you to unpin single packages...
;(unpin! pinned-package)
;; ...or multiple packages
;(unpin! pinned-package another-pinned-package)
;; ...Or *all* packages (NOT RECOMMENDED; will likely break things)
;(unpin! t)
#+end_src

** Package Configuration in Doom :noexport:

This is how Doom recommends we configure our packages:

#+begin_src emacs-lisp :exports none
;; Whenever you reconfigure a package, make sure to wrap your config in an
;; `after!' block, otherwise Doom's defaults may override your settings. E.g.
;;
;;   (after! PACKAGE
;;     (setq x y))
;;
;; The exceptions to this rule:
;;
;;   - Setting file/directory variables (like `org-directory')
;;   - Setting variables which explicitly tell you to set them before their
;;     package is loaded (see 'C-h v VARIABLE' to look up their documentation).
;;   - Setting doom variables (which start with 'doom-' or '+').
;;
;; Here are some additional functions/macros that will help you configure Doom.
;;
;; - `load!' for loading external *.el files relative to this one
;; - `use-package!' for configuring packages
;; - `after!' for running code after a package has loaded
;; - `add-load-path!' for adding directories to the `load-path', relative to
;;   this file. Emacs searches the `load-path' when you load packages with
;;   `require' or `use-package'.
;; - `map!' for binding new keys
;;
;; To get information about any of these functions/macros, move the cursor over
;; the highlighted symbol at press 'K' (non-evil users must press 'C-c c k').
;; This will open documentation for it, including demos of how they are used.
;; Alternatively, use `C-h o' to look up a symbol (functions, variables, faces,
;; etc).
;;
;; You can also try 'gd' (or 'C-c c d') to jump to their definition and see how
;; they are implemented.
#+end_src

** On Use-Package :noexport:

[[https://github.com/jwiegley/use-package][Use-Package]] provides a set of macros to load and configure packages. With that in mind, the macros it provides need to be used correctly. Here are a few tips.

- :init - Code runs before package has been loaded. Because this ALWAYS runs, you should restrict this to code that will execute successfully regardless if the package is present on your system or not.
- :config -
- :commands -
- :custom -
- :defer -
- :if -
- :disabled -
- :requires -
- :preface -
- :autoload
- :after -
- :hook -
- :bind -
- :bind-keymap -

** On Doom Macros and Variables :noexport:

Doom also provides us with a set of macros
* Org

[[https://orgmode.org/][Org Mode]] describes itself as, "a GNU Emacs major mode for keeping notes, authoring documents, computational notebooks, literate programming, maintaining to-do lists, planning projects, and more — in a fast and effective plain text system."

Often, users struggle to define org mode. Increasingly, people are finding more uses and interactions for it, which renders it even harder to thoroughly define. I aim to continue this trend.

** Init
*** Open gtd.org

I use the GTD system in org-mode.

This setup toggles open/closed the gtd.org file and its popup side window.

First, I define a constant to set the file to be shown.

#+begin_src emacs-lisp :tangle no :noweb-ref org-init
(defconst noncog/gtd-file "~/Documents/org/gtd/gtd.org")
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref org-init
(defun noncog/toggle-gtd ()
  "A function for toggling the view of the your chosen file in a side window."
  (interactive)
  (if (get-file-buffer noncog/gtd-file)
      (progn(kill-buffer (get-file-buffer noncog/gtd-file))(message "Killed GTD buffer."))
    (progn(display-buffer (find-file-noselect noncog/gtd-file))(message "Opened GTD buffer."))))
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref org-init
;;(set-popup-rule! "^gtd.org" :side 'right :vslot -1 :width 60 :modeline t :select t :quit nil)
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref org-init
(map! :leader :desc "Open gtd.org" "o g" #'noncog/toggle-gtd) ; evil style
#+end_src

** Config
*** Set Agenda Files

By default, this value is set to =org-directory=, but if you require control over which files/directories are scanned you can manually set them here.

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(setq org-agenda-files (list
                        "~/Projects/exocortex/nodes/calendar.org"
                        ;"gtd/inbox.org"
                        ;"gtd/gtd.org"
                        ;"personal/habits.org"
                        ))
#+end_src

*** Enable Habits Module

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(add-to-list 'org-modules 'org-habit t)             ; Enables org-habit in modules.
#+end_src

*** Habits Settings

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(setq org-habit-show-habits-only-for-today t        ; Ensure habits only shown in one section.
      org-habit-show-all-today t)                   ; Keep habits visible even if done today.
#+end_src

*** Logging Settings

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(setq org-log-done 'time                            ; Add completion time to DONE items.
      org-log-into-drawer t)                        ; Puts log times into a drawer to hide them.
#+end_src

*** Refile Targets

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(setq org-refile-targets
      '(;("gtd.org" :regexp . "\\(?:\\(?:Note\\|Task\\)s\\)")
        ("~/Projects/exocortex/nodes/calendar.org" :maxlevel . 3)
        ;("someday.org" :maxlevel . 2)
        ))
;; consider adding org-roam directory as the need arises.
#+end_src

*** Keywords

I have excess keywords on purpose and will likely remove/simplify them when I figure out their best use.

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(setq org-todo-keywords
      '((sequence      ; For headings.
         "TODO(t!)"    ; A task that needs doing & is ready to do.
         "NEXT(n!)"    ; A task that needs doing & is ready to do.
         "STRT(s!)"    ; A task that is in progress.
         "WAIT(w@/!)"  ; Something external is holding up this task.
         "HOLD(h@/!)"  ; This task is paused/on hold because of me.
         "PROJ(p!)"    ; A project, which usually contains other tasks.
         "IDEA(i!)"    ; An unconfirmed and unapproved task or notion.
         "NOTE(N!)"    ; A fleeting note, in person, idea, link, anything.
         "APPT(a!)"    ; An appointment.
         "MEET(m!)"    ; A meeting.
         "READ(r!)"    ; Something to read.
         "LINK(l!)"    ; A link I want to note.
         "|"           ; Marker signifying remaining are a "completed" states.
         "DONE(d!)"    ; Task successfully completed.
         "KILL(k@/!)") ; Task was cancelled, aborted or is no longer applicable.
        (sequence      ; For nesting headings like lists.
         "[ ](T)"      ; A task that needs doing.
         "[-](S!)"     ; Task is in progress.
         "[?](W@/!)"   ; Task is being held up or paused.
         "|"
         "[X](D)"))    ; Task was completed.
      org-todo-keyword-faces
      '(("[-]"  . +org-todo-active)
        ("STRT" . +org-todo-active)
        ("NOTE" . +org-todo-active)
        ("[?]"  . +org-todo-onhold)
        ("WAIT" . +org-todo-onhold)
        ("HOLD" . +org-todo-onhold)
        ("PROJ" . +org-todo-project)
        ("KILL" . +org-todo-cancel)))
#+end_src

*** Capture Templates

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(setq org-capture-templates
      `(("i" "Inbox" entry
         (file+headline "inbox.org" "Inbox")
         "* %?\n%i\n" :prepend t)
        ))
#+end_src

*** Capture Keybind

I switch the default scratchbuffer and org-capture keybinds.

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(map! :leader :desc "Org capture" "x" #'org-capture)
#+end_src

*** Behavior Settings

Some general behavior settings that improve org for my tastes.

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(setq org-return-follows-link t                     ; Pressing enter opens links.
      org-capture-bookmark nil                      ; Prevent org capture from adding to bookmarks.
      org-log-states-order-reversed nil             ; Log state changes in drawer chronologically.
      org-list-allow-alphabetical t                 ; Enable use of alphabet as list bullets.
      org-insert-heading-respect-content nil        ; Insert the heading at cursor, not at end of list.
      org-imenu-depth 10                            ; Allow imenu to search deeply in org docs.
      org-use-property-inheritance t                ; Sub-headings inherit parent properties. Useful.
      org-use-fast-todo-selection 'auto             ; Method used for org-todo. ('auto, 'exprt, or 'nil)
      org-fold-core-style 'overlays                 ; Used to hide IDs in Org Roam backlinks buffer.
      ;org-extend-today-until 25
      evil-collection-calendar-want-org-bindings t) ; Add evil bindings to org's calendar. Much needed.
#+end_src

*** Org LaTeX Settings
**** Enable LaTeX Previews

This shows the rendered LaTeX within the org buffer.

#+begin_src emacs-lisp :tangle no :noweb-ref org-disabled
(setq org-startup-with-latex-preview nil)
#+end_src

**** Enable Syntax Highlighting

I add syntax highlighting for LaTeX in orgmode buffers. Found [[https://github.com/tecosaur/emacs-config/blob/master/config.org#prettier-highlighting][here]].

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(setq org-highlight-latex-and-related '(native script entities))
#+end_src

Unfortunately, when using =native= highlighting the =org-block= face (think source block background color) is added to LaTeX code.

We can override this background color using the following snippet.

#+begin_src emacs-lisp
(require 'org-src)
(add-to-list 'org-src-block-faces '("latex" (:inherit default :extend t)))
#+end_src

*** Appearance

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(setq org-ellipsis " ▾ "                            ; Set custom ellipsis for folded headings.
      org-startup-with-inline-images t              ; Show images at startup.
      org-hide-leading-stars t                      ; Remove excess heading stars.
      org-hide-emphasis-markers t                   ; Hide formatting for emphasis markup. See org-appear.
      org-pretty-entities nil                       ; Show entities like sub/superscript as UTF8.
      org-hidden-keywords nil                       ; Considering using to hide certain keywords with org-appear and org-modern.
      org-src-preserve-indentation t)               ; Prevents changes to whitespace in source blocks.
#+end_src

*** View Exported Org File

[[https://github.com/tecosaur/emacs-config/blob/master/config.org#view-exported-file][Tecosaur]] created a function and keybind to view the recently exported org-file.

#+begin_src emacs-lisp
(map! :map org-mode-map
      :localleader
      :desc "View exported file"
      "v" #'org-view-output-file)

(defun org-view-output-file (&optional org-file-path)
  "Visit buffer open on the first output file (if any),
found, using `org-view-output-file-extensions'."
  (interactive)
  (let* ((org-file-path (or org-file-path (buffer-file-name) ""))
         (dir (file-name-directory org-file-path))
         (basename (file-name-base org-file-path))
         (output-file nil))
    (dolist (ext org-view-output-file-extensions)
      (unless output-file
        (when (file-exists-p
               (concat dir basename "." ext))
          (setq output-file (concat dir basename "." ext)))))
    (if output-file
        (if (member (file-name-extension output-file) org-view-external-file-extensions)
            (browse-url-xdg-open output-file)
          (pop-to-buffer (or (find-buffer-visiting output-file)
                             (find-file-noselect output-file))))
      (message "No exported file found"))))

(defvar org-view-output-file-extensions '("pdf" "md" "rst" "txt" "tex" "html")
  "Find output files with these extensions, in order, viewing the first match.")
(defvar org-view-external-file-extensions '("html")
  "File formats that should be opened externally.")
#+end_src

*** Insert Zero Width Spaces

#+begin_src emacs-lisp
(map! :map org-mode-map
      :nie "M-SPC M-SPC" (cmd! (insert "\u200B")))
#+end_src

*** Fix Org Capture Random Breakage

Testing out this [[https://github.com/doomemacs/doomemacs/issues/5714][fix]].

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(defadvice! my/+org--restart-mode-h-careful-restart (fn &rest args)
  :around #'+org--restart-mode-h
  (let ((old-org-capture-current-plist (and (bound-and-true-p org-capture-mode)
                                            (bound-and-true-p org-capture-current-plist))))
    (apply fn args)
    (when old-org-capture-current-plist
      (setq-local org-capture-current-plist old-org-capture-current-plist)
      (org-capture-mode +1))))
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref org-config
(add-hook! 'org-capture-after-finalize-hook (org-element-cache-reset t))
#+end_src

** No Web Assembly :noexport:

#+begin_src emacs-lisp :noweb no-export
(after! org
  (use-package! org
    :init
    <<org-init>>
    :config
    <<org-config>>
    ))
#+end_src

* Org Habit

#+begin_src emacs-lisp :tangle no
(use-package! org-habit
    ;:after org
    )
#+end_src

* Org Agenda

This built-in library creates an overview of collected action items, events, and dates based on some criteria and displays them in organized manner in a separate buffer.

** Init
*** Custom Agenda Launcher
**** Function

Define an interactive function to call my custom agenda from (M-x) or by keybind.

#+begin_src emacs-lisp :tangle no :noweb-ref org-agenda-init
(defun noncog/my-agenda ()
  "My custom agenda launcher."
  (interactive)
  (org-agenda nil "o"))
#+end_src

**** Keybind

#+begin_src emacs-lisp :tangle no :noweb-ref org-agenda-init
(map! :leader :desc "My agenda" "o a o" #'noncog/my-agenda)
#+end_src

** Config
*** Logging Settings

#+begin_src emacs-lisp :tangle no :noweb-ref org-agenda-config
(setq org-agenda-start-with-log-mode t)             ; Show 'completed' items in agenda.
;(setq org-agenda-compact-blocks t)
#+end_src

*** Appearance
**** Popup Window

Use Doom's popup window rules to control how the agenda is displayed. This creates a dedicated side window on the right.

I use a custom width variable programatically align window and columns within as I can't trust auto-align.

#+begin_src emacs-lisp :tangle no :noweb-ref org-agenda-config
(setq noncog/agenda-width 70)
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref org-agenda-config
(set-popup-rule! "^*Org Agenda*" :side 'right :vslot 1 :width noncog/agenda-width :modeline nil :select t :quit t)
#+end_src

**** Section Title Face

#+begin_src emacs-lisp :tangle no :noweb-ref org-agenda-config
(custom-set-faces!
  '(org-agenda-structure
    :height 1.3 :weight bold))
#+end_src

**** Remove Empty Agenda Sections

If one of my agenda blocks has no information, I don't want to see it.

#+begin_src emacs-lisp :tangle no :noweb-ref org-agenda-config
(defun noncog/agenda-remove-empty ()
  "A simple function to remove empty agenda sections. Scans for blank lines.
Blank sections defined by having two consecutive blank lines.
Not compatible with the block separator."
  (interactive)
  (setq buffer-read-only nil)
  ;; initializes variables and scans first line.
  (goto-char (point-min))
  (let* ((agenda-blank-line "[[:blank:]]*$")
         (content-line-count (if (looking-at-p agenda-blank-line) 0 1))
         (content-blank-line-count (if (looking-at-p agenda-blank-line) 1 0))
         (start-pos (point)))
    ;; step until the end of the buffer
    (while (not (eobp))
      (forward-line 1)
       (cond
        ;; delete region if previously found two blank lines
        ((when (> content-blank-line-count 1)
          (delete-region start-pos (point))
          (setq content-blank-line-count 0)
          (setq start-pos (point))))
        ;; if found a non-blank line
        ((not (looking-at-p agenda-blank-line))
         (setq content-line-count (1+ content-line-count))
         (setq start-pos (point))
         (setq content-blank-line-count 0))
        ;; if found a blank line
        ((looking-at-p agenda-blank-line)
         (setq content-blank-line-count (1+ content-blank-line-count)))))
    ;; final blank line check at end of file
    (when (> content-blank-line-count 1)
      (delete-region start-pos (point))
      (setq content-blank-line-count 0)))
  ;; return to top and finish
  (goto-char (point-min))
  (setq buffer-read-only t)
)
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref org-agenda-config
(add-hook! 'org-agenda-finalize-hook #'noncog/agenda-remove-empty)
#+end_src

**** TODO Tags Column

#+begin_src emacs-lisp :tangle no :noweb-ref org-agenda-config
(setq org-agenda-tags-column (+ 10 (* -1 noncog/agenda-width)))
;(setq org-overriding-columns-format "%10TODO %7EFFORT %PRIORITY     %100ITEM 100%TAGS")
;(setq org-columns-default-format "%60ITEM(Task) %TODO %6Effort(Estim){:}  %6CLOCKSUM(Clock) %TAGS")
;(setq org-agenda-tags-column 'auto)
#+end_src

**** TODO Base Agenda View

Set base format to change the regular view.

#+begin_src emacs-lisp :tangle no :noweb-ref org-agenda-config-disable
(setq org-agenda-prefix-format '((agenda . " %i %-12:c%?-12t% s")
                                 (todo . " %i %-12:c")
                                 (tags . " %i %-12:c")
                                 (search . " %i %-12:c")))
#+end_src

*** Custom Agenda
**** Tag Finding Helper Functions

#+begin_src emacs-lisp :tangle no :noweb-ref org-agenda-config
(defun noncog/skip-tag (tag)
  "Skip trees with this tag."
  (let* ((next-headline (save-excursion (or (outline-next-heading) (point-max))))
         (current-headline (or (and (org-at-heading-p) (point))
                               (save-excursion (org-back-to-heading)))))
    (if (member tag (org-get-tags current-headline))
        next-headline nil)))
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref org-agenda-config
(defun noncog/skip-all-but-this-tag (tag)
  "Skip trees that are not this tag."
  (let ((subtree-end (save-excursion (org-end-of-subtree t))))
    (if (re-search-forward (concat ":" tag ":") subtree-end t)
        nil          ; tag found, do not skip
      subtree-end))) ; tag not found, continue after end of subtree
#+end_src

**** My Agenda

#+begin_src emacs-lisp :tangle no :noweb-ref org-agenda-config
(setq org-agenda-custom-commands
      '(
        ("o" "My Agenda" (
         (agenda
          ""
          ( ;; Today
           ;(org-agenda-overriding-header "Today\n")
           (org-agenda-overriding-header " Agenda\n")
           (org-agenda-day-face-function (lambda (date) 'org-agenda-date))
           (org-agenda-block-separator nil)
           (org-agenda-format-date " %a, %b %-e %y")  ; american date format
           (org-agenda-start-on-weekday nil)          ; start today
           (org-agenda-start-day nil)                 ; don't show previous days
           (org-agenda-span 1)                        ; only show today
           (org-scheduled-past-days 0)                ; don't show overdue
           (org-deadline-warning-days 0)              ; don't show deadlines for the future
           (org-agenda-time-leading-zero t)           ; unify times formatting
           (org-agenda-remove-tags t)
           (org-agenda-time-grid '((today remove-match) (800 1000 1200 1400 1600 1800 2000 2200) "" ""))
           ;(org-agenda-todo-keyword-format "%-4s")
           (org-agenda-prefix-format '((agenda . " %8:c %-5t ")))
           (org-agenda-dim-blocked-tasks nil)
           (org-agenda-skip-function '(noncog/skip-tag "inbox"))
           (org-agenda-entry-types '(:timestamp :deadline :scheduled))
           ))
         (agenda
          ""
          ( ;; Next Three Days
           ;(org-agenda-overriding-header "\nNext Three Days\n")
           (org-agenda-overriding-header "")
           (org-agenda-day-face-function (lambda (date) 'org-agenda-date))
           (org-agenda-block-separator nil)
           (org-agenda-format-date " %a %b %-e")
           (org-agenda-start-on-weekday nil)
           (org-agenda-start-day "+1d")
           (org-agenda-span 3)
           (org-scheduled-past-days 0)
           (org-deadline-warning-days 0)
           (org-agenda-time-leading-zero t)
           (org-agenda-skip-function '(or (noncog/skip-tag "inbox") (org-agenda-skip-entry-if 'todo '("DONE" "KILL"))))
           (org-agenda-entry-types '(:deadline :scheduled))
           (org-agenda-time-grid '((daily weekly) () "" ""))
           (org-agenda-prefix-format '((agenda . "  %?-9:c%t ")))
           ;(org-agenda-todo-keyword-format "%-4s")
           (org-agenda-dim-blocked-tasks nil)
           ))
         (agenda
          ""
          ( ;; Upcoming Deadlines
           (org-agenda-overriding-header "\n Coming Up\n")
           (org-agenda-day-face-function (lambda (date) 'org-agenda-date))
           (org-agenda-block-separator nil)
           (org-agenda-format-date " %a %b %-e")
           (org-agenda-start-on-weekday nil)
           (org-agenda-start-day "+4d")
           (org-agenda-span 14)
           (org-scheduled-past-days 0)
           (org-deadline-warning-days 0)
           (org-agenda-time-leading-zero t)
           (org-agenda-time-grid nil)
           (org-agenda-prefix-format '((agenda . "  %?-5t %?-9:c")))
           ;(org-agenda-todo-keyword-format "%-4s")
           (org-agenda-skip-function '(or (noncog/skip-tag "inbox") (org-agenda-skip-entry-if 'todo '("DONE" "KILL"))))
           (org-agenda-entry-types '(:deadline :scheduled))
           (org-agenda-show-all-dates nil)
           (org-agenda-dim-blocked-tasks nil)
           ))
         (agenda
          ""
          ( ;; Past Due
           (org-agenda-overriding-header "\n Past Due\n")
           (org-agenda-day-face-function (lambda (date) 'org-agenda-date))
           (org-agenda-block-separator nil)
           (org-agenda-format-date "%a %b %-e")
           (org-agenda-start-on-weekday nil)
           (org-agenda-start-day "-60d")
           (org-agenda-span 60)
           (org-scheduled-past-days 60)
           (org-deadline-past-days 60)
           (org-deadline-warning-days 0)
           (org-agenda-time-leading-zero t)
           (org-agenda-time-grid nil)
           (org-agenda-prefix-format '((agenda . "  %?-9:c%t ")))
           ;(org-agenda-todo-keyword-format "%-4s")
           (org-agenda-skip-function '(or (noncog/skip-tag "inbox") (org-agenda-skip-entry-if 'todo '("DONE" "KILL"))))
           (org-agenda-entry-types '(:deadline :scheduled))
           (org-agenda-show-all-dates nil)
           (org-agenda-dim-blocked-tasks nil)
           ))
         (todo
          ""
          ( ;; Important Tasks No Date
           (org-agenda-overriding-header "\n Important Tasks - No Date\n")
           (org-agenda-block-separator nil)
           (org-agenda-skip-function '(org-agenda-skip-entry-if 'timestamp 'notregexp "\\[\\#A\\]"))
           (org-agenda-block-separator nil)
           (org-agenda-time-grid nil)
           (org-agenda-prefix-format '((todo . "  %?:c ")))
           ;(org-agenda-todo-keyword-format "%-4s")
           (org-agenda-dim-blocked-tasks nil)
           ))
         (todo
          ""
          ( ;; Next
           (org-agenda-overriding-header "\n Next\n")
           (org-agenda-block-separator nil)
           (org-agenda-skip-function '(org-agenda-skip-entry-if 'nottodo '("NEXT" "STRT")))
           (org-agenda-block-separator nil)
           (org-agenda-time-grid nil)
           (org-agenda-prefix-format '((todo . "  %?:c ")))
           ;(org-agenda-todo-keyword-format "%-4s")
           (org-agenda-dim-blocked-tasks nil)
           ))
         (tags-todo
          "inbox"
          ( ;; Inbox
           (org-agenda-overriding-header (propertize "\n Inbox\n" 'help-echo "Effort: 'c e' Refile: 'SPC m r'")) ; Ads mouse hover tooltip.
           ;(org-agenda-remove-tags t)
           (org-agenda-block-separator nil)
           (org-agenda-prefix-format "  %?-4e ")
           ;(org-agenda-todo-keyword-format "%-4s")
           ))
         ))))
#+end_src

** No Web Assembly :noexport:

#+begin_src emacs-lisp :noweb no-export
(after! org-agenda
  (use-package! org-agenda
    :init
    <<org-agenda-init>>
    :config
    <<org-agenda-config>>
    ))
#+end_src

* Ox (Org Export)

This built-in library implements a generic export engine for Org. It uses different backends to change the translation of org documents into various other formats.

** Config
*** Export Depth

By default only the first three headings, including titles are exported. Five levels of depth seems like a reasonable value for LaTeX and HTML exports. Tecosaur reasoned that HTML5 has six heading levels but Org exports start at the second, leaving us with just five to use. It should also challenge/prevent me from overly nesting information.

#+begin_src emacs-lisp :tangle no :noweb-ref ox-config
(setq org-export-headline-levels 5)
#+end_src

*** Creator String

I like to include this on my LaTeX exports to allude to the tools that I like to use.

#+begin_src emacs-lisp :tangle no :noweb-ref ox-config
(setq org-export-with-creator t
      org-export-creator-string (format "Doom Emacs %s (Org mode %s)" emacs-version org-version))
#+end_src

*** Ignore Org Headlines But Keep Content in Export

This setting allows you to use the =:ignore:= tag to remove a heading from an export but keep its contents.

#+begin_src emacs-lisp
(require 'ox-extra)
(ox-extras-activate '(ignore-headlines))
#+end_src

** No Web Assembly :noexport:

#+begin_src emacs-lisp :noweb no-export
(after! ox
  (use-package! ox
    :config
    <<ox-config>>
    ))
#+end_src

* Ox Latex

This built-in library is the LaTeX backend for the Org Export Engine.

** Init
*** Set PDF Process Config

#+begin_src emacs-lisp :tangle no :noweb-ref ox-latex-init
(setq org-latex-pdf-process '("LC_ALL=en_US.UTF-8 latexmk -f -pdf -%latex -shell-escape -interaction=nonstopmode -output-directory=%o %f"))
#+end_src

*** Set Source Block Backend

This adds theming and syntax highlighting to our source blocks in latex exports.

#+begin_src emacs-lisp :tangle no :noweb-ref ox-latex-init
(setq org-latex-src-block-backend 'engraved)
#+end_src

** Config
*** Custom Document Class

#+begin_src emacs-lisp :tangle no :noweb-ref ox-latex-config
(add-to-list 'org-latex-classes
             '("notes"
               "\\documentclass{article}
                [NO-DEFAULT-PACKAGES]
                [PACKAGES]
                [EXTRA]"
               ("\\section{%s}" . "\\section*{%s}")
               ("\\subsection{%s}" . "\\subsection*{%s}")
               ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
               ("\\paragraph{%s}" . "\\paragraph*{%s}")
               ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))
#+end_src

** No Web Assembly :noexport:

#+begin_src emacs-lisp :noweb no-export
(use-package! ox-latex
  :init
  <<ox-latex-init>>
  :config
  <<ox-latex-config>>
  )
#+end_src

* Engrave Faces

[[https://github.com/tecosaur/engrave-faces][Engrave Faces]] is a generic exporter that passes a fontified buffer to a backend to be exported to a particular format.

It provides theming and syntax highlighting in code blocks for our org-mode html and latex exports!

#+begin_src emacs-lisp
(use-package! engrave-faces-latex
  :after ox-latex)
#+end_src

#+begin_src emacs-lisp
(use-package! engrave-faces-html
  :after ox-html)
#+end_src

* Org Fragtog

[[https://github.com/io12/org-fragtog][Org Fragtog]] toggles LaTeX fragments as the cursor enters and exits them. It's org-appear for LaTeX!

** Enable

No configuration, just enable it.

#+begin_src emacs-lisp :tangle no
(use-package! org-fragtog
  :hook (org-mode . org-fragtog-mode))
#+end_src

* Org Modern

[[https://github.com/minad/org-modern][Org Modern]] implements a “modern” style for your Org buffers using font locking and text properties.

** Config
*** Appearance
#+begin_src emacs-lisp :tangle no :noweb-ref org-modern-config
(setq org-modern-hide-stars nil                     ; Let Org handle hiding the stars. Caused issue.
      org-modern-table-vertical 1                   ; Use thinner lines than default.
      org-modern-table-horizontal 0.2               ; Unify line thickness with vertical line.
      org-modern-progress nil                       ; Use default progress face.
      org-modern-priority nil                       ; Use default priority face.
      org-modern-todo-faces                         ; Inherit Doom's Org faces.
      '(("TODO" :inverse-video t :inherit org-todo)
        ("PROJ" :inverse-video t :inherit +org-todo-project)
        ("STRT" :inverse-video t :inherit +org-todo-active)
        ("[-]"  :inverse-video t :inherit +org-todo-active)
        ("HOLD" :inverse-video t :inherit +org-todo-onhold)
        ("WAIT" :inverse-video t :inherit +org-todo-onhold)
        ("[?]"  :inverse-video t :inherit +org-todo-onhold)
        ("KILL" :inverse-video t :inherit +org-todo-cancel)
        ("NO"   :inverse-video t :inherit +org-todo-cancel))
      org-modern-star '("◉" "○" "✸" "✿" "✤" "✜" "◆" "▶")
      org-modern-horizontal-rule (make-string 80 ?─)
      )
#+end_src

** No Web Assembly :noexport:

#+begin_src emacs-lisp :noweb no-export
(use-package! org-modern
  :hook (org-mode . org-modern-mode)
  :config
  <<org-modern-config>>
  )
#+end_src

* Org Modern Indent

#+begin_src emacs-lisp
(use-package! org-modern-indent
  :config ; add late to hook
  (add-hook 'org-mode-hook #'org-modern-indent-mode 1))
#+end_src

* Org Appear

[[https://github.com/awth13/org-appear][Org Appear]] makes invisible Org elements like emphasis markers magically appear.

** Config
*** Appearance

#+begin_src emacs-lisp :tangle no :noweb-ref org-appear-config
(setq org-appear-autoemphasis t                   ; Show emphasis markup.
      org-appear-autosubmarkers t                 ; Show sub/superscript
      org-appear-autoentities nil                 ; Show LaTeX like Org pretty entities.
      org-appear-autolinks nil                    ; Shows Org links.
      org-appear-autokeywords nil                 ; Shows hidden Org keywords.
      org-appear-inside-latex nil)                ; Show LaTeX code. Use Fragtog instead.
#+end_src

** No Web Assembly :noexport:

#+begin_src emacs-lisp :noweb no-export
(use-package! org-appear
  :hook (org-mode . org-appear-mode)
  :config
  <<org-appear-config>>
  )
#+end_src

* Org Roam

[[https://github.com/org-roam/org-roam][Org Roam]] is a plain-text knowledge management system. It providing a solution for non-hierarchical note-taking and linking.

** Init

*** Set Roam Directory

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-init
(setq org-roam-directory (file-truename "~/Projects/exocortex"))
#+end_src

*** Disable If No Roam Directory

Don't use Org Roam if the directory isn't present to avoid errors.

See [[file:config.el][config.el]] to understand how this works. Thanks Teco.

#+begin_src emacs-lisp :tangle (if (file-exists-p "~/Projects/exocortex") "no" "packages.el")
(package! org-roam :disable t)
#+end_src

*** Set Database Location

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-init
(setq org-roam-db-location (file-truename "~/Projects/exocortex/exocortex.db"))
#+end_src

*** Set Attachments Directory

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-init
(setq org-attach-id-dir (file-truename "~/Projects/exocortex/attachments"))
#+end_src

*** Exclude Directories

Currently not excluding any. This is a place holder for when I do.

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-init
;(setq org-roam-file-exclude-regexp (rx (or "data/" "inbox.org")) )
(setq org-roam-graph-exclude-matcher '("inbox.org"))
#+end_src

** Config
*** Enable Autosync

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-config
(org-roam-db-autosync-mode)
#+end_src

*** Capture Templates

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-config
(setq org-roam-capture-templates
      '(("d" "default" plain
         "%?"
         :target
         (file+head "nodes/${slug}.org"
                    "#+title: ${title}\n#+filetags: :draft:\n")
         :immediate-finish t
         :unnarrowed t)
        ))
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-config
;; TODO: set org-roam-dailies-capture-templates
#+end_src

*** Find Random Draft Nodes

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-config
(defun noncog/org-roam-is-draft-p (node)
  "Is this org-roam node a draft?"
  (member "draft" (org-roam-node-tags node))
  )
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-config
(defun noncog/org-roam-random-draft ()
  "Get a random node with the draft tag. "
  (interactive)
  (org-roam-node-random nil #'noncog/org-roam-is-draft-p))
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref org-roam-config
(map! :leader :desc "Random draft node" "n r u" #'noncog/org-roam-random-draft)
#+end_src

** No Web Assembly :noexport:

#+begin_src emacs-lisp :noweb no-export
(after! org-roam
  (use-package! org-roam
    :init
    <<org-roam-init>>
    :config
    <<org-roam-config>>
    ))
#+end_src

* Org Roam UI

[[https://github.com/org-roam/org-roam-ui][org-roam-ui]] is a frontend for exploring and interacting with your org-roam notes.

Stolen from [[https://github.com/org-roam/org-roam-ui/issues/52#issuecomment-912246556][here]].

#+begin_src emacs-lisp
(set-popup-rule! "^*xwidget" :ignore t :side 'left :width 120 :vslot 1 :quit t :select t :modeline nil)
#+end_src

#+begin_src emacs-lisp
(defcustom org-roam-ui-use-webkit t
  "Use embedded webkit to preview.
This requires GNU/Emacs version >= 26 and built with the `--with-xwidgets`
option."
  :type 'boolean
  :group 'roam)

(defun org-roam-ui-browser (url)
  "Use browser specified by user to load URL.
Use default browser if nil."
  (if org-roam-ui-url-browser
      (let ((browse-url-generic-program org-roam-ui-url-browser)
            (browse-url-generic-args roam-url-args))
        (ignore browse-url-generic-program)
        (ignore browse-url-generic-args)
        (browse-url-generic url))
    (browse-url url)))

(defun org-roam-ui-open-url (url)
  "Ask the browser to load URL.
Use default browser unless `xwidget' is available."
  (if (and org-roam-ui-use-webkit
           (featurep 'xwidget-internal))
      (progn
        (save-window-excursion (xwidget-webkit-browse-url url))
        (let ((buf (xwidget-buffer (xwidget-webkit-current-session))))
          (when (buffer-live-p buf) (and (eq buf (current-buffer)) (quit-window)))
          (display-buffer buf)))
            (let (display-buffer-alist) (org-roam-ui-browser url))))
#+end_src

#+begin_src emacs-lisp
;;;###autoload
(define-minor-mode org-roam-ui-open-in-browser
  "open org-roam-ui in the browser"
 :lighter "roam"
 (org-roam-ui-open-url "http://127.0.0.1:35901"))
#+end_src


#+begin_src emacs-lisp
(use-package! org-roam-ui
  ;;:after org-roam ;; or :after org
  ;;         normally we'd recommend hooking orui after org-roam, but since org-roam does not have
  ;;         a hookable mode anymore, you're advised to pick something yourself
  ;;         if you don't care about startup time, use
  :hook (after-init . org-roam-ui-mode)
  :config
  (setq org-roam-ui-sync-theme t
        org-roam-ui-follow t
        org-roam-ui-update-on-save t
        org-roam-ui-open-on-start nil))
#+end_src

** Replace Graph Keybinds with Roam-UI

#+begin_src emacs-lisp
(map! :leader :desc "Roam-UI graph" "n r g" #'org-roam-ui-open-in-browser)
#+end_src

#+begin_src emacs-lisp
;(map! :leader :desc "Roam-UI graph here" "n r G" #'org-roam-ui-open)
#+end_src

* Org Noter

[[https://github.com/weirdNox/org-noter][Org Noter]] creates Org notes that are kept in sync with PDF documents as you scroll through them. Scroll your notes and the pages scroll too.

#+begin_src emacs-lisp :tangle no :noweb-ref org-noter-config
(setq org-noter-separate-notes-from-heading t)      ; Adds a blank line between headings and notes.
(setq org-noter-always-create-frame nil)            ; Don't create a new frame for the session.
(setq org-noter-kill-frame-at-session-end nil)            ; Don't kill any frames since we don't create any.
;;(setq org-noter-notes-window-location 'other-frame)
;;(setq org-noter-notes-search-path '(""))
#+end_src

** No Web Assembly :noexport:

#+begin_src emacs-lisp :noweb no-export
(after! org-noter
  (use-package! org-noter
    :config
    <<org-noter-config>>
    ))
#+end_src

* Projectile

[[https://github.com/bbatsov/projectile][Projectile]] is a project interaction library for Emacs. It provides easy project management and navigation.

** Config
*** Set Projects Search Path

I use the same convention for project location on each OS I use.

#+begin_src emacs-lisp :tangle no :noweb-ref projectile-config
(setq projectile-project-search-path '("~/Projects"))
#+end_src

*** List Uncommitted Projects

I add a keybind to quickly view which projects have uncommitted changes.

#+begin_src emacs-lisp :tangle no :noweb-ref projectile-config
(map! :map project-prefix-map
      :leader
      :desc "List dirty projects"
      "p l" #'projectile-browse-dirty-projects)
#+end_src

** No Web Assembly :noexport:

#+begin_src emacs-lisp :noweb no-export
(after! projectile
  (use-package! projectile
    :config
    <<projectile-config>>
    ))
#+end_src

* PlantUML

[[https://plantuml.com][PlantUML]] is a component that allows you to quickly write several types of UML diagrams using its language.

This integrates well with org mode for generating UML diagrams from source blocks.

** Config
*** Set Execution Mode

I use a local jar executable instead of contacting the website.

#+begin_src emacs-lisp :tangle no :noweb-ref plantuml-mode-config
(setq plantuml-default-exec-mode 'jar)
#+end_src

*** Ensure Local Installation

Downloads the jar file if it's not on the system.

#+begin_src emacs-lisp :tangle no :noweb-ref plantuml-mode-config
(unless (file-exists-p plantuml-jar-path)
  (plantuml-download-jar))
#+end_src

** No Web Assembly :noexport:

#+begin_src emacs-lisp :noweb no-export
(after! plantuml-mode
  <<plantuml-mode-config>>
  )
#+end_src

* PDF Tools

[[https://github.com/vedang/pdf-tools][PDF Tools]] is a replacement PDF viewer for the default, DocView, in Emacs. It's required for =org-noter=.

#+begin_src emacs-lisp
(pdf-tools-install)
#+end_src

** Config
*** Bugfix: Prevent Crash on macOS Ventura

Found [[https://github.com/vedang/pdf-tools/issues/173#issuecomment-1341882242][here]].

#+begin_src emacs-lisp :tangle no :noweb-ref pdf-tools-config
(when IS-MAC (add-hook 'pdf-tools-enabled-hook 'pdf-view-dark-minor-mode))
#+end_src

** No Web Assembly :noexport:

#+begin_src emacs-lisp :noweb no-export
(after! pdf-tools
  (use-package! pdf-tools
    :config
    <<pdf-tools-config>>
    ))
#+end_src

* Yasnippet

[[https://github.com/joaotavora/yasnippet][Yasnippet]] is a template system for Emacs. It allows you to type an abbreviation and automatically expand it.

** Resources
- [[https://joaotavora.github.io/yasnippet/index.html][Yasnippet Documentation]]
- [[https://github.com/doomemacs/snippets][Doom Snippets]]

** Config
*** Enable Nested Snippets

#+begin_src emacs-lisp :tangle no :noweb-ref yasnippet-config
(setq yas-triggers-in-field t)
#+end_src

** No Web Assembly :noexport:

#+begin_src emacs-lisp :noweb no-export
(after! yasnippet
  (use-package! yasnippet
    :config
    <<yasnippet-config>>
    ))
#+end_src

* Magit

[[https://magit.vc][Magit]] is a powerful Git user interface for Emacs.

** Dotfiles Git Bare Repository Support

Out of the box Magit doesn't support bare repositories, which are commonly used to manage dotfiles. I've extended an old method of loading the corresponding Git environment variables when relevant directories are open. This method works everywhere and seamlessly integrates managing my dotfiles into Magit. It could easily be extended to support multiple bare repositories as well.

It simply gets a list of all your dotfiles from the repository and whenever you're in their releveant directory it modifies the Magit/Git environment variable to support the bare repository whenever you need it.

#+begin_src emacs-lisp :tangle no :noweb-ref magit-config
(defun my/magit-process-environment (env)
  "Detect and set git -bare repo env vars when in tracked dotfile directories."
  (let* ((default (file-name-as-directory (expand-file-name default-directory)))
         (git-dir (expand-file-name "~/.dotfiles/"))
         (work-tree (expand-file-name "~/"))
         (dotfile-dirs
          (-map (apply-partially 'concat work-tree)
                (-uniq (-keep #'file-name-directory (split-string (shell-command-to-string
                (format "/usr/bin/git --git-dir=%s --work-tree=%s ls-tree --full-tree --name-only -r HEAD"
                        git-dir work-tree))))))))
    (push work-tree dotfile-dirs)
    (when (member default dotfile-dirs)
      (push (format "GIT_WORK_TREE=%s" work-tree) env)
      (push (format "GIT_DIR=%s" git-dir) env)))
  env)
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref magit-config
(advice-add 'magit-process-environment
            :filter-return #'my/magit-process-environment)
#+end_src

** Commit Linter

I've developed a custom Git commit linter based on [[https://github.com/angular/angular/blob/main/CONTRIBUTING.md#-commit-message-format][Angular]] and [[https://www.conventionalcommits.org/][Conventional Commits]].

The code is based on this [[https://www.adventuresinwhy.com/post/commit-message-linting/][this]] post but highly modified to conform to my chosen conventions.

*** Define Convention Checks

This option paralells =git-commit-style-convention-checks= from Magit.

This is a custom list of checks that allows the user to specify which will be performed by our checker.

#+begin_src emacs-lisp :tangle no :noweb-ref magit-linter
(defcustom my-git-commit-style-convention-checks '(summary-has-type
                                                   summary-type-lowercase
                                                   summary-has-separator
                                                   summary-scope-lowercase
                                                   summary-title-starts-with-lowercase
                                                   summary-title-uses-imperative-verb
                                                   summary-title-not-end-in-punctuation)
  "List of checks performed by `my-git-commit-check-style-conventions'.
Valid members are `summary-has-type',  `summary-type-lowercase',
`summary-has-separator', `summary-scope-lowercase',
`summary-title-starts-with-lowercase', `summary-title-uses-imperative-verb', and
`summary-title-not-end-in-punctuation'.
That function is a member of `git-commit-finish-query-functions'."
  :options '(summary-has-type
             summarty-type-lowercase
             summary-has-separator
             summary-scope-lowercase
             summary-title-starts-with-lowercase
             summary-title-uses-imperative-verb
             summary-title-not-end-in-punctuation
             )
  :type '(list :convert-widget custom-hook-convert-widget)
  :group 'git-commit)
#+end_src

*** Define Convention Checker

This function parallels =git-commit-check-style-conventions= from Magit.

#+begin_src emacs-lisp :tangle no :noweb-ref magit-linter
(defun my-git-commit-check-style-conventions (&optional force) ; TODO check using force
  "Check for violations of certain basic style conventions.

For each violation ask the user if she wants to proceed anyway.
Option `my-git-commit-check-style-conventions' controls which
conventions are checked."
  (save-excursion
    (goto-char (point-min))
    (re-search-forward (git-commit-summary-regexp) nil t)
    (let* ((summary (match-string 1))
           (commit-type (substring summary 0 (string-match-p "[()!:]" summary)))
           (commit-separator-check (string-match-p "^.*[^[:blank:]]:" summary))
           (commit-separator-location (string-match-p ":" summary))
           (commit-scope (if (string-match-p "(.*)[!:]" summary) (substring summary (1+ (string-match-p "(" summary)) (string-match-p ")!?:?" summary)) nil))
           (commit-title (if commit-separator-check (substring summary (+ commit-separator-location 2)) "undetectable-title"))
           (lowercase-title-first-word (downcase (substring commit-title 0 (string-match-p "[[:blank:]]" commit-title)))))
      (and (or (not (memq 'summary-type-lowercase my-git-commit-style-convention-checks))
               (let ((case-fold-search nil)) (string-match-p "^[[:lower:]]*$" commit-type))
               (y-or-n-p "Commit type is not lowercase. Commit anyway?"))
           (or (not (memq 'summary-has-type my-git-commit-style-convention-checks))
               (car (member commit-type (get-commit-types)))
               (when (y-or-n-p "Commit type is invalid. Commit anyway?")
                 (when (y-or-n-p (format "Add `%s' to list of commit types?" commit-type))
                   (with-temp-buffer
                     (insert commit-type)
                     (insert "\n")
                     (write-region (point-min) (point-max) commit-types-file t))) t))
           (or (not (memq 'summary-has-separator my-git-commit-style-convention-checks))
               (not (null commit-separator-check))
               (y-or-n-p "Commit title has invalid separator. Commit anyway?"))
           (or (not (memq 'summary-scope-lowercase my-git-commit-style-convention-checks))
               (when (or (not commit-scope) (string-empty-p commit-scope)) (y-or-n-p "Commit scope is empty. Commit anyway?"))
               (when commit-scope (if (let ((case-fold-search nil)) (string-match-p "^[[:lower:]]*$" commit-scope)) t
                                    (y-or-n-p "Commit scope invalid. Only lowercase letters allowed. Commit anyway?"))))
           (or (not (memq 'summary-title-starts-with-lowercase my-git-commit-style-convention-checks))
               (if (not commit-separator-check) (y-or-n-p "Title undetectable. Commit anyway?") (let ((case-fold-search nil))
                 (string-match-p "^[[:lower:]]" commit-title)))
               (y-or-n-p "Commit title does not start with lowercase letter. Commit anyway?"))
           (or (not (memq 'summary-title-uses-imperative-verb my-git-commit-style-convention-checks))
               (if (not commit-separator-check) (y-or-n-p "Imperative verb undetectable. Commit anyway?")
                 (car (member lowercase-title-first-word (get-imperative-verbs))))
               (when (y-or-n-p "Commit title should use imperative verb. Does it?")
                 (when (y-or-n-p (format "Add `%s' to list of commit types?" lowercase-title-first-word))
                   (with-temp-buffer
                     (insert lowercase-title-first-word)
                     (insert "\n")
                     (write-region (point-min) (point-max) imperative-verbs-file t))) t))
           (or (not (memq 'summary-title-not-end-in-punctuation my-git-commit-style-convention-checks))
              (not (string-match-p "[\\.!\\?;,:]$" commit-title))
              (y-or-n-p "Commit title ends with punctuation. Commit anyway?"))))))
#+end_src

*** Commit Types File Loader

#+begin_src emacs-lisp :tangle no :noweb-ref magit-linter
(setq commit-types-file "~/.config/git/commit/commit-types")
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref magit-linter
(defun get-commit-types ()
  "Return a list of commit types."
  (let ((file-path commit-types-file))
    (with-temp-buffer
      (insert-file-contents file-path)
      (split-string (buffer-string) "\n" t))))
#+end_src

*** Imperative Verbs File Loader

#+begin_src emacs-lisp :tangle no :noweb-ref magit-linter
(setq imperative-verbs-file "~/.config/git/commit/imperative-verbs")
#+end_src

#+begin_src emacs-lisp :tangle no :noweb-ref magit-linter
(defun get-imperative-verbs ()
  "Return a list of imperative verbs."
  (let ((file-path imperative-verbs-file))
    (with-temp-buffer
      (insert-file-contents file-path)
      (split-string (buffer-string) "\n" t))))
#+end_src

*** Commit Template

I add the following template to my Git commit message to remind me of the Conventional Commits standard. This is not meant to be exhaustive, only a reminder.

#+begin_example

#------------------------------------------------------------------------
# Subject line: type(scope): description
#------------------------------------------------------------------------
# Types: Required noun describing commit type.
#
#    build - Changes build system or external dependencies.
#    chore - Changes external user won't see. (configs/internal task)
#       ci - Changes CI configuration files or scripts.
#     docs - Changes documentation only.
#     feat - A new feature.
#      fix - A bug fix.
#     perf - Change that improves performance.
# refactor - Change that neither fixes a bug nor adds a feature.
#   revert - Change that corrects a commit.
#    style - Changes don't affect meaning. (white-space, format, etc.)
#     test - Adds test or corrects existing test.
#
#------------------------------------------------------------------------
# Scope:       Optional noun describing relevant section of codebase.
#              Must be inside parenthesis if used.
#------------------------------------------------------------------------
# Description: Required short summary of the changes.
#              Must follow a colon after type or scope.
#              No ending punctuation.
#------------------------------------------------------------------------
# Body:        Optional longer description providing additional context.
#              Must begin one blank line after subject/title.
#              Free-form, may consist of newlines and paragraphs.
#------------------------------------------------------------------------
# Footer:      Optional git trailer.
#              Must begin one blank line after body paragraph.
#              Tokens must use '-' in place of white-space.
#              May contain spaces and newlines.
#
# References:  Links information/issues/commits/PRs.
#              Closed issues should be listed on separate line.
#
# BREAKING CHANGE: Must be indicated in title or footer.
#                  If title: Indicate using ! before colon. (!:)
#                            Must use body to describe.
#                  If footer: Must be uppercase text.
#                             Must have a colon and spaced description.
#                             Description should be lowercase.
#------------------------------------------------------------------------
#+end_example

And I enable it in my Git config using this.

#+begin_example
[commit]
    template = ~/.config/git/commit-message
#+end_example

** Custom
*** Set Max Lengths

These are commonly enforced commit length standards.

#+begin_src emacs-lisp :tangle no :noweb-ref magit-custom
(git-commit-summary-max-length 50)                  ; Maximum title (summary) length.
(git-commit-fill-column 72)                         ; Description column limit.
#+end_src

** Config
*** Hook Commit Linter

#+begin_src emacs-lisp :tangle no :noweb-ref magit-config
(add-hook 'after-save-hook 'magit-after-save-refresh-status t)
(add-to-list 'git-commit-finish-query-functions
             #'my-git-commit-check-style-conventions)
#+end_src

** No Web Assembly :noexport:

#+begin_src emacs-lisp :noweb no-export
(after! magit
  <<magit-linter>>
  (use-package! magit
    :custom
    <<magit-custom>>
    :config
    <<magit-config>>
    ))
#+end_src

* Company

[[http://company-mode.github.io][Company]] (complete anything) is a text completion framework for Emacs. It uses backends and frontends to retrieve and display completion candidates.

** Config
*** Behavior

#+begin_src emacs-lisp :tangle no :noweb-ref company-config
(setq company-idle-delay 0.3
      company-tooltip-limit 10
      company-minimum-prefix-length 1)
#+end_src

*** Backend Settings

**** Org-mode

#+begin_src emacs-lisp :tangle no :noweb-ref company-config
(set-company-backend! 'org-mode
  '(company-capf company-files :with company-yasnippet))
#+end_src

**** Sh-mode

#+begin_src emacs-lisp :tangle no :noweb-ref company-config
(set-company-backend! 'sh-mode
  '(company-shell company-files :with company-yasnippet))
#+end_src

** No Web Assembly :noexport:

#+begin_src emacs-lisp :noweb no-export
(after! company
  (use-package! company
    :config
    <<company-config>>
    ))
#+end_src

* Vterm

[[https://github.com/akermu/emacs-libvterm][Vterm]] is the most capable Emacs terminal emulator with unrivaled performance and compatibility.

** Fix =C-backspace=

I love this keybind, more things should use it. Including vterm...

Thanks [[https://github.com/elken/doom#fix-c-backspace][Elken]]!

#+begin_src emacs-lisp :tangle no :noweb-ref vterm-config
(define-key vterm-mode-map (kbd "<C-backspace>") (lambda () (interactive) (vterm-send-key (kbd "C-w"))))
#+end_src

** No Web Assembly :noexport:

#+begin_src emacs-lisp :noweb no-export
(after! vterm
  (use-package! vterm
    :config
    <<vterm-config>>
    ))
#+end_src

* Which-Key

[[https://github.com/justbur/emacs-which-key][Which-Key]] is a minor-mode for Emacs that displays keybinds for your currently unfinished inputs.

** Fix Height issue

I was having an issue using =emacsclient= where which-key was being cut off below the modeline. A simple solution (found [[https://github.com/justbur/emacs-which-key/issues/231#issuecomment-627503184][here]]) is to add spaces below the keybinds. Realistically this doesn't work everywhere but it's good enough for now.

#+begin_src emacs-lisp
;; Add an extra line to work around bug in which-key imprecise
(after! which-key
  (defun add-which-key-line (f &rest r) (progn (apply f (list (cons (+ 1 (car (car r))) (cdr (car r)))))))
  (advice-add 'which-key--show-popup :around #'add-which-key-line)
  )
#+end_src

* Persp-Mode

[[https://github.com/Bad-ptr/persp-mode.el][Persp-Mode]] is used by Doom to manage workspaces across frames.

** Disable Features

By default, when using emacsclient, Doom creates a new workspace for each emacsclient window. I don't want this, so we'll disable it.

#+begin_src emacs-lisp
(after! persp-mode
  (setq persp-emacsclient-init-frame-behaviour-override nil))
#+end_src

* Visual Fill Column

[[https://codeberg.org/joostkremers/visual-fill-column][visual-fill-column]] is an Emacs minor mode that enables word wrapping at a column and centering the buffer content.

I use this to center org-mode buffers primarily. In Doom, I get this package by enabling the zen module, which is totally compatible with using visual-fill-column in this way.

#+begin_src emacs-lisp
(defun noncog/org-mode-visual-fill ()
  (setq visual-fill-column-width 100
        visual-fill-column-center-text t)
  (visual-fill-column-mode 1))

(use-package! visual-fill-column
  :hook (org-mode . noncog/org-mode-visual-fill))
#+end_src
