#+TITLE:Cogmacs Config
#+STARTUP: hideblocks
These are my dotfiles for vanilla emacs. I use Chemacs 2 to load both vanilla and doom emacs. Thus, this directory is not the default one. That one is now inhabited by chemacs2. This is a constant work in my progress...I may become doomed.

This is my version of an organized vanilla emacs config. Good luck!
* Package System
I use use-package to manage my packages. The main reason I do, is that use-package automatically installs the latest of my desired packages when I first launch Emacs. Otherwise, one would have to use the built in GUI package installer to manually install all of their desired packages. I strive for automation and this not only accomplishes that, but also cleans up much of the elisp configuration leading to greater readability.
#+BEGIN_SRC emacs-lisp :tangle init.el
(require 'package)

(setq package-archives
      '(("gnu" . "https://elpa.gnu.org/packages/")
		("melpa" . "https://melpa.org/packages/")))

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(setq use-package-always-ensure t
      use-package-verbose t)
#+END_SRC

* Emacs
This section modifies built in package settings or settings without a corresponding package.
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package emacs
  :ensure nil
  :preface
  ;; intuitive split settings
  (defun noncog/split-and-follow-horizontally ()
    "Split window below."
    (interactive)
    (split-window-below)
    (other-window 1))
  (defun noncog/split-and-follow-vertically ()
    "Split window right."
    (interactive)
    (split-window-right)
    (other-window 1))
  ;; prevent functions from hiding windows. used by calling advice, see org section for example
  (defun noncog/no-delete-windows (oldfun &rest args)
	(cl-letf (((symbol-function 'delete-other-windows) 'ignore)) (apply oldfun args)))
  :config
  ;; basic interface configuration
  (set-face-attribute 'default nil :font "Fira Code") ; set font
  (set-cursor-color "#ff79c6")                        ; set cursor color
  (tool-bar-mode -1)                                  ; disable the toolbar
  (menu-bar-mode -1)                                  ; disable the menu bar
  (tooltip-mode -1)                                   ; disable tooltips
  (scroll-bar-mode -1)                                ; disable visible scrollbar
  (line-number-mode 1)                                ; enable line number in minibuffer lighter
  (column-number-mode 1)                              ; enable column number in minibuffer lighter
  (setq visible-bell nil)                             ; disable screen flashing at end of file
  (setq inhibit-startup-screen t)                     ; removes startup splash-screen/message
  ;; behavior
  (global-auto-revert-mode 1)                         ; autoloads changes to files
  (setq-default load-prefer-newer t)                  ; loads newer versions of packages
  (delete-selection-mode 1)                           ; replaces active region by typing
  (setq show-parens-delay 0)                          ; remove delay of showing parenthesis
  (show-paren-mode 1)                                 ; show matching parenthesis
  (setq help-window-select t)                         ; auto select help windows when created
  (setq backup-directory-alist                        ; move backup files to folder instead of littering
		'(("." . "~/.config/cogmacs/file-backups")))
  ;; custom buffer windowing
  (add-to-list 'display-buffer-alist '("*Apropos*" display-buffer-same-window))
  (add-to-list 'display-buffer-alist '("*Help*" display-buffer-same-window))
  (add-to-list 'display-buffer-alist '("*Warning*" display-buffer-at-bottom))
  ;; smooth scrolling
  (setq scroll-step 1)                                ; scroll window one line at a time
  (setq scroll-conservatively 101)                    ; value above 100 removes half page jump
  (setq auto-window-vscroll nil)                      ; default to above scroll settings per window, never change them
  ;; line numbers for specific modes                  ; to find mode-hooks, when in mode/file do C-h v major-mode RET. Or C-h m.
  (dolist (mode '(sh-mode-hook
		  conf-mode-hook))                      ; all conf-modes inherit this property. no-info on this variable, but works. 
  (add-hook mode (lambda () (display-line-numbers-mode 1))))
  ;; global keybinds
  (global-set-key (kbd "C-=") 'text-scale-increase)   ; set zoom in
  (global-set-key (kbd "C--") 'text-scale-decrease)   ; set zoom out
  ;; custom intuitive split settings
  (global-set-key (kbd "C-x 2") #'noncog/split-and-follow-horizontally)
  (global-set-key (kbd "C-x 3") #'noncog/split-and-follow-vertically)
  )
#+END_SRC

* Delight
Use-package has support for both diminish and delight, which are packages used for hiding minor-mode lighters from the modeline. I prefer delight as the documentation is better and diminish failed me. I may one day switch to minions to hide all lighters behind an icon. Or use mood-line or doom Semodeline.
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package delight)
#+END_SRC

* Org Mode
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package org
  :preface
  (defun noncog/org-heading-size ()
    "set org headings to same size - theme and face independent"
    (dolist (face '(org-level-1
		    org-level-2
		    org-level-3
		    org-level-4
		    org-level-5))
      (set-face-attribute face nil :weight 'semi-bold :height 1.0)))
  :hook
  ((org-mode . visual-line-mode)                      ; enable line wrapping
   (org-mode . org-indent-mode)                       ; enable virtual indents and hide leading stars for readability
   (org-mode . noncog/org-heading-size))              ; enable custom org-heading-size
  :config
  ;; settings
  ;; looks
  (setq org-ellipsis " ▾")                            ; set custom ellipsis
  (setq org-hide-emphasis-markers t)                  ; hide formatting for markup
  (setq org-edit-src-content-indentation 0)           ; prevent adding spaces/indents to source code blocks
  ;(setq org-src-preserve-indentation t)               ; don't change indents, or add any spaces
  ;; logging
  (setq org-agenda-start-with-log-mode t)             ; show 'completed' done items in agenda
  (setq org-log-done 'time)                           ; add completion time to DONE items.
  (setq org-log-into-drawer t)                        ; puts log times into a drawer to hide them
  ;; behavior
  (setq org-return-follows-link t)                    ; enter opens links in org
  (setq org-capture-bookmark nil)                     ; prevent org capture from adding to bookmarks list
  (setq org-use-fast-todo-selection 'expert)          ; prevent org-todo from modifying windows
  ;; custom org note windowing
  (advice-add 'org-add-log-note :around 'noncog/no-delete-windows) ; prevent from hiding other windows
  (add-to-list 'display-buffer-alist '("*Org Note*" (display-buffer-below-selected) (window-height . 10))) ; display buffer in this window
  ;; custom org capture windowing
  (with-eval-after-load "org-capture" (advice-add 'org-capture-place-template :around 'noncog-no-delete-windows)) ; prevent from hiding other windows
  (add-to-list 'display-buffer-alist '("*Org Select*" (display-buffer-at-bottom) (window-height . 15))) ; display buffer at bottom
  (add-to-list 'display-buffer-alist '("CAPTURE-.note" (display-buffer-at-bottom) (window-height . 15))) ; display buffer at bottom
  
  ;; directories and files
  (setq org-directory "~/documents/org")              ; set org file directory - only used for some prompt for capturing
  (setq org-agenda-files '("~/documents/org"))         ; set org agenda directory or list of files to query
  (setq org-default-notes-file "~/documents/org/notes.org")
  ;; custom todo states and tags                                            ; ! timestamp 
  (setq org-todo-keywords                                                   ; @ note      
      '((sequence "TODO(t)" "WAIT(w@/!)" "|" "DONE(d!)" "CANCELED(c@/!)"))) ; / settings to use when leaving state: ! or @
  ;; global keybinds                                                        
  (global-set-key (kbd "C-c l") 'org-store-link)
  (global-set-key (kbd "C-c a") 'org-agenda)
;  (global-set-key (kbd "C-c c") 'noncog-org-capture)
  (global-set-key (kbd "C-c c") 'org-capture)
  ;; hiding minibuffer lighters
  :delight
  (org-indent-mode nil org-indent)                    ; hide indent-mode 
  (visual-line-mode nil emacs))                       ; hide visual-line-mode
#+END_SRC

** Org Bullets
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package org-bullets
  :after org                                          ; ensures org-bullets package is loaded after org package
  :hook (org-mode . org-bullets-mode)                 ; start bullets-mode after org-mode
  :config
  (setq org-bullets-bullet-list '("Ͻ" "✖" "➖" "❯" "○" "➡" "➕" "⬤"))
  )
#+END_SRC
Here are some custom utf-8 symbols I've been toying with:
#+BEGIN_SRC
Default:
("◉" "○" "✸" "✿")
➜ ▸ ➡ ❯ ➤ ▻ ▹ ► ▷ ▸
 ◢ ◣ ◤ ◥
⚊ − — ➖ 〜 ┅ ✚ ➕ ✘
▾ ⬇ ▽
◎ ● ◐ ◑ ◒ ◓ ◖ ◗
⬤ Փ ○ ✦ ✧
□ ■ ▣ ▤ ▢ ⬕ ⬖ ⬗ ⬘ ⬙ ◆ ◇
⚞ ☰ ▰ ▱ ▮ ▯ ╺ ╼
⚖ ⚗ ☥
#+END_SRC

** Org Noter
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package org-noter
  :config
  ;; settings
  (setq org-noter-always-create-frame nil)            ; prevent noter from making a new frame
  )           
#+END_SRC

* Counsel/Ivy/Swiper
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package counsel
  :config
  ;; settings
  (setq ivy-count-format "(%d/%d) ")
  ; global keybinds
  (global-set-key (kbd "C-s") 'swiper-isearch)
  (global-set-key (kbd "M-x") 'counsel-M-x)
  (global-set-key (kbd "C-x C-f") 'counsel-find-file)
  (global-set-key (kbd "C-x b") 'counsel-switch-buffer)
  (global-set-key (kbd "C-c b") 'counsel-bookmark)
  (global-set-key (kbd "C-c d") 'counsel-descbinds)
  (global-set-key (kbd "C-h f") 'counsel-describe-function)
  (global-set-key (kbd "C-h v") 'counsel-describe-variable)
  ;; start mode
  (ivy-mode 1)
  ;; hiding minibuffer lighters
  :delight ivy-mode                                   ; hide ivy-mode
  )
#+END_SRC

* Ivy Rich
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package ivy-rich
  :after ivy                                          ; ensures ivy-rich package is loaded after ivy
  :config
  ;; settings
  (setq ivy-initial-inputs-alist nil)                 ; removes ^ from ivy, means can search any words in commands
  ;; start mode
  (ivy-rich-mode 1)
  )
#+END_SRC

* Ace-Window
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package ace-window
  :config
  ;; settings
  (setq aw-background nil)                            ; removes black overlay
  (setq aw-keys '(?a ?s ?d ?f ?g ?h ?j ?k ?l))        ; switch from number keys to home row keys for window-ids
  ;(setq aw-dispatch-always t)                         ; enables ace-window for any window count
  ;; global keybinds
  (global-set-key (kbd "M-o") 'ace-window)
  )
#+END_SRC

* Pulsar
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package pulsar
  :config
  ;; note - not using pulsar-pulse-functions and defining them all
  (setq pulsar-pulse-on-window-change t)
  (setq pulsar-pulse t)
  (setq pulsar-delay 0.055)
  (setq pulsar-iterations 10)
  (setq pulsar-face 'pulsar-magenta)
  (setq pulsar-highlight-face 'pulsar-yellow)
  
(pulsar-global-mode 1))
#+END_SRC
* PDF Tools
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package pdf-tools
  ;; mode keybind
  :bind (:map pdf-view-mode-map ("C-s" . isearch-forward)) ; use isearch instead of ivy-search in pdf-mode as it breaks it
  :config
  ;; settings
  (setq-default pdf-view-display-size 'fit-page)      ; fit pdf to window
  )
;; start mode
(pdf-tools-install)                                   ; fails to start inside of :config, put here instead.
#+END_SRC

* Projectile
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package projectile
  :bind-keymap ("C-c p" . projectile-command-map)
  :config
  ;; settings
  (setq projectile-project-search-path '("~/projects/"))
  (setq projectile-completion-system 'ivy)
  ;; start mode
  (projectile-mode)
  ;; hiding minibuffer lighters
  :delight '(:eval (concat " " (projectile-project-name)))) ; use custom projectile minibuffer lighter with project name
#+END_SRC

* Dashboard
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package dashboard
  :init
  (setq initial-buffer-choice (lambda () (get-buffer-create "*dashboard*"))) ; set new frames from emacsclient -c to dashboard
  :config
  ;; settings
  (setq dashboard-center-content t                    ; center dashboard
        dashboard-set-init-info nil)                  ; hide package and load time info
  (setq dashboard-items '((recents  . 5)              ; customize dashboard items
                          (agenda . 5)
                          (projects . 5)
                          (bookmarks . 5)))
  ;; start mode
  (dashboard-setup-startup-hook)
  ;; hiding minibuffer lighters
  :delight dashboard-mode                             ; hide dashboard-mode
  )
#+END_SRC

* Which Key
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package which-key
  :config
  ;; settings
  (setq which-key-idle-delay 0.5)
  ;; start mode
  (which-key-mode)
  ;; hiding minibuffer lighters
  :delight which-key-mode                             ; hide which-key-mode
  )
#+END_SRC

* Dracula Theme
I use *Dracula* theme everywhere I can. Check it out: [[https://draculatheme.com/][here]]
#+BEGIN_SRC emacs-lisp :tangle init.el
(use-package dracula-theme
  :config
  (load-theme 'dracula t)
  )
#+END_SRC

* Tips
- C-h k - Gives info about keybinds you can use for setting them.

- To see current modes:
  - C-h v major-mode RET - lists major-mode
  - C-h m - lists minor-modes

- display-line-numbers-mode is faster than linum-mode
  - linum-mode adds a gutter to the left. See: https://www.reddit.com/r/emacs/comments/tf9u4e/line_number_display/
  - I display line numbers per major mode I want to use it with. Not globally and disable per mode I don't.
     - I want to do this so that it does not show up in the list of enabled modes
       
- If you want to know which package a variable belongs to, do C-h v or M-x describe-variable followed by the var name (for a function name, C-h f or M-x describe-function). From the *Help* window that pops up, navigate to the package's .el file and see the (provide ..) call to find out the package name.

- setq-default sets the global variable compared to setq which sets local buffer variable.
