(("cogmacs" . ((user-emacs-directory . "~/.config/cogmacs")
               (server-name . "cogmacs")))
 ("doom" . ((user-emacs-directory . "/opt/doom")
            (server-name . "doom")
            (env . (("DOOMDIR" . "~/.config/doom"))))))
