#+tags: export noexport
#+export_exclude_tags: exclude noexport

#+startup: show2levels hideblocks

#+html:<div align="center">
* Yabai

#+begin_html
<a href="https://orgmode.org"><img src="https://img.shields.io/badge/Org-literate%20config-%2377aa99?style=flat-square&logo=org&logoColor=white"></a>
<a href="https://www.gnu.org/software/emacs/"><img src="https://img.shields.io/badge/Made_with-Emacs-blueviolet.svg?style=flat-square&logo=GNU%20Emacs&logoColor=white"></a>

<p><code><a href="https://github.com/koekeishiya/yabai">Yabai</a></code> is an open source tiling window manager for macOS.</p>

</div>
#+end_html

** Controls
These controls allow me to execute shell commands from within org-mode.

[[shell:brew services restart yabai][Restart Yabai]]

** Startup
*** Load Scripting Additions

The following is required to enable scripting additions at startup.

#+begin_src sh :tangle yabairc :shebang "#!/usr/bin/env sh"
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
#+end_src

*** Debugging

#+begin_src sh :tangle yabairc
yabai -m config debug_output on
#+end_src

** Settings
*** List of Options :noexport:

#+begin_src sh :tangle no
# active_window_border_color  0xff775759   \ # Color of the border of focused window.
# active_window_opacity       1.0          \ # Opacity of the focused window.
# auto_balance                off          \ # Balance the window tree upon change so all windows occupy same area.
# bottom_padding              12           \
# focus_follows_mouse         off          \ # Auto focus window under mouse.
# insert_feedback_color       0xffd75f5f   \ # Color of the window --insert message selection.
# layout                      bsp          \
# left_padding                12           \
# mouse_action1               move         \ # Action performed when pressing mouse_modifier + button1.
# mouse_action2               resize       \ # Action performed when pressing mouse_modifier + button2.
# mouse_drop_action           swap         \ # Action performed when bsp-managed window is dropped in the center another managed window.
# mouse_follows_focus         off          \ # When focus window, put mouse at center.
# mouse_modifier              fn           \ # Keyboard modifier used for moving and resizing windows.
# normal_window_border_color  0xff555555   \ # Color of the unfocused window.
# normal_window_opacity       0.90         \ # Opacity of an unfocused window.
# right_padding               12           \
# split_ratio                 0.50         \ # Specify size distribution when window is split.
# split_type                  auto         \ # Specify how a window should be split. [vertical|horizontal|auto]
# top_padding                 12           \
# window_animation_duration   0.0          \ # Duration of window frame animation. If 0.0 change in dimension not animated. Requires screen recording permissions.
# window_animation_frame_rate 120          \ # Frame rate of window frame animation. Expressed in FPS.
# window_border               off          \ # Draw a border for windows.
# window_border_blur          off          \ # Blur border allowing it to act as a backdrop for transparent windows.
# window_border_hidpi         on           \ # Draw border in high resolution mode. Uses significantly more memory.
# window_border_radius        12           \ # Radius of window border.
# window_border_width         4            \ # Width of window borders. If given width is odd, will be incremented by 1.
# window_gap                  06           \
# window_opacity              off          \ # Enable opacity for windows.
# window_opacity_duration     0.0          \ # Duration of transition between active / normal opacity.
# window_origin_display       default      \ # Specify display new windows are managed in.
# window_placement            second_child \ # Specify if managed window becomes 1st or 2nd leaf-node.
# window_shadow               on           \ # Draw shadows for windows.
# window_topmost              off          \ # Make floating windows stay on top.
# window_zoom_persist         on           \ # Windows keep zoom-state through layout changes.
# debug_output                off          \ # Enable output of debug info to stdout.
# external_bar                off          \ # Specify padding for external bar.
#+end_src

*** Default Layout

#+begin_src sh :tangle yabairc
yabai -m config layout bsp
#+end_src

*** Floating Windows

Keep floating windows on top.

#+begin_src sh :tangle yabairc
yabai -m config window_topmost on
#+end_src

** Looks
*** Gaps

#+begin_src sh :tangle yabairc
yabai -m config top_padding    10
yabai -m config bottom_padding 10
yabai -m config left_padding   10
yabai -m config right_padding  10
yabai -m config window_gap     10
#+end_src

*** Window Borders

#+begin_src sh :tangle yabairc
yabai -m config active_window_border_color  0xff6272A4
yabai -m config normal_window_border_color  0xff555555
yabai -m config window_border               on
yabai -m config window_border_blur          off
yabai -m config window_border_hidpi         off
yabai -m config window_border_width         2
#+end_src

*** Window Shadows

#+begin_src sh :tangle yabairc
yabai -m config window_shadow off
#+end_src

** Workspace Apps
*** Ignore List

These apps won't be tiled.

#+begin_src sh :tangle yabairc
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Open Cycle Time$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Barrier$" manage=off sticky=on
#+end_src

*** Assign Apps to Spaces

#+begin_src sh :tangle yabairc
yabai -m rule --add app="^Emacs$" space=^1
yabai -m rule --add app="^LibreWolf$" space=^2
yabai -m rule --add app="^Firefox$" space=^2
yabai -m rule --add app="^Safari$" space=^2
yabai -m rule --add app="^(CLion|PyCharm)$" space=^3
yabai -m rule --add app="^Gimp$" space=^4
yabai -m rule --add app="^Blender$" space=^5
yabai -m rule --add app="^Anki$" space=^6
yabai -m rule --add app="^Tor Browser$" space=^7
yabai -m rule --add app="kitty" space=^8
yabai -m rule --add app="^Discord" space=^9
#+end_src

*** Name Spaces

#+begin_src sh :tangle yabairc
# yabai -m space 1 --label "Emacs"
# yabai -m space 2 --label "Safari"
# yabai -m space 8 --label "Kitty"
#+end_src

** Signals

*** Quit Programs When Last Window Destroyed

This type of signal can be used to automatically detect when a program no longer has windows and should be quit. This is a "feature" of macOS that I have always disliked. Let's fix it.

#+begin_src sh :tangle yabairc
yabai -m signal --add event=window_destroyed app="^Firefox$" action="osascript -e 'quit app \"Firefox\"'" active=yes
#+end_src

#+begin_src sh :tangle yabairc
yabai -m signal --add event=window_destroyed app="^LibreWolf$" action="osascript -e 'quit app \"LibreWolf\"'" active=yes
#+end_src

*** Automatically Resize SketchyBar

Whenever the screen resolution changes, restart sketchybar, which has a helper script to detect the new menu bar height.

#+begin_src sh :tangle yabairc
yabai -m signal --add event=display_resized action="brew services restart sketchybar"
#+end_src

*** Fix Emacs Window Focus

This is an issue that arises for me using =emacsclient= and a patch from emacs-plus: =--with-no-frame-refocus=. This fix automatically refocuses an Emacs window in the space after I close one. The reason I'm using this patch is to prevent the default behavior where Emacs will focus another frame if you close one. This is intended for use with emacs-everywhere and org-protocol.

#+begin_src sh :tangle yabairc
yabai -m signal --add event=window_destroyed app="^Emacs$" action="yabai -m display --focus 1" active=yes
#+end_src

Always focus a newly created Emacs window.

#+begin_src sh :tangle yabairc
yabai -m signal --add event=window_created app="^Emacs$" action="yabai -m window --focus \$YABAI_WINDOW_ID"
#+end_src

The effect of this signal is to focus Emacs after a non-Emacs window on the same space is closed.

#+begin_src sh :tangle yabairc
yabai -m signal --add event=window_resized app="^Emacs$" action="yabai -m display --focus 1" active=no
#+end_src

*** Fix Firefox Window Focus

Always focus a newly created Firefox window.

#+begin_src sh :tangle yabairc
yabai -m signal --add event=window_created app="^Firefox$" action="yabai -m window --focus \$YABAI_WINDOW_ID"
#+end_src

#+begin_src sh :tangle yabairc
yabai -m signal --add event=window_created app="^LibreWolf$" action="yabai -m window --focus \$YABAI_WINDOW_ID"
#+end_src

