#+tags: export noexport
#+export_exclude_tags: exclude noexport

#+startup: show2levels hideblocks

#+html:<div align="center">

* Yabai

#+begin_html
<a href="https://orgmode.org"><img src="https://img.shields.io/badge/Org-literate%20config-%2377aa99?style=flat-square&logo=org&logoColor=white"></a>
<a href="https://www.gnu.org/software/emacs/"><img src="https://img.shields.io/badge/Made_with-Emacs-blueviolet.svg?style=flat-square&logo=GNU%20Emacs&logoColor=white"></a>

<p><code><a href="https://github.com/koekeishiya/yabai">Yabai</a></code> is an open source tiling window manager for macOS.</p>

</div>
#+end_html

** Settings
*** List of Options :noexport:

#+begin_src sh :tangle no
# active_window_border_color  0xff775759   \ # Color of the border of focused window.
# active_window_opacity       1.0          \ # Opacity of the focused window.
# auto_balance                off          \ # Balance the window tree upon change so all windows occupy same area.
# bottom_padding              12           \
# focus_follows_mouse         off          \ # Auto focus window under mouse.
# insert_feedback_color       0xffd75f5f   \ # Color of the window --insert message selection.
# layout                      bsp          \
# left_padding                12           \
# mouse_action1               move         \ # Action performed when pressing mouse_modifier + button1.
# mouse_action2               resize       \ # Action performed when pressing mouse_modifier + button2.
# mouse_drop_action           swap         \ # Action performed when bsp-managed window is dropped in the center another managed window.
# mouse_follows_focus         off          \ # When focus window, put mouse at center.
# mouse_modifier              fn           \ # Keyboard modifier used for moving and resizing windows.
# normal_window_border_color  0xff555555   \ # Color of the unfocused window.
# normal_window_opacity       0.90         \ # Opacity of an unfocused window.
# right_padding               12           \
# split_ratio                 0.50         \ # Specify size distribution when window is split.
# split_type                  auto         \ # Specify how a window should be split. [vertical|horizontal|auto]
# top_padding                 12           \
# window_animation_duration   0.0          \ # Duration of window frame animation. If 0.0 change in dimension not animated. Requires screen recording permissions.
# window_animation_frame_rate 120          \ # Frame rate of window frame animation. Expressed in FPS.
# window_border               off          \ # Draw a border for windows.
# window_border_blur          off          \ # Blur border allowing it to act as a backdrop for transparent windows.
# window_border_hidpi         on           \ # Draw border in high resolution mode. Uses significantly more memory.
# window_border_radius        12           \ # Radius of window border.
# window_border_width         4            \ # Width of window borders. If given width is odd, will be incremented by 1.
# window_gap                  06           \
# window_opacity              off          \ # Enable opacity for windows.
# window_opacity_duration     0.0          \ # Duration of transition between active / normal opacity.
# window_origin_display       default      \ # Specify display new windows are managed in.
# window_placement            second_child \ # Specify if managed window becomes 1st or 2nd leaf-node.
# window_shadow               on           \ # Draw shadows for windows.
# window_topmost              off          \ # Make floating windows stay on top.
# window_zoom_persist         on           \ # Windows keep zoom-state through layout changes.
# debug_output                off          \ # Enable output of debug info to stdout.
# external_bar                off          \ # Specify padding for external bar.
#+end_src

*** Load Scripting Additions

The following is required to enable scripting additions at startup.

#+begin_src sh :tangle yabairc :shebang "#!/usr/bin/env sh"
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
#+end_src

*** Debugging

#+begin_src sh :tangle yabairc
yabai -m config debug_output off
#+end_src

*** Default Layout

#+begin_src sh :tangle yabairc
yabai -m config layout bsp
#+end_src

*** Floating Windows

Prevent floating windows from spawning behind others...

#+begin_src sh :tangle yabairc
yabai -m config window_topmost off
#+end_src

** Utilities

Using the following settings I implement the scratchpad functionality from i3 as well as several convenience functions.

*** Windows
**** Focused Window

#+begin_src sh :tangle yabairc
yabai -m signal --add event=window_focused action="printf "%s" \$YABAI_WINDOW_ID > \$HOME/.config/yabai/state/focused_window_id"
#+end_src

*** Spaces
**** Focused Space

#+begin_src sh :tangle yabairc
yabai -m signal --add event=space_changed action="\$HOME/.config/yabai/scripts/focused_space.sh \$YABAI_SPACE_ID"
#+end_src

**** Scratchpad Space

#+begin_src sh :tangle yabairc
source "$HOME/.config/yabai/scripts/update_scratchpad_space.sh"
#+end_src

*** Sketchybar
**** Automatically Resize SketchyBar

Whenever the screen resolution changes, restart sketchybar, which has a helper script to detect the new menu bar height to match the height in pixels of the notch in the screen.

#+begin_src sh :tangle yabairc
yabai -m signal --add event=display_resized action="brew services restart sketchybar"
#+end_src

** Appearance
*** Window Borders

#+begin_src sh :tangle yabairc
yabai -m config active_window_border_color  0xff6272A4
yabai -m config normal_window_border_color  0xff555555
yabai -m config window_border               on
yabai -m config window_border_blur          off
yabai -m config window_border_hidpi         off
yabai -m config window_border_width         1
#+end_src

*** Window Shadows

#+begin_src sh :tangle yabairc
yabai -m config window_shadow off
#+end_src

*** Window Animatinos

#+begin_src sh :tangle yabairc
yabai -m config window_animation_duration 0.0
#+end_src

*** Gaps

#+begin_src sh :tangle yabairc
yabai -m config top_padding    12
yabai -m config bottom_padding 8
yabai -m config left_padding   8
yabai -m config right_padding  8
yabai -m config window_gap     8
#+end_src

** Controls

I use Vim based movement binds with Yabai. These keybinds mirror my Linux configuration using i3 as much as possible.

*** Focus Windows

#+begin_src conf :tangle ~/.config/skhd/skhdrc
alt - h [
  ,*      : yabai -m window --focus west
  "Emacs" ~
]
alt - j  [
  ,*      : yabai -m window --focus south
  "Emacs" ~
]
alt - k  [
  ,*      : yabai -m window --focus north
  "Emacs" ~
]
alt - l  [
  ,*      : yabai -m window --focus east
  "Emacs" ~
]
#+end_src

*** Move Windows

#+begin_src conf :tangle ~/.config/skhd/skhdrc
shift + alt - h : yabai -m window --swap west
shift + alt - j : yabai -m window --swap south
shift + alt - k : yabai -m window --swap north
shift + alt - l : yabai -m window --swap east
#+end_src

**** Warp Windows

#+begin_src conf :tangle ~/.config/skhd/skhdrc
shift + alt + cmd - h : yabai -m window --warp west
shift + alt + cmd - j : yabai -m window --warp south
shift + alt + cmd - k : yabai -m window --warp north
shift + alt + cmd - l : yabai -m window --warp east
#+end_src

*** Split Windows

#+begin_src conf :tangle ~/.config/skhd/skhdrc
alt - s  [
  ,*      : yabai -m window --toggle split
  "Emacs" ~
]
alt - v  [
  ,*      : yabai -m window --toggle split
  "Emacs" ~
]
#+end_src

*** Kill Windows

#+begin_src conf :tangle ~/.config/skhd/skhdrc
shift + alt - q  [
  ,*      : yabai -m window --close
  "Emacs" ~
]
#+end_src

*** Floating Window Controls
*** Layout Controls

#+begin_src conf :tangle ~/.config/skhd/skhdrc
alt - f11 : yabai -m window --toggle zoom-fullscreen
#+end_src

*** Resize Windows
**** Balance Windows

#+begin_src conf :tangle ~/.config/skhd/skhdrc
alt - 0x18  [
  ,*      : yabai -m space --balance
  "Emacs" ~
]
#+end_src

** Workspace and Applications
*** Ignore List

These apps won't be tiled.

#+begin_src sh :tangle yabairc
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Open Cycle Time$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Barrier$" manage=off
#+end_src

*** Emacs

#+begin_src sh :tangle yabairc
yabai -m rule --add app="Emacs$" space=^1
#+end_src

#+begin_src conf :tangle ~/.config/skhd/skhdrc
alt - e : yabai -m space --focus 1
shift + alt - e : emacsclient -c -n --alternate-editor=""
cmd + shift + alt - e : yabai -m window --space 1; yabai -m space --focus 1
#+end_src

*** Firefox

#+begin_src sh :tangle yabairc
yabai -m rule --add app="Firefox$" space=^2
yabai -m rule --add app="LibreWolf$" space=^2
#+end_src

#+begin_src conf :tangle ~/.config/skhd/skhdrc
alt - f : yabai -m space --focus 2
shift + alt - f : export MOZ_DISABLE_SAFE_MODE_KEY=1; /opt/homebrew/bin/librewolf -profile $HOME/.config/firefox/noncog
cmd + shift + alt - f : yabai -m window --space 2; yabai -m space --focus 2
#+end_src

**** Quit Browsers When Last Window Destroyed

This type of signal can be used to automatically detect when a program no longer has windows and should be quit. This is a "feature" of macOS that I have always disliked. Let's fix it.

#+begin_src sh :tangle yabairc
yabai -m signal --add event=window_destroyed app="^Firefox$" action="osascript -e 'quit app \"Firefox\"'" active=yes
#+end_src

#+begin_src sh :tangle yabairc
yabai -m signal --add event=window_destroyed app="^LibreWolf$" action="osascript -e 'quit app \"LibreWolf\"'" active=yes
#+end_src

#+begin_src sh :tangle yabairc
yabai -m signal --add event=window_destroyed app="^Safari$" action="osascript -e 'quit app \"Safari\"'" active=yes
#+end_src

*** Safari

#+begin_src sh :tangle yabairc
yabai -m rule --add app="Safari$" space=^2
#+end_src

*** Tor

#+begin_src sh :tangle yabairc
yabai -m rule --add app="Tor Browswer$" space=^2
#+end_src

#+begin_src conf :tangle ~/.config/skhd/skhdrc
alt - t : yabai -m space --focus 2
shift + alt - t : open -n -a "Tor Browser"
cmd + shift + alt - t : yabai -m window --space 2; yabai -m space --focus 2
#+end_src

*** Code (IDE)

#+begin_src sh :tangle yabairc
yabai -m rule --add app="(CLion|PyCharm)$" space=^3
#+end_src

#+begin_src conf :tangle ~/.config/skhd/skhdrc
alt - c : yabai -m space --focus 3
shift + alt - c : open -n -a "CLion"
cmd + shift + alt - c : yabai -m window --space 3; yabai -m space --focus 3
#+end_src

*** Blender

#+begin_src sh :tangle yabairc
yabai -m rule --add app="(Gimp|Blender)$" space=^4
#+end_src

#+begin_src conf :tangle ~/.config/skhd/skhdrc
alt - b : yabai -m space --focus 5
shift + alt - b : open -n -a "Blender"
cmd + shift + alt - b : yabai -m window --space 5; yabai -m space --focus 5
#+end_src

*** Kitty

#+begin_src conf :tangle ~/.config/skhd/skhdrc
alt - return : $HOME/.config/yabai/scripts/scratchpad.sh "kitty"
shift + alt - return : $HOME/.config/yabai/scripts/launch_one_instance.sh "kitty" "open -n -a "kitty""
#+end_src

**** Scratchpad App Setup

#+begin_src sh :tangle yabairc
yabai -m rule --add app="kitty" grid=6:6:1:1:4:4 manage=off
#+end_src

#+begin_src sh :tangle yabairc
yabai -m signal --add event=window_created action="\$HOME/.config/yabai/scripts/scratchpad_win_id.sh \$YABAI_WINDOW_ID kitty" app="kitty"
#+end_src

#+begin_src sh :tangle yabairc
yabai -m signal --add event=window_destroyed action="\$HOME/.config/yabai/scripts/scratchpad_win_id_reset.sh kitty" app="kitty"
#+end_src

*** Discord


#+begin_src conf :tangle ~/.config/skhd/skhdrc
alt - d : $HOME/.config/yabai/scripts/scratchpad.sh "Discord"
shift + alt - d : open -n -a "Discord"
#+end_src

**** Scratchpad App Setup

#+begin_src sh :tangle yabairc
yabai -m rule --add app="^Discord" grid=10:10:1:0:8:10 manage=off
#+end_src

#+begin_src sh :tangle yabairc
yabai -m signal --add event=window_focused action="\$HOME/.config/yabai/scripts/scratchpad_win_id.sh \$YABAI_WINDOW_ID Discord" app="Discord"
#+end_src

#+begin_src sh :tangle yabairc
yabai -m signal --add event=window_destroyed action="\$HOME/.config/yabai/scripts/scratchpad_win_id_reset.sh Discord" app="Discord"
#+end_src

*** Spotify

#+begin_src conf :tangle ~/.config/skhd/skhdrc
alt - m : $HOME/.config/yabai/scripts/scratchpad.sh "Spotify"
shift + alt - m : open -n -a "Spotify"
#+end_src

**** Scratchpad App Setup

#+begin_src sh :tangle yabairc
yabai -m rule --add app="Spotify" grid=6:6:1:1:4:4 manage=off
#+end_src

#+begin_src sh :tangle yabairc
yabai -m signal --add event=window_created action="\$HOME/.config/yabai/scripts/scratchpad_win_id.sh \$YABAI_WINDOW_ID Spotify" app="Spotify"
#+end_src

#+begin_src sh :tangle yabairc
yabai -m signal --add event=window_destroyed action="\$HOME/.config/yabai/scripts/scratchpad_win_id_reset.sh Spotify" app="Spotify"
#+end_src

*** YouTube
