#!/usr/bin/env sh
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config debug_output off

yabai -m config layout bsp

yabai -m config window_topmost off

yabai -m signal --add event=window_focused action="printf "%s" \$YABAI_WINDOW_ID > \$HOME/.config/yabai/state/focused_window_id"

yabai -m signal --add event=space_changed action="\$HOME/.config/yabai/scripts/focused_space.sh \$YABAI_SPACE_ID"

source "$HOME/.config/yabai/scripts/update_scratchpad_space.sh"

yabai -m signal --add event=display_resized action="brew services restart sketchybar"

yabai -m config active_window_border_color  0xff6272A4
yabai -m config normal_window_border_color  0xff555555
yabai -m config window_border               on
yabai -m config window_border_blur          off
yabai -m config window_border_hidpi         off
yabai -m config window_border_width         1

yabai -m config window_shadow off

yabai -m config window_animation_duration 0.0

yabai -m config top_padding    12
yabai -m config bottom_padding 8
yabai -m config left_padding   8
yabai -m config right_padding  8
yabai -m config window_gap     8

yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Open Cycle Time$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Barrier$" manage=off

yabai -m rule --add app="Emacs$" space=^1

yabai -m rule --add app="Firefox$" space=^2
yabai -m rule --add app="LibreWolf$" space=^2

yabai -m signal --add event=window_destroyed app="^Firefox$" action="osascript -e 'quit app \"Firefox\"'" active=yes

yabai -m signal --add event=window_destroyed app="^LibreWolf$" action="osascript -e 'quit app \"LibreWolf\"'" active=yes

yabai -m signal --add event=window_destroyed app="^Safari$" action="osascript -e 'quit app \"Safari\"'" active=yes

yabai -m rule --add app="Safari$" space=^2

yabai -m rule --add app="Tor Browswer$" space=^2

yabai -m rule --add app="(CLion|PyCharm)$" space=^3

yabai -m rule --add app="(Gimp|Blender)$" space=^4

yabai -m rule --add app="kitty" grid=6:6:1:1:4:4 manage=off

yabai -m signal --add event=window_created action="\$HOME/.config/yabai/scripts/scratchpad_win_id.sh \$YABAI_WINDOW_ID kitty" app="kitty"

yabai -m signal --add event=window_destroyed action="\$HOME/.config/yabai/scripts/scratchpad_win_id_reset.sh kitty" app="kitty"

yabai -m rule --add app="^Discord" grid=10:10:1:0:8:10 manage=off

yabai -m signal --add event=window_focused action="\$HOME/.config/yabai/scripts/scratchpad_win_id.sh \$YABAI_WINDOW_ID Discord" app="Discord"

yabai -m signal --add event=window_destroyed action="\$HOME/.config/yabai/scripts/scratchpad_win_id_reset.sh Discord" app="Discord"

yabai -m rule --add app="Spotify" grid=6:6:1:1:4:4 manage=off

yabai -m signal --add event=window_created action="\$HOME/.config/yabai/scripts/scratchpad_win_id.sh \$YABAI_WINDOW_ID Spotify" app="Spotify"

yabai -m signal --add event=window_destroyed action="\$HOME/.config/yabai/scripts/scratchpad_win_id_reset.sh Spotify" app="Spotify"
