#!/usr/bin/env sh
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config debug_output off

yabai -m config layout bsp

yabai -m config window_topmost on

yabai -m config active_window_border_color  0xff6272A4
yabai -m config normal_window_border_color  0xff555555
yabai -m config window_border               on
yabai -m config window_border_blur          off
yabai -m config window_border_hidpi         off
yabai -m config window_border_width         2

yabai -m config window_shadow off

yabai -m config top_padding    10
yabai -m config bottom_padding 10
yabai -m config left_padding   10
yabai -m config right_padding  10
yabai -m config window_gap     10

yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Open Cycle Time$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Barrier$" manage=off

yabai -m rule --add app="^Emacs$" space=^1

yabai -m rule --add app="^(Firefox|LibreWolf|Safari|Tor Browswer)$" space=^2

yabai -m signal --add event=window_created app="^(Firefox|LibreWolf|Safari|Tor Browser)$" action="yabai -m window --focus \$YABAI_WINDOW_ID"

yabai -m signal --add event=window_destroyed app="^Firefox$" action="osascript -e 'quit app \"Firefox\"'" active=yes

yabai -m signal --add event=window_destroyed app="^LibreWolf$" action="osascript -e 'quit app \"LibreWolf\"'" active=yes

yabai -m signal --add event=window_destroyed app="^Safari$" action="osascript -e 'quit app \"Safari\"'" active=yes

yabai -m rule --add app="^(CLion|PyCharm)$" space=^3

yabai -m rule --add app="^(Gimp|Blender)$" space=^4

yabai -m rule --add app="kitty" space=^8

yabai -m rule --add app="^Discord" space=^9

yabai -m signal --add event=display_resized action="brew services restart sketchybar"
