#!/usr/bin/env bash

if [ "$1" == "sync" ]; then
    case "$OSTYPE" in
        linux*)
            emacsclient -e "(kill-emacs)"
            "$HOME"/.config/emacs/bin/doom sync
            emacs --daemon
            ;;
        darwin*)
            emacs_service="$(brew services list | grep "^emacs" | awk '{print $1}')"
            brew services stop "$emacs_service"
            "$HOME"/.config/emacs/bin/doom sync
            brew services start "$emacs_service"
            ;;
        *)
            echo "OS not supported"
            ;;
    esac
else
    "$HOME"/.config/emacs/bin/doom "$1"
fi
sleep 7
emacsclient -c &
