#+export_exclude_tags: exclude noexport
#+tags: export noexport

#+html:<div align="center">

* SketchyBar
#+begin_html
<p>
<a href="https://orgmode.org"><img src="https://img.shields.io/badge/Org-literate%20document-%2377aa99?style=flat-square&logo=org&logoColor=white"></a> <a href="https://www.gnu.org/software/emacs/"><img src="https://img.shields.io/badge/Made_with-Emacs-blueviolet.svg?style=flat-square&logo=GNU%20Emacs&logoColor=white"></a>
</p>
<p><code><a href="https://github.com/FelixKratz/SketchyBar">SketchyBar</a></code> is an open source status bar replacement for macOS.</p>
#+end_html

#+html:</div>

** About
*** Resources
- [[https://felixkratz.github.io/SketchyBar/config/bar][Documentation]]

*** Literate Configuration

It should be noted that I use a [[https://leanpub.com/lit-config/read][literate configuration]]. This enables me to have a single annotated file for a particular configuration which automatically writes out the actual configuration file from the .org file.

**** README.org != config files

#+begin_quote
*Warning:* README.org does not represent the actual config files because of my use of =noweb= blocks. This is done to better share the features I use, not how the configurations are actually written. For example, these code blocks are out of order compared to the actual files for easier viewing here on GitHub. To see 'under the hood', refer to the actual files and the raw README.org file.
#+end_quote

** Global Properties

This section sets the default values of the bar which will be inherited by future configurations.

*** Global Variables
**** Padding

#+begin_src sh :tangle no :noweb-ref defaults
PADDING=4
#+end_src

**** Fonts

#+begin_src sh :tangle no :noweb-ref defaults
FONT="Hack Nerd Font"
#+end_src

#+begin_src sh :tangle no :noweb-ref defaults
#FONT_LABEL=
#+end_src

#+begin_src sh :tangle no :noweb-ref defaults
#FONT_ICON=
#+end_src

**** Theme

This custom variable controls the theme of the bar.

#+begin_src sh :tangle no :noweb-ref defaults
THEME=1 # 1 = Dracula, 2 = Catppuccin Frappe, 3 = Catppuccin Mocha
#+end_src

**** Bar Type

This variable changes the design type of the bar. Coming soon...

#+begin_src sh :tangle no :noweb-ref defaults
#BAR_TYPE=1 # 1 = , 2 =
#+end_src

*** Bar Defaults

#+begin_src sh :tangle no :noweb-ref defaults
bar_defaults=(
    color=$BAR_COLOR
    border_color=$BORDER_COLOR
    position=top
    height=36
    margin=-2
    y_offset=-2
    corner_radius=0
    border_width=2
    blur_radius=30
    padding_left=15
    padding_right=15
    notch_width=200
    notch_offset=0
    display=main
    hidden=off
    topmost=off
    sticky=on
    font_smoothing=off
    shadow=off
)
#+end_src

*** Icon Defaults

#+begin_src sh :tangle no :noweb-ref defaults
icon_defaults=(
    icon.color=$ICON_COLOR
    icon.font="$FONT:Bold:17.0"
    icon.padding_left=$PADDING
    icon.padding_right=$PADDING
)
#+end_src

*** Label Defaults

#+begin_src sh :tangle no :noweb-ref defaults
label_defaults=(
    label.color=$LABEL_COLOR
    label.font="$FONT:Semibold:13.0"
    label.padding_left=$PADDING
    label.padding_right=$PADDING
)
#+end_src

*** Background Defaults

#+begin_src sh :tangle no :noweb-ref defaults
background_defaults=(
    background.height=26
    background.corner_radius=9
    background.border_width=2
    #background.padding_left=$PADDING
    #background.padding_right=$PADDING
)
#+end_src

*** Popup Defaults

#+begin_src sh :tangle no :noweb-ref defaults
popup_defaults=(
    #popup.height=30
    popup.background.border_width=2
    popup.background.corner_radius=9
    popup.background.color=$POPUP_COLOR
    popup.background.border_color=$POPUP_BORDER_COLOR
    #popup.horizontal=false
    #popup.background.shadow.drawing=on
    #popup.blur_radius=20
)
#+end_src

*** Set Defaults

#+begin_src sh :tangle no :noweb-ref defaults
sketchybar --bar "${bar_defaults[@]}"
sketchybar --default updates=when_shown \
    "${icon_defaults[@]}" \
    "${label_defaults[@]}" \
    "${background_defaults[@]}" \
    "${popup_defaults[@]}"
#+end_src

** Bar
*** Left

#+begin_src sh :tangle no :noweb-ref bar
source "$PLUGIN_DIR/spaces/item.sh"

sketchybar --add item space_separator left                         \
           --set space_separator icon=ļ                            \
                                 padding_left=10                   \
                                 padding_right=10                  \
                                 label.drawing=off                 \
                                                                   \
           --add item front_app left                               \
           --set front_app       script="$PLUGIN_DIR/front_app.sh" \
                                 icon.drawing=off                  \
           --subscribe front_app front_app_switched
#+end_src

*** Center

#+begin_src sh :tangle no :noweb-ref bar
# none yet
#+end_src

*** Right

#+begin_src sh :tangle no :noweb-ref bar
source "$PLUGIN_DIR/date/item.sh"
source "$PLUGIN_DIR/wifi/item.sh"
#+end_src

*** Old Config

#+begin_src sh :tangle no :noweb-ref bar
# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

# sketchybar --add item clock right                              \
#            --set clock   update_freq=10                        \
#                          icon=ļ                                \
#                          script="$PLUGIN_DIR/clock.sh"         \
#                                                                \
#            --add item wifi right                               \
#            --set wifi    script="$PLUGIN_DIR/wifi.sh"          \
#                          icon=ļŖØ                               \
#            --subscribe wifi wifi_change                        \
#                                                                \
#            --add item volume right                             \
#            --set volume  script="$PLUGIN_DIR/volume.sh"        \
#            --subscribe volume volume_change                    \
#                                                                \
#            --add item battery right                            \
#            --set battery script="$PLUGIN_DIR/battery.sh"       \
#                          update_freq=120                       \
#            --subscribe battery system_woke power_source_change
#+end_src

** Colors

I typically use the [[https://draculatheme.com/][Dracula]] theme everywhere I can! I'm also trying [[https://github.com/catppuccin/catppuccin][Catppuccin]].

*** Global Colors

#+begin_src sh :tangle no :noweb-ref colors
BLACK=0xff000000
WHITE=0xffffffff
TRANSPARENT=0x00000000
#+end_src

*** Dracula

#+begin_src sh :tangle no :noweb-ref colors
if [[ $THEME -eq 1 ]]; then
    echo "Dracula"
#+end_src

*** Catppuccin Frappe

#+begin_src sh :tangle no :noweb-ref colors
elif [[ $THEME -eq 2 ]]; then
    # Define Frappe colors
    ROSEWATER=0xfff2d5cf
    FLAMINGO=0xffeebebe
    PINK=0xfff4b8e4
    MAUVE=0xffca9ee6
    RED=0xffe78284
    MAROON=0xffea999c
    PEACH=0xffef9f76
    YELLOW=0xffe5c890
    GREEN=0xffa6d189
    TEAL=0xff81c8be
    SKY=0xff99d1db
    SAPPHIRE=0xff85c1dc
    BLUE=0xff8caaee
    LAVENDER=0xffbabbf1
    TEXT=0xffc6d0f5
    SUBTEXT1=0xffb5bfe2
    SUBTEXT0=0xffa5adce
    OVERLAY2=0xff949cbb
    OVERLAY1=0xff838ba7
    OVERLAY0=0xff737994
    SURFACE2=0xff626880
    SURFACE1=0xff51576d
    SURFACE0=0xff414559
    BASE=0xff303446
    MANTLE=0xff292c3c
    CRUST=0xff232634
    # Translate colors to SketchyBar
    BAR_COLOR=$BASE
    BORDER_COLOR=$SURFACE1
    ICON_COLOR=$TEXT
    LABEL_COLOR=$TEXT
    POPUP_COLOR=$BASE
    POPUP_BORDER_COLOR=$TEXT
    SHADOW_COLOR=$CRUST
    #HIGHLIGHT_COLOR=
#+end_src

*** Catppuccin Mocha

#+begin_src sh :tangle no :noweb-ref colors
else
    # Define mocha colors
    ROSEWATER=0xfff5e0dc
    FLAMINGO=0xfff2cdcd
    PINK=0xfff5c2e7
    MAUVE=0xffcba6f7
    RED=0xfff38ba8
    MAROON=0xffeba0ac
    PEACH=0xfffab387
    YELLOW=0xfff9e2af
    GREEN=0xffa6e3a1
    TEAL=0xff94e2d5
    SKY=0xff89dceb
    SAPPHIRE=0xff74c7ec
    BLUE=0xff89b4fa
    LAVENDER=0xffb4befe
    TEXT=0xffcdd6f4
    SUBTEXT1=0xffbac2de
    SUBTEXT0=0xffa6adc8
    OVERLAY2=0xff9399b2
    OVERLAY1=0xff7f849c
    OVERLAY0=0xff6c7086
    SURFACE2=0xff585b70
    SURFACE1=0xff45475a
    SURFACE0=0xff313244
    BASE=0xff1e1e2e
    MANTLE=0xff181825
    CRUST=0xff11111b
    TRANSPARENT=0x00000000
    # Translate colors to SketchyBar
    BAR_COLOR=$BASE
    BORDER_COLOR=$SURFACE1
    ICON_COLOR=$TEXT
    LABEL_COLOR=$TEXT
    POPUP_COLOR=$BASE
    POPUP_BORDER_COLOR=$TEXT
    SHADOW_COLOR=$CRUST
    #HIGHLIGHT_COLOR=
fi
#+end_src

** Plugins

#+begin_src sh :tangle no :noweb-ref plugins
PLUGIN_DIR="$HOME/.config/sketchybar/plugins"
#+end_src

** Helpers

** Tweaks
*** Remove Volume Indicator

Unload the macOS on screen indicator overlay for volume change.

#+begin_src sh :tangle no :noweb-ref tweaks
launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist >/dev/null 2>&1 &
#+end_src

** Finalize

This command is only used at the end of initial configuration to force all scripts to run upon start. It should never be run in an item script.

#+begin_src sh :tangle no :noweb-ref finalize
sketchybar --update
#+end_src

** No Web Assembly :noexport:

#+begin_src sh :tangle sketchybarrc :noweb no-export :shebang "#!/usr/bin/env bash"
<<tweaks>>

<<plugins>>

<<colors>>

<<defaults>>

<<bar>>

<<finalize>>
#+end_src
