#!/usr/bin/env bash
# shellcheck disable=SC1091

source "$CONFIG_DIR/colors.sh" # Loads all defined colors
source "$CONFIG_DIR/icons.sh"  # Loads all defined icons

# Directories
PLUGINS_DIR="$CONFIG_DIR/plugins" # Directory where all the plugin scripts are stored
HELPERS_DIR="$CONFIG_DIR/helpers"

# Global Variables
FONT="SF Pro" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
PADDING=4     # All paddings use this value (icon, label, background)
BORDER_WIDTH=2
BAR_COLOR="$TRANSPARENT"

# Unload the macOS on screen indicator overlay for volume change
launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist >/dev/null 2>&1 &

# General Bar Appearance
bar=(
    color="$BAR_COLOR"
    border_color="$BAR_BORDER_COLOR"
    position=top
    margin=-2
    y_offset=-2
    corner_radius=0
    border_width="$BORDER_WIDTH"
    height=$(($("$HELPERS_DIR"/get_menu_bar_height) + BORDER_WIDTH))
    blur_radius=30
    padding_left=15
    padding_right=15
    notch_width=200
    notch_offset=0
    display=main
    hidden=off
    topmost=on
    sticky=on
    font_smoothing=off
    shadow=off
)
sketchybar --bar "${bar[@]}"

# Default Values
defaults=(
    updates=when_shown
    icon.font="$FONT:Bold:17.0"
    icon.color="$ICON_COLOR"
    icon.padding_left="$PADDING"
    icon.padding_right="$PADDING"
    label.font="$FONT:Semibold:13.0"
    label.color="$LABEL_COLOR"
    label.padding_left="$PADDING"
    label.padding_right="$PADDING"
    padding_right="$PADDING"
    padding_left="$PADDING"
    background.height=26
    background.corner_radius=9
    background.border_width=2
    popup.background.border_width=2
    popup.background.corner_radius=9
    popup.background.border_color="$POPUP_BORDER_COLOR"
    popup.background.color="$POPUP_COLOR"
    #popup.blur_radius=20
    popup.background.shadow.drawing=on
)
sketchybar --default "${defaults[@]}"

source "$PLUGINS_DIR/yabai/item.sh"
source "$PLUGINS_DIR/spaces/item.sh"
source "$PLUGINS_DIR/brew/item.sh"
source "$PLUGINS_DIR/volume/item.sh"

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update

echo "Sketchybar configuation loaded..."
